// LES SAUTS — leurs mots.
//
// Tout ce que la longueur, le triple et la hauteur ecrivent a l'ecran :
// consignes, aides, notes des gestes, essais nuls, classement, carriere, et
// l'accueil de Jumper.
//
// POURQUOI ILS NE SONT PAS DANS sprinter-i18n.js, avec les autres. Pour la
// meme raison que les mots du molosse (halloween-mots.ts) : la table commune
// est publiee sur un global, un bundler ne peut pas suivre ce qui y entre, et
// ces lignes partaient dans le build public alors que les sauts n'y sont pas
// (canal.ts, SAUTS_OUVERTS). Ici, elles partent avec le morceau de Jumper.
//
// Restent dans la table commune les noms des epreuves (disc_*) et leurs cotes
// (saut_cotes, triple_cotes, haut_cotes) : l'accueil public les affiche.
//
// Contrairement au molosse, on ne passe pas par une fonction a soi : les mots
// rejoignent UI au chargement du module, et les ecrans gardent N.t(). Chaque
// fichier qui les lit importe ce module ; le premier charge suffit, les
// suivants ne font rien. Une cle deja presente dans UI n'est pas ecrasee.

import { SprinterI18N } from './engine';

export const MOTS_SAUTS = {
  // Le saut en longueur. « Mordu » comme au poids : c'est le mot du juge.
  // « Ramené » est celui des entraineurs — les jambes qu'on ramene devant
  // avant de toucher le sable.
  saut_c_partir:   ['ALTERNE POUR T’ÉLANCER', 'ALTERNATE TO RUN UP'],
  saut_c_appel:    ['APPUIE SUR LA PLANCHE', 'HIT THE BOARD'],
  saut_c_angle:    ['TIENS… RELÂCHE POUR T’ENVOLER', 'HOLD… RELEASE TO TAKE OFF'],
  saut_c_ramene:   ['LES DEUX POUCES : JAMBES DEVANT', 'BOTH THUMBS: LEGS FORWARD'],
  saut_choix:      ['CHOISIS TON CONCOURS', 'CHOOSE YOUR COMPETITION'],
  saut_aide_1:     ['Alterne les deux pavés pour prendre ton élan.',
                    'Alternate both pads to build your run-up.'],
  saut_aide_2:     ['Dans le dernier mètre, appuie : ton pied se pose sur la planche. Après la ligne, c’est mordu.',
                    'In the last metre, press: your foot lands on the board. Past the line, it’s a foul.'],
  saut_aide_3:     ['Garde le doigt appuyé : l’angle monte. Relâche vers 21° pour t’envoler.',
                    'Keep your finger down: the angle rises. Release near 21° to take off.'],
  saut_aide_4:     ['En l’air, alterne pour pédaler, puis les deux pouces ensemble pour ramener les jambes.',
                    'In the air, alternate to hitch-kick, then both thumbs together to bring your legs forward.'],
  saut_regle:      ['1 minute par essai · 3 essais',
                    '1 minute per attempt · 3 attempts'],
  saut_verrou:     ['un podium ouvre l’étape suivante', 'a podium unlocks the next stage'],
  saut_tour:       ['ESSAI {n}/{t}', 'ATTEMPT {n}/{t}'],
  saut_a_toi:      ['À TOI', 'YOUR TURN'],
  saut_saute:      ['{n} s’élance…', '{n} is on the runway…'],
  saut_passer:     ['toucher pour passer', 'tap to skip'],
  saut_elan:       ['ÉLAN', 'RUN-UP'],
  saut_planche:    ['PLANCHE', 'BOARD'],
  saut_planche_cm: ['{n} cm de la ligne', '{n} cm from the line'],
  saut_angle:      ['ANGLE', 'ANGLE'],
  saut_mordu:      ['MORDU', 'FOUL'],
  saut_nul_planche:  ['le pied a franchi la ligne', 'the foot crossed the line'],
  saut_nul_traverse: ['couru à travers la planche', 'ran through the board'],
  saut_nul_temps:    ['la minute est écoulée', 'the minute ran out'],
  saut_r_parfait:  ['RAMENÉ PARFAIT', 'PERFECT LANDING'],
  saut_r_bon:      ['BON RAMENÉ', 'GOOD LANDING'],
  saut_r_tot:      ['RAMENÉ TÔT', 'EARLY LANDING'],
  saut_r_assis:    ['ASSIS EN ARRIÈRE', 'FELL BACK'],
  saut_r_tard:     ['RAMENÉ TARD', 'LATE LANDING'],
  saut_r_sans:     ['PIEDS SOUS LE BASSIN', 'FEET UNDER THE HIPS'],
  saut_ciseau:     ['CISEAU', 'HITCH-KICK'],
  saut_vent:       ['vent {v} m/s', 'wind {v} m/s'],
  saut_vent_trop:  ['vent {v} m/s : non homologable', 'wind {v} m/s: not ratified'],
  saut_classement: ['CLASSEMENT', 'STANDINGS'],
  saut_a_battre:   ['à battre', 'to beat'],
  saut_elimine:    ['ÉLIMINÉ APRÈS TROIS ESSAIS', 'OUT AFTER THREE ATTEMPTS'],
  saut_qualifie:   ['QUALIFIÉ POUR LES TROIS DERNIERS ESSAIS', 'THROUGH TO THE LAST THREE'],
  saut_fini:       ['CONCOURS TERMINÉ', 'COMPETITION OVER'],
  saut_or:         ['MÉDAILLE D’OR', 'GOLD MEDAL'],
  saut_argent:     ['MÉDAILLE D’ARGENT', 'SILVER MEDAL'],
  saut_bronze:     ['MÉDAILLE DE BRONZE', 'BRONZE MEDAL'],
  saut_place:      ['{p} place', '{p} place'],
  saut_nm:         ['SANS MARQUE', 'NO MARK'],
  saut_record_perso: ['RECORD PERSONNEL', 'PERSONAL BEST'],
  saut_record:     ['record du monde {m} m — {n}, {a}', 'world record {m} m — {n}, {a}'],
  saut_debloque:   ['étape suivante débloquée', 'next stage unlocked'],
  saut_refaire:    ['REFAIRE LE CONCOURS', 'JUMP AGAIN'],
  saut_suivant:    ['ÉTAPE SUIVANTE', 'NEXT STAGE'],
  saut_quitter:    ['QUITTER', 'LEAVE'],
  saut_rm:         ['RM', 'WR'],
  // Le triple saut. « Cloche-pied » et « foulée bondissante » sont les mots
  // des entraineurs ; l'anglais dit hop, step, jump.
  triple_c_cloche: ['MÊME PIED : APPUIE À LA POSE', 'SAME FOOT: PRESS AS YOU LAND'],
  triple_c_foulee: ['L’AUTRE PIED : APPUIE À LA POSE', 'OTHER FOOT: PRESS AS YOU LAND'],
  triple_aide_1:   ['Élan, puis appuie sur la planche et tiens : l’angle monte. Relâche vers 15° — le cloche-pied est rasant.',
                    'Run up, then press on the board and hold: the angle rises. Release near 15° — the hop stays low.'],
  triple_aide_2:   ['Cloche-pied : tu retombes sur le MÊME pied. Appuie sur le même pavé quand il s’allume, tiens, relâche.',
                    'Hop: you land on the SAME foot. Press the same pad when it lights up, hold, release.'],
  triple_aide_3:   ['Foulée bondissante : tu retombes sur l’AUTRE pied, avec l’autre pavé.',
                    'Step: you land on the OTHER foot, with the other pad.'],
  triple_aide_4:   ['Le saut finit comme en longueur : relâche vers 20°, puis les deux pouces pour ramener les jambes.',
                    'The jump ends like the long jump: release near 20°, then both thumbs to bring the legs forward.'],
  triple_regle:    ['un mauvais pied, et l’essai est nul · planche à {m} m du sable, cloche-pied et foulée sur la piste',
                    'wrong foot and the attempt is void · board {m} m from the sand, hop and step on the runway'],
  triple_planche:  ['planche à {m} m', 'board at {m} m'],
  triple_nul_pied:   ['mauvais pied', 'wrong foot'],
  triple_nul_rompu:  ['bond cassé', 'broken bound'],
  triple_nul_hors:   ['retombé avant le sable', 'landed short of the sand'],
  triple_nul_sable:  ['un bond posé dans le sable', 'a bound landed in the sand'],
  triple_p_sable:  ['DANS LE SABLE', 'IN THE SAND'],
  triple_p_actif:  ['APPUI ACTIF', 'ACTIVE LANDING'],
  triple_p_bon:    ['BON APPUI', 'GOOD LANDING'],
  triple_p_ecrase: ['APPUI ÉCRASÉ', 'HEAVY LANDING'],
  triple_p_rompu:  ['BOND CASSÉ', 'BROKEN BOUND'],
  triple_mauvais_pied: ['MAUVAIS PIED', 'WRONG FOOT'],
  // Le saut en hauteur. « Rouleau dorsal » est le Fosbury des entraineurs
  // francais ; « passer » une barre est le mot du reglement, et du juge.
  // L'accueil de Jumper et la carriere des sauts.
  saut_court_longueur: ['LONGUEUR', 'LONG'],
  saut_court_triple:   ['TRIPLE', 'TRIPLE'],
  saut_court_hauteur:  ['HAUTEUR', 'HIGH'],
  saut_court_perche:   ['PERCHE', 'POLE'],
  saut_meilleurs:  ['MEILLEURS SAUTS', 'BEST JUMPS'],
  saut_rp:         ['RP', 'PB'],
  saut_aucun:      ['Aucun concours', 'No competition yet'],
  saut_annonce:    ['annoncé à {m}', 'announced at {m}'],
  saut_accueil:    ['ACCUEIL', 'HOME'],
  saut_carriere_refaire: ['RECOMMENCER LA CARRIÈRE', 'RESTART THE CAREER'],
  saut_qualifie_etape:   ['PODIUM : L’ÉTAPE SUIVANTE T’ATTEND', 'PODIUM: THE NEXT STAGE AWAITS'],
  saut_carriere_finie:   ['HORS DU PODIUM : LA CARRIÈRE S’ARRÊTE ICI', 'OFF THE PODIUM: THE CAREER ENDS HERE'],
  saut_champion:   ['SIX ÉTAPES : CHAMPION DES SAUTS', 'SIX STAGES: JUMPING CHAMPION'],
  jumper_oneshot_desc:  ['UN CONCOURS, L’ÉTAPE DE TON CHOIX', 'ONE COMPETITION, THE STAGE OF YOUR CHOICE'],
  jumper_oneshot_choix: ['CHOISIS TON CONCOURS', 'CHOOSE YOUR COMPETITION'],
  jumper_versus_desc:   ['DÉFIS ENTRE AMIS', 'CHALLENGES BETWEEN FRIENDS'],
  jumper_versus_titre:  ['DÉFIS ET DUELS DE SAUT', 'JUMPING CHALLENGES AND DUELS'],
  jumper_versus_txt:    ['Lancer sa meilleure marque à un ami, sauter contre lui en direct : les duels arrivent sur les sauts.',
                         'Send your best mark to a friend, jump against them live: duels are coming to the jumps.'],
  jumper_reglement: ['LE RÈGLEMENT', 'THE RULES'],
  jumper_comment:   ['COMMENT ON SAUTE', 'HOW TO JUMP'],
  haut_c_partir:   ['ALTERNE POUR T’ÉLANCER', 'ALTERNATE TO RUN UP'],
  haut_c_elan:     ['VITESSE CONTRÔLÉE : PAS TROP VITE', 'CONTROLLED SPEED: NOT TOO FAST'],
  haut_c_appel:    ['PIED GAUCHE : APPUIE POUR L’APPEL', 'LEFT FOOT: PRESS TO TAKE OFF'],
  haut_c_angle:    ['TIENS… RELÂCHE POUR T’ENVOLER', 'HOLD… RELEASE TO TAKE OFF'],
  haut_c_cambre:   ['APPUIE ET TIENS : CAMBRE-TOI', 'PRESS AND HOLD: ARCH'],
  haut_c_jambes:   ['RELÂCHE : LES JAMBES !', 'RELEASE: KICK THE LEGS!'],
  haut_aide_1:     ['Alterne pour courir ton élan en J. Ne cours pas au maximum : vers 8 m/s, la vitesse s’affiche en vert.',
                    'Alternate to run your J approach. Don’t sprint flat out: around 8 m/s the speed turns green.'],
  haut_aide_2:     ['Près de la barre, le pavé GAUCHE s’allume : appuie pour poser ton pied d’appel, ni trop loin ni trop près.',
                    'Near the bar the LEFT pad lights up: press to plant your take-off foot, not too far, not too close.'],
  haut_aide_3:     ['Garde-le appuyé : l’angle monte. Relâche dans le secteur vert pour t’envoler.',
                    'Keep it pressed: the angle rises. Release in the green sector to take off.'],
  haut_aide_4:     ['En l’air, appuie et tiens quand ton bassin arrive sur la barre : tu te cambres.',
                    'In the air, press and hold as your hips reach the bar: you arch.'],
  haut_aide_5:     ['Relâche quand il est passé : tes jambes partent vers le ciel. Trop tôt ou trop tard, la barre tombe.',
                    'Release once they are over: your legs kick up. Too early or too late, the bar falls.'],
  haut_regle:      ['3 échecs de suite éliminent · on peut passer une barre',
                    '3 misses in a row and you are out · you may pass a height'],
  haut_depart:     ['barre de départ {h}', 'opening height {h}'],
  haut_pesanteur:  ['pesanteur {g} m/s²', 'gravity {g} m/s²'],
  haut_barre:      ['BARRE {h}', 'BAR {h}'],
  haut_essai:      ['ESSAI {n} SUR 3', 'ATTEMPT {n} OF 3'],
  haut_suite:      ['{n} échec(s) de suite', '{n} miss(es) in a row'],
  haut_sauter:     ['SAUTER', 'JUMP'],
  haut_passer:     ['PASSER', 'PASS'],
  haut_passe:      ['PASSE', 'PASS'],
  haut_franchi:    ['FRANCHI', 'CLEARED'],
  haut_echec:      ['ÉCHEC', 'MISS'],
  haut_saute:      ['{n} s’élance à {h}…', '{n} attempts {h}…'],
  haut_tombee:     ['BARRE TOMBÉE', 'BAR DOWN'],
  haut_tremble:    ['la barre a tremblé…', 'the bar wobbled…'],
  haut_par_epaules: ['touchée par les épaules', 'hit with the shoulders'],
  haut_par_bassin:  ['touchée par le bassin', 'hit with the hips'],
  haut_par_genoux:  ['touchée par les cuisses', 'hit with the thighs'],
  haut_par_talons:  ['touchée par les talons', 'hit with the heels'],
  haut_nul_dessous: ['passé sous la barre', 'ran under the bar'],
  haut_nul_temps:   ['la minute est écoulée', 'time ran out'],
  haut_cambre_parfait: ['CAMBRURE PARFAITE', 'PERFECT ARCH'],
  haut_cambre_bon:     ['BONNE CAMBRURE', 'GOOD ARCH'],
  haut_cambre_tot:     ['CAMBRURE TÔT', 'EARLY ARCH'],
  haut_cambre_tard:    ['CAMBRURE TARD', 'LATE ARCH'],
  haut_cambre_sans:    ['SANS CAMBRURE', 'NO ARCH'],
  haut_jambes_parfait: ['JAMBES PARFAITES', 'PERFECT KICK'],
  haut_jambes_bon:     ['BONNES JAMBES', 'GOOD KICK'],
  haut_jambes_tot:     ['JAMBES TÔT', 'EARLY KICK'],
  haut_jambes_tard:    ['JAMBES TARD', 'LATE KICK'],
  haut_jambes_sans:    ['JAMBES NON LANCÉES', 'NO KICK'],
  haut_elan_juste:     ['ÉLAN JUSTE', 'SPOT-ON SPEED'],
  haut_elan_trop:      ['TROP VITE', 'TOO FAST'],
  haut_elan_lent:      ['ÉLAN UN PEU LENT', 'A LITTLE SLOW'],
  haut_elan_trop_lent: ['ÉLAN TROP LENT', 'TOO SLOW'],
  haut_appel:      ['appel à {d} m', 'take-off {d} m out'],
  haut_vise:       ['visé {a}°', 'target {a}°'],
  haut_partage_titre: ['EX ÆQUO POUR L’OR', 'TIED FOR GOLD'],
  haut_partage_txt:   ['Même barre, mêmes essais, mêmes échecs. Le règlement prévoit un barrage — ou le partage du titre, si vous le voulez tous.',
                       'Same height, same attempts, same misses. The rules call for a jump-off — or a shared title, if you all agree.'],
  haut_partager:   ['PARTAGER L’OR', 'SHARE THE GOLD'],
  haut_barrage:    ['BARRAGE', 'JUMP-OFF'],
  haut_barrage_essai: ['BARRAGE · UN SEUL ESSAI', 'JUMP-OFF · ONE ATTEMPT'],
  haut_libre:      ['TU AS GAGNÉ : CHOISIS TA BARRE', 'YOU HAVE WON: CHOOSE YOUR BAR'],
  haut_arreter:    ['S’ARRÊTER LÀ', 'STOP HERE'],
  haut_record_tente: ['TENTATIVE DE RECORD DU MONDE', 'WORLD RECORD ATTEMPT'],
};

for (const cle in MOTS_SAUTS) {
  if (!(cle in SprinterI18N.UI)) SprinterI18N.UI[cle] = MOTS_SAUTS[cle];
}
