/* -----------------------------------------------------------------------
   SPRINTER — español.
   Ce qui manque ici retombe sur l'anglais, cle par cle : voir
   sprinter-i18n.js. Verification : node tools/langues-verifier.mjs es
   ----------------------------------------------------------------------- */
export default {
  ord(n, feminine) { return n + (feminine ? 'ª' : 'º'); },

  LEVEL_NAMES: [
    'Encuentro escolar', 'Nivel regional', 'Nivel nacional',
    'Campeonato del Mundo', 'Juegos Mundiales', 'Intergaláctico'
  ],

  RACE_SUB: {
    '100': 'la recta',
    '200': 'curva y recta',
    '400': 'una vuelta a la pista'
  },

  UI: {
    // apertura y bienvenida
    races: '100 - 200 - 400 METROS',
    tagline: 'seis etapas, un solo crono que batir',
    tap_start: 'toca la pantalla para empezar',
    six_stages: '   -   seis etapas',
    six_stages_bare: 'seis etapas',
    best_runs: 'MEJORES RECORRIDOS',
    no_run: 'aún no has terminado ningún recorrido',
    furthest: 'etapa más lejana: ',
    of_six: ' de 6',
    start: 'EMPEZAR',
    sound: 'sonido: ',
    yes: 'sí',
    no: 'no',

    // cinemáticas
    rival: 'EL CORREDOR A BATIR',
    favourite: 'El favorito',
    after_race: 'DESPUÉS DE LA CARRERA',
    crowned: 'TÍTULO INTERGALÁCTICO',
    fastest_1: 'EL SER MÁS RÁPIDO',
    fastest_2: 'DE TODAS LAS GALAXIAS',
    full_run_in: 'recorrido completo en ',
    announced: 'crono anunciado: ',
    stage_up: 'ETAPA ',
    six_cleared: 'SEIS ETAPAS SUPERADAS',
    skip_now: 'toca otra vez para saltar',
    skip_twice: 'toca dos veces para saltar',

    // salida y fases de carrera
    reaction: 'REACCIÓN',
    react_top: 'REACCIÓN PERFECTA',
    false_start: 'HAS SALIDO ANTES',
    wait_gun: 'espera el disparo',
    phase_drive: 'IMPULSO',
    phase_trans: 'TRANSICIÓN',
    phase_max: 'VELOCIDAD MÁXIMA',
    drive_hint: 'asienta tu cadencia',
    trans_2: 'TRANSICIÓN PERFECTA',
    trans_1: 'BUENA TRANSICIÓN',
    trans_0: 'TRANSICIÓN FALLIDA',
    start_line: 'salida: {r} s de reacción   -   {g}',
    no_start: 'salida fallada',

    // carrera
    stumble: 'TROPIEZAS',
    to_beat: 'a batir: ',
    to_race: 'corres contra ',
    ready: 'A SUS PUESTOS',
    get_set: 'LISTOS',
    go: 'YA',
    alternate: 'alterna los dos botones',
    alternate_kb: 'alterna las dos flechas',
    you: 'TÚ',
    opponent: 'RIVAL',
    depart: 'SALIDA',
    arrivee: 'META',

    // resultados
    stage_done: 'ETAPA {n} SUPERADA',
    first_in: '1.º puesto en ',
    total_of: ' s   -   total ',
    place: '{o} PUESTO',
    dnf: 'abandono',
    unfinished: 'sin terminar',
    race_again: '¿OTRA VEZ?',
    next_stage: 'ETAPA {n}',
    home: 'INICIO',
    replay: 'JUGAR OTRA VEZ',
    run_done: 'RECORRIDO COMPLETADO',
    six_in: 'seis etapas superadas en ',
    stage_low: 'etapa ',

    // distintivos
    new_record: 'NUEVO RÉCORD',
    top3: 'TOP 3',
    top10: 'TOP 10',
    best_run: 'MEJOR RECORRIDO',
    top3_runs: 'TOP 3 DE RECORRIDOS',
    top10_runs: 'TOP 10 DE RECORRIDOS',

    // clasificación mundial
    top500: 'TOP 500 - HISTÓRICO',
    your_name: 'tu nombre',
    save_score: 'GUARDAR MI CRONO',
    saving_score: 'enviando...',
    score_saved: '{r} en el TOP 500 mundial',
    score_save_fail: 'no se pudo enviar, inténtalo más tarde',
    score_name_taken: 'este nombre pertenece a otro dispositivo',
    score_taken_help: 'elige otro, o vincula este dispositivo a tu nombre en MIS CARRERAS con tu código de recuperación',
    view_top500: 'VER EL TOP 500',
    top500_court: 'TOP 500',
    close: 'CERRAR',
    loading_ranks: 'cargando la clasificación...',
    empty_top500: 'aún no hay cronos registrados',
    your_rank: 'TU PUESTO: {r}',
    outside_top500: 'fuera del top 500',
    edit_name: 'CAMBIAR EL NOMBRE',
    best_split_short: 'mejor etapa:',
    top500_sub: 'mejor crono en una sola carrera',
    cat_race: 'POR CARRERA',
    cat_run: 'RECORRIDO COMPLETO',
    cat_mine: 'MIS CARRERAS',
    cat_mine_sub: 'todas las carreras que has hecho',
    mine_empty: 'aún no hay ninguna carrera en esta prueba',
    mine_count: '{n} carreras — mejor: {s} s',
    mine_note: 'El TOP 500 solo guarda tu mejor crono por prueba; este historial lo guarda todo. Reserva tu nombre para encontrarlo en tus otros dispositivos.',

    // duelos
    duel_title: 'CLASIFICACIÓN DE DUELOS',
    duel_sub: 'retos enviados y respondidos',
    duel_open: 'VER LA CLASIFICACIÓN DE DUELOS',
    duel_rules_init: 'RETO ENVIADO',
    duel_rules_recv: 'RETO RESPONDIDO',
    duel_rules_line: 'victoria {v}   ·   derrota {d}   ·   empate {n}',
    duel_rules_all: 'todos los duelos cuentan, enviados o respondidos',
    duel_rules_why: 'enviar un reto es enseñar tu crono primero',
    duel_counts: '{l} enviados · {r} respondidos',
    duel_sur: 'EL DUELO SE CORRE EN',

    // nombre, país, redes
    name_set: 'ELIGE TU NOMBRE',
    name_title: 'TU NOMBRE',
    name_why: 'es lo que aparece en el TOP 500, en tus retos y en los duelos',
    name_save: 'GUARDAR',
    name_saved: 'GUARDADO',
    name_taken: 'ese nombre ya está cogido',
    name_code: 'TU CÓDIGO DE RECUPERACIÓN',
    pays_title: 'TU NACIONALIDAD',
    pays_opt: 'solo una vez',
    pays_aucun: 'elige tu país',
    pays_why: 'la necesitas para correr un campeonato nacional — y después no se puede cambiar',
    pays_vu: 'parece que te conectas desde {pays} — tú decides',
    pays_save: 'ELEGIR',
    pays_confirm: '¿Correr por {pays}?\n\nEs definitivo: decide en qué campeonato nacional entras, y no se puede cambiar.',
    pays_fige: 'definitivo',
    pays_on: 'corres por este país — tu bandera acompaña a tu nombre en el campeonato',
    pays_deja: 'tu nacionalidad ya está elegida, no se puede cambiar',
    pays_first: 'guarda primero tu nombre',
    pays_bad: 'país no válido',
    insta_title: 'TU INSTAGRAM',
    insta_ph: 'tu usuario, sin la @',
    insta_why: 'tu perfil queda accesible desde el TOP 500 y desde tus retos',
    insta_note: 'declarado por ti, sin verificar — Instagram ya no permite un inicio de sesión real para una cuenta personal',
    insta_link: 'VINCULAR MI CUENTA',
    insta_linked: 'CUENTA VINCULADA',
    insta_unlink: 'DESVINCULAR',
    insta_on: 'tu perfil aparece en el TOP 500 — tócalo para abrirlo',
    insta_gone: 'cuenta desvinculada, tu perfil ya no aparece en ninguna parte',
    insta_bad: 'usuario no válido',
    insta_first: 'guarda primero tu nombre',
    insta_notyours: 'este nombre no es tuyo en este dispositivo',
    insta_visit: 'ver el perfil de Instagram de {n}',
    name_code_why: 'apúntalo: recupera tu nombre y tus carreras en otro teléfono',

    // visita guiada
    tour_open: 'HACER LA VISITA',
    tour_1_t: 'ALTERNA',
    tour_1_s: 'izquierda, derecha, izquierda. Toda la carrera es eso.',
    tour_2_t: 'LA CARRERA DEPORTIVA',
    tour_2_s: 'seis etapas, del patio del colegio a la final intergaláctica',
    tour_3_t: 'EL TOP 500',
    tour_3_s: 'tu crono contra el mundo entero',
    tour_4_t: 'EL FANTASMA',
    tour_4_s: 'envía tu carrera a un amigo — corre contra ti',
    tour_5_t: 'EN DIRECTO',
    tour_5_s: 'mismo disparo, cada uno en su teléfono',
    tour_play: 'DÉJAME JUGAR',

    // one shot: explicación
    os_tuto_open: 'PARA QUÉ SIRVE ESTE MODO',
    os_tuto_1_t: 'ELIGE TUS PRUEBAS',
    os_tuto_2_t: 'UN SOLO INTENTO',
    os_tuto_3_t: 'TU CRONO CUENTA',
    os_tuto_1_s: 'una, dos o las tres',
    os_tuto_2_s: 'sin repetir, sin eliminación',
    os_tuto_3_s: 'TOP 500, y un amigo puede aceptarlo',
    os_tuto_go: 'EMPEZAR UN ONE SHOT',

    // tutorial
    tuto_ask_t: 'PRIMERA CARRERA',
    tuto_ask_s: 'el gesto se aprende en treinta segundos',
    tuto_ask_yes: 'APRENDER EL GESTO',
    tuto_ask_no: 'DÉJAME CORRER',
    tuto_watch: 'MIRA',
    tuto_your_turn: 'TE TOCA',
    tuto_1_t: 'ALTERNA',
    tuto_2_t: 'AL DISPARO',
    tuto_3_t: 'AMPLIO, LUEGO CORTO',
    tuto_v_early: 'DEMASIADO PRONTO',
    tuto_v_late: 'demasiado tarde',
    tuto_v_perfect: 'PERFECTO',
    tuto_v_good: 'BIEN',
    tuto_v_slow: 'NO ES BASTANTE RÁPIDO',
    tuto_v_flat: 'RITMO PLANO',
    tuto_replay_demo: 'ver otra vez',
    tuto_again: 'OTRA VEZ',
    tuto_next: 'SIGUIENTE',
    tuto_done_t: 'TE TOCA CORRER',
    tuto_start: 'EMPEZAR',
    tuto_replay: 'ver otra vez',
    tuto_skip: 'saltar',
    tuto_open: 'CÓMO SE JUEGA',

    // carrera en directo
    live_title: 'CARRERA EN DIRECTO',
    live_desc: 'salís los dos con el mismo disparo, cada uno en su teléfono — sin fantasma, nadie sabe quién gana',
    live_create: 'ABRIR UNA PISTA',
    live_join: 'UNIRSE',
    live_or: 'o',
    live_room: 'PISTA ABIERTA',
    live_waiting: 'envía este código a tu rival — la carrera empieza cuando seáis dos',
    live_ready: 'LISTO',
    live_notready: 'TODAVÍA NO',
    live_empty_seat: 'calle libre — esperando rival',
    live_go: 'ESTOY LISTO',
    live_unready: 'CANCELAR',
    live_leave: 'salir de la pista',
    live_none: 'no hay ninguna pista con ese código',
    live_full: 'esa pista ya está completa',
    live_gone: 'tu rival ha salido de la pista',
    live_closed: 'se ha cortado la conexión',
    live_invite: 'Te espero en la pista. Código {c} — {l}',

    // relevos
    relais_titre: 'RELEVO 4 × 100',
    relais_desc: 'cuatro corredores, un testigo. Un equipo es su alineación: los mismos cuatro nombres, el mismo equipo.',
    relais_invitations: 'TE HAN INVITADO',
    relais_mes_equipes: 'TUS EQUIPOS',
    relais_creer: 'FORMAR UN EQUIPO',
    relais_nom_equipe: 'nombre del equipo',
    relais_coequipier: 'compañero {n}',
    relais_inviter: 'INVITAR A LOS TRES',
    relais_incomplet: 'hacen falta un nombre y tres compañeros',
    relais_attend: 'pendiente',
    relais_ok: 'dentro',
    relais_refuse: 'ha rehusado',
    relais_fixer_ordre: 'FIJAR EL ORDEN DE CARRERA',
    relais_manque_reponses: 'faltan respuestas antes de poder correr',
    relais_manque_refus: 'un compañero ha rehusado — este equipo no puede correr',
    relais_prete: 'equipo listo',
    relais_classement: 'CLASIFICACIÓN POR EQUIPOS',
    relais_plein_titre: 'DOS EQUIPOS, NO TRES',
    relais_plein: 'ya corres para dos equipos. Deja aquel en el que ya no corres para formar otro.',
    relais_plein_invit: 'ya corres para dos equipos — deja uno para aceptar esto.',
    relais_quitter: 'DEJARLO',
    relais_quitter_sur: '¿dejarlo para siempre?',
    relais_quitter_sub: 'solo vuelves con una nueva invitación',
    relais_reste: 'queda una plaza',
    relais_place: '1 de 2 equipos',
    relais_places: '{n} de 2 equipos',
    relais_courir: 'IR A LA PISTA',
    relais_mon_rang: 'corres la posta {n}',
    relais_premier: 'sales de los tacos, de pie. Una salida nula elimina a todo el equipo.',
    relais_ta_marque: 'TU MARCA EN LA ZONA',
    relais_zone_debut: 'dentro',
    relais_zone_fin: 'fuera',
    relais_marque_conseil: 'más adelante sales más rápido, pero puedes dejar la zona antes que el testigo. Más atrás lo recibes seguro — parado.',
    relais_attend_equipe: 'falta(n) {n} compañero(s)',
    relais_temoin_a: 'TESTIGO EN',
    relais_spectateur: 'LOS DEMÁS ESTÁN CORRIENDO',
    relais_porte: 'LLEVA',
    relais_attends_temoin: 'ESPERA',
    relais_prends: 'COGE EL TESTIGO',
    relais_donne: 'PASA EL TESTIGO',
    relais_arrivee: 'RELEVO COMPLETADO',
    relais_elimine: 'EQUIPO ELIMINADO',
    relais_elimine_pourquoi: 'en la posta {r}: {c}',
    relais_passages: 'LOS TRES RELEVOS',
    relais_elimine_court: 'fuera',
    relais_fantome: 'FANTASMA',

    // confrontación entre equipos
    conf_titre: 'CORRER CONTRA OTROS EQUIPOS',
    conf_desc: 'un disparo, un orden de llegada. Abre un código y compártelo, o introduce el que te han dado.',
    conf_ouvrir: 'ABRIR UNA CONFRONTACIÓN',
    conf_rejoindre: 'UNIRSE',
    conf_code: 'código',
    conf_code_court: 'ese código es demasiado corto',
    conf_partage: 'COMPARTE ESTE CÓDIGO CON LOS DEMÁS EQUIPOS',
    conf_places: '{n} equipos en la pista',
    conf_engagees: '{n} DE {m} EQUIPOS',
    conf_attend_adversaire: 'hace falta al menos otro equipo, o un fantasma',
    conf_classement: 'ORDEN DE LLEGADA',
    conf_encore: 'los demás todavía están corriendo',

    // fantasmas de equipo
    fantome_titre: 'RETAR A LOS DIEZ MEJORES RECORRIDOS',
    fantome_desc: 'ya se han corrido: se repiten, y no pueden ser eliminados ni batidos en un relevo. Es la única forma de medirse con los mejores sin reunir a ocho personas.',
    fantome_aucun: 'aún no hay ningún recorrido registrado — el primer equipo que complete un relevo abre el baile.',
    fantome_choisis: '{n} de {m} elegidos',
    fantome_defier: 'RETARLOS',

    // campeonato
    champ_directs: 'los {n} primeros pasan',
    champ_reveal: 'LOS MEJORES PERDEDORES',
    champ_reveal_desc: 'no han ganado ninguna carrera. Salen del crono de todas ellas.',
    champ_continue: 'CONTINUAR',
    champ_sacre: '{n} se proclama campeón — ver el podio',
    champ_titre_duree: 'título durante tres meses',
    champ_rv_course: 'PRÓXIMA CARRERA',
    champ_rv_reveal: 'MEJORES PERDEDORES REVELADOS',
    champ_rv_sacre: 'CEREMONIA',
    champ_quitter: 'salir del campeonato',

    // calles en directo
    live_lanes: 'CALLES',
    live_lanes_duel: 'un duelo: el ganador se lleva puntos, el perdedor devuelve algunos',
    live_lanes_course: 'una carrera: un orden de llegada, sin puntos de duelo',
    live_won: 'CARRERA GANADA',
    live_sur: 'DE {n} PARTICIPANTES',
    live_ordre: 'ORDEN DE LLEGADA',
    live_lost: 'CARRERA PERDIDA',

    // presentación y micro
    pres_title: 'PRESENTACIÓN DE LOS ATLETAS',
    pres_lane: 'CALLE',
    pres_you: 'ESE ERES TÚ',
    pres_mic_on: 'MICRO ABIERTO',
    pres_mic_off: 'micro rechazado',
    mic_winner: 'HABLA EL GANADOR',

    // vídeo de la carrera
    review_title: 'EL VÍDEO DE TU CARRERA',
    review_making: 'grabando…',
    review_dl: 'DESCARGAR',
    review_left: 'se borra en {t}',
    review_gone: 'el vídeo se ha borrado',
    review_kept: 'lo que has descargado se queda en tu teléfono',
    review_none: 'este dispositivo no puede grabar la carrera',
    live_tie: 'LLEGADA IGUALADA',
    live_vs: 'en directo contra {n}',
    live_gap: '{s} s de diferencia',
    link_in_app: '¿JUEGO INSTALADO?',
    link_in_app_sub: 'ábrelo desde tu pantalla de inicio e introduce este código — toca para copiar',

    // retos recibidos
    duel_answered: 'HAN RESPONDIDO A TU RETO',
    duel_more: 'queda {n} resultado más',
    duel_mores: 'quedan {n} resultados más',
    duel_next: 'SIGUIENTE',
    duel_ok: 'ENTENDIDO',

    // fantasma
    ghost_mode: 'MODO FANTASMA',
    ghost_ahead: 'DELANTE',
    ghost_behind: 'DETRÁS',
    ghost_level: 'IGUALADO',
    ghost_home: 'el fantasma ha cruzado la meta',
    ghost_live: 'el fantasma corre a tu lado',
    duel_must: 'envía un reto, o responde al de un amigo',
    duel_empty: 'aún no has jugado ningún duelo',
    duel_pts: 'pts',

    // los otros mundos
    monde_sprinter_sous: 'la recta y la vuelta',
    monde_hurdlers_sous: 'la misma calle, con diez obstáculos dentro',
    monde_jumper_sous: 'construye la carrera y despega del suelo',
    monde_thrower_sous: 'un círculo, un artefacto y todo el cuerpo',
    monde_bientot: 'PRONTO',
    monde_retour: 'VOLVER A SPRINTER',

    // disciplinas
    disc_100: '100 METROS',
    disc_200: '200 METROS',
    disc_400: '400 METROS',
    disc_100h: '100 M VALLAS',
    disc_110h: '110 M VALLAS',
    disc_400h: '400 M VALLAS',
    disc_longueur: 'SALTO DE LONGITUD',
    disc_hauteur: 'SALTO DE ALTURA',
    disc_triple: 'TRIPLE SALTO',
    disc_perche: 'SALTO CON PÉRTIGA',
    disc_poids: 'LANZAMIENTO DE PESO',
    disc_marteau: 'LANZAMIENTO DE MARTILLO',
    disc_disque: 'LANZAMIENTO DE DISCO',
    disc_javelot: 'LANZAMIENTO DE JABALINA',

    // pullas
    pique_0: 'Ni siquiera he tenido que intentarlo.',
    pique_1: '¿quieres que lo repita a cámara lenta?',
    pique_2: 'me ha dado tiempo a aburrirme.',
    pique_3: 'la meta está por aquí.',
    pique_4: 'gracias por el calentamiento.',
    pique_5: 'he mirado atrás y no había nadie.',
    pique_6: '¿has corrido? no he visto pasar nada.',
    pique_7: 'guarda ese crono, será un bonito recuerdo.',

    // dejar un mensaje
    mot_titre: 'DÉJALE UNAS PALABRAS A {n}',
    mot_placeholder: 'pínchale en dos líneas',
    mot_vocal: 'VOZ',
    mot_ecouter: 'ESCUCHAR',
    mot_refaire: 'grabar otra vez',
    mot_envoyer: 'ENVIAR',
    mot_envoye: '{n} lo leerá cuando vuelva',
    mot_micro_refuse: 'has rechazado el micro — el texto también sirve',
    mot_ecouter_sa_voix: 'ESCUCHAR LO QUE HA DICHO',
    mot_ephemere: 'esta grabación desaparece al cerrar esta ventana',
    mot_illisible: 'este mensaje no se puede reproducir en este dispositivo',

    // moderación
    mod_signaler: 'denunciar',
    mod_titre: '¿Por qué lo denuncias?',
    mod_explique: 'Una denuncia la lee una persona. El bloqueo surte efecto de inmediato.',
    mod_insulte: 'insulto',
    mod_haine: 'odio, racismo',
    mod_sexuel: 'sexual',
    mod_menace: 'amenaza',
    mod_autre: 'otro',
    mod_envoye: 'Denunciado. Alguien lo leerá.',
    mod_deja: 'ya denunciado',
    mod_bloquer: 'bloquear a {n}',
    mod_bloque: '{n} ya no puede escribirte.',
    mod_annuler: 'cancelar',

    // revancha
    duel_revanche: 'QUIERO LA REVANCHA',
    duel_revanche_sub: 'misma prueba — ahora te toca poner el crono',
    duel_renvoyer: 'devolverle el código a {n}',
    duel_revanche_envoyee: 'REVANCHA ENVIADA',
    os_revanche_sans_cible: 'no se ha podido avisar a {n} — envíale tú el código',
    duel_revanche_ratee_titre: 'TODAVÍA NO',
    duel_revanche_ratee: 'necesitabas menos de {s} s para devolverle el reto a {n} — no ha salido nada',

    // divisiones
    rang_departemental: 'PROVINCIAL',
    rang_regional: 'REGIONAL',
    rang_national: 'NACIONAL',
    rang_elite: 'ÉLITE',
    rang_legende: 'LEYENDA',
    rang_court_departemental: 'PRO',
    rang_court_regional: 'REG',
    rang_court_national: 'NAC',
    rang_court_elite: 'ÉLITE ',
    rang_court_legende: 'LEYENDA',
    duel_lp: 'PL',
    duel_monte_a11y: 'sube {n} puestos',
    duel_descend_a11y: 'baja {n} puestos',
    duel_lp_long: 'puntos de liga',
    duel_promu: 'ASCENDIDO A {r}',
    duel_relegue: 'DESCENDIDO A {r}',
    duel_reste: '{n} para la siguiente división',
    duel_regle: 'responder a un reto paga más que enviarlo: el crono ya está puesto, y sabes lo que hay que batir.',
    duel_record: '{v}V · {d}D · {n}E',
    duel_you: 'TÚ',
    duel_since: 'desde tu última visita',
    duel_unranked: 'aún sin clasificar — juega un duelo',
    duel_won: 'DUELO GANADO',
    duel_lost: 'DUELO PERDIDO',
    duel_tie: 'EMPATE',
    duel_final: 'resultado definitivo — un reto no se repite',
    duel_delta: '{p} punto',
    duel_deltas: '{p} puntos',

    // salida nula
    false_out: 'SALIDA NULA',
    false_out_sub: 'eliminado — el duelo está perdido',
    false_out_seul: 'eliminado — esta carrera acaba aquí',
    false_out_rule: 'una sola carrera, sin segunda oportunidad',
    false_out_libre: 'puedes volver a correrla',
    false_out_gun: 'has salido antes del disparo',
    duel_await: 'resultado del duelo…',
    duel_vs: 'contra {n}',
    duel_seen: 'duelo ya resuelto',
    duel_see: 'VER LA CLASIFICACIÓN',

    // one shot
    os_once: 'una vez enviado el reto, el crono es definitivo',
    os_rejouer: 'CORRER OTRA VEZ',
    os_rejouer_sub: 'una carrera más, ahora mismo — esta se queda como está',
    os_defier: 'RETAR A ALGUIEN',
    os_defier_sub: 'abre la clasificación y elige rival — otro, o el mismo',
    relance_gagne_0: 'VE A POR OTRO',
    relance_gagne_0_sub: 'ese ya está. Siguiente.',
    relance_gagne_1: 'EL SIGUIENTE, POR FAVOR',
    relance_gagne_1_sub: 'la clasificación está llena de gente, y tú estás en racha.',
    relance_gagne_2: '¿QUIÉN MÁS?',
    relance_gagne_2_sub: 'pregúntale a la clasificación. Alguien responderá.',
    relance_perdu_0: 'MÉTETE CON ALGUIEN MÁS PEQUEÑO',
    relance_perdu_0_sub: 'baja una división — nadie tiene por qué enterarse',
    relance_perdu_1: 'BUSCA A ALGUIEN MÁS LENTO',
    relance_perdu_1_sub: 'existen. Estadísticamente, existen.',
    relance_perdu_2: 'TODAVÍA QUEDAN PRINCIPIANTES',
    relance_perdu_2_sub: 'no sospechan nada. Es el momento.',
    os_defi_sans_cible: '{n} no está en el TOP 500 de esta prueba — envíale tú el código',
    os_verrou_direct: 'carrera en directo: tu rival ha corrido en el mismo momento — ese resultado se mantiene',
    os_verrou_recu: 'ese crono ya ha llegado a tu rival — no se puede retirar',
    os_verrou_envoye: 'el reto está enviado — ese es el crono que tiene que batir',
    os_verrou_faux: 'salida nula en un duelo: la carrera está perdida. Envía un reto nuevo para empezar de cero.',
    cut_skip: 'SALTAR',

    // identidad
    id_title: 'TU NOMBRE',
    id_code_title: 'CÓDIGO DE RECUPERACIÓN',
    id_code_note: 'apúntalo: vincula tus otros dispositivos a este nombre e impide que nadie te lo quite',
    id_show: 'VER MI CÓDIGO',
    id_reserve: 'RESERVAR',
    id_taken: 'este nombre ya está cogido',
    id_taken_help: 'si es tuyo, introduce su código de recuperación',
    id_link: 'VINCULAR',
    id_linked: 'dispositivo vinculado a {n}',
    id_bad_code: 'código incorrecto',
    id_unknown: 'nombre desconocido',
    id_link_title: '¿OTRO DISPOSITIVO?',
    id_link_help: 'introduce tu nombre y tu código para recuperar aquí tus cronos y tu historial',

    // instalación
    install_title: 'INSTALAR EL JUEGO',
    install_why: 'pantalla completa, sin barra del navegador, y se juega sin conexión',
    install_do: 'INSTALAR',
    install_later: 'más tarde',
    install_ios_1: 'Toca',
    install_ios_2: 'Compartir',
    install_ios_3: 'abajo en Safari, y luego',
    install_ios_4: 'Añadir a pantalla de inicio',

    // modos y categorías
    mode_career_s: 'carrera deportiva',
    mode_oneshot_s: 'one shot',
    cat_race_sub: 'mejor crono en una sola carrera',
    cat_run_sub: 'total de las seis etapas',
    empty_cat_run: 'aún no hay ningún recorrido completo registrado',
    will_enter: '{s} s: {r} en el TOP 500, pon tu nombre',

    // récord del mundo
    wr_title: 'RÉCORD DEL MUNDO',
    wr_sub: 'mejor crono del mundo en {d} m',
    wr_old: 'récord anterior: {s} s',
    wr_first: 'primer crono en el tablón',
    wr_gain: '{s} s más rápido',
    wr_save: 'PONER MI NOMBRE',
    wr_saving: 'guardando...',
    wr_done: '{n} es {r} en el TOP 500',
    wr_fail: 'no se pudo enviar, inténtalo otra vez',
    wr_see: 'VER EL TOP 500',
    wr_later: 'más tarde',
    os_top_checking: 'comprobando las clasificaciones...',
    os_top_none: 'ningún crono entra en el TOP 500',
    os_top_intro: '{n} crono entra en el TOP 500',
    os_top_intro_n: '{n} cronos entran en el TOP 500',
    os_top_line: '{d} m — {s} s — {r}',
    os_top_saved: 'cronos guardados como {n}',
    top500_count: '{n} cronos clasificados de 500',
    os_top_better: 'tu récord de {d} m sigue en {s} s',
    os_kept_title: 'TU RÉCORD SE MANTIENE',
    os_kept_line: '{d} m: ya tienes {s} s ({r} en el TOP 500)',
    os_kept_now: 'estos {s} s no lo baten — la clasificación solo guarda tu mejor crono',

    // pausa
    pause_title: 'CARRERA EN PAUSA',
    pause_note: 'si sales ahora pierdes el crono actual',
    resume: 'CONTINUAR',

    // retos
    challenge_them: 'RETAR',
    target_run: 'corre tus {d} m: el reto va para {n}',
    target_sent: 'reto enviado a {n}',
    inbox_one: 'RETO RECIBIDO',
    inbox_many: '{n} RETOS RECIBIDOS',
    inbox_from: '{n} te reta en {d} m',
    inbox_accept: 'ACEPTAR',
    inbox_later: 'más tarde',
    run_total_short: 'recorrido completo:',
    run_total_tiny: 'recorrido',
    best_split_tiny: 'carrera',
    score_saved_race: '{r} en el TOP 500 mundial con {s} s',
    mode_career: 'CARRERA DEPORTIVA',
    mode_oneshot: 'ONE SHOT',
    mode_versus: 'RETO',
    career_desc: 'las seis etapas seguidas, un solo crono',
    oneshot_desc: 'elige tus pruebas, un solo intento',
    versus_desc: 'corre contra el fantasma de otro jugador',
    pick_events: 'PRUEBAS',
    pick_level: 'NIVEL',
    pick_none: 'elige al menos una prueba',
    launch_oneshot: 'VAMOS',
    event_n: 'PRUEBA {n} / {t}',
    next_event: 'SIGUIENTE PRUEBA',
    oneshot_done: 'ONE SHOT COMPLETADO',
    total_in: 'total: ',
    challenge_code: 'CÓDIGO DE RETO',
    challenge_enter: 'introduce el código que te han dado',
    challenge_load: 'CARGAR',
    challenge_loading: 'cargando el reto...',
    challenge_bad: 'código no encontrado',
    challenge_net: 'fallo de conexión, inténtalo otra vez',
    challenge_from: 'reto de {n}',
    challenge_beat: 'a batir: {s} s',
    challenge_aveugle: 'descubrirás su crono corriendo',
    challenge_accept: 'ACEPTAR EL RETO',
    challenge_make: 'RETAR A UN AMIGO',
    challenge_making: 'creando el reto...',
    challenge_share: 'envía este código y tu amigo correrá contra tu fantasma',
    challenge_copy: 'COPIAR ENLACE',
    challenge_copied: 'enlace copiado',
    challenge_copy_code: 'COPIAR CÓDIGO',
    share_send: 'ENVIAR EL RETO',
    share_whatsapp: 'WhatsApp',
    share_sms: 'SMS',
    share_other: 'Snapchat, Instagram…',
    share_other_hint: 'Snapchat e Instagram se abren desde el menú de compartir.',
    affiche_share: 'COMPARTIR MI RECORRIDO',
    affiche_making: 'Creando la imagen…',
    affiche_saved: 'imagen guardada',
    affiche_failed: 'no se pudo crear la imagen',
    affiche_hint: 'una imagen de tu recorrido, para Instagram o TikTok',
    code_copied: 'código copiado',
    challenge_rematch: 'DEVOLVER EL RETO',
    challenge_rematch_sub: 'has ganado — rétale en el recorrido que acabas de hacer',
    challenge_won: 'RETO GANADO',
    challenge_lost: 'RETO PERDIDO',
    challenge_gap: 'diferencia: {s} s',
    ghost_label: 'FANTASMA',
    you_label: 'TÚ',
    dnf_short: 'ABD',
    composing: 'componiendo la banda sonora...',

    // teclado
    sound_off: 'SONIDO APAGADO  (S)',
    press_enter: 'pulsa INTRO',
    skip_now_kb: 'pulsa INTRO otra vez para saltar',
    skip_twice_kb: 'pulsa INTRO dos veces para saltar',
    stage_dash: 'ETAPA {n}   -   {s}',
    furthest_kb: 'etapa más lejana alcanzada: {a} de {b}',
    enter_start: 'INTRO: empezar   -   S: sonido   -   L: idioma   -   ESC: salir',
    how_to_play: 'CÓMO SE JUEGA',
    help_1: 'Alterna  <-  y  ->  sin',
    help_2: 'repetir la misma tecla.',
    help_3: 'Un ritmo constante da velocidad;',
    help_4: 'repetir te hace tropezar, pero',
    help_5: 'siempre puedes volver a arrancar.',
    best_stage: 'MEJORES CRONOS DE ESTA ETAPA',
    no_time: 'aún no hay ningún crono registrado',
    arrows_pick: 'flechas para elegir   -   INTRO para confirmar   -   ',
    yn_short: 'atajo S / N',
    you_beat: 'Has batido a {w} y superado las seis etapas.',
    the_zeze: 'los ZEZE',
    your_times: 'TUS CRONOS',
    total: 'TOTAL',
    enter_replay: 'INTRO: correr otra vez      M: inicio',
    stumble_kb: '¡TROPIEZAS!',
    go_kb: '¡YA!',
    to_beat_line: 'A BATIR:  {n}   -   {s} s',
    best_times_of: 'MEJORES CRONOS  -  {s}',
    enter_next: 'INTRO   ->   ETAPA {n}: {s}',
    full_run_pc: 'recorrido completo en {s} s',
    announced_pc: 'crono anunciado: {s} s',
    quit: 'ESC: salir'
  },

  CUTS: {
    intro: [
      [ // etapa 1
        ['{n} lleva tres años ganando todas las carreras del patio.',
         'Su secreto: nadie se atreve a adelantarle, el balón es suyo.',
         'Calienta con zapatos de colegio, por principio.',
         'Su madre graba desde detrás de la valla. Sobre todo la valla.'],
        ['{n} tiene el récord del colegio, escrito con rotulador en la pared del gimnasio.',
         'Lo cronometró un compañero, con un reloj de agujas.',
         'El profesor de gimnasia asintió una vez. Con eso quedó oficial.',
         'Ahora repintan la pared alrededor del récord.'],
        ['{n} pidió la calle 4. Le dieron la calle 4.',
         'Hace sus ejercicios: rodillas altas, talones al glúteo, suspiros hondos.',
         'Su dorsal está impreso en casa, un poco torcido.',
         'El número es el 1. Lo imprimió él mismo, solo.']
      ],
      [ // etapa 2
        ['{n} lleva cuatro horas calentando.',
         'Su chándal lleva su nombre bordado en la espalda, en mayúsculas.',
         'Tiene un ritual: tres pasos atrás, una respiración, un guiño.',
         'El guiño no va dirigido a nadie en particular.'],
        ['{n} llega con dos pares de clavos y una nevera portátil.',
         'La nevera contiene un plátano y una enorme determinación.',
         'Ajusta los tacos al milímetro, y luego los vuelve a ajustar.',
         'Y una tercera vez. El juez de salida espera, educadamente.'],
        ['{n} quedó segundo en el regional del año pasado.',
         'Lo describe como una victoria que le robó el viento de cara.',
         'La medición oficial dijo viento nulo. Él discute la medición.',
         'Ha traído su propio anemómetro. No sabe usarlo.']
      ],
      [ // etapa 3
        ['{n} ha salido en la televisión regional.',
         'Treinta y ocho segundos de imagen. Los ha visto seiscientas veces.',
         'Firma autógrafos antes de la carrera, para ganar tiempo.',
         'En tiques de la compra, a falta de algo mejor.'],
        ['{n} tiene un apodo que no usa nadie: la Flecha del Norte.',
         'Lo cuela él mismo en todas las entrevistas.',
         'El locutor acaba de presentarlo con su nombre real, por error.',
         'Ha pedido una rectificación por megafonía. Llegará más tarde.'],
        ['{n} se tatuó su marca personal en el antebrazo.',
         'La enseña a cámara lenta durante la presentación de los atletas.',
         'Cuatro corredores de esta final ya han batido ese número.',
         'El tatuaje, por desgracia, no se actualiza.']
      ],
      [ // etapa 4
        ['{n} tiene un patrocinador, un agente y un fisioterapeuta.',
         'Los tres le dicen que es imbatible. A los tres les paga él.',
         'Su agente ya ha reservado la sala para la rueda de prensa de la victoria.',
         'El catering está encargado. Hay canapés.'],
        ['{n} lleva once meses siendo el número uno del mundo.',
         'Se enteró en directo y desde entonces no ha mirado atrás.',
         'Literalmente: su fisio se lo desaconsejó con firmeza.',
         'Ahora gira el torso entero. Más lento, pero queda elegante.'],
        ['El locutor anuncia a {n}. El estadio se pone en pie.',
         'Señala a la grada, luego al cielo, luego a la cámara.',
         'La cámara estaba en otro atleta. Empieza todo otra vez.',
         'El realizador cede. El gesto durará once segundos.']
      ],
      [ // etapa 5
        ['{n} lleva ocho meses ensayando su celebración.',
         'La ha registrado como marca. Solo falta ganar la carrera.',
         'Un coro de cuarenta personas espera su señal.',
         'Se han aprendido una canción. La canción dice su nombre, largo rato.'],
        ['{n} viste los colores de su país, y le importa de verdad.',
         'La bandera está en los clavos, en el dorsal y en la toalla.',
         'La toalla no corre, pero está lista desde el martes.',
         'Un miembro del equipo la lleva a todas partes desde la ceremonia de apertura.'],
        ['{n} juró que no miraría a sus rivales en los tacos.',
         'Así que mira al frente, con una intensidad notable.',
         'Un poco demasiado al frente: miró a la pared durante la presentación.',
         'La pared no se clasificó para esta final.']
      ],
      [ // etapa 6
        ['{n} viene de un universo donde la gravedad es opcional.',
         'Termina sus carreras antes de decidir empezarlas.',
         'Su récord está vigente en once dimensiones a la vez.',
         'En la duodécima tropezó, pero eso nadie lo saca.'],
        ['{n} ha corrido estos cien metros en once universos paralelos.',
         'Ganó los once. El duodécimo nunca se homologó.',
         'Allí el juez de meta era una nebulosa, poco fiable en la línea.',
         'La nebulosa fue suspendida tres temporadas.'],
        ['La familia ZEZE ocupa las siete calles. Es reglamentario.',
         'Han traído su propio juez de salida, su propio viento, su propia meta.',
         'El reglamento lo escribió un ZEZE y lo revisó un ZEZE.',
         'Tiene una sola frase: gana un ZEZE.']
      ]
    ],

    defeat: [
      [ // etapa 1
        ['{n} recurre el resultado ante el vigilante del comedor.',
         'El vigilante se está comiendo un bocadillo. El resultado se mantiene.',
         'Después le pide un fallo al delegado de clase.',
         'El delegado de clase quedó último. Lo está disfrutando.'],
        ['{n} explica que el suelo del patio está irregular.',
         'Lleva irregular para todo el mundo desde mil novecientos sesenta.',
         'Después menciona un cordón desatado. Sus zapatos son de velcro.',
         'El profesor escribe tu crono en la pared. Justo encima del suyo.'],
        ['{n} anuncia que en realidad no estaba corriendo.',
         'Estaba calentando. La carrera de verdad era la siguiente.',
         'Nadie lo sabía, lo que explica muchas cosas.',
         'Suena el timbre. La carrera siguiente no llegará nunca.']
      ],
      [ // etapa 2
        ['{n} explica que su reloj no llegó a arrancar.',
         'Así que, técnicamente, esta carrera no ha existido.',
         'Se ofrece a repetirla ahora mismo, entre gente seria.',
         'Luego recuerda que tiene un tren. No tiene ningún tren.'],
        ['{n} pide ver la foto de llegada.',
         'Le enseñan la foto. Claramente detrás, y muy bien enfocado.',
         'Pide la misma foto desde otro ángulo.',
         'Desde ese ángulo sigue detrás, pero algo más borroso.'],
        ['{n} guarda los dos pares de clavos sin decir palabra.',
         'Anuncia que se pasa al 400, una prueba más táctica.',
         'Luego al 800. Luego al maratón, donde todo acaba de todas formas.',
         'Se va con su nevera. El plátano sigue intacto.']
      ],
      [ // etapa 3
        ['{n} anuncia su retirada en directo.',
         'Luego se lo repiensa: vuelta a los entrenamientos el lunes.',
         'Señala que ese lunes en concreto lo tiene muy cargado.',
         'El lunes siguiente también, resulta.'],
        ['{n} exige un control antidopaje para el ganador.',
         'Y luego uno para él, en aras de la equidad.',
         'Los dos dan negativo. Le parece sospechoso.',
         'Pide un tercer control. Al equipo de cronometraje.'],
        ['{n} les enseña el antebrazo a los periodistas.',
         'El récord tatuado no se ha movido. Menos da una piedra.',
         'Anuncia seis semanas de concentración en altura.',
         'La montaña que ha elegido mide doscientos metros.']
      ],
      [ // etapa 4
        ['{n} exige una segunda medición del viento.',
         'Se convoca al viento. El viento no comparece.',
         'La rueda de prensa de la victoria sigue adelante, ya no hay forma de anularla.',
         'Los canapés están excelentes. Algo es algo.'],
        ['{n} mira la pantalla gigante durante veinte segundos.',
         'La clasificación no cambia. La pantalla tampoco.',
         'Pregunta si la señal es en directo. Le dicen que sí.',
         'Pregunta entonces si hay una señal diferida. No la hay.'],
        ['En la zona mixta, {n} habla de progresión y de proceso.',
         'Usa la palabra ciclo once veces en dos minutos.',
         'Un periodista le pregunta su crono. Responde: el crono llegará.',
         'Su crono ya está en el marcador detrás de él, muy grande.']
      ],
      [ // etapa 5
        ['{n} hace su celebración de todos modos.',
         'El público aplaude, por educación.',
         'El coro, mal informado, arranca con la canción.',
         'Cuarenta personas cantan su nombre. Habría preferido el silencio.'],
        ['{n} da su vuelta de honor con la bandera, según lo previsto.',
         'El ganador da la misma vuelta, en sentido contrario.',
         'Se cruzan dos veces. La segunda es peor.',
         'La toalla no lo vio venir.'],
        ['{n} se sube al segundo escalón del podio.',
         'Felicita al ganador con un apretón de manos larguísimo.',
         'Lo bastante largo para repetir la foto oficial tres veces.',
         'En la tercera sonríe. Se nota lo que le cuesta.']
      ],
      [ // etapa 6
        ['{n} recalcula la trayectoria de su galaxia.',
         'Resulta que pasaba justo por el segundo puesto.',
         'Alega una anomalía temporal, y luego un problema con sus zapatillas.',
         'Las dos explicaciones se contradicen. Se queda con las dos.'],
        ['{n} pide la clasificación de los otros once universos.',
         'En los once acaba de perder también. Simultáneamente.',
         'Se ofrece a abrir un duodécimo, solo por ver.',
         'El duodécimo está ocupado. Allí también llegaste primero.'],
        ['Los otros seis ZEZE miran a {n} con mucha calma.',
         'Nadie dice una palabra. El silencio dura cuatro años luz.',
         '{n} acaba proponiendo: hoy el suelo estaba distinto.',
         'El suelo no ha cambiado desde que se construyó la pista.']
      ]
    ],

    taunt: [
      [ // etapa 1
        ['{n} señala el marcador, sin decir palabra.',
         'Ya lo ha firmado. Con rotulador permanente.',
         'Te da su bocadillo. "Para el camino", dice.',
         'Tú no habías pedido ningún bocadillo.'],
        ['{n} da una vuelta de honor. Tres metros, por falta de sitio.',
         'Saluda largamente a un público imaginario.',
         'Te ofrece la revancha. Luego mira su reloj.',
         'No tiene reloj. El gesto ya lo decía todo.'],
        ['{n} recoge sus cosas tranquilamente, silbando.',
         'La melodía es tu nombre, con música de marcha triunfal.',
         'Te da una palmada en el hombro. "La próxima", dice.',
         'No se lo cree ni por un segundo, y se le nota.']
      ],
      [ // etapa 2
        ['{n} mira el crono, y luego te mira a ti, con intención.',
         'No dice nada. El silencio es más cruel que las palabras.',
         'Firma autógrafos. El primero es para ti.',
         'Eso tampoco lo habías pedido.'],
        ['{n} llama a su entrenador. "Hemos terminado pronto", le dice.',
         'El entrenador pregunta por qué. "Por educación", responde.',
         'Te ofrece sostener su medalla. Solo un momento.',
         'El momento dura diez minutos. Hace fotos.'],
        ['{n} guarda sus clavos en una funda con tu nombre.',
         'Es una broma privada. El público no la sigue.',
         'Te ofrece agua de su botella. Está vacía.',
         'El gesto, dice, importa más que el agua.']
      ],
      [ // etapa 3
        ['{n} saluda a la cámara. Después te saluda a ti.',
         'El segundo saludo es bastante menos cordial.',
         'Comenta tu carrera con los periodistas, en detalle.',
         'Su detalle favorito: el momento en que miraste atrás.'],
        ['{n} pide el micrófono. Se lo dan, contra todo criterio.',
         'Da las gracias a su familia, a su club y a ti, en ese orden.',
         '"Sin él", dice, "no habría sabido igual".',
         'No aclara a qué se refiere. No hace falta.'],
        ['{n} se ofrece a repasar tu carrera juntos, con calma.',
         'El repaso dura una palabra. La dice muy despacio.',
         'Te da la mano dos veces seguidas, por si acaso.',
         'La primera no le pareció bastante convincente.']
      ],
      [ // etapa 4
        ['{n} da una entrevista. El tema eres tú, curiosamente.',
         'Tres minutos. Ni una palabra sobre su propia carrera.',
         'Concluye diciendo que ha aprendido mucho. De tu derrota.',
         'El periodista lo apunta palabra por palabra, incómodo.'],
        ['{n} le hace una señal a su agente para añadir una línea al palmarés.',
         'La línea dice simplemente: contra ti, una vez más.',
         'Te invita a la rueda de prensa de la victoria.',
         'Te espera una silla, justo al fondo, sin micrófono.'],
        ['{n} te enseña la clasificación en su móvil, haciendo zoom.',
         'Hace zoom un buen rato. Tu línea queda muy por debajo de la suya.',
         '"Puedo mandártela por correo", ofrece, servicial.',
         'Tú no le diste tu dirección. Él ya la tiene.']
      ],
      [ // etapa 5
        ['{n} saluda a la grada, y luego se vuelve hacia ti, solemne.',
         'El gesto que hace después no figura en ningún reglamento.',
         'Un periodista le pide unas palabras para el rival derrotado.',
         'Dice siete. Ninguna saldrá en el artículo.'],
        ['{n} sube al podio, y luego baja un escalón.',
         'Te invita a ver la medalla de cerca.',
         'Muy de cerca. Es de oro. Insiste en ese punto.',
         'Empieza el himno. Canta fuerte, mirándote.'],
        ['{n} dedica su victoria a su familia, a sus patrocinadores y a ti.',
         '"Sin un rival tan motivador", dice, sincero.',
         'La palabra motivador suena a insulto sabiamente disfrazado.',
         'El público aplaude, sin entender por qué te pones rojo.']
      ],
      [ // etapa 6
        ['{n} mira a los otros seis ZEZE. Asienten, todos a la vez.',
         'El veredicto es unánime, y se dicta sin un solo sonido.',
         'Se graba una placa conmemorativa, en una lengua muerta.',
         'Dice, en esencia: lo intentó. Algo es algo.'],
        ['{n} recalcula tu posición en once dimensiones distintas.',
         'En todas ellas el resultado es idéntico, al segundo.',
         'Te regala un mapa del universo en el que habrías ganado.',
         'Ese universo, precisa, todavía no existe.'],
        ['{n} tiende la mano al cielo. Una galaxia se ilumina, dócil.',
         'Durante un instante forma la silueta de su sonrisa.',
         'Los siete ZEZE se consultan, y luego se vuelven hacia ti.',
         'El silencio que sigue dura cuatro años luz. Educadamente.']
      ]
    ],

    champion: [
      ['Los siete ZEZE deliberan largamente.',
       'Ninguno encuentra una excusa admisible. Es la primera vez.',
       'La clasificación se actualiza en catorce mil millones de sistemas.',
       'Se coloca una placa en la línea de meta.',
       'Tu nombre está mal escrito, pero está.'],
      ['El locutor busca una palabra. Ninguna le parece bastante grande.',
       'Se limita a leer el crono, dos veces, para asegurarse.',
       'Siete ZEZE miran la pantalla gigante sin decir nada.',
       'Se crea una comisión para revisar la línea de meta.',
       'La línea está recta. La clasificación también.'],
      ['La vuelta de honor dura más que la carrera.',
       'Es aritmética simple, y nadie se queja.',
       'Te dan una bandera. No sabes de qué galaxia viene.',
       'Viene de todas: han fusionado los diseños para la ocasión.',
       'El coro ha reescrito su canción. Dice tu nombre, por fin.']
    ]
  }
};
