/* -----------------------------------------------------------------------
   SPRINTER — Bahasa Indonesia.
   Ce qui manque ici retombe sur l'anglais, cle par cle : voir
   sprinter-i18n.js. Verification : node tools/langues-verifier.mjs id
   ----------------------------------------------------------------------- */
export default {
  // Dalam bahasa Indonesia: ke-1, ke-2, ke-3.
  ord(n) { return 'ke-' + n; },

  LEVEL_NAMES: [
    'Lomba sekolah', 'Tingkat daerah', 'Tingkat nasional',
    'Kejuaraan Dunia', 'Pesta Olahraga Dunia', 'Antargalaksi'
  ],

  RACE_SUB: {
    '100': 'lintasan lurus',
    '200': 'tikungan dan lurus',
    '400': 'satu putaran lintasan'
  },

  UI: {
    races: '100 - 200 - 400 METER',
    tagline: 'enam tahap, satu catatan waktu untuk dikalahkan',
    tap_start: 'sentuh layar untuk mulai',
    six_stages: '   -   enam tahap',
    six_stages_bare: 'enam tahap',
    best_runs: 'LARI TERBAIK',
    no_run: 'belum ada rangkaian yang selesai',
    furthest: 'tahap terjauh: ',
    of_six: ' dari 6',
    start: 'MULAI',
    sound: 'suara: ',
    yes: 'ya',
    no: 'tidak',

    rival: 'PELARI YANG HARUS DIKALAHKAN',
    favourite: 'Sang unggulan',
    after_race: 'SETELAH LOMBA',
    crowned: 'GELAR ANTARGALAKSI',
    fastest_1: 'MAKHLUK TERCEPAT',
    fastest_2: 'DI SEGALA GALAKSI',
    full_run_in: 'rangkaian penuh dalam ',
    announced: 'waktu yang diumumkan: ',
    stage_up: 'TAHAP ',
    six_cleared: 'ENAM TAHAP DILEWATI',
    skip_now: 'sentuh lagi untuk melewati',
    skip_twice: 'sentuh dua kali untuk melewati',

    reaction: 'REAKSI',
    react_top: 'REAKSI SEMPURNA',
    false_start: 'START TERLALU CEPAT',
    wait_gun: 'tunggu tembakan',
    phase_drive: 'DORONGAN',
    phase_trans: 'TRANSISI',
    phase_max: 'KECEPATAN PUNCAK',
    drive_hint: 'mantapkan iramamu',
    trans_2: 'TRANSISI SEMPURNA',
    trans_1: 'TRANSISI BAGUS',
    trans_0: 'TRANSISI GAGAL',
    start_line: 'start: reaksi {r} d   -   {g}',
    no_start: 'start terlewat',

    stumble: 'KAMU TERSANDUNG',
    to_beat: 'harus dikalahkan: ',
    to_race: 'kamu berlari melawan ',
    ready: 'BERSEDIA',
    get_set: 'SIAP',
    go: 'YA',
    alternate: 'tekan kedua tombol bergantian',
    alternate_kb: 'tekan kedua panah bergantian',
    you: 'KAMU',
    opponent: 'LAWAN',
    depart: 'START',
    arrivee: 'GARIS FINIS',

    stage_done: 'TAHAP {n} DILEWATI',
    first_in: 'peringkat pertama dengan ',
    total_of: ' d   -   total ',
    place: 'PERINGKAT {o}',
    dnf: 'tidak selesai',
    unfinished: 'belum selesai',
    race_again: 'SEKALI LAGI?',
    next_stage: 'TAHAP {n}',
    home: 'BERANDA',
    replay: 'MAIN LAGI',
    run_done: 'RANGKAIAN SELESAI',
    six_in: 'enam tahap dilewati dalam ',
    stage_low: 'tahap ',

    new_record: 'REKOR BARU',
    top3: 'TOP 3',
    top10: 'TOP 10',
    best_run: 'RANGKAIAN TERBAIK',
    top3_runs: 'TOP 3 RANGKAIAN',
    top10_runs: 'TOP 10 RANGKAIAN',

    top500: 'TOP 500 - SEPANJANG MASA',
    your_name: 'namamu',
    save_score: 'SIMPAN WAKTUKU',
    saving_score: 'mengirim...',
    score_saved: 'peringkat {r} di TOP 500 dunia',
    score_save_fail: 'gagal mengirim, coba lagi nanti',
    score_name_taken: 'nama ini milik perangkat lain',
    score_taken_help: 'pilih nama lain, atau hubungkan perangkat ini ke namamu di LOMBAKU dengan kode pemulihan',
    view_top500: 'LIHAT TOP 500',
    top500_court: 'TOP 500',
    close: 'TUTUP',
    loading_ranks: 'memuat peringkat...',
    empty_top500: 'belum ada catatan waktu',
    your_rank: 'PERINGKATMU: {r}',
    outside_top500: 'di luar 500 besar',
    edit_name: 'UBAH NAMA',
    best_split_short: 'tahap terbaik:',
    top500_sub: 'waktu terbaik dalam satu lomba',
    cat_race: 'PER LOMBA',
    cat_run: 'RANGKAIAN PENUH',
    cat_mine: 'LOMBAKU',
    cat_mine_sub: 'semua lomba yang kamu jalani',
    mine_empty: 'belum ada lomba di nomor ini',
    mine_count: '{n} lomba — terbaik: {s} d',
    mine_note: 'TOP 500 hanya menyimpan waktu terbaikmu per nomor; riwayat ini menyimpan semuanya. Pesan namamu agar bisa menemukannya di perangkat lain.',

    duel_title: 'PERINGKAT DUEL',
    duel_sub: 'tantangan yang dikirim dan dijawab',
    duel_open: 'LIHAT PERINGKAT DUEL',
    duel_rules_init: 'TANTANGAN DIKIRIM',
    duel_rules_recv: 'TANTANGAN DIJAWAB',
    duel_rules_line: 'menang {v}   ·   kalah {d}   ·   seri {n}',
    duel_rules_all: 'setiap duel dihitung, dikirim maupun dijawab',
    duel_rules_why: 'yang menantang adalah yang menunjukkan waktunya lebih dulu',
    duel_counts: '{l} dikirim · {r} dijawab',
    duel_sur: 'DUEL DILARIKAN DI',

    name_set: 'PILIH NAMAMU',
    name_title: 'NAMAMU',
    name_why: 'inilah yang tampil di TOP 500, pada tantanganmu dan dalam duel',
    name_save: 'SIMPAN',
    name_saved: 'TERSIMPAN',
    name_taken: 'nama itu sudah dipakai',
    name_code: 'KODE PEMULIHANMU',
    pays_title: 'KEWARGANEGARAANMU',
    pays_opt: 'hanya sekali',
    pays_aucun: 'pilih negaramu',
    pays_why: 'diperlukan untuk kejuaraan nasional — dan tidak bisa diubah setelahnya',
    pays_vu: 'sepertinya kamu terhubung dari {pays} — terserah kamu',
    pays_save: 'PILIH',
    pays_confirm: 'Berlari untuk {pays}?\n\nIni final: menentukan kejuaraan nasional mana yang kamu ikuti, dan tidak bisa diubah.',
    pays_fige: 'final',
    pays_on: 'kamu berlari untuk negara ini — benderanya menyertai namamu di kejuaraan',
    pays_deja: 'kewarganegaraanmu sudah dipilih dan tidak bisa diubah',
    pays_first: 'simpan namamu dulu',
    pays_bad: 'negara tidak sah',
    insta_title: 'INSTAGRAM-MU',
    insta_ph: 'nama penggunamu, tanpa @',
    insta_why: 'profilmu bisa dibuka dari TOP 500 dan dari tantanganmu',
    insta_note: 'kamu sendiri yang menyatakan, tanpa verifikasi — Instagram tidak lagi mengizinkan login sungguhan untuk akun pribadi',
    insta_link: 'HUBUNGKAN AKUNKU',
    insta_linked: 'AKUN TERHUBUNG',
    insta_unlink: 'PUTUSKAN',
    insta_on: 'profilmu tampil di TOP 500 — sentuh untuk membuka',
    insta_gone: 'akun diputuskan, profilmu tidak tampil di mana pun lagi',
    insta_bad: 'nama pengguna tidak sah',
    insta_first: 'simpan namamu dulu',
    insta_notyours: 'nama ini bukan milikmu di perangkat ini',
    insta_visit: 'lihat profil Instagram {n}',
    name_code_why: 'catat: kode ini mengembalikan nama dan lombamu di ponsel lain',

    tour_open: 'IKUTI TUR',
    tour_1_t: 'BERGANTIAN',
    tour_1_s: 'kiri, kanan, kiri. Seluruh lomba cuma itu.',
    tour_2_t: 'KARIER',
    tour_2_s: 'enam tahap, dari halaman sekolah sampai final antargalaksi',
    tour_3_t: 'TOP 500',
    tour_3_s: 'waktumu melawan seluruh dunia',
    tour_4_t: 'BAYANGAN',
    tour_4_s: 'kirim lombamu ke teman — dia berlari melawanmu',
    tour_5_t: 'LANGSUNG',
    tour_5_s: 'satu tembakan yang sama, masing-masing di ponsel sendiri',
    tour_play: 'BIARKAN AKU MAIN',

    os_tuto_open: 'UNTUK APA MODE INI',
    os_tuto_1_t: 'PILIH NOMORMU',
    os_tuto_2_t: 'HANYA SATU KESEMPATAN',
    os_tuto_3_t: 'WAKTUMU DIHITUNG',
    os_tuto_1_s: 'satu, dua, atau ketiganya',
    os_tuto_2_s: 'tanpa ulang, tanpa tersingkir',
    os_tuto_3_s: 'TOP 500, dan teman bisa menjawabnya',
    os_tuto_go: 'MULAI ONE SHOT',

    tuto_ask_t: 'LOMBA PERTAMA',
    tuto_ask_s: 'gerakannya dipelajari dalam tiga puluh detik',
    tuto_ask_yes: 'PELAJARI GERAKANNYA',
    tuto_ask_no: 'BIARKAN AKU LARI',
    tuto_watch: 'LIHAT',
    tuto_your_turn: 'GILIRANMU',
    tuto_1_t: 'BERGANTIAN',
    tuto_2_t: 'SAAT TEMBAKAN',
    tuto_3_t: 'LEBAR, LALU PENDEK',
    tuto_v_early: 'TERLALU CEPAT',
    tuto_v_late: 'terlambat',
    tuto_v_perfect: 'SEMPURNA',
    tuto_v_good: 'BAGUS',
    tuto_v_slow: 'BELUM CUKUP CEPAT',
    tuto_v_flat: 'IRAMA DATAR',
    tuto_replay_demo: 'lihat lagi',
    tuto_again: 'LAGI',
    tuto_next: 'LANJUT',
    tuto_done_t: 'GILIRANMU BERLARI',
    tuto_start: 'MULAI',
    tuto_replay: 'lihat lagi',
    tuto_skip: 'lewati',
    tuto_open: 'CARA BERMAIN',

    live_title: 'LOMBA LANGSUNG',
    live_desc: 'kalian start pada tembakan yang sama, masing-masing di ponsel sendiri — tanpa bayangan, tak ada yang tahu siapa menang',
    live_create: 'BUKA LINTASAN',
    live_join: 'GABUNG',
    live_or: 'atau',
    live_room: 'LINTASAN TERBUKA',
    live_waiting: 'kirim kode ini ke lawanmu — lomba mulai begitu kalian berdua',
    live_ready: 'SIAP',
    live_notready: 'BELUM',
    live_empty_seat: 'jalur kosong — menunggu lawan',
    live_go: 'AKU SIAP',
    live_unready: 'BATAL',
    live_leave: 'tinggalkan lintasan',
    live_none: 'tidak ada lintasan dengan kode itu',
    live_full: 'lintasan itu sudah penuh',
    live_gone: 'lawanmu meninggalkan lintasan',
    live_closed: 'sambungan terputus',
    live_invite: 'Aku menunggumu di lintasan. Kode {c} — {l}',

    relais_titre: 'ESTAFET 4 × 100',
    relais_desc: 'empat pelari, satu tongkat. Tim adalah susunannya: empat nama yang sama, tim yang sama.',
    relais_invitations: 'KAMU DIUNDANG',
    relais_mes_equipes: 'TIM-TIMMU',
    relais_creer: 'BENTUK TIM',
    relais_nom_equipe: 'nama tim',
    relais_coequipier: 'rekan {n}',
    relais_inviter: 'UNDANG KETIGANYA',
    relais_incomplet: 'perlu satu nama dan tiga rekan',
    relais_attend: 'menunggu',
    relais_ok: 'ikut',
    relais_refuse: 'menolak',
    relais_fixer_ordre: 'TENTUKAN URUTAN LARI',
    relais_manque_reponses: 'masih menunggu jawaban sebelum bisa berlari',
    relais_manque_refus: 'seorang rekan menolak — tim ini tidak bisa berlari',
    relais_prete: 'tim siap',
    relais_classement: 'KLASEMEN TIM',
    relais_plein_titre: 'DUA TIM, BUKAN TIGA',
    relais_plein: 'kamu sudah berlari untuk dua tim. Tinggalkan tim yang tidak kamu bela lagi untuk membentuk yang baru.',
    relais_plein_invit: 'kamu sudah berlari untuk dua tim — tinggalkan satu untuk menerima ini.',
    relais_quitter: 'KELUAR',
    relais_quitter_sur: 'keluar selamanya?',
    relais_quitter_sub: 'kamu hanya kembali lewat undangan baru',
    relais_reste: 'tersisa satu tempat',
    relais_place: '1 dari 2 tim',
    relais_places: '{n} dari 2 tim',
    relais_courir: 'KE LINTASAN',
    relais_mon_rang: 'kamu berlari di kaki ke-{n}',
    relais_premier: 'kamu start dari balok, berdiri. Start salah menggugurkan seluruh tim.',
    relais_ta_marque: 'TANDAMU DI ZONA',
    relais_zone_debut: 'masuk',
    relais_zone_fin: 'keluar',
    relais_marque_conseil: 'makin ke depan makin cepat startnya, tapi kamu bisa keluar zona sebelum tongkat tiba. Makin ke belakang pasti menerimanya — tapi dari diam.',
    relais_attend_equipe: 'masih kurang {n} rekan',
    relais_temoin_a: 'TONGKAT DI',
    relais_spectateur: 'YANG LAIN SEDANG BERLARI',
    relais_porte: 'MEMBAWA',
    relais_attends_temoin: 'TUNGGU',
    relais_prends: 'AMBIL TONGKAT',
    relais_donne: 'BERIKAN TONGKAT',
    relais_arrivee: 'ESTAFET SELESAI',
    relais_elimine: 'TIM TERSINGKIR',
    relais_elimine_pourquoi: 'di kaki ke-{r}: {c}',
    relais_passages: 'TIGA PERGANTIAN',
    relais_elimine_court: 'gugur',
    relais_fantome: 'BAYANGAN',

    conf_titre: 'BERLARI MELAWAN TIM LAIN',
    conf_desc: 'satu tembakan, satu urutan finis. Buka kode dan bagikan, atau masukkan kode yang kamu terima.',
    conf_ouvrir: 'BUKA KONFRONTASI',
    conf_rejoindre: 'GABUNG',
    conf_code: 'kode',
    conf_code_court: 'kode itu terlalu pendek',
    conf_partage: 'BAGIKAN KODE INI KE TIM LAIN',
    conf_places: '{n} tim di lintasan',
    conf_engagees: '{n} DARI {m} TIM',
    conf_attend_adversaire: 'perlu setidaknya satu tim lagi, atau satu bayangan',
    conf_classement: 'URUTAN FINIS',
    conf_encore: 'yang lain masih berlari',

    fantome_titre: 'TANTANG SEPULUH RANGKAIAN TERBAIK',
    fantome_desc: 'mereka sudah dilarikan: mereka diputar ulang, tidak bisa gugur maupun dikalahkan di pergantian. Inilah satu-satunya cara mengukur diri dengan yang terbaik tanpa mengumpulkan delapan orang.',
    fantome_aucun: 'belum ada rangkaian tercatat — tim pertama yang menuntaskan estafet membuka jalan.',
    fantome_choisis: '{n} dari {m} dipilih',
    fantome_defier: 'TANTANG MEREKA',

    champ_directs: '{n} teratas lolos',
    champ_reveal: 'PECUNDANG TERCEPAT',
    champ_reveal_desc: 'mereka tidak memenangi satu lomba pun. Mereka datang dari catatan waktu semua lomba.',
    champ_continue: 'LANJUT',
    champ_sacre: '{n} dinobatkan — lihat podium',
    champ_titre_duree: 'gelar berlaku tiga bulan',
    champ_rv_course: 'LOMBA BERIKUTNYA',
    champ_rv_reveal: 'PECUNDANG TERCEPAT DIUMUMKAN',
    champ_rv_sacre: 'UPACARA',
    champ_quitter: 'keluar dari kejuaraan',

    live_lanes: 'JALUR',
    live_lanes_duel: 'duel: pemenang mengambil poin, yang kalah mengembalikan sebagian',
    live_lanes_course: 'lomba: ada urutan finis, tanpa poin di peringkat duel',
    live_won: 'LOMBA DIMENANGKAN',
    live_sur: 'DARI {n} PELARI',
    live_ordre: 'URUTAN FINIS',
    live_lost: 'LOMBA KALAH',

    pres_title: 'PERKENALAN ATLET',
    pres_lane: 'JALUR',
    pres_you: 'ITU KAMU',
    pres_mic_on: 'MIKROFON AKTIF',
    pres_mic_off: 'mikrofon ditolak',
    mic_winner: 'PEMENANG BERBICARA',

    review_title: 'VIDEO LOMBAMU',
    review_making: 'merekam…',
    review_dl: 'UNDUH',
    review_left: 'dihapus dalam {t}',
    review_gone: 'video sudah dihapus',
    review_kept: 'yang kamu unduh tetap ada di ponselmu',
    review_none: 'perangkat ini tidak bisa merekam lomba',
    live_tie: 'FINIS SERI',
    live_vs: 'langsung melawan {n}',
    live_gap: 'selisih {s} d',
    link_in_app: 'GAME SUDAH TERPASANG?',
    link_in_app_sub: 'buka dari layar utama lalu masukkan kode ini — sentuh untuk menyalin',

    duel_answered: 'TANTANGANMU DIJAWAB',
    duel_more: 'masih ada {n} hasil menunggu',
    duel_mores: 'masih ada {n} hasil menunggu',
    duel_next: 'LANJUT',
    duel_ok: 'MENGERTI',

    ghost_mode: 'MODE BAYANGAN',
    ghost_ahead: 'DI DEPAN',
    ghost_behind: 'DI BELAKANG',
    ghost_level: 'SEIMBANG',
    ghost_home: 'bayangan sudah melewati garis',
    ghost_live: 'bayangan berlari di sampingmu',
    duel_must: 'kirim tantangan, atau jawab tantangan teman',
    duel_empty: 'belum ada duel yang dimainkan',
    duel_pts: 'poin',

    monde_sprinter_sous: 'lintasan lurus dan satu putaran',
    monde_hurdlers_sous: 'jalur yang sama, dengan sepuluh rintangan di dalamnya',
    monde_jumper_sous: 'bangun awalan lalu tinggalkan tanah',
    monde_thrower_sous: 'satu lingkaran, satu alat, dan seluruh tubuh',
    monde_bientot: 'SEGERA',
    monde_retour: 'KEMBALI KE SPRINTER',

    disc_100: '100 METER',
    disc_200: '200 METER',
    disc_400: '400 METER',
    disc_100h: '100 M GAWANG',
    disc_110h: '110 M GAWANG',
    disc_400h: '400 M GAWANG',
    disc_longueur: 'LOMPAT JAUH',
    disc_hauteur: 'LOMPAT TINGGI',
    disc_triple: 'LOMPAT JANGKIT',
    disc_perche: 'LOMPAT GALAH',
    disc_poids: 'TOLAK PELURU',
    disc_marteau: 'LEMPAR MARTIL',
    disc_disque: 'LEMPAR CAKRAM',
    disc_javelot: 'LEMPAR LEMBING',

    pique_0: 'Aku bahkan tidak perlu berusaha.',
    pique_1: 'mau kuulang dengan gerakan lambat?',
    pique_2: 'aku sempat bosan menunggu.',
    pique_3: 'garis finisnya di sebelah sini.',
    pique_4: 'terima kasih untuk pemanasannya.',
    pique_5: 'aku menoleh ke belakang dan tidak ada siapa-siapa.',
    pique_6: 'kamu berlari? aku tidak melihat apa pun lewat.',
    pique_7: 'simpan waktu itu, akan jadi kenangan manis.',

    mot_titre: 'TINGGALKAN DUA BARIS UNTUK {n}',
    mot_placeholder: 'sindir dia dalam dua baris',
    mot_vocal: 'SUARA',
    mot_ecouter: 'DENGARKAN',
    mot_refaire: 'rekam ulang',
    mot_envoyer: 'KIRIM',
    mot_envoye: '{n} akan membacanya setelah kembali',
    mot_micro_refuse: 'mikrofon ditolak — teks juga bisa',
    mot_ecouter_sa_voix: 'DENGAR APA YANG DIA KATAKAN',
    mot_ephemere: 'rekaman ini lenyap begitu kamu menutup jendela ini',
    mot_illisible: 'pesan ini tidak bisa diputar di perangkat ini',

    mod_signaler: 'laporkan',
    mod_titre: 'Kenapa kamu melaporkannya?',
    mod_explique: 'Laporan dibaca oleh manusia. Pemblokiran berlaku seketika.',
    mod_insulte: 'penghinaan',
    mod_haine: 'kebencian, rasisme',
    mod_sexuel: 'konten seksual',
    mod_menace: 'ancaman',
    mod_autre: 'lainnya',
    mod_envoye: 'Dilaporkan. Seseorang akan membacanya.',
    mod_deja: 'sudah dilaporkan',
    mod_bloquer: 'blokir {n}',
    mod_bloque: '{n} tidak bisa menulis kepadamu lagi.',
    mod_annuler: 'batal',

    duel_revanche: 'AKU MAU BALAS',
    duel_revanche_sub: 'nomor yang sama — kini giliranmu memasang waktu',
    duel_renvoyer: 'kirim kembali kode ke {n}',
    duel_revanche_envoyee: 'TANTANGAN BALASAN DIKIRIM',
    os_revanche_sans_cible: '{n} tidak bisa diberi tahu — kirim sendiri kodenya',
    duel_revanche_ratee_titre: 'BELUM',
    duel_revanche_ratee: 'kamu perlu di bawah {s} d untuk membalas tantangan ke {n} — tidak ada yang terkirim',

    rang_departemental: 'KABUPATEN',
    rang_regional: 'DAERAH',
    rang_national: 'NASIONAL',
    rang_elite: 'ELIT',
    rang_legende: 'LEGENDA',
    rang_court_departemental: 'KAB',
    rang_court_regional: 'DAE',
    rang_court_national: 'NAS',
    rang_court_elite: 'ELIT ',
    rang_court_legende: 'LEGENDA',
    duel_lp: 'PL',
    duel_monte_a11y: 'naik {n} peringkat',
    duel_descend_a11y: 'turun {n} peringkat',
    duel_lp_long: 'poin liga',
    duel_promu: 'PROMOSI KE {r}',
    duel_relegue: 'DEGRADASI KE {r}',
    duel_reste: '{n} lagi ke divisi berikutnya',
    duel_regle: 'menjawab tantangan lebih menguntungkan daripada mengirimnya: waktunya sudah terpampang, dan kamu tahu apa yang harus dikalahkan.',
    duel_record: '{v}M · {d}K · {n}S',
    duel_you: 'KAMU',
    duel_since: 'sejak kunjungan terakhirmu',
    duel_unranked: 'belum berperingkat — mainkan satu duel',
    duel_won: 'DUEL DIMENANGKAN',
    duel_lost: 'DUEL KALAH',
    duel_tie: 'SERI',
    duel_final: 'hasil final — tantangan tidak diulang',
    duel_delta: '{p} poin',
    duel_deltas: '{p} poin',

    false_out: 'START SALAH',
    false_out_sub: 'tersingkir — duel kalah',
    false_out_seul: 'tersingkir — lomba ini berakhir di sini',
    false_out_rule: 'hanya satu lomba, tanpa kesempatan kedua',
    false_out_libre: 'kamu boleh mengulanginya',
    false_out_gun: 'berangkat sebelum tembakan',
    duel_await: 'hasil duel…',
    duel_vs: 'melawan {n}',
    duel_seen: 'duel sudah diputuskan',
    duel_see: 'LIHAT PERINGKAT',

    os_once: 'begitu tantangan terkirim, waktunya final',
    os_rejouer: 'LARI LAGI',
    os_rejouer_sub: 'satu lomba lagi, sekarang — yang ini tetap seperti adanya',
    os_defier: 'TANTANG SESEORANG',
    os_defier_sub: 'buka peringkat dan pilih lawanmu — orang lain, atau yang sama',
    relance_gagne_0: 'AMBIL YANG BERIKUTNYA',
    relance_gagne_0_sub: 'yang itu beres. Berikutnya.',
    relance_gagne_1: 'BERIKUTNYA, SILAKAN',
    relance_gagne_1_sub: 'peringkatnya penuh orang, dan kamu sedang panas.',
    relance_gagne_2: 'SIAPA LAGI?',
    relance_gagne_2_sub: 'tanya peringkatnya. Pasti ada yang menjawab.',
    relance_perdu_0: 'CARI YANG LEBIH KECIL',
    relance_perdu_0_sub: 'turun satu divisi — tidak perlu ada yang tahu',
    relance_perdu_1: 'CARI YANG LEBIH LAMBAT',
    relance_perdu_1_sub: 'mereka ada. Secara statistik, mereka ada.',
    relance_perdu_2: 'MASIH ADA PEMULA',
    relance_perdu_2_sub: 'mereka tidak curiga apa-apa. Ini saatnya.',
    os_defi_sans_cible: '{n} tidak ada di TOP 500 nomor ini — kirim sendiri kodenya',
    os_verrou_direct: 'lomba langsung: lawanmu berlari pada saat yang sama — hasil itu yang berlaku',
    os_verrou_recu: 'waktu itu sudah sampai ke lawanmu — tidak bisa ditarik kembali',
    os_verrou_envoye: 'tantangan sudah terkirim — itulah waktu yang harus dia kalahkan',
    os_verrou_faux: 'start salah dalam duel: lomba kalah. Kirim tantangan baru untuk mulai dari awal.',
    cut_skip: 'LEWATI',

    id_title: 'NAMAMU',
    id_code_title: 'KODE PEMULIHAN',
    id_code_note: 'catat: kode ini menghubungkan perangkat lainmu ke nama ini, dan mencegah orang lain mengambilnya',
    id_show: 'TAMPILKAN KODEKU',
    id_reserve: 'PESAN',
    id_taken: 'nama ini sudah dipakai',
    id_taken_help: 'kalau memang milikmu, masukkan kode pemulihannya',
    id_link: 'HUBUNGKAN',
    id_linked: 'perangkat terhubung ke {n}',
    id_bad_code: 'kode salah',
    id_unknown: 'nama tidak dikenal',
    id_link_title: 'PERANGKAT LAIN?',
    id_link_help: 'masukkan nama dan kodemu untuk menemukan catatan waktu dan riwayatmu di sini',

    install_title: 'PASANG GAME',
    install_why: 'layar penuh, tanpa bilah peramban, dan bisa dimainkan luring',
    install_do: 'PASANG',
    install_later: 'nanti',
    install_ios_1: 'Sentuh',
    install_ios_2: 'Bagikan',
    install_ios_3: 'di bagian bawah Safari, lalu',
    install_ios_4: 'Tambah ke Layar Utama',

    mode_career_s: 'karier',
    mode_oneshot_s: 'one shot',
    cat_race_sub: 'waktu terbaik dalam satu lomba',
    cat_run_sub: 'total keenam tahap',
    empty_cat_run: 'belum ada rangkaian penuh yang tercatat',
    will_enter: '{s} d: peringkat {r} di TOP 500, tulis namamu',

    wr_title: 'REKOR DUNIA',
    wr_sub: 'waktu terbaik dunia di {d} m',
    wr_old: 'rekor sebelumnya: {s} d',
    wr_first: 'waktu pertama di papan',
    wr_gain: '{s} d lebih cepat',
    wr_save: 'TULIS NAMAKU',
    wr_saving: 'menyimpan...',
    wr_done: '{n} berada di peringkat {r} TOP 500',
    wr_fail: 'gagal mengirim, coba lagi',
    wr_see: 'LIHAT TOP 500',
    wr_later: 'nanti',
    top500_count: '{n} waktu masuk peringkat dari 500',

    pause_title: 'LOMBA DIJEDA',
    pause_note: 'keluar sekarang berarti melepaskan waktu yang sedang berjalan',
    resume: 'LANJUTKAN',

    challenge_them: 'TANTANG',
    target_run: 'lari {d} m milikmu: tantangan akan dikirim ke {n}',
    target_sent: 'tantangan dikirim ke {n}',
    inbox_one: 'TANTANGAN DITERIMA',
    inbox_many: '{n} TANTANGAN DITERIMA',
    inbox_from: '{n} menantangmu di {d} m',
    inbox_accept: 'TERIMA',
    inbox_later: 'nanti',
    run_total_short: 'rangkaian penuh:',
    run_total_tiny: 'rangkaian',
    best_split_tiny: 'lomba',
    score_saved_race: 'peringkat {r} di TOP 500 dunia dengan {s} d',
    mode_career: 'KARIER',
    mode_oneshot: 'ONE SHOT',
    mode_versus: 'TANTANGAN',
    career_desc: 'keenam tahap berturut-turut, satu catatan waktu',
    oneshot_desc: 'pilih nomormu, satu kesempatan saja',
    versus_desc: 'lari melawan bayangan pemain lain',
    pick_events: 'NOMOR',
    pick_level: 'TINGKAT',
    pick_none: 'pilih setidaknya satu nomor',
    launch_oneshot: 'AYO',
    event_n: 'NOMOR {n} / {t}',
    next_event: 'NOMOR BERIKUTNYA',
    oneshot_done: 'ONE SHOT SELESAI',
    total_in: 'total: ',
    challenge_code: 'KODE TANTANGAN',
    challenge_enter: 'masukkan kode yang kamu terima',
    challenge_load: 'MUAT',
    challenge_loading: 'memuat tantangan...',
    challenge_bad: 'kode tidak ditemukan',
    challenge_net: 'sambungan gagal, coba lagi',
    challenge_from: 'tantangan dari {n}',
    challenge_beat: 'harus dikalahkan: {s} d',
    challenge_aveugle: 'kamu akan tahu waktunya sambil berlari',
    challenge_accept: 'TERIMA TANTANGAN',
    challenge_make: 'TANTANG SEORANG TEMAN',
    challenge_making: 'membuat tantangan...',
    challenge_share: 'kirim kode ini, temanmu akan berlari melawan bayanganmu',
    challenge_copy: 'SALIN TAUTAN',
    challenge_copied: 'tautan disalin',
    challenge_copy_code: 'SALIN KODE',
    share_send: 'KIRIM TANTANGAN',
    share_whatsapp: 'WhatsApp',
    share_sms: 'SMS',
    share_other: 'Snapchat, Instagram…',
    share_other_hint: 'Snapchat dan Instagram terbuka lewat menu berbagi.',
    affiche_share: 'BAGIKAN RANGKAIANKU',
    affiche_making: 'Membuat gambar…',
    affiche_saved: 'gambar tersimpan',
    affiche_failed: 'gambar gagal dibuat',
    affiche_hint: 'gambar rangkaianmu, untuk Instagram atau TikTok',
    code_copied: 'kode disalin',
    challenge_rematch: 'TANTANG BALIK',
    challenge_rematch_sub: 'kamu menang — tantang dia di rangkaian yang baru saja kamu jalani',
    challenge_won: 'TANTANGAN DIMENANGKAN',
    challenge_lost: 'TANTANGAN KALAH',
    challenge_gap: 'selisih: {s} d',
    ghost_label: 'BAYANGAN',
    you_label: 'KAMU',
    dnf_short: 'TS',
    composing: 'menyusun musik latar...',

    sound_off: 'SUARA MATI  (S)',
    press_enter: 'tekan ENTER',
    skip_now_kb: 'tekan ENTER lagi untuk melewati',
    skip_twice_kb: 'tekan ENTER dua kali untuk melewati',
    stage_dash: 'TAHAP {n}   -   {s}',
    furthest_kb: 'tahap terjauh yang dicapai: {a} dari {b}',
    enter_start: 'ENTER: mulai   -   S: suara   -   L: bahasa   -   ESC: keluar',
    how_to_play: 'CARA BERMAIN',
    help_1: 'Tekan  <-  dan  ->  bergantian',
    help_2: 'tanpa mengulang tombol yang sama.',
    help_3: 'Irama yang tetap membangun kecepatan;',
    help_4: 'pengulangan membuatmu tersandung, tapi',
    help_5: 'kamu selalu bisa melaju lagi.',
    best_stage: 'WAKTU TERBAIK TAHAP INI',
    no_time: 'belum ada catatan waktu',
    arrows_pick: 'panah untuk memilih   -   ENTER untuk memastikan   -   ',
    yn_short: 'pintasan Y / T',
    you_beat: 'Kamu mengalahkan {w} dan melewati keenam tahap.',
    the_zeze: 'para ZEZE',
    your_times: 'CATATAN WAKTUMU',
    total: 'TOTAL',
    enter_replay: 'ENTER: lari lagi      M: beranda',
    stumble_kb: 'KAMU TERSANDUNG!',
    go_kb: 'YA!',
    to_beat_line: 'HARUS DIKALAHKAN:  {n}   -   {s} d',
    best_times_of: 'WAKTU TERBAIK  -  {s}',
    enter_next: 'ENTER   ->   TAHAP {n}: {s}',
    full_run_pc: 'rangkaian penuh dalam {s} d',
    announced_pc: 'waktu yang diumumkan: {s} d',
    quit: 'ESC: keluar',

    // accueil : le nom, le drapeau, Instagram, un pas a la fois
    bienvenue_titre: 'SELAMAT DATANG',
    bv_nom_t: 'NAMAMU',
    bv_nom_s: 'ia mengikuti setiap catatan waktumu',
    bv_pays_t: 'BENDERAMU',
    bv_pays_s: 'untuk kejuaraan — final',
    bv_insta_t: 'INSTAGRAM-MU',
    bv_insta_s: 'terbuka dari peringkat — kamu yang menyatakan, tanpa verifikasi',
    bv_passer: 'lewati',
    bv_suite: 'LANJUT',
    bienvenue_plus: 'NANTI',
    bienvenue_go: 'AYO MULAI',
    contact: 'HUBUNGI KAMI',

    // la montee au classement, annoncee et lue a voix haute
    places_1: 'PERINGKAT',
    places_n: 'PERINGKAT',
    classement_entree: 'MASUK PERINGKAT',
    classement_bouge_a11y: 'naik {n} peringkat — {r} di {c}',
    classement_perd_a11y: 'turun {n} peringkat — {r} di {c}',
    classement_entre_a11y: 'masuk peringkat — {r} di {c}',

    // notifications
    avis_title: 'NOTIFIKASI',
    avis_desc: 'diberi tahu saat game tertutup',
    avis_pourquoi: 'tantangan yang masuk tengah malam tak ada artinya kalau baru kamu temukan besoknya',
    avis_activer: 'NYALAKAN NOTIFIKASI',
    avis_couper: 'BERHENTI MENERIMA',
    avis_actives: 'notifikasi menyala',
    avis_essai: 'KIRIMI AKU UJI COBA',
    avis_essai_ok: 'terkirim — mestinya sampai dalam sedetik',
    avis_essai_ko: 'tidak ada yang keluar: periksa apakah notifikasi diizinkan',
    avis_refuse: 'kamu menolaknya: itu dibuka lagi di pengaturan ponsel, bukan di sini',
    avis_installer: 'di iPhone, tambahkan dulu game ke layar utama: Safari hanya memberikannya ke aplikasi terpasang',
    avis_indispo: 'peramban ini tidak bisa menerimanya',
    avis_erreur: 'server tidak berhasil mencatat langganan',
    avis_choisir: 'YANG INGIN AKU TERIMA',
    avis_g_defi: 'Tantangan yang masuk',
    avis_g_defi_s: 'seseorang mengirimimu waktu untuk dikalahkan',
    avis_g_selection: 'Pemanggilan kejuaraan',
    avis_g_selection_s: 'kamu salah satu dari 32 pelari',
    avis_g_direct: 'Tantangan langsung',
    avis_g_direct_s: 'seseorang menunggu di lintasan, sekarang',
    avis_g_relais: 'Undangan estafet',
    avis_g_relais_s: 'sebuah tim menginginkanmu',
    avis_g_rendezvous: 'Jam mulai kejuaraan',
    avis_g_rendezvous_s: 'seperempat jam sebelum tiap lomba',
    avis_g_assister: 'Final, dan siapa yang memenangkannya',
    avis_g_assister_s: 'seperempat jam sebelumnya, lalu penobatan — meski kamu tidak ikut',
    avis_g_record: 'Rekor dunia yang jatuh',
    avis_g_record_s: 'puncak sebuah nomor berpindah tangan',
    avis_suivre: 'KEJUARAAN YANG MANA',
    avis_suivre_national: 'negaraku',
    avis_suivre_continental: 'benuaku',
    avis_suivre_mondial: 'Kejuaraan Dunia',
    avis_suivre_vide: 'centang setidaknya satu, kalau tidak tak ada yang dikirim',
    avis_suivre_nom: 'pesan namamu di atas agar negaramu diketahui',

    // inviter quelqu un sur la piste, par son nom
    live_inviter: 'UNDANG SEORANG PEMAIN',
    live_inviter_ph: 'namanya',
    live_inviter_ok: '{n} sudah diberi tahu — ponselnya berdering',
    live_inviter_ko: 'tak ada yang memesan nama itu: kirimkan saja kodenya',
    live_invite_recue: '{n} menunggumu di lintasan',
    live_invite_rejoindre: 'GABUNG',

    // suppression du profil
    id_del: 'HAPUS PROFILKU',
    id_del_what: 'namamu, kodemu, catatan waktumu di peringkat, riwayat daringmu, tantangan dan duelmu dihapus dari server, di semua perangkatmu.',
    id_del_keep: 'kemajuan karier dan lomba yang tersimpan di perangkat ini tidak tersentuh.',
    id_del_final: 'ini final: tidak satu pun bisa dikembalikan.',
    id_del_confirm: 'ketik {n} untuk memastikan',
    id_del_go: 'HAPUS',
    id_del_cancel: 'batal',
    id_del_done: 'profil dihapus',
    id_del_device: 'nama ini belum dipesan: yang berasal dari perangkat ini sudah dihapus',
    id_del_code: 'perangkat ini tidak terhubung ke nama ini: masukkan kode pemulihannya',

    // le record personnel a la fin d un one shot
    os_record_titre: 'REKOR PECAH',
    os_record_titre_n: 'REKOR-REKOR PECAH',
    os_record_sur: 'di {d} m',
    os_record_premier: 'waktu pertama di nomor ini',
    os_record_gain: '{s} d lebih cepat',
    os_record_rang: '{r} di TOP 500 - SEPANJANG MASA',
    os_record_saved: 'disimpan atas nama {n}',
    os_record_suite: 'LANJUT',
    os_record_sansnom: 'pilih namamu di layar utama untuk mencatatkannya di TOP 500',

    // le record du monde qui tombe, et les piques qui l accompagnent
    wrm_titre: 'REKOR DUNIA',
    wrm_sur: 'di {d} m',
    wrm_pris: 'direbut dari {n} — {s} d lebih cepat',
    wrm_pris_soi: 'rekornya sendiri, diperbaiki {s} d',
    wrm_defier: 'PERGI KALAHKAN',
    wrm_note_0: 'pengumuman untuk para penantang: mistarnya baru saja naik.',
    wrm_note_1: 'ada yang mau menjawab? Kami menunggu.',
    wrm_note_2: 'yang lain dimohon dengan hormat untuk berlari lebih cepat.',
    wrm_note_3: 'waktu ini akan bertahan cukup lama. Kecuali.',
    wrm_note_4: 'puncak papan berpindah tangan. Untuk sekarang.',
    wrm_note_5: 'memberi selamat itu pilihan. Mengalahkan tidak.',
    wrm_note_6: 'ada waktu yang harus dikalahkan. Bukan waktumu.',
    wrm_note_7: 'di suatu tempat, seseorang baru saja berlari lebih baik darimu.',
    wrm_note_8: 'lintasan terbuka. Rekornya jauh lebih tertutup.',
    wrm_note_9: 'baca lagi waktunya kalau mau. Ia tidak akan bergerak sendiri.',
    wrm_note_10: 'dua pilihan: berlatih, atau membiasakan diri.',
    wrm_note_11: 'nama baru di puncak papan. Namamu ada di bawahnya.',
    wrm_note_12: 'belum pernah ada yang memecahkan rekor dengan membaca notifikasi.',
    wrm_note_13: 'bayangannya menunggu di TOP 500. Ia tidak menggigit.',
    wrm_note_14: 'ini cuma rekor. Rekor bisa direbut kembali.',
    wrm_note_15: 'balok startnya kosong. Sekadar memberi tahu.'
  },

  CUTS: {
    intro: [
      [ // tahap 1
        ['{n} sudah tiga tahun memenangi semua lomba di halaman sekolah.',
         'Rahasianya: tak ada yang berani menyalip, bolanya memang miliknya.',
         'Dia pemanasan pakai sepatu sekolah, atas dasar prinsip.',
         'Ibunya merekam dari balik pagar. Kebanyakan yang terekam pagar.'],
        ['{n} pemegang rekor sekolah, ditulis spidol di dinding aula.',
         'Waktunya dicatat seorang teman sekelas, pakai jam berjarum.',
         'Guru olahraga mengangguk sekali. Sejak itu resmi.',
         'Sekarang dinding dicat mengelilingi rekor itu.'],
        ['{n} minta jalur 4. Dia dapat jalur 4.',
         'Dia menjalankan latihannya: lutut tinggi, tumit ke belakang, tarikan napas panjang.',
         'Nomor dadanya dicetak di rumah, sedikit miring.',
         'Nomornya 1. Dia mencetaknya sendiri, sendirian.']
      ],
      [ // tahap 2
        ['{n} sudah empat jam pemanasan.',
         'Di punggung trainingnya namanya disulam, dengan huruf besar.',
         'Dia punya ritual: tiga langkah mundur, satu tarikan napas, satu kedipan.',
         'Kedipan itu tidak ditujukan kepada siapa pun.'],
        ['{n} datang dengan dua pasang sepatu paku dan satu kotak pendingin.',
         'Di kotak itu ada sebuah pisang dan tekad yang berlimpah.',
         'Dia menyetel balok start sampai milimeter, lalu menyetel ulang.',
         'Lalu ketiga kalinya. Petugas start menunggu, dengan sopan.'],
        ['{n} finis kedua di kejuaraan daerah tahun lalu.',
         'Dia menyebutnya kemenangan yang dicuri angin dari depan.',
         'Pengukuran resmi menyebut tanpa angin. Dia menggugat pengukurannya.',
         'Dia membawa anemometer sendiri. Dia tidak bisa memakainya.']
      ],
      [ // tahap 3
        ['{n} pernah masuk televisi daerah.',
         'Tiga puluh delapan detik tayangan. Dia menontonnya enam ratus kali.',
         'Dia membagikan tanda tangan sebelum lomba, demi menghemat waktu.',
         'Di struk belanja, karena tak ada yang lebih baik.'],
        ['{n} punya julukan yang tak dipakai siapa pun: Panah Utara.',
         'Dia sendiri yang menyelipkannya di setiap wawancara.',
         'Penyiar baru saja menyebut nama aslinya, karena keliru.',
         'Dia minta ralat lewat pengeras suara. Ralatnya menyusul.'],
        ['{n} menato rekor pribadinya di lengan bawah.',
         'Dia menunjukkannya dengan gerakan lambat saat perkenalan atlet.',
         'Empat pelari di final ini sudah melewati angka itu.',
         'Sayangnya, tato tidak memperbarui dirinya sendiri.']
      ],
      [ // tahap 4
        ['{n} punya sponsor, agen, dan fisioterapis.',
         'Ketiganya bilang dia tak terkalahkan. Ketiganya dibayar olehnya.',
         'Agennya bahkan sudah memesan ruangan untuk konferensi pers kemenangan.',
         'Katering sudah dipesan. Ada kanape.'],
        ['{n} sudah sebelas bulan jadi nomor satu dunia.',
         'Dia tahu itu saat siaran langsung dan sejak itu tak pernah menoleh ke belakang.',
         'Secara harfiah: fisioterapisnya melarang keras.',
         'Kini dia memutar seluruh badan. Lebih lambat, tapi terlihat gagah.'],
        ['Penyiar memanggil {n}. Seisi stadion berdiri.',
         'Dia menunjuk tribun, lalu langit, lalu kamera.',
         'Kameranya sedang mengarah ke atlet lain. Dia mengulang semuanya.',
         'Sutradara mengalah. Gerakan itu akan berlangsung sebelas detik.']
      ],
      [ // tahap 5
        ['{n} sudah delapan bulan melatih selebrasinya.',
         'Dia mendaftarkannya sebagai merek. Tinggal memenangi lombanya.',
         'Paduan suara empat puluh orang menunggu isyaratnya.',
         'Mereka menghafal sebuah lagu. Lagu itu menyebut namanya, panjang lebar.'],
        ['{n} memakai warna negaranya, dan itu sungguh penting baginya.',
         'Benderanya ada di sepatu, di nomor dada, dan di handuk.',
         'Handuknya tidak ikut berlari, tapi sudah siap sejak Selasa.',
         'Seorang ofisial membawanya ke mana-mana sejak upacara pembukaan.'],
        ['{n} bersumpah tidak akan melirik lawan-lawannya di balok start.',
         'Maka dia menatap lurus ke depan, dengan intensitas yang mencolok.',
         'Sedikit terlalu jauh ke depan: saat perkenalan dia menatap tembok.',
         'Tembok itu tidak lolos ke final ini.']
      ],
      [ // tahap 6
        ['{n} berasal dari semesta tempat gravitasi bersifat pilihan.',
         'Dia menyelesaikan lombanya sebelum memutuskan untuk memulainya.',
         'Rekornya berlaku di sebelas dimensi sekaligus.',
         'Di dimensi kedua belas dia tersandung, tapi itu tidak pernah disinggung.'],
        ['{n} sudah berlari seratus meter ini di sebelas semesta paralel.',
         'Dia memenangi kesebelasnya. Yang kedua belas tidak pernah disahkan.',
         'Hakim finis di sana adalah sebuah nebula, tak bisa diandalkan di garis.',
         'Nebula itu diskors tiga musim.'],
        ['Keluarga ZEZE menempati ketujuh jalur. Itu sesuai aturan.',
         'Mereka membawa petugas start sendiri, angin sendiri, dan garis finis sendiri.',
         'Aturannya ditulis seorang ZEZE dan diperiksa seorang ZEZE.',
         'Panjangnya satu kalimat: ZEZE yang menang.']
      ]
    ],

    defeat: [
      [ // tahap 1
        ['{n} mengajukan banding atas hasilnya ke penjaga kantin.',
         'Penjaga kantin sedang makan roti. Hasilnya tidak berubah.',
         'Lalu dia meminta putusan dari ketua kelas.',
         'Ketua kelas finis terakhir. Dia sangat menikmati ini.'],
        ['{n} menjelaskan bahwa permukaan halaman tidak rata.',
         'Permukaan itu tidak rata bagi semua orang sejak seribu sembilan ratus enam puluh.',
         'Lalu dia menyebut tali sepatu yang lepas. Sepatunya berperekat.',
         'Guru menulis waktumu di dinding. Tepat di atas waktunya.'],
        ['{n} mengumumkan bahwa dia sebenarnya tidak sedang berlomba.',
         'Dia sedang pemanasan. Lomba yang sebenarnya adalah yang berikutnya.',
         'Tidak ada yang diberi tahu, dan itu menjelaskan banyak hal.',
         'Bel berbunyi. Lomba berikutnya tidak akan pernah terjadi.']
      ],
      [ // tahap 2
        ['{n} menjelaskan bahwa jamnya tidak pernah menyala.',
         'Jadi, secara teknis, lomba ini tidak pernah ada.',
         'Dia menawarkan mengulangnya sekarang juga, di antara orang serius.',
         'Lalu dia ingat ada kereta. Dia tidak punya kereta apa pun.'],
        ['{n} minta melihat foto finis.',
         'Fotonya ditunjukkan. Jelas di belakang, dan sangat tajam.',
         'Dia minta foto yang sama dari sudut lain.',
         'Dari sudut itu dia tetap di belakang, hanya sedikit lebih buram.'],
        ['{n} membereskan kedua pasang sepatunya tanpa sepatah kata.',
         'Dia mengumumkan pindah ke 400, nomor yang lebih taktis.',
         'Lalu 800. Lalu maraton, tempat segalanya berakhir juga.',
         'Dia pergi membawa kotak pendinginnya. Pisangnya masih utuh.']
      ],
      [ // tahap 3
        ['{n} mengumumkan pensiun saat siaran langsung.',
         'Lalu berubah pikiran: Senin kembali berlatih.',
         'Dia mencatat bahwa Senin yang satu itu kebetulan sangat padat.',
         'Senin berikutnya juga, ternyata.'],
        ['{n} menuntut tes doping untuk sang pemenang.',
         'Lalu satu untuk dirinya sendiri, demi keadilan.',
         'Keduanya negatif. Menurutnya itu mencurigakan.',
         'Dia minta tes ketiga. Untuk alat pencatat waktu.'],
        ['{n} menunjukkan lengannya kepada para wartawan.',
         'Rekor yang ditato itu tidak bergeser. Lumayan juga.',
         'Dia mengumumkan enam pekan pemusatan di dataran tinggi.',
         'Gunung yang dia pilih tingginya dua ratus meter.']
      ],
      [ // tahap 4
        ['{n} menuntut pengukuran angin yang kedua.',
         'Angin dipanggil. Angin tidak hadir.',
         'Konferensi pers kemenangan tetap berjalan, sudah tak bisa dibatalkan.',
         'Kanapenya luar biasa. Itu sudah lumayan.'],
        ['{n} menatap layar raksasa selama dua puluh detik.',
         'Klasemennya tidak berubah. Layarnya juga tidak.',
         'Dia bertanya apakah tayangannya langsung. Dijawab iya.',
         'Lalu dia bertanya apakah ada tayangan tunda. Tidak ada.'],
        ['Di zona campuran, {n} berbicara tentang perkembangan dan proses.',
         'Dia memakai kata siklus sebelas kali dalam dua menit.',
         'Seorang wartawan menanyakan waktunya. Jawabnya: waktunya akan datang.',
         'Waktunya sudah terpampang di papan di belakangnya, sangat besar.']
      ],
      [ // tahap 5
        ['{n} tetap menjalankan selebrasinya.',
         'Penonton bertepuk tangan, demi kesopanan.',
         'Paduan suara, yang salah informasi, mulai menyanyi.',
         'Empat puluh orang menyanyikan namanya. Dia lebih suka hening.'],
        ['{n} mengambil lap kehormatan dengan bendera, sesuai rencana.',
         'Sang pemenang mengambil lap yang sama, ke arah berlawanan.',
         'Mereka berpapasan dua kali. Yang kedua lebih pahit.',
         'Handuk itu tidak menduganya.'],
        ['{n} naik ke anak tangga kedua podium.',
         'Dia memberi selamat kepada pemenang dengan jabat tangan yang sangat panjang.',
         'Cukup panjang sehingga foto resmi diulang tiga kali.',
         'Di yang ketiga dia tersenyum. Terlihat betapa mahal harganya.']
      ],
      [ // tahap 6
        ['{n} menghitung ulang lintasan galaksinya.',
         'Ternyata lintasan itu melewati tepat di posisi kedua.',
         'Dia menyebut anomali waktu, lalu masalah pada sepatunya.',
         'Kedua penjelasan itu saling bertentangan. Dia menyimpan keduanya.'],
        ['{n} meminta klasemen dari sebelas semesta lainnya.',
         'Di kesebelasnya dia juga baru saja kalah. Secara bersamaan.',
         'Dia menawarkan membuka semesta kedua belas, sekadar melihat.',
         'Yang kedua belas sudah terisi. Di sana pun kamu finis pertama.'],
        ['Keenam ZEZE lainnya menatap {n} dengan sangat tenang.',
         'Tak seorang pun bersuara. Keheningannya berlangsung empat tahun cahaya.',
         'Akhirnya {n} mengusulkan: permukaannya beda hari ini.',
         'Permukaannya tidak berubah sejak lintasan itu dibangun.']
      ]
    ],

    taunt: [
      [ // tahap 1
        ['{n} menunjuk papan skor, tanpa sepatah kata.',
         'Dia sudah menandatanganinya. Dengan spidol permanen.',
         'Dia menyodorkan rotinya kepadamu. «Buat di jalan», katanya.',
         'Kamu tidak pernah minta roti.'],
        ['{n} mengambil lap kehormatan. Tiga meter, karena tempatnya sempit.',
         'Dia melambai lama kepada penonton khayalan.',
         'Dia menawarimu tanding ulang. Lalu melirik jam tangannya.',
         'Dia tidak punya jam tangan. Isyaratnya sudah cukup bicara.'],
        ['{n} membereskan barangnya dengan santai, sambil bersiul.',
         'Nadanya adalah namamu, dalam irama mars kemenangan.',
         'Dia menepuk bahumu. «Lain kali», katanya.',
         'Dia tidak percaya itu sedetik pun, dan itu kelihatan.']
      ],
      [ // tahap 2
        ['{n} melirik jam, lalu melirikmu, dengan tatapan penuh arti.',
         'Dia tidak berkata apa-apa. Diamnya lebih kejam daripada kata-kata.',
         'Dia membagikan tanda tangan. Yang pertama untukmu.',
         'Itu pun tidak kamu minta.'],
        ['{n} menelepon pelatihnya. «Kami selesai lebih awal», katanya.',
         'Pelatihnya bertanya kenapa. «Demi kesopanan», jawabnya.',
         'Dia membiarkanmu memegang medalinya. Sebentar saja.',
         'Sebentar itu berlangsung sepuluh menit. Dia sibuk memotret.'],
        ['{n} memasukkan sepatunya ke tas yang bertuliskan namamu.',
         'Itu lelucon orang dalam. Penonton tidak mengikuti.',
         'Dia menawarimu air dari botolnya. Botolnya kosong.',
         'Isyaratnya, katanya, lebih berarti daripada airnya.']
      ],
      [ // tahap 3
        ['{n} melambai ke kamera. Lalu melambai kepadamu.',
         'Lambaian kedua terasa jelas kurang ramah.',
         'Dia membahas lombamu dengan para wartawan, sampai rinci.',
         'Rincian favoritnya: saat kamu menoleh ke belakang.'],
        ['{n} meminta mikrofon. Dia diberi, meski akal sehat berkata lain.',
         'Dia berterima kasih kepada keluarganya, klubnya, dan kamu, dengan urutan itu.',
         '«Tanpa dia», katanya, «rasanya tidak akan sama».',
         'Dia tidak menjelaskan maksudnya. Memang tidak perlu.'],
        ['{n} menawarkan meninjau lombamu bersama, dengan tenang.',
         'Tinjauannya sepanjang satu kata. Dia mengucapkannya sangat pelan.',
         'Dia menjabat tanganmu dua kali berturut-turut, untuk memastikan.',
         'Yang pertama dirasa kurang meyakinkan.']
      ],
      [ // tahap 4
        ['{n} memberi wawancara. Topiknya, anehnya, adalah kamu.',
         'Tiga menit. Tak sepatah kata pun tentang lombanya sendiri.',
         'Dia menutup dengan berkata banyak belajar. Dari kekalahanmu.',
         'Wartawan mencatatnya kata demi kata, dengan tidak nyaman.'],
        ['{n} memberi isyarat kepada agennya untuk menambah satu baris di rekamnya.',
         'Barisnya berbunyi sederhana: melawanmu, sekali lagi.',
         'Dia mengundangmu ke konferensi pers kemenangan.',
         'Sebuah kursi menantimu, di baris paling belakang, tanpa mikrofon.'],
        ['{n} menunjukkan klasemen di ponselnya, sambil memperbesar.',
         'Dia memperbesar cukup lama. Barismu jauh di bawah barisnya.',
         '«Bisa kukirim lewat surel», tawarnya, dengan ramah.',
         'Kamu tidak pernah memberinya alamatmu. Dia sudah memilikinya.']
      ],
      [ // tahap 5
        ['{n} melambai ke tribun, lalu berbalik kepadamu, dengan khidmat.',
         'Apa yang dia lakukan setelah itu tidak ada di aturan mana pun.',
         'Seorang wartawan minta sepatah kata untuk lawan yang kalah.',
         'Dia memberi tujuh. Tak satu pun masuk ke artikel.'],
        ['{n} naik ke podium, lalu turun satu anak tangga.',
         'Dia mengundangmu melihat medalinya dari dekat.',
         'Sangat dekat. Medalinya emas. Poin itu dia tekankan.',
         'Lagu kebangsaan dimulai. Dia menyanyi keras, sambil menatapmu.'],
        ['{n} mempersembahkan kemenangannya kepada keluarganya, sponsornya, dan kamu.',
         '«Tanpa lawan sememotivasi ini», katanya, dengan tulus.',
         'Kata memotivasi jatuh seperti hinaan yang disamarkan dengan rapi.',
         'Penonton bertepuk tangan, tanpa tahu kenapa wajahmu memerah.']
      ],
      [ // tahap 6
        ['{n} menatap keenam ZEZE lainnya. Mereka mengangguk, bersamaan.',
         'Putusannya bulat, dan dijatuhkan tanpa satu bunyi pun.',
         'Sebuah plakat peringatan diukir, dalam bahasa yang sudah mati.',
         'Bunyinya kurang lebih: dia sudah mencoba. Itu pun ada harganya.'],
        ['{n} menghitung ulang posisimu di sebelas dimensi berbeda.',
         'Di setiap dimensi hasilnya sama persis, sampai ke detiknya.',
         'Dia memberimu peta semesta tempat kamu seharusnya menang.',
         'Semesta itu, katanya, belum ada.'],
        ['{n} mengulurkan tangan ke langit. Sebuah galaksi menyala, patuh.',
         'Sesaat galaksi itu membentuk lengkung senyumnya.',
         'Ketujuh ZEZE berunding, lalu berpaling kepadamu.',
         'Keheningan yang menyusul berlangsung empat tahun cahaya. Dengan sopan.']
      ]
    ],

    champion: [
      ['Ketujuh ZEZE berunding lama.',
       'Tak satu pun menemukan alasan yang bisa diterima. Ini yang pertama.',
       'Klasemen diperbarui di empat belas miliar sistem.',
       'Sebuah plakat dipasang di garis finis.',
       'Namamu salah eja di sana, tapi namamu ada.'],
      ['Penyiar mencari satu kata. Tak ada yang cukup besar.',
       'Dia cuma membacakan waktunya, dua kali, untuk memastikan.',
       'Tujuh ZEZE menatap layar raksasa tanpa berkata apa-apa.',
       'Sebuah komisi dibentuk untuk memeriksa garis finis.',
       'Garisnya lurus. Klasemennya juga.'],
      ['Lap kehormatan berlangsung lebih lama daripada lombanya.',
       'Itu aritmetika sederhana, dan tak ada yang mengeluh.',
       'Seseorang menyodorkan bendera. Kamu tidak tahu itu dari galaksi mana.',
       'Dari semuanya: rancangannya dilebur demi kesempatan ini.',
       'Paduan suara menulis ulang lagunya. Kini lagu itu menyebut namamu, akhirnya.']
    ]
  }
};
