/* -----------------------------------------------------------------------
   SPRINTER — italiano.
   Ce qui manque ici retombe sur l'anglais, cle par cle : voir
   sprinter-i18n.js. Verification : node tools/langues-verifier.mjs it
   ----------------------------------------------------------------------- */
export default {
  ord(n, feminine) { return n + (feminine ? 'ª' : 'º'); },

  LEVEL_NAMES: [
    'Gara scolastica', 'Livello regionale', 'Livello nazionale',
    'Campionati del Mondo', 'Giochi Mondiali', 'Intergalattico'
  ],

  RACE_SUB: {
    '100': 'il rettilineo',
    '200': 'curva e rettilineo',
    '400': 'un giro di pista'
  },

  UI: {
    races: '100 - 200 - 400 METRI',
    tagline: 'sei tappe, un solo tempo da battere',
    tap_start: 'tocca lo schermo per iniziare',
    six_stages: '   -   sei tappe',
    six_stages_bare: 'sei tappe',
    best_runs: 'MIGLIORI PERCORSI',
    no_run: 'nessun percorso ancora completato',
    furthest: 'tappa più lontana: ',
    of_six: ' su 6',
    start: 'INIZIA',
    sound: 'audio: ',
    yes: 'sì',
    no: 'no',

    rival: 'IL CORRIDORE DA BATTERE',
    favourite: 'Il favorito',
    after_race: 'DOPO LA GARA',
    crowned: 'TITOLO INTERGALATTICO',
    fastest_1: "L'ESSERE PIÙ VELOCE",
    fastest_2: 'DI TUTTE LE GALASSIE',
    full_run_in: 'percorso completo in ',
    announced: 'tempo annunciato: ',
    stage_up: 'TAPPA ',
    six_cleared: 'SEI TAPPE SUPERATE',
    skip_now: 'tocca di nuovo per saltare',
    skip_twice: 'tocca due volte per saltare',

    reaction: 'REAZIONE',
    react_top: 'REAZIONE PERFETTA',
    false_start: 'PARTITO TROPPO PRESTO',
    wait_gun: 'aspetta lo sparo',
    phase_drive: 'SPINTA',
    phase_trans: 'TRANSIZIONE',
    phase_max: 'VELOCITÀ MASSIMA',
    drive_hint: 'trova la tua cadenza',
    trans_2: 'TRANSIZIONE PERFETTA',
    trans_1: 'BUONA TRANSIZIONE',
    trans_0: 'TRANSIZIONE SBAGLIATA',
    start_line: 'partenza: {r} s di reazione   -   {g}',
    no_start: 'partenza mancata',

    stumble: 'INCIAMPI',
    to_beat: 'da battere: ',
    to_race: 'corri contro ',
    ready: 'AI VOSTRI POSTI',
    get_set: 'PRONTI',
    go: 'VIA',
    alternate: 'alterna i due pulsanti',
    alternate_kb: 'alterna le due frecce',
    you: 'TU',
    opponent: 'AVVERSARIO',
    depart: 'PARTENZA',
    arrivee: 'ARRIVO',

    stage_done: 'TAPPA {n} SUPERATA',
    first_in: '1º posto in ',
    total_of: ' s   -   totale ',
    place: '{o} POSTO',
    dnf: 'ritiro',
    unfinished: 'non completato',
    race_again: 'DI NUOVO?',
    next_stage: 'TAPPA {n}',
    home: 'HOME',
    replay: 'GIOCA ANCORA',
    run_done: 'PERCORSO COMPLETATO',
    six_in: 'sei tappe superate in ',
    stage_low: 'tappa ',

    new_record: 'NUOVO RECORD',
    top3: 'TOP 3',
    top10: 'TOP 10',
    best_run: 'MIGLIOR PERCORSO',
    top3_runs: 'TOP 3 DEI PERCORSI',
    top10_runs: 'TOP 10 DEI PERCORSI',

    top500: 'TOP 500 - DI SEMPRE',
    your_name: 'il tuo nome',
    save_score: 'SALVA IL MIO TEMPO',
    saving_score: 'invio in corso...',
    score_saved: '{r} nella TOP 500 mondiale',
    score_save_fail: 'invio fallito, riprova più tardi',
    score_name_taken: 'questo nome appartiene a un altro dispositivo',
    score_taken_help: 'scegline un altro, oppure collega questo dispositivo al tuo nome in LE MIE GARE con il tuo codice di recupero',
    view_top500: 'VEDI LA TOP 500',
    top500_court: 'TOP 500',
    close: 'CHIUDI',
    loading_ranks: 'caricamento della classifica...',
    empty_top500: 'nessun tempo registrato per ora',
    your_rank: 'IL TUO POSTO: {r}',
    outside_top500: 'fuori dalla top 500',
    edit_name: 'MODIFICA IL NOME',
    best_split_short: 'miglior tappa:',
    top500_sub: 'miglior tempo in una singola gara',
    cat_race: 'PER GARA',
    cat_run: 'PERCORSO COMPLETO',
    cat_mine: 'LE MIE GARE',
    cat_mine_sub: 'tutte le gare che hai corso',
    mine_empty: 'nessuna gara in questa specialità',
    mine_count: '{n} gare — migliore: {s} s',
    mine_note: 'La TOP 500 tiene solo il tuo miglior tempo per specialità; questo storico tiene tutto. Prenota il tuo nome per ritrovarlo sui tuoi altri dispositivi.',

    duel_title: 'CLASSIFICA DUELLI',
    duel_sub: 'sfide inviate e accettate',
    duel_open: 'VEDI LA CLASSIFICA DUELLI',
    duel_rules_init: 'SFIDA INVIATA',
    duel_rules_recv: 'SFIDA ACCETTATA',
    duel_rules_line: 'vittoria {v}   ·   sconfitta {d}   ·   pareggio {n}',
    duel_rules_all: 'ogni duello conta, inviato o accettato',
    duel_rules_why: 'lanciare una sfida vuol dire mostrare il proprio tempo per primo',
    duel_counts: '{l} inviate · {r} accettate',
    duel_sur: 'IL DUELLO SI CORRE SU',

    name_set: 'SCEGLI IL TUO NOME',
    name_title: 'IL TUO NOME',
    name_why: 'è quello che appare nella TOP 500, sulle tue sfide e nei duelli',
    name_save: 'SALVA',
    name_saved: 'SALVATO',
    name_taken: 'quel nome è già preso',
    name_code: 'IL TUO CODICE DI RECUPERO',
    pays_title: 'LA TUA NAZIONALITÀ',
    pays_opt: 'una sola volta',
    pays_aucun: 'scegli il tuo paese',
    pays_why: 'ti serve per correre un campionato nazionale — e dopo non si cambia',
    pays_vu: 'sembra che ti colleghi da {pays} — decidi tu',
    pays_save: 'SCEGLI',
    pays_confirm: 'Correre per {pays}?\n\nÈ definitivo: decide a quale campionato nazionale accedi, e non si può cambiare.',
    pays_fige: 'definitivo',
    pays_on: 'corri per questo paese — la tua bandiera segue il tuo nome al campionato',
    pays_deja: 'la tua nazionalità è già scelta, non si può cambiare',
    pays_first: 'salva prima il tuo nome',
    pays_bad: 'paese non valido',
    insta_title: 'IL TUO INSTAGRAM',
    insta_ph: 'il tuo nome utente, senza la @',
    insta_why: 'il tuo profilo diventa raggiungibile dalla TOP 500 e dalle tue sfide',
    insta_note: 'dichiarato da te, non verificato — Instagram non consente più un accesso reale per un account personale',
    insta_link: 'COLLEGA IL MIO ACCOUNT',
    insta_linked: 'ACCOUNT COLLEGATO',
    insta_unlink: 'SCOLLEGA',
    insta_on: 'il tuo profilo appare nella TOP 500 — toccalo per aprirlo',
    insta_gone: 'account scollegato, il tuo profilo non appare più da nessuna parte',
    insta_bad: 'nome utente non valido',
    insta_first: 'salva prima il tuo nome',
    insta_notyours: 'questo nome non è tuo su questo dispositivo',
    insta_visit: 'vedi il profilo Instagram di {n}',
    name_code_why: 'annotalo: recupera il tuo nome e le tue gare su un altro telefono',

    tour_open: 'FAI IL GIRO',
    tour_1_t: 'ALTERNA',
    tour_1_s: 'sinistra, destra, sinistra. La gara è tutta qui.',
    tour_2_t: 'LA CARRIERA',
    tour_2_s: 'sei tappe, dal cortile della scuola alla finale intergalattica',
    tour_3_t: 'LA TOP 500',
    tour_3_s: 'il tuo tempo contro il mondo intero',
    tour_4_t: 'IL FANTASMA',
    tour_4_s: 'manda la tua gara a un amico — corre contro di te',
    tour_5_t: 'IN DIRETTA',
    tour_5_s: 'stesso sparo, ognuno sul proprio telefono',
    tour_play: 'FAMMI GIOCARE',

    os_tuto_open: 'A COSA SERVE QUESTA MODALITÀ',
    os_tuto_1_t: 'SCEGLI LE TUE GARE',
    os_tuto_2_t: 'UN SOLO TENTATIVO',
    os_tuto_3_t: 'IL TUO TEMPO CONTA',
    os_tuto_1_s: 'una, due o tutte e tre',
    os_tuto_2_s: 'nessuna ripetizione, nessuna eliminazione',
    os_tuto_3_s: 'TOP 500, e un amico può raccoglierla',
    os_tuto_go: 'INIZIA UN ONE SHOT',

    tuto_ask_t: 'PRIMA GARA',
    tuto_ask_s: 'il gesto si impara in trenta secondi',
    tuto_ask_yes: 'IMPARA IL GESTO',
    tuto_ask_no: 'FAMMI CORRERE',
    tuto_watch: 'GUARDA',
    tuto_your_turn: 'TOCCA A TE',
    tuto_1_t: 'ALTERNA',
    tuto_2_t: 'SULLO SPARO',
    tuto_3_t: 'AMPIO, POI STRETTO',
    tuto_v_early: 'TROPPO PRESTO',
    tuto_v_late: 'troppo tardi',
    tuto_v_perfect: 'PERFETTO',
    tuto_v_good: 'BENE',
    tuto_v_slow: 'NON ABBASTANZA VELOCE',
    tuto_v_flat: 'RITMO PIATTO',
    tuto_replay_demo: 'guarda di nuovo',
    tuto_again: 'ANCORA',
    tuto_next: 'AVANTI',
    tuto_done_t: 'TOCCA A TE CORRERE',
    tuto_start: 'INIZIA',
    tuto_replay: 'guarda di nuovo',
    tuto_skip: 'salta',
    tuto_open: 'COME SI GIOCA',

    live_title: 'GARA IN DIRETTA',
    live_desc: 'partite entrambi allo stesso sparo, ognuno sul proprio telefono — niente fantasma, nessuno sa chi vince',
    live_create: 'APRI UNA PISTA',
    live_join: 'ENTRA',
    live_or: 'oppure',
    live_room: 'PISTA APERTA',
    live_waiting: 'manda questo codice al tuo avversario — la gara parte quando siete in due',
    live_ready: 'PRONTO',
    live_notready: 'NON ANCORA',
    live_empty_seat: 'corsia libera — in attesa di un avversario',
    live_go: 'SONO PRONTO',
    live_unready: 'ANNULLA',
    live_leave: 'esci dalla pista',
    live_none: 'nessuna pista con quel codice',
    live_full: 'quella pista è già piena',
    live_gone: 'il tuo avversario ha lasciato la pista',
    live_closed: 'la connessione è caduta',
    live_invite: 'Ti aspetto in pista. Codice {c} — {l}',

    relais_titre: 'STAFFETTA 4 × 100',
    relais_desc: 'quattro corridori, un testimone. Una squadra è la sua formazione: gli stessi quattro nomi, la stessa squadra.',
    relais_invitations: 'SEI STATO INVITATO',
    relais_mes_equipes: 'LE TUE SQUADRE',
    relais_creer: 'FORMA UNA SQUADRA',
    relais_nom_equipe: 'nome della squadra',
    relais_coequipier: 'compagno {n}',
    relais_inviter: 'INVITA I TRE',
    relais_incomplet: 'servono un nome e tre compagni',
    relais_attend: 'in attesa',
    relais_ok: 'dentro',
    relais_refuse: 'ha rifiutato',
    relais_fixer_ordre: "FISSA L'ORDINE DI CORSA",
    relais_manque_reponses: 'mancano ancora risposte prima di poter correre',
    relais_manque_refus: 'un compagno ha rifiutato — questa squadra non può correre',
    relais_prete: 'squadra pronta',
    relais_classement: 'CLASSIFICA A SQUADRE',
    relais_plein_titre: 'DUE SQUADRE, NON TRE',
    relais_plein: 'corri già per due squadre. Lascia quella in cui non corri più per formarne un’altra.',
    relais_plein_invit: 'corri già per due squadre — lasciane una per accettare.',
    relais_quitter: 'LASCIA',
    relais_quitter_sur: 'lasciare per sempre?',
    relais_quitter_sub: 'si rientra solo con un nuovo invito',
    relais_reste: 'resta un posto',
    relais_place: '1 di 2 squadre',
    relais_places: '{n} di 2 squadre',
    relais_courir: 'VAI IN PISTA',
    relais_mon_rang: 'corri la {n}ª frazione',
    relais_premier: 'parti dai blocchi, in piedi. Una falsa partenza elimina tutta la squadra.',
    relais_ta_marque: 'IL TUO SEGNO NELLA ZONA',
    relais_zone_debut: 'dentro',
    relais_zone_fin: 'fuori',
    relais_marque_conseil: 'più avanti parti più veloce ma rischi di uscire dalla zona prima del testimone. Più indietro lo prendi di sicuro — da fermo.',
    relais_attend_equipe: 'manca(no) ancora {n} compagno/i',
    relais_temoin_a: 'TESTIMONE A',
    relais_spectateur: 'GLI ALTRI STANNO CORRENDO',
    relais_porte: 'PORTA',
    relais_attends_temoin: 'ASPETTA',
    relais_prends: 'PRENDI IL TESTIMONE',
    relais_donne: 'PASSA IL TESTIMONE',
    relais_arrivee: 'STAFFETTA COMPLETATA',
    relais_elimine: 'SQUADRA ELIMINATA',
    relais_elimine_pourquoi: 'alla frazione {r}: {c}',
    relais_passages: 'I TRE CAMBI',
    relais_elimine_court: 'fuori',
    relais_fantome: 'FANTASMA',

    conf_titre: 'CORRI CONTRO ALTRE SQUADRE',
    conf_desc: 'uno sparo, un ordine di arrivo. Apri un codice e condividilo, oppure inserisci quello che ti hanno dato.',
    conf_ouvrir: 'APRI UN CONFRONTO',
    conf_rejoindre: 'ENTRA',
    conf_code: 'codice',
    conf_code_court: 'quel codice è troppo corto',
    conf_partage: 'CONDIVIDI QUESTO CODICE CON LE ALTRE SQUADRE',
    conf_places: '{n} squadre in pista',
    conf_engagees: '{n} DI {m} SQUADRE',
    conf_attend_adversaire: 'serve almeno un’altra squadra, o un fantasma',
    conf_classement: 'ORDINE DI ARRIVO',
    conf_encore: 'gli altri stanno ancora correndo',

    fantome_titre: 'SFIDA I DIECI MIGLIORI PERCORSI',
    fantome_desc: 'sono già stati corsi: si ripetono, e non possono essere eliminati né battuti a un cambio. È l’unico modo per misurarsi con i migliori senza radunare otto persone.',
    fantome_aucun: 'nessun percorso registrato — la prima squadra che completa una staffetta apre le danze.',
    fantome_choisis: '{n} di {m} scelti',
    fantome_defier: 'SFIDALI',

    champ_directs: 'passano i primi {n}',
    champ_reveal: 'I MIGLIORI PERDENTI',
    champ_reveal_desc: 'non hanno vinto nessuna gara. Arrivano dal tempo di tutte.',
    champ_continue: 'CONTINUA',
    champ_sacre: '{n} viene incoronato — vedi il podio',
    champ_titre_duree: 'titolo per tre mesi',
    champ_rv_course: 'PROSSIMA GARA',
    champ_rv_reveal: 'MIGLIORI PERDENTI RIVELATI',
    champ_rv_sacre: 'CERIMONIA',
    champ_quitter: 'esci dal campionato',

    live_lanes: 'CORSIE',
    live_lanes_duel: 'un duello: chi vince prende punti, chi perde ne restituisce',
    live_lanes_course: 'una gara: un ordine di arrivo, nessun punto sulla classifica duelli',
    live_won: 'GARA VINTA',
    live_sur: 'SU {n} PARTENTI',
    live_ordre: 'ORDINE DI ARRIVO',
    live_lost: 'GARA PERSA',

    pres_title: 'PRESENTAZIONE DEGLI ATLETI',
    pres_lane: 'CORSIA',
    pres_you: 'QUESTO SEI TU',
    pres_mic_on: 'MICROFONO APERTO',
    pres_mic_off: 'microfono rifiutato',
    mic_winner: 'PARLA IL VINCITORE',

    review_title: 'IL VIDEO DELLA TUA GARA',
    review_making: 'registrazione…',
    review_dl: 'SCARICA',
    review_left: 'cancellato tra {t}',
    review_gone: 'il video è stato cancellato',
    review_kept: 'quello che hai scaricato resta sul tuo telefono',
    review_none: 'questo dispositivo non può registrare la gara',
    live_tie: 'ARRIVO IN PARITÀ',
    live_vs: 'in diretta contro {n}',
    live_gap: '{s} s di distacco',
    link_in_app: 'GIOCO INSTALLATO?',
    link_in_app_sub: 'aprilo dalla schermata home e inserisci questo codice — tocca per copiare',

    duel_answered: 'LA TUA SFIDA È STATA ACCETTATA',
    duel_more: 'resta {n} risultato',
    duel_mores: 'restano {n} risultati',
    duel_next: 'AVANTI',
    duel_ok: 'CAPITO',

    ghost_mode: 'MODALITÀ FANTASMA',
    ghost_ahead: 'AVANTI',
    ghost_behind: 'DIETRO',
    ghost_level: 'PARI',
    ghost_home: 'il fantasma ha tagliato il traguardo',
    ghost_live: 'il fantasma corre accanto a te',
    duel_must: 'manda una sfida, o rispondi a quella di un amico',
    duel_empty: 'nessun duello ancora giocato',
    duel_pts: 'pt',

    monde_sprinter_sous: 'il rettilineo e il giro',
    monde_hurdlers_sous: 'la stessa corsia, con dieci ostacoli dentro',
    monde_jumper_sous: 'costruisci la rincorsa e stacca da terra',
    monde_thrower_sous: 'un cerchio, un attrezzo e tutto il corpo',
    monde_bientot: 'PRESTO',
    monde_retour: 'TORNA A SPRINTER',

    disc_100: '100 METRI',
    disc_200: '200 METRI',
    disc_400: '400 METRI',
    disc_100h: '100 M OSTACOLI',
    disc_110h: '110 M OSTACOLI',
    disc_400h: '400 M OSTACOLI',
    disc_longueur: 'SALTO IN LUNGO',
    disc_hauteur: 'SALTO IN ALTO',
    disc_triple: 'SALTO TRIPLO',
    disc_perche: 'SALTO CON L ASTA',
    disc_poids: 'GETTO DEL PESO',
    disc_marteau: 'LANCIO DEL MARTELLO',
    disc_disque: 'LANCIO DEL DISCO',
    disc_javelot: 'LANCIO DEL GIAVELLOTTO',

    pique_0: 'Non ho nemmeno dovuto provarci.',
    pique_1: 'vuoi che lo rifaccia al rallentatore?',
    pique_2: 'ho fatto in tempo ad annoiarmi.',
    pique_3: 'il traguardo è da questa parte.',
    pique_4: 'grazie per il riscaldamento.',
    pique_5: 'mi sono girato e non c’era nessuno.',
    pique_6: 'hai corso? non ho visto passare niente.',
    pique_7: 'tieni quel tempo, sarà un bel ricordo.',

    mot_titre: 'LASCIA DUE RIGHE A {n}',
    mot_placeholder: 'punzecchialo in due righe',
    mot_vocal: 'VOCE',
    mot_ecouter: 'RIASCOLTA',
    mot_refaire: 'registra di nuovo',
    mot_envoyer: 'INVIA',
    mot_envoye: '{n} lo leggerà al ritorno',
    mot_micro_refuse: 'il microfono è stato rifiutato — va bene anche il testo',
    mot_ecouter_sa_voix: 'ASCOLTA COSA HA DETTO',
    mot_ephemere: 'questa registrazione sparisce quando chiudi questa finestra',
    mot_illisible: 'questo messaggio non si riproduce su questo dispositivo',

    mod_signaler: 'segnala',
    mod_titre: 'Perché lo segnali?',
    mod_explique: 'Una segnalazione la legge una persona. Il blocco vale subito.',
    mod_insulte: 'insulto',
    mod_haine: 'odio, razzismo',
    mod_sexuel: 'sessuale',
    mod_menace: 'minaccia',
    mod_autre: 'altro',
    mod_envoye: 'Segnalato. Qualcuno lo leggerà.',
    mod_deja: 'già segnalato',
    mod_bloquer: 'blocca {n}',
    mod_bloque: '{n} non può più scriverti.',
    mod_annuler: 'annulla',

    duel_revanche: 'VOGLIO LA RIVINCITA',
    duel_revanche_sub: 'stessa specialità — ora tocca a te fissare il tempo',
    duel_renvoyer: 'rimanda il codice a {n}',
    duel_revanche_envoyee: 'RIVINCITA INVIATA',
    os_revanche_sans_cible: 'non è stato possibile avvisare {n} — mandagli tu il codice',
    duel_revanche_ratee_titre: 'NON ANCORA',
    duel_revanche_ratee: 'ti serviva meno di {s} s per rilanciare la sfida a {n} — non è partito niente',

    rang_departemental: 'PROVINCIALE',
    rang_regional: 'REGIONALE',
    rang_national: 'NAZIONALE',
    rang_elite: 'ÉLITE',
    rang_legende: 'LEGGENDA',
    rang_court_departemental: 'PRO',
    rang_court_regional: 'REG',
    rang_court_national: 'NAZ',
    rang_court_elite: 'ÉLITE ',
    rang_court_legende: 'LEGGENDA',
    duel_lp: 'PL',
    duel_monte_a11y: 'sale di {n} posti',
    duel_descend_a11y: 'scende di {n} posti',
    duel_lp_long: 'punti lega',
    duel_promu: 'PROMOSSO IN {r}',
    duel_relegue: 'RETROCESSO IN {r}',
    duel_reste: '{n} alla divisione successiva',
    duel_regle: 'rispondere a una sfida rende più che lanciarla: il tempo è già sul tabellone, e sai cosa devi battere.',
    duel_record: '{v}V · {d}S · {n}P',
    duel_you: 'TU',
    duel_since: 'dalla tua ultima visita',
    duel_unranked: 'non ancora in classifica — gioca un duello',
    duel_won: 'DUELLO VINTO',
    duel_lost: 'DUELLO PERSO',
    duel_tie: 'PAREGGIO',
    duel_final: 'risultato definitivo — una sfida non si ripete',
    duel_delta: '{p} punto',
    duel_deltas: '{p} punti',

    false_out: 'FALSA PARTENZA',
    false_out_sub: 'eliminato — il duello è perso',
    false_out_seul: 'eliminato — questa gara finisce qui',
    false_out_rule: 'una sola gara, nessuna seconda occasione',
    false_out_libre: 'puoi rifarla',
    false_out_gun: 'partito prima dello sparo',
    duel_await: 'risultato del duello…',
    duel_vs: 'contro {n}',
    duel_seen: 'duello già chiuso',
    duel_see: 'VEDI LA CLASSIFICA',

    os_once: 'una volta inviata la sfida, il tempo è definitivo',
    os_rejouer: 'CORRI ANCORA',
    os_rejouer_sub: 'un’altra gara, subito — questa resta com’è',
    os_defier: 'SFIDA QUALCUNO',
    os_defier_sub: 'apri la classifica e scegli l’avversario — un altro, o lo stesso',
    relance_gagne_0: 'VAI A PRENDERNE UN ALTRO',
    relance_gagne_0_sub: 'quello è sistemato. Avanti.',
    relance_gagne_1: 'IL PROSSIMO, PREGO',
    relance_gagne_1_sub: 'la classifica è piena di gente, e tu sei lanciato.',
    relance_gagne_2: 'CHI ALTRO?',
    relance_gagne_2_sub: 'chiedi alla classifica. Qualcuno risponde.',
    relance_perdu_0: 'PRENDITELA CON UNO PIÙ PICCOLO',
    relance_perdu_0_sub: 'scendi di una divisione — non deve saperlo nessuno',
    relance_perdu_1: 'TROVA QUALCUNO PIÙ LENTO',
    relance_perdu_1_sub: 'esistono. Statisticamente, esistono.',
    relance_perdu_2: 'CI SONO ANCORA I PRINCIPIANTI',
    relance_perdu_2_sub: 'non sospettano niente. È il momento.',
    os_defi_sans_cible: '{n} non è nella TOP 500 di questa specialità — mandagli tu il codice',
    os_verrou_direct: 'gara in diretta: il tuo avversario ha corso nello stesso momento — quel risultato vale',
    os_verrou_recu: 'quel tempo è arrivato al tuo avversario — non si può ritirare',
    os_verrou_envoye: 'la sfida è partita — è quello il tempo da battere',
    os_verrou_faux: 'falsa partenza in un duello: la gara è persa. Manda una nuova sfida per ricominciare.',
    cut_skip: 'SALTA',

    id_title: 'IL TUO NOME',
    id_code_title: 'CODICE DI RECUPERO',
    id_code_note: 'annotalo: collega i tuoi altri dispositivi a questo nome, e impedisce che qualcuno te lo prenda',
    id_show: 'MOSTRA IL MIO CODICE',
    id_reserve: 'PRENOTA',
    id_taken: 'questo nome è già preso',
    id_taken_help: 'se è tuo, inserisci il suo codice di recupero',
    id_link: 'COLLEGA',
    id_linked: 'dispositivo collegato a {n}',
    id_bad_code: 'codice errato',
    id_unknown: 'nome sconosciuto',
    id_link_title: 'UN ALTRO DISPOSITIVO?',
    id_link_help: 'inserisci nome e codice per ritrovare qui i tuoi tempi e il tuo storico',

    install_title: 'INSTALLA IL GIOCO',
    install_why: 'schermo intero, senza barra del browser, e si gioca offline',
    install_do: 'INSTALLA',
    install_later: 'più tardi',
    install_ios_1: 'Tocca',
    install_ios_2: 'Condividi',
    install_ios_3: 'in basso su Safari, poi',
    install_ios_4: 'Aggiungi alla schermata Home',

    mode_career_s: 'carriera',
    mode_oneshot_s: 'one shot',
    cat_race_sub: 'miglior tempo in una singola gara',
    cat_run_sub: 'totale delle sei tappe',
    empty_cat_run: 'nessun percorso completo registrato',
    will_enter: '{s} s: {r} nella TOP 500, metti il tuo nome',

    wr_title: 'RECORD DEL MONDO',
    wr_sub: 'miglior tempo al mondo sui {d} m',
    wr_old: 'record precedente: {s} s',
    wr_first: 'primo tempo sul tabellone',
    wr_gain: '{s} s più veloce',
    wr_save: 'METTICI IL MIO NOME',
    wr_saving: 'salvataggio...',
    wr_done: '{n} è {r} nella TOP 500',
    wr_fail: 'invio fallito, riprova',
    wr_see: 'VEDI LA TOP 500',
    wr_later: 'più tardi',
    os_top_checking: 'controllo delle classifiche...',
    os_top_none: 'nessun tempo entra nella TOP 500',
    os_top_intro: '{n} tempo entra nella TOP 500',
    os_top_intro_n: '{n} tempi entrano nella TOP 500',
    os_top_line: '{d} m — {s} s — {r}',
    os_top_saved: 'tempi salvati come {n}',
    top500_count: '{n} tempi in classifica su 500',
    os_top_better: 'il tuo record sui {d} m resta {s} s',
    os_kept_title: 'IL TUO RECORD REGGE',
    os_kept_line: '{d} m: hai già {s} s ({r} nella TOP 500)',
    os_kept_now: 'questi {s} s non lo battono — la classifica tiene solo il migliore',

    pause_title: 'GARA IN PAUSA',
    pause_note: 'uscire adesso vuol dire rinunciare al tempo in corso',
    resume: 'RIPRENDI',

    challenge_them: 'SFIDA',
    target_run: 'corri i tuoi {d} m: la sfida va a {n}',
    target_sent: 'sfida inviata a {n}',
    inbox_one: 'SFIDA RICEVUTA',
    inbox_many: '{n} SFIDE RICEVUTE',
    inbox_from: '{n} ti sfida sui {d} m',
    inbox_accept: 'ACCETTA',
    inbox_later: 'più tardi',
    run_total_short: 'percorso completo:',
    run_total_tiny: 'percorso',
    best_split_tiny: 'gara',
    score_saved_race: '{r} nella TOP 500 mondiale con {s} s',
    mode_career: 'CARRIERA',
    mode_oneshot: 'ONE SHOT',
    mode_versus: 'SFIDA',
    career_desc: 'le sei tappe di fila, un solo tempo',
    oneshot_desc: 'scegli le tue gare, un solo tentativo',
    versus_desc: 'corri contro il fantasma di un altro giocatore',
    pick_events: 'GARE',
    pick_level: 'LIVELLO',
    pick_none: 'scegli almeno una gara',
    launch_oneshot: 'VIA',
    event_n: 'GARA {n} / {t}',
    next_event: 'GARA SUCCESSIVA',
    oneshot_done: 'ONE SHOT COMPLETATO',
    total_in: 'totale: ',
    challenge_code: 'CODICE SFIDA',
    challenge_enter: 'inserisci il codice che hai ricevuto',
    challenge_load: 'CARICA',
    challenge_loading: 'caricamento della sfida...',
    challenge_bad: 'codice non trovato',
    challenge_net: 'connessione fallita, riprova',
    challenge_from: 'sfida da {n}',
    challenge_beat: 'da battere: {s} s',
    challenge_aveugle: 'scoprirai il suo tempo correndo',
    challenge_accept: 'ACCETTA LA SFIDA',
    challenge_make: 'SFIDA UN AMICO',
    challenge_making: 'creazione della sfida...',
    challenge_share: 'manda questo codice, il tuo amico corre contro il tuo fantasma',
    challenge_copy: 'COPIA IL LINK',
    challenge_copied: 'link copiato',
    challenge_copy_code: 'COPIA IL CODICE',
    share_send: 'INVIA LA SFIDA',
    share_whatsapp: 'WhatsApp',
    share_sms: 'SMS',
    share_other: 'Snapchat, Instagram…',
    share_other_hint: 'Snapchat e Instagram si aprono dal menu di condivisione.',
    affiche_share: 'CONDIVIDI IL MIO PERCORSO',
    affiche_making: 'Creazione immagine…',
    affiche_saved: 'immagine salvata',
    affiche_failed: 'immagine non riuscita',
    affiche_hint: 'un’immagine del tuo percorso, per Instagram o TikTok',
    code_copied: 'codice copiato',
    challenge_rematch: 'RILANCIA LA SFIDA',
    challenge_rematch_sub: 'hai vinto — sfidalo sul percorso che hai appena fatto',
    challenge_won: 'SFIDA VINTA',
    challenge_lost: 'SFIDA PERSA',
    challenge_gap: 'distacco: {s} s',
    ghost_label: 'FANTASMA',
    you_label: 'TU',
    dnf_short: 'RIT',
    composing: 'composizione della colonna sonora...',

    sound_off: 'AUDIO SPENTO  (S)',
    press_enter: 'premi INVIO',
    skip_now_kb: 'premi di nuovo INVIO per saltare',
    skip_twice_kb: 'premi INVIO due volte per saltare',
    stage_dash: 'TAPPA {n}   -   {s}',
    furthest_kb: 'tappa più lontana raggiunta: {a} di {b}',
    enter_start: 'INVIO: inizia   -   S: audio   -   L: lingua   -   ESC: esci',
    how_to_play: 'COME SI GIOCA',
    help_1: 'Alterna  <-  e  ->  senza',
    help_2: 'ripetere lo stesso tasto.',
    help_3: 'Un ritmo costante dà velocità;',
    help_4: 'una ripetizione ti fa inciampare, ma',
    help_5: 'puoi sempre ripartire.',
    best_stage: 'MIGLIORI TEMPI DI QUESTA TAPPA',
    no_time: 'nessun tempo registrato',
    arrows_pick: 'frecce per scegliere   -   INVIO per confermare   -   ',
    yn_short: 'scorciatoia S / N',
    you_beat: 'Hai battuto {w} e superato tutte e sei le tappe.',
    the_zeze: 'gli ZEZE',
    your_times: 'I TUOI TEMPI',
    total: 'TOTALE',
    enter_replay: 'INVIO: corri ancora      M: home',
    stumble_kb: 'INCIAMPI!',
    go_kb: 'VIA!',
    to_beat_line: 'DA BATTERE:  {n}   -   {s} s',
    best_times_of: 'MIGLIORI TEMPI  -  {s}',
    enter_next: 'INVIO   ->   TAPPA {n}: {s}',
    full_run_pc: 'percorso completo in {s} s',
    announced_pc: 'tempo annunciato: {s} s',
    quit: 'ESC: esci'
  },

  CUTS: {
    intro: [
      [ // tappa 1
        ['{n} vince tutte le gare del cortile da tre anni.',
         'Il segreto: nessuno osa superarlo, il pallone è suo.',
         'Si scalda con le scarpe da scuola, per principio.',
         'Sua madre riprende da dietro la recinzione. Soprattutto la recinzione.'],
        ['{n} detiene il record della scuola, scritto a pennarello sul muro della palestra.',
         'Lo ha cronometrato un compagno, con un orologio a lancette.',
         'Il professore di ginnastica ha annuito una volta. È diventato ufficiale.',
         'Adesso ridipingono il muro tutto intorno al record.'],
        ['{n} ha chiesto la corsia 4. Gli hanno dato la corsia 4.',
         'Fa i suoi esercizi: ginocchia alte, calciata, sospiri profondi.',
         'Il pettorale è stampato in casa, un po’ storto.',
         'Il numero è 1. Se l’è stampato da solo.']
      ],
      [ // tappa 2
        ['{n} si scalda da quattro ore.',
         'La tuta ha il suo nome ricamato sulla schiena, in maiuscolo.',
         'Ha un rituale: tre passi indietro, un respiro, un occhiolino.',
         'L’occhiolino non è rivolto a nessuno in particolare.'],
        ['{n} arriva con due paia di chiodate e una borsa frigo.',
         'Nella borsa c’è una banana e moltissima determinazione.',
         'Regola i blocchi al millimetro, poi li rimette a posto.',
         'E una terza volta. Lo starter aspetta, educatamente.'],
        ['{n} è arrivato secondo ai regionali l’anno scorso.',
         'La descrive come una vittoria rubata dal vento contrario.',
         'La misura ufficiale diceva vento zero. Lui contesta la misura.',
         'Ha portato il suo anemometro. Non sa usarlo.']
      ],
      [ // tappa 3
        ['{n} è passato in televisione regionale.',
         'Trentotto secondi di immagini. Li ha guardati seicento volte.',
         'Firma autografi prima della gara, per guadagnare tempo’.',
         'Su scontrini, in mancanza di meglio.'],
        ['{n} ha un soprannome che non usa nessuno: la Freccia del Nord.',
         'Lo infila lui stesso in ogni intervista.',
         'Lo speaker lo ha appena presentato col nome vero, per errore.',
         'Ha chiesto una rettifica dagli altoparlanti. Arriverà più tardi.'],
        ['{n} si è tatuato il primato personale sull’avambraccio.',
         'Lo mostra al rallentatore durante la presentazione degli atleti.',
         'Quattro corridori di questa finale hanno già battuto quel numero.',
         'Il tatuaggio, purtroppo, non si aggiorna.']
      ],
      [ // tappa 4
        ['{n} ha uno sponsor, un procuratore e un fisioterapista.',
         'Tutti e tre gli dicono che è imbattibile. Tutti e tre li paga lui.',
         'Il procuratore ha già prenotato la sala per la conferenza della vittoria.',
         'Il catering è ordinato. Ci sono i canapè.'],
        ['{n} è numero uno al mondo da undici mesi.',
         'Lo ha saputo in diretta e da allora non si è mai voltato indietro.',
         'Letteralmente: il fisioterapista glielo ha sconsigliato con forza.',
         'Adesso gira tutto il busto. Più lento, ma fa la sua figura.'],
        ['Lo speaker chiama {n}. Lo stadio si alza in piedi.',
         'Indica la tribuna, poi il cielo, poi la telecamera.',
         'La telecamera era su un altro atleta. Ricomincia tutto da capo’.',
         'La regia cede. Il gesto durerà undici secondi.']
      ],
      [ // tappa 5
        ['{n} prova la sua esultanza da otto mesi.',
         'L’ha registrata come marchio. Manca solo vincere la gara.',
         'Un coro di quaranta persone aspetta il suo segnale.',
         'Hanno imparato una canzone. La canzone dice il suo nome, a lungo.'],
        ['{n} indossa i colori del suo paese, e ci tiene molto.',
         'La bandiera è sulle chiodate, sul pettorale e sull’asciugamano.',
         'L’asciugamano non corre, ma è pronto da martedì.',
         'Un membro dello staff lo porta ovunque dalla cerimonia di apertura.'],
        ['{n} aveva giurato di non guardare i rivali sui blocchi.',
         'Così fissa dritto davanti a sé, con notevole intensità.',
         'Un po troppo dritto: alla presentazione ha fissato il muro.',
         'Il muro non si era qualificato per questa finale.']
      ],
      [ // tappa 6
        ['{n} viene da un universo dove la gravità è facoltativa.',
         'Finisce le sue gare prima di decidere di cominciarle.',
         'Il suo record vale in undici dimensioni insieme.',
         'Nella dodicesima è inciampato, ma nessuno lo tira fuori.'],
        ['{n} ha corso questi cento metri in undici universi paralleli.',
         'Li ha vinti tutti e undici. Il dodicesimo non è mai stato omologato.',
         'Lì il giudice di arrivo era una nebulosa, poco affidabile sulla linea.',
         'La nebulosa è stata squalificata per tre stagioni.'],
        ['La famiglia ZEZE occupa tutte e sette le corsie. È regolamentare.',
         'Hanno portato il proprio starter, il proprio vento, il proprio arrivo.',
         'Il regolamento lo ha scritto uno ZEZE e rivisto uno ZEZE.',
         'È lungo una frase: vince uno ZEZE.']
      ]
    ],

    defeat: [
      [ // tappa 1
        ['{n} fa ricorso contro il risultato al sorvegliante della mensa.',
         'Il sorvegliante sta mangiando un panino. Il risultato resta.',
         'Poi chiede un verdetto al rappresentante di classe.',
         'Il rappresentante di classe è arrivato ultimo. Se la sta godendo.'],
        ['{n} spiega che il fondo del cortile è irregolare.',
         'È irregolare per tutti dal millenovecentosessanta.',
         'Poi accenna a un laccio slacciato. Le sue scarpe hanno lo strappo’.',
         'Il professore scrive il tuo tempo sul muro. Proprio sopra il suo.'],
        ['{n} annuncia che non stava correndo davvero.',
         'Si stava scaldando. La gara vera era la prossima.',
         'Nessuno era stato avvisato, il che spiega molte cose.',
         'Suona la campanella. La prossima gara non ci sarà mai.']
      ],
      [ // tappa 2
        ['{n} spiega che il suo orologio non è mai partito.',
         'Quindi, tecnicamente, questa gara non è mai esistita.',
         'Si offre di rifarla subito, tra gente seria.',
         'Poi si ricorda che ha un treno. Non ha nessun treno.'],
        ['{n} chiede di vedere il fotofinish.',
         'Gli mostrano la foto. Chiaramente dietro, e a fuoco perfetto.',
         'Chiede la stessa foto da un’altra angolazione.',
         'Da quell’angolo è ancora dietro, ma un po’ più sfocato.'],
        ['{n} ripone le due paia di chiodate senza dire una parola.',
         'Annuncia il passaggio ai 400, gara più tattica.',
         'Poi gli 800. Poi la maratona, dove tutto finisce comunque.',
         'Se ne va con la borsa frigo. La banana è intatta.']
      ],
      [ // tappa 3
        ['{n} annuncia il ritiro in diretta.',
         'Poi ci ripensa: lunedì di nuovo agli allenamenti.',
         'Fa notare che quel lunedì in particolare è molto pieno.',
         'Anche il lunedì dopo, a quanto pare.'],
        ['{n} chiede un controllo antidoping per il vincitore.',
         'Poi uno per sé, per correttezza.',
         'Sono entrambi negativi. La cosa gli sembra sospetta.',
         'Chiede un terzo controllo. Al cronometraggio.'],
        ['{n} mostra l’avambraccio ai giornalisti.',
         'Il record tatuato non si è mosso. Meglio di niente.',
         'Annuncia sei settimane di ritiro in altura.',
         'La montagna che ha scelto è alta duecento metri.']
      ],
      [ // tappa 4
        ['{n} pretende una seconda misura del vento.',
         'Il vento viene convocato. Il vento non si presenta.',
         'La conferenza della vittoria si tiene lo stesso, non si può più annullare.',
         'I canapè sono ottimi. È già qualcosa.'],
        ['{n} fissa il maxischermo per venti secondi.',
         'La classifica non cambia. Nemmeno lo schermo.',
         'Chiede se l’immagine è in diretta. Gli dicono di sì.',
         'Chiede allora se c’è un segnale differito. Non c’è.'],
        ['In zona mista, {n} parla di crescita e di percorso.',
         'Usa la parola ciclo undici volte in due minuti.',
         'Un giornalista gli chiede il tempo’. Risponde: il tempo arriverà.',
         'Il suo tempo è già sul tabellone dietro di lui, molto grande.']
      ],
      [ // tappa 5
        ['{n} fa la sua esultanza lo stesso.',
         'Il pubblico applaude, per educazione.',
         'Il coro, mal informato, attacca la canzone.',
         'Quaranta persone cantano il suo nome. Avrebbe preferito il silenzio.'],
        ['{n} fa il giro d’onore con la bandiera, come previsto.',
         'Il vincitore fa lo stesso giro, nel senso opposto.',
         'Si incrociano due volte. La seconda è peggio.',
         'L’asciugamano non se l’aspettava.'],
        ['{n} sale sul secondo gradino del podio.',
         'Si congratula col vincitore con una stretta di mano lunghissima.',
         'Abbastanza lunga da rifare la foto ufficiale tre volte.',
         'Nella terza sorride. Si vede quanto gli costa.']
      ],
      [ // tappa 6
        ['{n} ricalcola la traiettoria della sua galassia.',
         'Passava esattamente per il secondo posto.',
         'Cita un’anomalia temporale, poi un problema alle scarpe.',
         'Le due spiegazioni si contraddicono. Se le tiene entrambe.'],
        ['{n} chiede le classifiche degli altri undici universi.',
         'In tutti e undici ha appena perso anche lì. Simultaneamente.',
         'Si offre di aprirne un dodicesimo, tanto per vedere.',
         'Il dodicesimo è occupato. Anche lì sei arrivato primo.'],
        ['Gli altri sei ZEZE guardano {n} con molta calma.',
         'Nessuno dice una parola. Il silenzio dura quattro anni luce.',
         '{n} alla fine propone: oggi il fondo era diverso.',
         'Il fondo non è cambiato da quando hanno costruito la pista.']
      ]
    ],

    taunt: [
      [ // tappa 1
        ['{n} indica il tabellone, senza dire una parola.',
         'L’ha già firmato. Con un pennarello indelebile.',
         'Ti dà il suo panino. "Per la strada", dice.',
         'Tu non avevi chiesto nessun panino.'],
        ['{n} fa il giro d’onore. Tre metri, per mancanza di spazio.',
         'Saluta a lungo un pubblico immaginario.',
         'Ti offre la rivincita. Poi guarda l’orologio.',
         'Non ha l’orologio. Il gesto ha già detto tutto.'],
        ['{n} raccoglie le sue cose con calma, fischiettando.',
         'Il motivo è il tuo nome, in versione marcia trionfale.',
         'Ti dà una pacca sulla spalla. "La prossima volta", dice.',
         'Non ci crede neanche per un secondo, e si vede.']
      ],
      [ // tappa 2
        ['{n} guarda il cronometro, poi guarda te, con intenzione.',
         'Non dice niente. Il silenzio è più crudele delle parole.',
         'Firma autografi. Il primo è per te.',
         'Neanche quello lo avevi chiesto.'],
        ['{n} chiama il suo allenatore. "Abbiamo finito presto", dice.',
         'L’allenatore chiede perché. "Per educazione", risponde.',
         'Ti lascia tenere la sua medaglia. Solo un attimo.',
         'L’attimo dura dieci minuti. Fa le foto.'],
        ['{n} ripone le chiodate in una custodia col tuo nome.',
         'È una battuta interna. Il pubblico non segue.',
         'Ti offre l’acqua della sua borraccia. È vuota.',
         'Il gesto, dice, conta più dell’acqua.']
      ],
      [ // tappa 3
        ['{n} saluta la telecamera. Poi saluta te.',
         'Il secondo saluto è decisamente meno cordiale.',
         'Commenta la tua gara con i giornalisti, nel dettaglio.',
         'Il suo dettaglio preferito: il momento in cui ti sei girato.'],
        ['{n} chiede il microfono. Glielo danno, contro ogni buon senso.',
         'Ringrazia la famiglia, la società e te, in quest ordine.',
         '"Senza di lui", dice, "non avrebbe avuto lo stesso sapore".',
         'Non spiega cosa intende. Non serve.'],
        ['{n} si offre di rivedere la tua gara insieme, con calma.',
         'La revisione è lunga una parola. La dice molto lentamente.',
         'Ti stringe la mano due volte di fila, per sicurezza.',
         'La prima non gli era sembrata abbastanza convincente.']
      ],
      [ // tappa 4
        ['{n} rilascia un’intervista. L’argomento sei tu, stranamente.',
         'Tre minuti. Niente sulla sua gara.',
         'Conclude dicendo che ha imparato molto. Dalla tua sconfitta.',
         'Il giornalista trascrive parola per parola, a disagio.'],
        ['{n} fa cenno al procuratore di aggiungere una riga al palmarès.',
         'La riga dice soltanto: contro di te, ancora una volta.',
         'Ti invita alla conferenza stampa della vittoria.',
         'Una sedia ti aspetta, proprio in fondo, senza microfono.'],
        ['{n} ti mostra la classifica sul telefono, ingrandendo.',
         'Ingrandisce per un bel po’. La tua riga sta molto sotto la sua.',
         '"Posso mandartela via mail", propone, servizievole.',
         'Non gli hai mai dato il tuo indirizzo. Lui ce l’ha già.']
      ],
      [ // tappa 5
        ['{n} saluta la tribuna, poi si volta verso di te, solenne.',
         'Il gesto che fa dopo non sta in nessun regolamento.',
         'Un giornalista gli chiede una parola per l’avversario battuto.',
         'Ne dice sette. Nessuna finirà nell’articolo.'],
        ['{n} sale sul podio, poi scende di un gradino.',
         'Ti invita a vedere la medaglia da vicino.',
         'Molto da vicino. È d’oro. Ci tiene a precisarlo.',
         'Parte l’inno. Canta forte, guardando te.'],
        ['{n} dedica la vittoria alla famiglia, agli sponsor e a te.',
         '"Senza un avversario così motivante", dice, sincero.',
         'La parola motivante suona come un insulto ben mascherato.',
         'Il pubblico applaude, senza capire perché diventi rosso.']
      ],
      [ // tappa 6
        ['{n} guarda gli altri sei ZEZE. Annuiscono, insieme.',
         'Il verdetto è unanime, ed emesso senza un suono.',
         'Viene incisa una targa commemorativa, in una lingua morta.',
         'Dice, in sostanza: ci ha provato. È già qualcosa.'],
        ['{n} ricalcola la tua posizione in undici dimensioni diverse.',
         'In ognuna il risultato è identico, al secondo.',
         'Ti regala una mappa dell’universo in cui avresti vinto.',
         'Quell universo, precisa, non esiste ancora.'],
        ['{n} tende la mano verso il cielo. Una galassia si accende, docile.',
         'Per un istante forma la sagoma del suo sorriso.',
         'I sette ZEZE si consultano, poi si voltano verso di te.',
         'Il silenzio che segue dura quattro anni luce. Educatamente.']
      ]
    ],

    champion: [
      ['I sette ZEZE si consultano a lungo.',
       'Nessuno trova una scusa accettabile. È la prima volta.',
       'La classifica viene aggiornata in quattordici miliardi di sistemi.',
       'Una targa viene posata sulla linea di arrivo.',
       'Il tuo nome è scritto male, ma c’è.'],
      ['Lo speaker cerca una parola. Nessuna è abbastanza grande.',
       'Legge semplicemente il tempo, due volte, per sicurezza.',
       'Sette ZEZE fissano il maxischermo senza dire niente.',
       'Viene creata una commissione per controllare la linea di arrivo.',
       'La linea è dritta. Anche la classifica.'],
      ['Il giro d’onore dura più della gara.',
       'È aritmetica semplice, e nessuno si lamenta.',
       'Ti porgono una bandiera. Non sai da quale galassia venga.',
       'Viene da tutte: hanno fuso i disegni per l’occasione.',
       'Il coro ha riscritto la canzone. Dice il tuo nome, finalmente.']
    ]
  }
};
