/* -----------------------------------------------------------------------
   SPRINTER — 日本語.
   Ce qui manque ici retombe sur l'anglais, cle par cle : voir
   sprinter-i18n.js. Verification : node tools/langues-verifier.mjs ja
   ----------------------------------------------------------------------- */
export default {
  // 日本語の順位は「第1」ではなく「1位」。place キーが「{o} 位」を持つため
  // ここでは数字だけを返す。
  ord(n) { return String(n); },

  LEVEL_NAMES: [
    '校内大会', '地区レベル', '全国レベル',
    '世界選手権', 'ワールドゲームズ', '銀河間'
  ],

  RACE_SUB: {
    '100': '直線',
    '200': 'カーブと直線',
    '400': 'トラック一周'
  },

  UI: {
    races: '100 - 200 - 400 メートル',
    tagline: '六つのステージ、破るべき記録はひとつ',
    tap_start: '画面をタップして開始',
    six_stages: '   -   六ステージ',
    six_stages_bare: '六ステージ',
    best_runs: 'ベストラン',
    no_run: 'まだ完走した記録はありません',
    furthest: '最遠ステージ: ',
    of_six: ' / 6',
    start: 'スタート',
    sound: 'サウンド: ',
    yes: 'オン',
    no: 'オフ',

    rival: '倒すべきランナー',
    favourite: '本命',
    after_race: 'レースのあと',
    crowned: '銀河間王者',
    fastest_1: '最速の存在',
    fastest_2: '全銀河で',
    full_run_in: '全走破タイム ',
    announced: '公式タイム: ',
    stage_up: 'ステージ ',
    six_cleared: '六ステージ突破',
    skip_now: 'もう一度タップでスキップ',
    skip_twice: '二回タップでスキップ',

    reaction: 'リアクション',
    react_top: '完璧なリアクション',
    false_start: '飛び出しが早すぎた',
    wait_gun: '号砲を待て',
    phase_drive: '加速',
    phase_trans: '切り替え',
    phase_max: 'トップスピード',
    drive_hint: 'リズムを固めろ',
    trans_2: '完璧な切り替え',
    trans_1: '良い切り替え',
    trans_0: '切り替え失敗',
    start_line: 'スタート: 反応 {r} 秒   -   {g}',
    no_start: 'スタート失敗',

    stumble: 'つまずいた',
    to_beat: '目標: ',
    to_race: '対戦相手は ',
    ready: '位置について',
    get_set: '用意',
    go: 'ドン',
    alternate: '二つのボタンを交互に',
    alternate_kb: '二つの矢印を交互に',
    you: 'あなた',
    opponent: '相手',
    depart: 'スタート',
    arrivee: 'ゴール',

    stage_done: 'ステージ {n} 突破',
    first_in: '1位、タイム ',
    total_of: ' 秒   -   合計 ',
    place: '{o} 位',
    dnf: '棄権',
    unfinished: '未完走',
    race_again: 'もう一度?',
    next_stage: 'ステージ {n}',
    home: 'ホーム',
    replay: 'もう一度プレイ',
    run_done: '走破完了',
    six_in: '六ステージ突破 ',
    stage_low: 'ステージ ',

    new_record: '自己新記録',
    top3: 'トップ3',
    top10: 'トップ10',
    best_run: 'ベストラン',
    top3_runs: '走破トップ3',
    top10_runs: '走破トップ10',

    top500: 'TOP 500 - 歴代',
    your_name: 'あなたの名前',
    save_score: 'タイムを保存',
    saving_score: '送信中...',
    score_saved: '世界 TOP 500 で {r} 位',
    score_save_fail: '送信できませんでした。あとで試してください',
    score_name_taken: 'この名前は別の端末のものです',
    score_taken_help: '別の名前を選ぶか、マイレースで復旧コードを使ってこの端末をあなたの名前に結び付けてください',
    view_top500: 'TOP 500 を見る',
    top500_court: 'TOP 500',
    close: '閉じる',
    loading_ranks: 'ランキング読み込み中...',
    empty_top500: 'まだ記録がありません',
    your_rank: 'あなたの順位: {r}',
    outside_top500: 'トップ500圏外',
    edit_name: '名前を変更',
    best_split_short: 'ベストステージ:',
    top500_sub: '単一レースのベストタイム',
    cat_race: 'レース別',
    cat_run: '全走破',
    cat_mine: 'マイレース',
    cat_mine_sub: 'これまで走ったすべてのレース',
    mine_empty: 'この種目のレースはまだありません',
    mine_count: '{n} レース — ベスト: {s} 秒',
    mine_note: 'TOP 500 は種目ごとのベストタイムだけを残します。この履歴はすべてを残します。他の端末で見つけられるよう名前を確保してください。',

    duel_title: '対決ランキング',
    duel_sub: '送った挑戦と受けた挑戦',
    duel_open: '対決ランキングを見る',
    duel_rules_init: '挑戦を送信',
    duel_rules_recv: '挑戦に応答',
    duel_rules_line: '勝ち {v}   ·   負け {d}   ·   引き分け {n}',
    duel_rules_all: '送った側も受けた側も、すべての対決が計上されます',
    duel_rules_why: '挑戦する側は、先に自分のタイムを見せることになる',
    duel_counts: '送信 {l} · 応答 {r}',
    duel_sur: '対決の種目',

    name_set: '名前を決める',
    name_title: 'あなたの名前',
    name_why: 'TOP 500、挑戦、対決に表示される名前です',
    name_save: '保存',
    name_saved: '保存しました',
    name_taken: 'その名前はすでに使われています',
    name_code: 'あなたの復旧コード',
    pays_title: '国籍',
    pays_opt: '一度だけ',
    pays_aucun: '国を選ぶ',
    pays_why: '全国選手権に出るために必要です。あとから変更はできません',
    pays_vu: '{pays} から接続しているようです — 決めるのはあなたです',
    pays_save: '決定',
    pays_confirm: '{pays} 代表として走りますか?\n\nこれは最終決定です。どの全国選手権に入るかが決まり、あとから変更できません。',
    pays_fige: '確定',
    pays_on: 'この国の代表として走ります — 選手権では名前の横に国旗が並びます',
    pays_deja: '国籍はすでに決まっており、変更できません',
    pays_first: '先に名前を保存してください',
    pays_bad: '無効な国',
    insta_title: 'あなたの Instagram',
    insta_ph: 'ユーザー名（@ なし）',
    insta_why: 'TOP 500 やあなたの挑戦からプロフィールを開けるようになります',
    insta_note: 'ご自身の申告であり、確認は行われていません — Instagram は個人アカウントの実ログインをもう認めていません',
    insta_link: 'アカウントを連携',
    insta_linked: '連携しました',
    insta_unlink: '連携を解除',
    insta_on: 'TOP 500 にプロフィールが表示されます — タップで開きます',
    insta_gone: '連携を解除しました。プロフィールはどこにも表示されません',
    insta_bad: '無効なユーザー名',
    insta_first: '先に名前を保存してください',
    insta_notyours: 'この端末では、この名前はあなたのものではありません',
    insta_visit: '{n} の Instagram を見る',
    name_code_why: '控えておいてください。別の端末で名前と記録を取り戻せます',

    tour_open: 'ガイドを見る',
    tour_1_t: '交互に',
    tour_1_s: '左、右、左。レースはそれだけです。',
    tour_2_t: 'キャリア',
    tour_2_s: '六ステージ、校庭から銀河間決勝まで',
    tour_3_t: 'TOP 500',
    tour_3_s: 'あなたのタイムと、世界のすべて',
    tour_4_t: 'ゴースト',
    tour_4_s: '自分のレースを友達に送る — 相手はあなたと走ります',
    tour_5_t: 'ライブ',
    tour_5_s: '同じ号砲で、それぞれの端末から',
    tour_play: '遊ばせて',

    os_tuto_open: 'このモードの狙い',
    os_tuto_1_t: '種目を選ぶ',
    os_tuto_2_t: '挑戦は一度きり',
    os_tuto_3_t: 'タイムは記録される',
    os_tuto_1_s: '一つ、二つ、または三つすべて',
    os_tuto_2_s: 'やり直しなし、脱落なし',
    os_tuto_3_s: 'TOP 500、そして友達が受けて立てます',
    os_tuto_go: 'ONE SHOT を始める',

    tuto_ask_t: '最初のレース',
    tuto_ask_s: '操作は三十秒で覚えられます',
    tuto_ask_yes: '操作を覚える',
    tuto_ask_no: '走らせて',
    tuto_watch: '見る',
    tuto_your_turn: 'あなたの番',
    tuto_1_t: '交互に',
    tuto_2_t: '号砲と同時に',
    tuto_3_t: '大きく、そして小さく',
    tuto_v_early: '早すぎ',
    tuto_v_late: '遅すぎ',
    tuto_v_perfect: '完璧',
    tuto_v_good: 'good',
    tuto_v_slow: '速さが足りない',
    tuto_v_flat: '平坦なリズム',
    tuto_replay_demo: 'もう一度見る',
    tuto_again: 'もう一度',
    tuto_next: '次へ',
    tuto_done_t: 'あなたが走る番',
    tuto_start: 'スタート',
    tuto_replay: 'もう一度見る',
    tuto_skip: 'スキップ',
    tuto_open: '遊びかた',

    live_title: 'ライブレース',
    live_desc: '同じ号砲で二人同時にスタート、それぞれの端末で — ゴーストなし、勝者は誰にもわかりません',
    live_create: 'トラックを開く',
    live_join: '参加',
    live_or: 'または',
    live_room: 'トラック開放中',
    live_waiting: 'このコードを相手に送ってください — 二人そろえばレース開始です',
    live_ready: '準備完了',
    live_notready: 'まだです',
    live_empty_seat: 'レーン空き — 相手を待っています',
    live_go: '準備できました',
    live_unready: 'キャンセル',
    live_leave: 'トラックを離れる',
    live_none: 'そのコードのトラックはありません',
    live_full: 'そのトラックはすでに満員です',
    live_gone: '相手がトラックを離れました',
    live_closed: '接続が切れました',
    live_invite: 'トラックで待っています。コード {c} — {l}',

    relais_titre: '4 × 100 リレー',
    relais_desc: '四人の走者、一本のバトン。チームとはその顔ぶれです。同じ四つの名前で、同じチーム。',
    relais_invitations: '招待されています',
    relais_mes_equipes: 'あなたのチーム',
    relais_creer: 'チームを組む',
    relais_nom_equipe: 'チーム名',
    relais_coequipier: 'メンバー {n}',
    relais_inviter: '三人を招待',
    relais_incomplet: '名前と三人のメンバーが必要です',
    relais_attend: '返答待ち',
    relais_ok: '参加',
    relais_refuse: '辞退',
    relais_fixer_ordre: '走順を決める',
    relais_manque_reponses: '走るにはまだ返答が足りません',
    relais_manque_refus: 'メンバーが辞退しました — このチームは走れません',
    relais_prete: 'チーム準備完了',
    relais_classement: 'チームランキング',
    relais_plein_titre: 'チームは二つまで',
    relais_plein: 'すでに二つのチームで走っています。別のチームを組むには、もう走らないチームを抜けてください。',
    relais_plein_invit: 'すでに二つのチームで走っています — これを受けるにはどれか一つを抜けてください。',
    relais_quitter: '抜ける',
    relais_quitter_sur: '完全に抜けますか?',
    relais_quitter_sub: '戻るには新しい招待が必要です',
    relais_reste: '残り一枠',
    relais_place: '2チーム中1',
    relais_places: '2チーム中{n}',
    relais_courir: 'トラックへ',
    relais_mon_rang: 'あなたは第 {n} 走者',
    relais_premier: 'スタブロックから立って出ます。フライングはチーム全員の失格です。',
    relais_ta_marque: 'ゾーン内のマーク',
    relais_zone_debut: '入口',
    relais_zone_fin: '出口',
    relais_marque_conseil: '前に取るほど速く出られますが、バトンより先にゾーンを出るおそれがあります。後ろに取れば確実に受け取れますが、静止からになります。',
    relais_attend_equipe: 'まだ {n} 人足りません',
    relais_temoin_a: 'バトンは',
    relais_spectateur: '他の走者が走っています',
    relais_porte: '所持',
    relais_attends_temoin: '待て',
    relais_prends: 'バトンを取れ',
    relais_donne: 'バトンを渡せ',
    relais_arrivee: 'リレー完了',
    relais_elimine: 'チーム失格',
    relais_elimine_pourquoi: '第 {r} 走: {c}',
    relais_passages: '三度のバトンパス',
    relais_elimine_court: '失格',
    relais_fantome: 'ゴースト',

    conf_titre: '他のチームと走る',
    conf_desc: '号砲はひとつ、着順もひとつ。コードを開いて共有するか、受け取ったコードを入力してください。',
    conf_ouvrir: '対抗戦を開く',
    conf_rejoindre: '参加',
    conf_code: 'コード',
    conf_code_court: 'そのコードは短すぎます',
    conf_partage: 'このコードを他のチームと共有',
    conf_places: 'トラックに {n} チーム',
    conf_engagees: '{m} チーム中 {n}',
    conf_attend_adversaire: 'もう一チーム、またはゴーストが必要です',
    conf_classement: '着順',
    conf_encore: '他はまだ走っています',

    fantome_titre: '上位十走破に挑む',
    fantome_desc: 'すでに走られた記録です。再生されるだけで、失格にもならず、バトンパスで抜かれることもありません。八人を集めずに最上位と競う唯一の方法です。',
    fantome_aucun: 'まだ記録がありません — 最初にリレーを完走したチームが口火を切ります。',
    fantome_choisis: '{m} 件中 {n} 件選択',
    fantome_defier: '挑戦する',

    champ_directs: '上位 {n} 名が通過',
    champ_reveal: '最速の敗者たち',
    champ_reveal_desc: '一つも勝っていません。全レースのタイムから拾い上げられます。',
    champ_continue: '続ける',
    champ_sacre: '{n} が戴冠 — 表彰台を見る',
    champ_titre_duree: 'タイトルは三か月間',
    champ_rv_course: '次のレース',
    champ_rv_reveal: '最速の敗者を発表',
    champ_rv_sacre: '表彰式',
    champ_quitter: '選手権から抜ける',

    live_lanes: 'レーン',
    live_lanes_duel: '対決: 勝者はポイントを得て、敗者は一部を失います',
    live_lanes_course: 'レース: 着順のみ、対決ランキングのポイントはありません',
    live_won: 'レース勝利',
    live_sur: '出走 {n} 名中',
    live_ordre: '着順',
    live_lost: 'レース敗北',

    pres_title: '選手紹介',
    pres_lane: 'レーン',
    pres_you: 'これがあなた',
    pres_mic_on: 'マイク オン',
    pres_mic_off: 'マイクを拒否',
    mic_winner: '勝者のコメント',

    review_title: 'あなたのレース映像',
    review_making: '録画中…',
    review_dl: 'ダウンロード',
    review_left: '{t} 後に削除',
    review_gone: '映像は削除されました',
    review_kept: 'ダウンロードしたものは端末に残ります',
    review_none: 'この端末ではレースを録画できません',
    live_tie: '同着',
    live_vs: 'ライブ、対戦相手 {n}',
    live_gap: '差 {s} 秒',
    link_in_app: 'ゲームは入っていますか?',
    link_in_app_sub: 'ホーム画面から開いてこのコードを入力してください — タップでコピー',

    duel_answered: 'あなたの挑戦に応答がありました',
    duel_more: '結果があと {n} 件',
    duel_mores: '結果があと {n} 件',
    duel_next: '次へ',
    duel_ok: '了解',

    ghost_mode: 'ゴーストモード',
    ghost_ahead: 'リード',
    ghost_behind: 'ビハインド',
    ghost_level: '横並び',
    ghost_home: 'ゴーストがゴールしました',
    ghost_live: 'ゴーストが隣を走っています',
    duel_must: '挑戦を送るか、友達の挑戦に応えてください',
    duel_empty: 'まだ対決していません',
    duel_pts: 'pt',

    monde_sprinter_sous: '直線と一周',
    monde_hurdlers_sous: '同じレーン、そこに十台のハードル',
    monde_jumper_sous: '助走を組み立てて、地面を離れる',
    monde_thrower_sous: 'サークルと器具と、全身',
    monde_bientot: '近日',
    monde_retour: 'SPRINTER に戻る',

    disc_100: '100 メートル',
    disc_200: '200 メートル',
    disc_400: '400 メートル',
    disc_100h: '100 メートルハードル',
    disc_110h: '110 メートルハードル',
    disc_400h: '400 メートルハードル',
    disc_longueur: '走幅跳',
    disc_hauteur: '走高跳',
    disc_triple: '三段跳',
    disc_perche: '棒高跳',
    disc_poids: '砲丸投',
    disc_marteau: 'ハンマー投',
    disc_disque: '円盤投',
    disc_javelot: 'やり投',

    pique_0: '本気を出すまでもなかった。',
    pique_1: 'スローモーションでもう一度やろうか?',
    pique_2: '退屈する時間まであったよ。',
    pique_3: 'ゴールはこっち側だよ。',
    pique_4: 'ウォーミングアップをありがとう。',
    pique_5: '振り返ったけど、誰もいなかった。',
    pique_6: '走ってた? 何も通り過ぎなかったけど。',
    pique_7: 'そのタイムは取っておきなよ。いい思い出になる。',

    mot_titre: '{n} にひとこと残す',
    mot_placeholder: '二行で刺す',
    mot_vocal: '音声',
    mot_ecouter: '再生',
    mot_refaire: '録り直す',
    mot_envoyer: '送信',
    mot_envoye: '{n} が戻ったときに読みます',
    mot_micro_refuse: 'マイクが拒否されました — 文字でも構いません',
    mot_ecouter_sa_voix: '相手の言葉を聞く',
    mot_ephemere: 'この録音はこのウィンドウを閉じると消えます',
    mot_illisible: 'このメッセージはこの端末では再生できません',

    mod_signaler: '報告',
    mod_titre: '報告の理由は?',
    mod_explique: '報告は人が読みます。ブロックはすぐに反映されます。',
    mod_insulte: '侮辱',
    mod_haine: '差別・ヘイト',
    mod_sexuel: '性的な内容',
    mod_menace: '脅迫',
    mod_autre: 'その他',
    mod_envoye: '報告しました。担当者が確認します。',
    mod_deja: '報告済みです',
    mod_bloquer: '{n} をブロック',
    mod_bloque: '{n} はあなたに書き込めなくなりました。',
    mod_annuler: 'キャンセル',

    duel_revanche: 'リベンジしたい',
    duel_revanche_sub: '同じ種目 — 今度はあなたがタイムを出す番です',
    duel_renvoyer: '{n} にコードを返す',
    duel_revanche_envoyee: 'リベンジを送信しました',
    os_revanche_sans_cible: '{n} に通知できませんでした — コードを自分で送ってください',
    duel_revanche_ratee_titre: 'まだです',
    duel_revanche_ratee: '{n} に挑戦を返すには {s} 秒を切る必要がありました — 何も送信されていません',

    rang_departemental: '県',
    rang_regional: '地区',
    rang_national: '全国',
    rang_elite: 'エリート',
    rang_legende: 'レジェンド',
    rang_court_departemental: '県',
    rang_court_regional: '地区',
    rang_court_national: '全国',
    rang_court_elite: 'エリート ',
    rang_court_legende: 'レジェンド',
    duel_lp: 'LP',
    duel_monte_a11y: '{n} 位上昇',
    duel_descend_a11y: '{n} 位下降',
    duel_lp_long: 'リーグポイント',
    duel_promu: '{r} に昇格',
    duel_relegue: '{r} に降格',
    duel_reste: '次のディビジョンまで {n}',
    duel_regle: '挑戦を受けるほうが、送るより多く得られます。タイムはすでに出ていて、何を破ればいいかわかっているからです。',
    duel_record: '{v}勝 · {d}敗 · {n}分',
    duel_you: 'あなた',
    duel_since: '前回訪問以降',
    duel_unranked: 'まだランク外 — 対決を一つこなしてください',
    duel_won: '対決に勝利',
    duel_lost: '対決に敗北',
    duel_tie: '引き分け',
    duel_final: '最終結果 — 挑戦はやり直せません',
    duel_delta: '{p} ポイント',
    duel_deltas: '{p} ポイント',

    false_out: 'フライング',
    false_out_sub: '失格 — 対決は敗北です',
    false_out_seul: '失格 — このレースはここで終わりです',
    false_out_rule: 'レースは一度きり、二度目はありません',
    false_out_libre: 'もう一度走れます',
    false_out_gun: '号砲より先に出ました',
    duel_await: '対決の結果…',
    duel_vs: '対戦相手 {n}',
    duel_seen: '対決はすでに決着しています',
    duel_see: 'ランキングを見る',

    os_once: '挑戦を送った時点でタイムは確定します',
    os_rejouer: 'もう一度走る',
    os_rejouer_sub: 'いますぐもう一本 — こちらはこのまま残ります',
    os_defier: '誰かに挑戦する',
    os_defier_sub: 'ランキングを開いて相手を選んでください — 別の人でも、同じ人でも',
    relance_gagne_0: '次の相手を捕まえに行こう',
    relance_gagne_0_sub: 'その相手は片付いた。次へ。',
    relance_gagne_1: '次の方、どうぞ',
    relance_gagne_1_sub: 'ランキングは人でいっぱい、そしてあなたは絶好調。',
    relance_gagne_2: '他には誰が?',
    relance_gagne_2_sub: 'ランキングに聞いてみよう。誰かが答える。',
    relance_perdu_0: 'もっと小物を選ぼう',
    relance_perdu_0_sub: '一つ下のディビジョンへ — 誰にも知られません',
    relance_perdu_1: 'もっと遅い人を探そう',
    relance_perdu_1_sub: '存在します。統計的に、存在します。',
    relance_perdu_2: '初心者はまだいる',
    relance_perdu_2_sub: '相手は何も気づいていない。いまが好機。',
    os_defi_sans_cible: '{n} はこの種目の TOP 500 にいません — コードを自分で送ってください',
    os_verrou_direct: 'ライブレース: 相手は同じ瞬間に走りました — その結果が有効です',
    os_verrou_recu: 'このタイムはすでに相手に届いています — 取り消せません',
    os_verrou_envoye: '挑戦は送信済みです — 相手が破るべきタイムはこれです',
    os_verrou_faux: '対決でのフライング: レースは敗北です。新しい挑戦を送って仕切り直してください。',
    cut_skip: 'スキップ',

    id_title: 'あなたの名前',
    id_code_title: '復旧コード',
    id_code_note: '控えておいてください。他の端末をこの名前に結び付け、他人に取られるのを防ぎます',
    id_show: 'コードを表示',
    id_reserve: '確保する',
    id_taken: 'この名前はすでに使われています',
    id_taken_help: 'あなたのものなら、その復旧コードを入力してください',
    id_link: '連携',
    id_linked: '端末を {n} に連携しました',
    id_bad_code: 'コードが違います',
    id_unknown: '不明な名前',
    id_link_title: '別の端末ですか?',
    id_link_help: '名前とコードを入力すると、記録と履歴をここで取り戻せます',

    install_title: 'ゲームをインストール',
    install_why: '全画面、ブラウザーのバーなし、オフラインでも遊べます',
    install_do: 'インストール',
    install_later: 'あとで',
    install_ios_1: 'タップ:',
    install_ios_2: '共有',
    install_ios_3: 'Safari の下部、そして',
    install_ios_4: 'ホーム画面に追加',

    mode_career_s: 'キャリア',
    mode_oneshot_s: 'one shot',
    cat_race_sub: '単一レースのベストタイム',
    cat_run_sub: '六ステージの合計',
    empty_cat_run: 'まだ全走破の記録がありません',
    will_enter: '{s} 秒: TOP 500 で {r} 位、名前を登録しましょう',

    wr_title: '世界記録',
    wr_sub: '{d} m の世界最高タイム',
    wr_old: '従来の記録: {s} 秒',
    wr_first: 'ボードに載る最初のタイム',
    wr_gain: '{s} 秒短縮',
    wr_save: '名前を刻む',
    wr_saving: '保存中...',
    wr_done: '{n} は TOP 500 で {r} 位',
    wr_fail: '送信できませんでした。もう一度お試しください',
    wr_see: 'TOP 500 を見る',
    wr_later: 'あとで',
    top500_count: '500 件中 {n} 件がランクイン',

    pause_title: 'レース一時停止',
    pause_note: 'ここでやめると、進行中のタイムは失われます',
    resume: '再開',

    challenge_them: '挑戦する',
    target_run: '{d} m を走ってください: 挑戦は {n} に届きます',
    target_sent: '{n} に挑戦を送りました',
    inbox_one: '挑戦が届きました',
    inbox_many: '挑戦が {n} 件届いています',
    inbox_from: '{n} が {d} m で挑戦してきました',
    inbox_accept: '受ける',
    inbox_later: 'あとで',
    run_total_short: '全走破:',
    run_total_tiny: '走破',
    best_split_tiny: 'レース',
    score_saved_race: '{s} 秒で世界 TOP 500 の {r} 位',
    mode_career: 'キャリア',
    mode_oneshot: 'ONE SHOT',
    mode_versus: '挑戦',
    career_desc: '六ステージ連続、タイムはひとつ',
    oneshot_desc: '種目を選んで、挑戦は一度きり',
    versus_desc: '他のプレイヤーのゴーストと走る',
    pick_events: '種目',
    pick_level: 'レベル',
    pick_none: '種目を一つ以上選んでください',
    launch_oneshot: 'GO',
    event_n: '種目 {n} / {t}',
    next_event: '次の種目',
    oneshot_done: 'ONE SHOT 完了',
    total_in: '合計: ',
    challenge_code: '挑戦コード',
    challenge_enter: '受け取ったコードを入力',
    challenge_load: '読み込む',
    challenge_loading: '挑戦を読み込み中...',
    challenge_bad: 'コードが見つかりません',
    challenge_net: '接続に失敗しました。もう一度お試しください',
    challenge_from: '{n} からの挑戦',
    challenge_beat: '目標: {s} 秒',
    challenge_aveugle: '相手のタイムは走りながらわかります',
    challenge_accept: '挑戦を受ける',
    challenge_make: '友達に挑戦する',
    challenge_making: '挑戦を作成中...',
    challenge_share: 'このコードを送ると、友達があなたのゴーストと走ります',
    challenge_copy: 'リンクをコピー',
    challenge_copied: 'リンクをコピーしました',
    challenge_copy_code: 'コードをコピー',
    share_send: '挑戦を送る',
    share_whatsapp: 'WhatsApp',
    share_sms: 'SMS',
    share_other: 'Snapchat、Instagram…',
    share_other_hint: 'Snapchat と Instagram は共有メニューから開きます。',
    affiche_share: '走破を共有',
    affiche_making: '画像を作成中…',
    affiche_saved: '画像を保存しました',
    affiche_failed: '画像を作成できませんでした',
    affiche_hint: '走破の画像です。Instagram や TikTok にどうぞ',
    code_copied: 'コードをコピーしました',
    challenge_rematch: '挑戦を返す',
    challenge_rematch_sub: 'あなたの勝ちです — いま走った走破で挑み返しましょう',
    challenge_won: '挑戦に勝利',
    challenge_lost: '挑戦に敗北',
    challenge_gap: '差: {s} 秒',
    ghost_label: 'ゴースト',
    you_label: 'あなた',
    dnf_short: 'DNF',
    composing: 'サウンドトラックを作曲中...',

    sound_off: 'サウンド オフ  (S)',
    press_enter: 'ENTER を押す',
    skip_now_kb: 'もう一度 ENTER でスキップ',
    skip_twice_kb: 'ENTER を二回でスキップ',
    stage_dash: 'ステージ {n}   -   {s}',
    furthest_kb: '到達した最遠ステージ: {b} 中 {a}',
    enter_start: 'ENTER: 開始   -   S: サウンド   -   L: 言語   -   ESC: 終了',
    how_to_play: '遊びかた',
    help_1: '同じキーを繰り返さずに  <-  と',
    help_2: '->  を交互に押します。',
    help_3: '一定のリズムが速度を生みます。',
    help_4: '繰り返すとつまずきますが、',
    help_5: 'いつでも立て直せます。',
    best_stage: 'このステージのベストタイム',
    no_time: 'まだ記録がありません',
    arrows_pick: '矢印で選択   -   ENTER で決定   -   ',
    yn_short: 'Y / N のショートカット',
    you_beat: '{w} を破り、六ステージすべてを突破しました。',
    the_zeze: 'ZEZE 一族',
    your_times: 'あなたのタイム',
    total: '合計',
    enter_replay: 'ENTER: もう一度走る      M: ホーム',
    stumble_kb: 'つまずいた!',
    go_kb: 'ドン!',
    to_beat_line: '目標:  {n}   -   {s} 秒',
    best_times_of: 'ベストタイム  -  {s}',
    enter_next: 'ENTER   ->   ステージ {n}: {s}',
    full_run_pc: '全走破 {s} 秒',
    announced_pc: '公式タイム: {s} 秒',
    quit: 'ESC: 終了',

    // accueil : le nom, le drapeau, Instagram, un pas a la fois
    bienvenue_titre: 'ようこそ',
    bv_nom_t: 'あなたの名前',
    bv_nom_s: 'すべてのタイムに付いて回ります',
    bv_pays_t: 'あなたの国旗',
    bv_pays_s: '選手権のため — 変更できません',
    bv_insta_t: 'あなたの Instagram',
    bv_insta_s: 'ランキングから開けます — 自己申告、未確認',
    bv_passer: 'スキップ',
    bv_suite: '次へ',
    bienvenue_plus: 'あとで',
    bienvenue_go: 'はじめる',
    contact: 'お問い合わせ',

    // la montee au classement, annoncee et lue a voix haute
    places_1: '位',
    places_n: '位',
    classement_entree: 'ランキング入り',
    classement_bouge_a11y: '{n} 位上昇 — {c} で {r} 位',
    classement_perd_a11y: '{n} 位下降 — {c} で {r} 位',
    classement_entre_a11y: 'ランキング入り — {c} で {r} 位',

    // notifications
    avis_title: '通知',
    avis_desc: 'ゲームを閉じていても知らせを受け取る',
    avis_pourquoi: '夜中に届いた挑戦も、翌日に気づいたのでは意味がありません',
    avis_activer: '通知をオンにする',
    avis_couper: '受け取りをやめる',
    avis_actives: '通知はオンです',
    avis_essai: 'テストを送ってもらう',
    avis_essai_ok: '送信しました — 一秒ほどで届くはずです',
    avis_essai_ko: '何も送信されませんでした。通知が許可されているか確認してください',
    avis_refuse: '以前に拒否しています。ここではなく端末の設定から開き直せます',
    avis_installer: 'iPhone ではまずホーム画面にゲームを追加してください。Safari は インストール済みのアプリにしか通知を渡しません',
    avis_indispo: 'このブラウザーでは受け取れません',
    avis_erreur: 'サーバーが登録を保存できませんでした',
    avis_choisir: '受け取りたいもの',
    avis_g_defi: '届いた挑戦',
    avis_g_defi_s: '誰かがあなたに破るべきタイムを送りました',
    avis_g_selection: '選手権への選出',
    avis_g_selection_s: 'あなたは 32 人の走者の一人です',
    avis_g_direct: 'ライブの挑戦',
    avis_g_direct_s: 'いま、誰かがトラックで待っています',
    avis_g_relais: 'リレーへの誘い',
    avis_g_relais_s: 'あるチームがあなたを求めています',
    avis_g_rendezvous: '選手権の開始時刻',
    avis_g_rendezvous_s: '各レースの十五分前に',
    avis_g_assister: '決勝と、その勝者',
    avis_g_assister_s: '十五分前に、そして戴冠 — あなたが出ていなくても',
    avis_g_record: '世界記録が破られたとき',
    avis_g_record_s: 'ある距離の首位が入れ替わります',
    avis_suivre: 'どの選手権を',
    avis_suivre_national: '自分の国',
    avis_suivre_continental: '自分の大陸',
    avis_suivre_mondial: '世界選手権',
    avis_suivre_vide: '少なくとも一つ選んでください。でないと何も届きません',
    avis_suivre_nom: '国がわかるよう、上で名前を確保してください',

    // inviter quelqu un sur la piste, par son nom
    live_inviter: 'プレイヤーを誘う',
    live_inviter_ph: '相手の名前',
    live_inviter_ok: '{n} に通知しました — 相手の端末が鳴っています',
    live_inviter_ko: 'その名前を確保している人はいません。コードを送ってください',
    live_invite_recue: '{n} がトラックで待っています',
    live_invite_rejoindre: '参加',

    // suppression du profil
    id_del: 'プロフィールを削除',
    id_del_what: 'あなたの名前、コード、ランキングのタイム、オンラインの履歴、挑戦と対決が、すべての端末でサーバーから削除されます。',
    id_del_keep: 'キャリアの進行と、この端末に残っているレースはそのままです。',
    id_del_final: 'これは最終的な操作です。どれも元に戻せません。',
    id_del_confirm: '確認のため {n} と入力してください',
    id_del_go: '削除',
    id_del_cancel: 'キャンセル',
    id_del_done: 'プロフィールを削除しました',
    id_del_device: 'この名前は確保されていませんでした。この端末から送られたものを消去しました',
    id_del_code: 'この端末はこの名前に結び付いていません。復旧コードを入力してください',

    // le record personnel a la fin d un one shot
    os_record_titre: '自己記録更新',
    os_record_titre_n: '自己記録を更新',
    os_record_sur: '{d} m で',
    os_record_premier: 'この距離での最初のタイム',
    os_record_gain: '{s} 秒短縮',
    os_record_rang: 'TOP 500 - 歴代で {r} 位',
    os_record_saved: '{n} の名前で保存しました',
    os_record_suite: '続ける',
    os_record_sansnom: 'TOP 500 に載せるには、ホーム画面で名前を決めてください',

    // le record du monde qui tombe, et les piques qui l accompagnent
    wrm_titre: '世界記録',
    wrm_sur: '{d} m で',
    wrm_pris: '{n} から奪取 — {s} 秒短縮',
    wrm_pris_soi: '自身の記録を {s} 秒更新',
    wrm_defier: '破りに行く',
    wrm_note_0: '挑戦者各位へ。基準が今しがた上がりました。',
    wrm_note_1: 'どなたか応じますか。こちらは待っています。',
    wrm_note_2: 'ほかの皆さまには、より速く走っていただくようお願いします。',
    wrm_note_3: 'このタイムはしばらく居座ります。よほどのことがなければ。',
    wrm_note_4: 'ボードの頂点が入れ替わりました。今のところは。',
    wrm_note_5: '祝福は任意です。更新は任意ではありません。',
    wrm_note_6: '破るべきタイムがあります。あなたのものではありません。',
    wrm_note_7: 'どこかで誰かが、たったいまあなたより速く走りました。',
    wrm_note_8: 'トラックは開いています。記録のほうはあまり開いていません。',
    wrm_note_9: 'タイムをもう一度読んでも構いません。ひとりでには動きません。',
    wrm_note_10: '選択肢は二つ。鍛えるか、慣れるか。',
    wrm_note_11: 'ボードの一番上に新しい名前。あなたのはもっと下です。',
    wrm_note_12: '通知を読んで記録を破った人は、まだ一人もいません。',
    wrm_note_13: 'その人のゴーストが TOP 500 で待っています。噛みつきはしません。',
    wrm_note_14: 'たかが記録です。記録は取り返せます。',
    wrm_note_15: 'スタブロックは空いています。念のため。'
  },

  CUTS: {
    intro: [
      [ // ステージ1
        ['{n} はこの三年、校庭のレースをすべて勝っている。',
         '秘訣は単純だ。誰も追い抜く勇気がない。ボールは彼のものだから。',
         '主義として、通学用の靴でウォーミングアップする。',
         '母親はフェンス越しに撮影している。だいたいフェンスが映っている。'],
        ['{n} は校内記録の保持者で、体育館の壁にマジックで書かれている。',
         '計測したのは同級生、針のある腕時計で。',
         '体育教師が一度うなずいた。それで公式になった。',
         'いまでは記録を避けて壁が塗り直される。'],
        ['{n} は4レーンを希望した。4レーンが与えられた。',
         'いつもの動きをこなす。もも上げ、かかと寄せ、深いため息。',
         'ゼッケンは自宅で印刷、少し傾いている。',
         '番号は1。ひとりで、自分で刷った。']
      ],
      [ // ステージ2
        ['{n} は四時間前からウォーミングアップしている。',
         'ジャージの背中には名前が刺繍されている、大文字で。',
         '儀式がある。三歩下がり、ひと息つき、ウインクを一つ。',
         'そのウインクは誰に向けたものでもない。'],
        ['{n} はスパイク二足とクーラーボックスを持って現れる。',
         '中身はバナナ一本と、有り余る決意。',
         'スタブロックをミリ単位で合わせ、それからやり直す。',
         'そして三度目。スターターは待っている、礼儀正しく。'],
        ['{n} は昨年の地区大会で二位だった。',
         '向かい風に盗まれた勝利だった、と本人は言う。',
         '公式計測は無風だった。彼はその計測に異を唱えている。',
         '自前の風速計を持参した。使い方は知らない。']
      ],
      [ // ステージ3
        ['{n} は地方テレビに映ったことがある。',
         '三十八秒の映像。六百回見返した。',
         '時間の節約のため、レース前にサインをしている。',
         'ほかに紙がないので、レシートの裏に。'],
        ['{n} には誰も使わないあだ名がある。北の矢。',
         'インタビューのたびに、自分でねじ込んでいる。',
         'アナウンサーはいま、手違いで本名のほうを読み上げた。',
         '場内放送での訂正を要求済み。訂正はあとで来る。'],
        ['{n} は自己ベストを前腕に彫っている。',
         '選手紹介の場でスローモーションのように見せる。',
         'この決勝の四人は、すでにその数字を破っている。',
         '残念ながら、タトゥーは自動更新されない。']
      ],
      [ // ステージ4
        ['{n} にはスポンサーと代理人とトレーナーがついている。',
         '三人とも彼は無敵だと言う。三人とも彼が雇っている。',
         '代理人は勝利会見の部屋をすでに押さえてある。',
         'ケータリングも手配済み。カナッペが並ぶ。'],
        ['{n} は十一か月、世界ランク一位だ。',
         '生放送でそれを知り、以来一度も振り返っていない。',
         '文字どおりに。トレーナーが強く止めたからだ。',
         'いまは上半身ごと回す。遅いが、見栄えはいい。'],
        ['アナウンサーが {n} を呼ぶ。スタジアムが総立ちになる。',
         'スタンドを指し、それから空を指し、それからカメラを指す。',
         'カメラは別の選手を映していた。彼は最初からやり直す。',
         'ディレクターが折れる。この所作は十一秒続くことになる。']
      ],
      [ // ステージ5
        ['{n} は八か月前からガッツポーズを練習している。',
         '商標登録も済ませた。あとはレースに勝つだけだ。',
         '四十人の合唱団が彼の合図を待っている。',
         '歌も覚えてある。歌詞には彼の名前が、長々と出てくる。'],
        ['{n} は自国の色をまとい、それを本気で大事にしている。',
         '国旗はスパイクにも、ゼッケンにも、タオルにもある。',
         'タオルは走らないが、火曜からずっと準備万端だ。',
         'スタッフの一人が開会式以来どこへでも運んでいる。'],
        ['{n} はスタブロックでライバルを見ないと誓っていた。',
         'そこで彼はまっすぐ前を見つめる、並外れた集中で。',
         'やや前を見すぎだ。選手紹介のときは壁を見つめていた。',
         'その壁はこの決勝に残っていない。']
      ],
      [ // ステージ6
        ['{n} は重力が任意である宇宙から来ている。',
         '走り始めると決める前に、レースを走り終えてしまう。',
         '彼の記録は十一の次元で同時に有効だ。',
         '十二次元目ではつまずいたが、誰もその話は持ち出さない。'],
        ['{n} はこの百メートルを十一の並行宇宙で走った。',
         '十一すべてで勝った。十二番目は公認されなかった。',
         'そこの決勝審判は星雲で、ゴール線の判定が当てにならない。',
         'その星雲は三シーズンの出場停止になった。'],
        ['ZEZE 一族が七レーンすべてを占める。規則どおりだ。',
         '自前のスターター、自前の風、自前のゴールを持ち込んでいる。',
         '規則を書いたのは ZEZE、点検したのも ZEZE。',
         '規則は一文だけだ。ZEZE が勝つ。']
      ]
    ],

    defeat: [
      [ // ステージ1
        ['{n} は結果を給食当番に不服申し立てする。',
         '当番はサンドイッチを食べている。結果は変わらない。',
         '次に学級委員に裁定を求める。',
         '学級委員は最下位だった。この状況を存分に楽しんでいる。'],
        ['{n} は校庭の路面が平らでないと説明する。',
         '一九六〇年以来、みんなにとって平らではない。',
         '次に靴ひもがほどけていたと言う。彼の靴はマジックテープだ。',
         '教師があなたのタイムを壁に書く。彼のすぐ上に。'],
        ['{n} は本当は走っていなかったと言い出す。',
         'ウォーミングアップだった。本番は次のレースだったと。',
         '誰にも知らされていなかったが、それで多くのことが説明される。',
         'チャイムが鳴る。次のレースは永遠に来ない。']
      ],
      [ // ステージ2
        ['{n} は自分の時計がそもそも動いていなかったと説明する。',
         'したがって技術的には、このレースは存在しなかったことになる。',
         'いますぐやり直そうと持ちかける、まじめな人間どうしで。',
         'そのあと電車があると思い出す。電車などない。'],
        ['{n} はゴール写真を見せてほしいと言う。',
         '写真が示される。明らかに後ろで、しかもよく写っている。',
         '同じ写真を別角度で、と頼む。',
         'その角度でもやはり後ろだが、少しだけぼやけている。'],
        ['{n} は無言でスパイク二足をしまう。',
         'より駆け引きのある400へ転向すると宣言する。',
         '次は800。そしてマラソン。どのみちそこで全部終わる。',
         'クーラーボックスを提げて去る。バナナは手つかずのままだ。']
      ],
      [ // ステージ3
        ['{n} は生放送で引退を表明する。',
         'そのあと考え直す。月曜から練習に戻ると。',
         'その月曜に限って予定が異様に詰まっている、と本人は言う。',
         '次の月曜も、どうやらそうらしい。'],
        ['{n} は勝者へのドーピング検査を要求する。',
         '公平のため、自分にも検査を、と付け加える。',
         '二つとも陰性だった。彼はそれを不審に思う。',
         '三度目の検査を要求する。計時機材のほうに。'],
        ['{n} は記者たちに前腕を見せる。',
         '彫られた記録は動いていない。まだましというものだ。',
         '六週間の高地合宿を宣言する。',
         '選んだ山は標高二百メートルだった。']
      ],
      [ // ステージ4
        ['{n} は風速の再計測を要求する。',
         '風が呼び出される。風は現れない。',
         '勝利会見は予定どおり開かれる。もう中止できないからだ。',
         'カナッペは絶品だ。それはそれで何よりだ。'],
        ['{n} は大型スクリーンを二十秒間見つめる。',
         '順位は変わらない。スクリーンも変わらない。',
         '映像は生かと尋ねる。生だと告げられる。',
         'では遅延の映像はあるかと尋ねる。ない。'],
        ['ミックスゾーンで {n} は進歩と過程について語る。',
         '二分間でサイクルという語を十一回使う。',
         '記者がタイムを尋ねる。答えは「タイムはこれから来る」。',
         '彼のタイムは背後の掲示板にもう出ている、とても大きく。']
      ],
      [ // ステージ5
        ['{n} はそれでもガッツポーズを実行する。',
         '観客は拍手する、礼儀として。',
         '知らされていない合唱団が、歌をやってしまう。',
         '四十人が彼の名を歌う。彼は沈黙のほうがよかった。'],
        ['{n} は予定どおり国旗を持って場内一周する。',
         '勝者も同じ一周をする、逆回りで。',
         '二度すれ違う。二度目のほうがこたえる。',
         'タオルはこの展開を予想していなかった。'],
        ['{n} は表彰台の二段目に上がる。',
         '勝者を、とても長い握手で祝福する。',
         '公式写真を三回撮り直すほど長い握手だ。',
         '三枚目で彼は笑う。それがどれほどの代償かが見て取れる。']
      ],
      [ // ステージ6
        ['{n} は自分の銀河の軌道を計算し直す。',
         'その軌道はちょうど二位の位置を通っていた。',
         '時間異常を挙げ、続いて靴の不具合を挙げる。',
         '二つの説明は互いに矛盾する。彼は両方を残しておく。'],
        ['{n} は他の十一宇宙の順位を要求する。',
         '十一すべてで、彼もいま負けたところだった。同時に。',
         '十二番目を開いてみようかと持ちかける、見るだけのつもりで。',
         '十二番目はふさがっている。そこでもあなたが一位だった。'],
        ['他の六人の ZEZE が、とても静かに {n} を見る。',
         '誰も一言も発しない。沈黙は四光年続く。',
         'ついに {n} が切り出す。今日は路面が違った、と。',
         'トラックができてから、路面は一度も変わっていない。']
      ]
    ],

    taunt: [
      [ // ステージ1
        ['{n} は無言で得点板を指さす。',
         'そこにはもうサインまでしてある。油性ペンで。',
         '自分のサンドイッチを差し出す。「道中でどうぞ」と言って。',
         'サンドイッチなど頼んでいない。'],
        ['{n} はウイニングランをする。場所がないので三メートル。',
         '架空の観客に、長々と手を振る。',
         'リベンジを持ちかける。それから腕時計を見る。',
         '腕時計はしていない。その仕草だけで十分だった。'],
        ['{n} はのんびり荷物をまとめる、口笛を吹きながら。',
         'その旋律はあなたの名前で、凱旋行進曲に乗せてある。',
         '肩を叩いて「次があるさ」と言う。',
         '一秒たりとも信じていない。そしてそれが顔に出ている。']
      ],
      [ // ステージ2
        ['{n} は時計を見て、それからあなたを見る、意味ありげに。',
         '何も言わない。その沈黙は言葉より残酷だ。',
         'サインを配りはじめる。一枚目はあなたに。',
         'それも頼んでいない。'],
        ['{n} はコーチに電話する。「早く終わりました」と。',
         'コーチが理由を尋ねる。「礼儀として」と答える。',
         'メダルを持たせてくれる。ほんの一瞬だけ。',
         'その一瞬は十分続く。彼は写真を撮りつづける。'],
        ['{n} はスパイクを、あなたの名前入りのケースにしまう。',
         '内輪の冗談だ。観客はついてこない。',
         'ボトルの水をすすめてくる。ボトルは空だ。',
         '大事なのは水ではなく気持ちだ、と彼は言う。']
      ],
      [ // ステージ3
        ['{n} はカメラに手を振る。それからあなたにも手を振る。',
         '二度目の手の振りは、目に見えて素っ気ない。',
         '記者たちとあなたのレースを、細部まで語り合う。',
         'お気に入りの細部は、あなたが振り返った瞬間だ。'],
        ['{n} はマイクを求める。良識に反して、渡される。',
         '家族に、クラブに、そしてあなたに感謝する。その順で。',
         '「彼がいなければ、この味は出なかった」と言う。',
         '何を言いたいのかは説明しない。説明の必要もない。'],
        ['{n} はあなたのレースを一緒に落ち着いて振り返ろうと言う。',
         '振り返りは一語で終わる。それをとてもゆっくり口にする。',
         '念のため、二度続けて握手する。',
         '一度目では説得力が足りないと感じたらしい。']
      ],
      [ // ステージ4
        ['{n} がインタビューに応じる。話題は、なぜかあなただ。',
         '三分間。自分のレースの話は一言もない。',
         '多くを学んだ、と締めくくる。あなたの敗戦から。',
         '記者は一語一句書き取る、居心地悪そうに。'],
        ['{n} は代理人に合図し、戦績に一行加えさせる。',
         'その一行はただこう書かれる。あなたを相手に、もう一度。',
         '勝利会見にあなたを招く。',
         '椅子が用意されている。いちばん後ろ、マイクなしで。'],
        ['{n} はスマホで順位表を見せてくる、拡大しながら。',
         'かなり長く拡大する。あなたの行は、彼の行のずっと下だ。',
         '「メールで送ろうか」と、親切に申し出る。',
         'アドレスを教えた覚えはない。彼はもう持っている。']
      ],
      [ // ステージ5
        ['{n} はスタンドに手を振り、それから厳かにあなたへ向き直る。',
         'そのあとの所作は、どの競技規則にも載っていない。',
         '記者が敗れた相手への一言を求める。',
         '彼は七つ言う。どれも記事には載らない。'],
        ['{n} は表彰台に上がり、そして一段だけ下りてくる。',
         'メダルを近くで見ていきなよ、と誘う。',
         'かなり近くで。金だ。そこを強調する。',
         '国歌が始まる。あなたを見ながら、大きな声で歌う。'],
        ['{n} は勝利を家族に、スポンサーに、そしてあなたに捧げる。',
         '「これほど刺激的な相手がいなければ」と、誠実に言う。',
         '刺激的という語が、巧みに包まれた侮辱として着地する。',
         '観客は拍手する。あなたが赤面する理由は知らないまま。']
      ],
      [ // ステージ6
        ['{n} が他の六人の ZEZE を見る。全員が同時にうなずく。',
         '評決は全会一致、しかも物音ひとつ立てずに下される。',
         '記念のプレートが彫られる、死語となった言語で。',
         'およそこう書いてある。彼は試みた。それだけでも何よりだ。'],
        ['{n} はあなたの順位を、十一の異なる次元で計算し直す。',
         'どの次元でも結果は同一だ、秒単位まで。',
         'あなたが勝っていた宇宙の地図をくれる。',
         'その宇宙はまだ存在しない、と彼は付け加える。'],
        ['{n} が空へ手を伸ばす。銀河がひとつ、素直に灯る。',
         'それは一瞬、彼の笑みの輪郭をかたどる。',
         '七人の ZEZE が相談し、それからあなたへ向き直る。',
         '続く沈黙は四光年続く。礼儀正しく。']
      ]
    ],

    champion: [
      ['七人の ZEZE が長い時間、協議する。',
       '誰ひとり、受け入れられる言い訳を見つけられない。前代未聞だ。',
       '順位表が百四十億の星系で更新される。',
       'ゴールラインに記念のプレートが据えられる。',
       'あなたの名前は綴りを間違えられている。それでも、そこにある。'],
      ['アナウンサーが言葉を探す。どれも大きさが足りない。',
       '結局タイムを読み上げるだけにする、念のため二度。',
       '七人の ZEZE が無言で大型スクリーンを見つめる。',
       'ゴールラインを検証する委員会が設けられる。',
       'ラインはまっすぐだ。順位表も同じく。'],
      ['ウイニングランのほうが、レースそのものより長く続く。',
       '単純な算数であり、誰も文句を言わない。',
       '旗を手渡される。どの銀河のものか見当もつかない。',
       'すべての銀河のものだ。この日のために意匠を統合したのだ。',
       '合唱団は歌を書き直した。ようやく、あなたの名前が出てくる。']
    ]
  }
};
