/* -----------------------------------------------------------------------
   SPRINTER — 한국어.
   Ce qui manque ici retombe sur l'anglais, cle par cle : voir
   sprinter-i18n.js. Verification : node tools/langues-verifier.mjs ko
   ----------------------------------------------------------------------- */
export default {
  // place 키가 이미 「{o}위」 형태이므로 숫자만 돌려준다.
  ord(n) { return String(n); },

  LEVEL_NAMES: [
    '교내 대회', '지역 수준', '전국 수준',
    '세계선수권', '올림픽', '은하 간'
  ],

  RACE_SUB: {
    '100': '직선 주로',
    '200': '곡선과 직선',
    '400': '트랙 한 바퀴'
  },

  UI: {
    races: '100 - 200 - 400 미터',
    tagline: '여섯 단계, 넘어야 할 기록은 하나',
    tap_start: '화면을 눌러 시작',
    six_stages: '   -   여섯 단계',
    six_stages_bare: '여섯 단계',
    best_runs: '최고 주행',
    no_run: '아직 완주한 기록이 없습니다',
    furthest: '가장 멀리 간 단계: ',
    of_six: ' / 6',
    start: '시작',
    sound: '소리: ',
    yes: '켜기',
    no: '끄기',

    rival: '넘어야 할 주자',
    favourite: '우승 후보',
    after_race: '경기가 끝난 뒤',
    crowned: '은하 간 타이틀',
    fastest_1: '가장 빠른 존재',
    fastest_2: '모든 은하에서',
    full_run_in: '전 구간 기록 ',
    announced: '공식 기록: ',
    stage_up: '단계 ',
    six_cleared: '여섯 단계 통과',
    skip_now: '다시 누르면 건너뜁니다',
    skip_twice: '두 번 누르면 건너뜁니다',

    reaction: '반응',
    react_top: '완벽한 반응',
    false_start: '너무 일찍 나갔습니다',
    wait_gun: '총성을 기다리세요',
    phase_drive: '가속',
    phase_trans: '전환',
    phase_max: '최고 속도',
    drive_hint: '리듬을 잡으세요',
    trans_2: '완벽한 전환',
    trans_1: '좋은 전환',
    trans_0: '전환 실패',
    start_line: '출발: 반응 {r}초   -   {g}',
    no_start: '출발 실패',

    stumble: '발이 엉켰습니다',
    to_beat: '목표: ',
    to_race: '상대는 ',
    ready: '제자리에',
    get_set: '준비',
    go: '출발',
    alternate: '두 버튼을 번갈아 누르세요',
    alternate_kb: '두 화살표를 번갈아 누르세요',
    you: '나',
    opponent: '상대',
    depart: '출발',
    arrivee: '결승선',

    stage_done: '단계 {n} 통과',
    first_in: '1위, 기록 ',
    total_of: '초   -   합계 ',
    place: '{o}위',
    dnf: '기권',
    unfinished: '미완주',
    race_again: '한 번 더?',
    next_stage: '단계 {n}',
    home: '홈',
    replay: '다시 하기',
    run_done: '주행 완료',
    six_in: '여섯 단계 통과 기록 ',
    stage_low: '단계 ',

    new_record: '개인 신기록',
    top3: 'TOP 3',
    top10: 'TOP 10',
    best_run: '최고 주행',
    top3_runs: '주행 TOP 3',
    top10_runs: '주행 TOP 10',

    top500: 'TOP 500 - 역대',
    your_name: '이름',
    save_score: '내 기록 저장',
    saving_score: '전송 중...',
    score_saved: '세계 TOP 500에서 {r}위',
    score_save_fail: '전송 실패, 나중에 다시 시도하세요',
    score_name_taken: '이 이름은 다른 기기의 것입니다',
    score_taken_help: '다른 이름을 고르거나, 내 경기에서 복구 코드로 이 기기를 이름에 연결하세요',
    view_top500: 'TOP 500 보기',
    top500_court: 'TOP 500',
    close: '닫기',
    loading_ranks: '순위를 불러오는 중...',
    empty_top500: '아직 등록된 기록이 없습니다',
    your_rank: '내 순위: {r}',
    outside_top500: 'TOP 500 밖',
    edit_name: '이름 변경',
    best_split_short: '최고 단계:',
    top500_sub: '단일 경기 최고 기록',
    cat_race: '종목별',
    cat_run: '전 구간',
    cat_mine: '내 경기',
    cat_mine_sub: '지금까지 뛴 모든 경기',
    mine_empty: '이 종목에는 아직 경기가 없습니다',
    mine_count: '{n}경기 — 최고: {s}초',
    mine_note: 'TOP 500은 종목별 최고 기록만 남깁니다. 이 기록은 전부를 남깁니다. 다른 기기에서 찾으려면 이름을 확보하세요.',

    duel_title: '대결 순위',
    duel_sub: '보낸 도전과 받은 도전',
    duel_open: '대결 순위 보기',
    duel_rules_init: '도전 전송',
    duel_rules_recv: '도전 응답',
    duel_rules_line: '승 {v}   ·   패 {d}   ·   무 {n}',
    duel_rules_all: '보낸 것이든 받은 것이든 모든 대결이 반영됩니다',
    duel_rules_why: '도전을 보내는 쪽이 자기 기록을 먼저 보여주게 됩니다',
    duel_counts: '{l}건 전송 · {r}건 응답',
    duel_sur: '대결 종목',

    name_set: '이름을 정하세요',
    name_title: '내 이름',
    name_why: 'TOP 500과 도전, 대결에 표시되는 이름입니다',
    name_save: '저장',
    name_saved: '저장했습니다',
    name_taken: '이미 사용 중인 이름입니다',
    name_code: '내 복구 코드',
    pays_title: '국적',
    pays_opt: '한 번만',
    pays_aucun: '나라를 고르세요',
    pays_why: '전국선수권에 나가려면 필요하며, 이후에는 바꿀 수 없습니다',
    pays_vu: '{pays}에서 접속한 것으로 보입니다 — 선택은 본인의 몫입니다',
    pays_save: '선택',
    pays_confirm: '{pays} 소속으로 뛰시겠습니까?\n\n최종 결정입니다. 어느 전국선수권에 들어갈지 정해지며, 바꿀 수 없습니다.',
    pays_fige: '확정',
    pays_on: '이 나라 소속으로 뜁니다 — 선수권에서 이름 옆에 국기가 붙습니다',
    pays_deja: '국적이 이미 정해졌으며 바꿀 수 없습니다',
    pays_first: '이름을 먼저 저장하세요',
    pays_bad: '올바르지 않은 나라',
    insta_title: '내 인스타그램',
    insta_ph: '아이디, @ 없이',
    insta_why: 'TOP 500과 도전에서 프로필을 열 수 있게 됩니다',
    insta_note: '본인이 밝힌 정보이며 확인되지 않았습니다 — 인스타그램은 개인 계정의 실제 로그인을 더는 허용하지 않습니다',
    insta_link: '내 계정 연결',
    insta_linked: '계정 연결됨',
    insta_unlink: '연결 해제',
    insta_on: 'TOP 500에 프로필이 표시됩니다 — 눌러서 열 수 있습니다',
    insta_gone: '연결을 해제했습니다. 프로필은 어디에도 표시되지 않습니다',
    insta_bad: '올바르지 않은 아이디',
    insta_first: '이름을 먼저 저장하세요',
    insta_notyours: '이 기기에서 이 이름은 본인의 것이 아닙니다',
    insta_visit: '{n}의 인스타그램 프로필 보기',
    name_code_why: '적어 두세요. 다른 휴대폰에서 이름과 기록을 되찾아 줍니다',

    tour_open: '둘러보기',
    tour_1_t: '번갈아',
    tour_1_s: '왼쪽, 오른쪽, 왼쪽. 경기는 그게 전부입니다.',
    tour_2_t: '커리어',
    tour_2_s: '여섯 단계, 학교 운동장부터 은하 간 결승까지',
    tour_3_t: 'TOP 500',
    tour_3_s: '내 기록과 온 세계',
    tour_4_t: '고스트',
    tour_4_s: '내 경기를 친구에게 보내면, 친구가 나와 겨룹니다',
    tour_5_t: '실시간',
    tour_5_s: '같은 총성, 각자의 휴대폰에서',
    tour_play: '그냥 하게 해줘',

    os_tuto_open: '이 모드는 무엇을 위한 것인가',
    os_tuto_1_t: '종목을 고르세요',
    os_tuto_2_t: '기회는 단 한 번',
    os_tuto_3_t: '기록이 반영됩니다',
    os_tuto_1_s: '하나, 둘, 아니면 셋 모두',
    os_tuto_2_s: '재도전 없음, 탈락 없음',
    os_tuto_3_s: 'TOP 500, 그리고 친구가 받아줄 수 있습니다',
    os_tuto_go: 'ONE SHOT 시작',

    tuto_ask_t: '첫 경기',
    tuto_ask_s: '조작은 삼십 초면 익힐 수 있습니다',
    tuto_ask_yes: '조작 익히기',
    tuto_ask_no: '그냥 뛰게 해줘',
    tuto_watch: '보기',
    tuto_your_turn: '내 차례',
    tuto_1_t: '번갈아',
    tuto_2_t: '총성에 맞춰',
    tuto_3_t: '넓게, 그다음 짧게',
    tuto_v_early: '너무 이릅니다',
    tuto_v_late: '너무 늦습니다',
    tuto_v_perfect: '완벽',
    tuto_v_good: '좋음',
    tuto_v_slow: '속도가 부족합니다',
    tuto_v_flat: '리듬이 평평합니다',
    tuto_replay_demo: '다시 보기',
    tuto_again: '다시',
    tuto_next: '다음',
    tuto_done_t: '이제 뛸 차례',
    tuto_start: '시작',
    tuto_replay: '다시 보기',
    tuto_skip: '건너뛰기',
    tuto_open: '조작 방법',

    live_title: '실시간 경기',
    live_desc: '같은 총성에 둘이 함께 출발합니다. 각자의 휴대폰에서 — 고스트 없이, 누가 이길지 아무도 모릅니다',
    live_create: '트랙 열기',
    live_join: '참가',
    live_or: '또는',
    live_room: '트랙 열림',
    live_waiting: '이 코드를 상대에게 보내세요 — 둘이 모이면 경기가 시작됩니다',
    live_ready: '준비 완료',
    live_notready: '아직',
    live_empty_seat: '레인 비어 있음 — 상대를 기다리는 중',
    live_go: '준비됐습니다',
    live_unready: '취소',
    live_leave: '트랙 나가기',
    live_none: '그 코드의 트랙이 없습니다',
    live_full: '그 트랙은 이미 찼습니다',
    live_gone: '상대가 트랙을 떠났습니다',
    live_closed: '연결이 끊겼습니다',
    live_invite: '트랙에서 기다리고 있습니다. 코드 {c} — {l}',

    relais_titre: '4 × 100 계주',
    relais_desc: '주자 넷, 배턴 하나. 팀은 곧 그 구성입니다. 같은 네 이름, 같은 팀.',
    relais_invitations: '초대를 받았습니다',
    relais_mes_equipes: '내 팀',
    relais_creer: '팀 꾸리기',
    relais_nom_equipe: '팀 이름',
    relais_coequipier: '동료 {n}',
    relais_inviter: '세 명 초대',
    relais_incomplet: '이름 하나와 동료 셋이 필요합니다',
    relais_attend: '대기 중',
    relais_ok: '합류',
    relais_refuse: '거절',
    relais_fixer_ordre: '주자 순서 정하기',
    relais_manque_reponses: '뛰기 전에 아직 답이 남아 있습니다',
    relais_manque_refus: '동료가 거절했습니다 — 이 팀은 뛸 수 없습니다',
    relais_prete: '팀 준비 완료',
    relais_classement: '팀 순위',
    relais_plein_titre: '팀은 둘까지',
    relais_plein: '이미 두 팀에서 뛰고 있습니다. 새 팀을 꾸리려면 더 이상 뛰지 않는 팀에서 나가세요.',
    relais_plein_invit: '이미 두 팀에서 뛰고 있습니다 — 이 초대를 받으려면 한 팀에서 나가세요.',
    relais_quitter: '나가기',
    relais_quitter_sur: '완전히 나갈까요?',
    relais_quitter_sub: '새 초대를 받아야만 돌아올 수 있습니다',
    relais_reste: '한 자리 남았습니다',
    relais_place: '2팀 중 1팀',
    relais_places: '2팀 중 {n}팀',
    relais_courir: '트랙으로',
    relais_mon_rang: '{n}번째 주자입니다',
    relais_premier: '스타팅 블록에서 선 자세로 출발합니다. 부정 출발은 팀 전체가 실격입니다.',
    relais_ta_marque: '구역 안의 내 마크',
    relais_zone_debut: '진입',
    relais_zone_fin: '이탈',
    relais_marque_conseil: '앞에 설수록 빠르게 나가지만, 배턴보다 먼저 구역을 벗어날 수 있습니다. 뒤에 설수록 확실히 받지만, 멈춘 상태에서 출발합니다.',
    relais_attend_equipe: '아직 {n}명이 부족합니다',
    relais_temoin_a: '배턴 위치',
    relais_spectateur: '다른 주자들이 달리고 있습니다',
    relais_porte: '보유',
    relais_attends_temoin: '기다리세요',
    relais_prends: '배턴을 받으세요',
    relais_donne: '배턴을 넘기세요',
    relais_arrivee: '계주 완료',
    relais_elimine: '팀 실격',
    relais_elimine_pourquoi: '{r}번째 주자: {c}',
    relais_passages: '세 번의 인계',
    relais_elimine_court: '실격',
    relais_fantome: '고스트',

    conf_titre: '다른 팀과 겨루기',
    conf_desc: '총성 하나, 결승 순서 하나. 코드를 열어 공유하거나, 받은 코드를 입력하세요.',
    conf_ouvrir: '맞대결 열기',
    conf_rejoindre: '참가',
    conf_code: '코드',
    conf_code_court: '코드가 너무 짧습니다',
    conf_partage: '이 코드를 다른 팀들과 공유하세요',
    conf_places: '트랙에 {n}팀',
    conf_engagees: '{m}팀 중 {n}팀',
    conf_attend_adversaire: '최소한 한 팀이 더 필요하거나, 고스트가 필요합니다',
    conf_classement: '결승 순서',
    conf_encore: '다른 팀들이 아직 달리고 있습니다',

    fantome_titre: '상위 열 개 주행에 도전',
    fantome_desc: '이미 뛴 기록입니다. 다시 재생될 뿐 실격되지도, 인계에서 밀리지도 않습니다. 여덟 명을 모으지 않고 최상위와 겨루는 유일한 방법입니다.',
    fantome_aucun: '아직 기록된 주행이 없습니다 — 계주를 처음 완주한 팀이 문을 엽니다.',
    fantome_choisis: '{m}개 중 {n}개 선택',
    fantome_defier: '도전하기',

    champ_directs: '상위 {n}명이 통과',
    champ_reveal: '가장 빠른 패자들',
    champ_reveal_desc: '한 경기도 이기지 못했습니다. 모든 경기의 기록에서 추려집니다.',
    champ_continue: '계속',
    champ_sacre: '{n}이(가) 우승 — 시상대 보기',
    champ_titre_duree: '타이틀은 석 달 동안',
    champ_rv_course: '다음 경기',
    champ_rv_reveal: '가장 빠른 패자 발표',
    champ_rv_sacre: '시상식',
    champ_quitter: '선수권 나가기',

    live_lanes: '레인',
    live_lanes_duel: '대결: 이긴 쪽이 점수를 얻고, 진 쪽이 일부를 내놓습니다',
    live_lanes_course: '경기: 결승 순서만 있고, 대결 순위 점수는 없습니다',
    live_won: '경기 승리',
    live_sur: '출발한 {n}명 중',
    live_ordre: '결승 순서',
    live_lost: '경기 패배',

    pres_title: '선수 소개',
    pres_lane: '레인',
    pres_you: '이게 나입니다',
    pres_mic_on: '마이크 켜짐',
    pres_mic_off: '마이크 거부됨',
    mic_winner: '승자의 한마디',

    review_title: '내 경기 영상',
    review_making: '녹화 중…',
    review_dl: '내려받기',
    review_left: '{t} 뒤 삭제',
    review_gone: '영상이 삭제되었습니다',
    review_kept: '내려받은 것은 휴대폰에 남습니다',
    review_none: '이 기기로는 경기를 녹화할 수 없습니다',
    live_tie: '동시 결승',
    live_vs: '실시간, 상대 {n}',
    live_gap: '{s}초 차',
    link_in_app: '게임이 설치되어 있나요?',
    link_in_app_sub: '홈 화면에서 열고 이 코드를 입력하세요 — 누르면 복사됩니다',

    duel_answered: '내 도전에 응답이 왔습니다',
    duel_more: '결과가 {n}건 더 있습니다',
    duel_mores: '결과가 {n}건 더 있습니다',
    duel_next: '다음',
    duel_ok: '확인',

    ghost_mode: '고스트 모드',
    ghost_ahead: '앞섬',
    ghost_behind: '뒤짐',
    ghost_level: '나란히',
    ghost_home: '고스트가 결승선을 통과했습니다',
    ghost_live: '고스트가 옆에서 달리고 있습니다',
    duel_must: '도전을 보내거나, 친구의 도전에 응하세요',
    duel_empty: '아직 대결한 적이 없습니다',
    duel_pts: '점',

    monde_sprinter_sous: '직선과 한 바퀴',
    monde_hurdlers_sous: '같은 레인에, 허들 열 개',
    monde_jumper_sous: '도움닫기를 만들고 땅을 떠나세요',
    monde_thrower_sous: '서클 하나, 기구 하나, 그리고 온몸',
    monde_bientot: '준비 중',
    monde_retour: 'SPRINTER로 돌아가기',

    disc_100: '100미터',
    disc_200: '200미터',
    disc_400: '400미터',
    disc_100h: '100미터 허들',
    disc_110h: '110미터 허들',
    disc_400h: '400미터 허들',
    disc_longueur: '멀리뛰기',
    disc_hauteur: '높이뛰기',
    disc_triple: '세단뛰기',
    disc_perche: '장대높이뛰기',
    disc_poids: '포환던지기',
    disc_marteau: '해머던지기',
    disc_disque: '원반던지기',
    disc_javelot: '창던지기',

    pique_0: '굳이 애쓸 필요도 없었어.',
    pique_1: '슬로모션으로 한 번 더 해줄까?',
    pique_2: '지루해질 시간까지 있었어.',
    pique_3: '결승선은 이쪽이야.',
    pique_4: '준비운동 상대해줘서 고마워.',
    pique_5: '뒤를 돌아봤는데 아무도 없더라.',
    pique_6: '뛴 거였어? 아무것도 지나가지 않던데.',
    pique_7: '그 기록은 간직해. 좋은 추억이 될 거야.',

    mot_titre: '{n}에게 한마디 남기기',
    mot_placeholder: '두 줄로 찔러 보세요',
    mot_vocal: '음성',
    mot_ecouter: '다시 듣기',
    mot_refaire: '다시 녹음',
    mot_envoyer: '보내기',
    mot_envoye: '{n}이(가) 돌아오면 읽게 됩니다',
    mot_micro_refuse: '마이크가 거부되었습니다 — 글로도 됩니다',
    mot_ecouter_sa_voix: '상대가 남긴 말 듣기',
    mot_ephemere: '이 녹음은 창을 닫으면 사라집니다',
    mot_illisible: '이 메시지는 이 기기에서 재생되지 않습니다',

    mod_signaler: '신고',
    mod_titre: '왜 신고하시나요?',
    mod_explique: '신고는 사람이 읽습니다. 차단은 즉시 적용됩니다.',
    mod_insulte: '모욕',
    mod_haine: '혐오, 인종차별',
    mod_sexuel: '성적인 내용',
    mod_menace: '협박',
    mod_autre: '기타',
    mod_envoye: '신고했습니다. 담당자가 읽습니다.',
    mod_deja: '이미 신고했습니다',
    mod_bloquer: '{n} 차단',
    mod_bloque: '{n}은(는) 더 이상 글을 보낼 수 없습니다.',
    mod_annuler: '취소',

    duel_revanche: '설욕하고 싶다',
    duel_revanche_sub: '같은 종목 — 이번엔 내가 기록을 세울 차례',
    duel_renvoyer: '{n}에게 코드 되돌려 보내기',
    duel_revanche_envoyee: '설욕 도전 전송',
    os_revanche_sans_cible: '{n}에게 알릴 수 없었습니다 — 코드를 직접 보내세요',
    duel_revanche_ratee_titre: '아직입니다',
    duel_revanche_ratee: '{n}에게 도전을 되돌리려면 {s}초 안쪽이 필요했습니다 — 아무것도 전송되지 않았습니다',

    rang_departemental: '시군',
    rang_regional: '지역',
    rang_national: '전국',
    rang_elite: '엘리트',
    rang_legende: '레전드',
    rang_court_departemental: '시군',
    rang_court_regional: '지역',
    rang_court_national: '전국',
    rang_court_elite: '엘리트 ',
    rang_court_legende: '레전드',
    duel_lp: 'LP',
    duel_monte_a11y: '{n}계단 상승',
    duel_descend_a11y: '{n}계단 하락',
    duel_lp_long: '리그 포인트',
    duel_promu: '{r}(으)로 승격',
    duel_relegue: '{r}(으)로 강등',
    duel_reste: '다음 디비전까지 {n}',
    duel_regle: '도전에 응하는 쪽이 보내는 쪽보다 많이 얻습니다. 기록은 이미 걸려 있고, 무엇을 넘어야 하는지 알기 때문입니다.',
    duel_record: '{v}승 · {d}패 · {n}무',
    duel_you: '나',
    duel_since: '마지막 방문 이후',
    duel_unranked: '아직 순위가 없습니다 — 대결을 한 번 치르세요',
    duel_won: '대결 승리',
    duel_lost: '대결 패배',
    duel_tie: '무승부',
    duel_final: '최종 결과 — 도전은 다시 치르지 않습니다',
    duel_delta: '{p}점',
    duel_deltas: '{p}점',

    false_out: '부정 출발',
    false_out_sub: '실격 — 대결은 패배입니다',
    false_out_seul: '실격 — 이 경기는 여기서 끝납니다',
    false_out_rule: '경기는 한 번뿐, 두 번째 기회는 없습니다',
    false_out_libre: '다시 뛸 수 있습니다',
    false_out_gun: '총성보다 먼저 나갔습니다',
    duel_await: '대결 결과…',
    duel_vs: '상대 {n}',
    duel_seen: '이미 판가름 난 대결입니다',
    duel_see: '순위 보기',

    os_once: '도전을 보내는 순간 기록은 확정됩니다',
    os_rejouer: '다시 뛰기',
    os_rejouer_sub: '지금 한 번 더 — 이 기록은 그대로 남습니다',
    os_defier: '누군가에게 도전',
    os_defier_sub: '순위를 열고 상대를 고르세요 — 다른 사람도, 같은 사람도',
    relance_gagne_0: '다음 상대를 잡으러 가자',
    relance_gagne_0_sub: '그쪽은 정리됐다. 다음.',
    relance_gagne_1: '다음 분, 들어오세요',
    relance_gagne_1_sub: '순위는 사람으로 가득하고, 지금 컨디션이 좋다.',
    relance_gagne_2: '또 누가 있지?',
    relance_gagne_2_sub: '순위에 물어보자. 누군가는 답한다.',
    relance_perdu_0: '더 만만한 상대를 고르자',
    relance_perdu_0_sub: '한 디비전 내려가자 — 아무도 알 필요 없다',
    relance_perdu_1: '더 느린 사람을 찾자',
    relance_perdu_1_sub: '있다. 통계적으로, 반드시 있다.',
    relance_perdu_2: '초보자는 아직 남아 있다',
    relance_perdu_2_sub: '아무것도 모르고 있다. 지금이 기회다.',
    os_defi_sans_cible: '{n}은(는) 이 종목 TOP 500에 없습니다 — 코드를 직접 보내세요',
    os_verrou_direct: '실시간 경기: 상대가 같은 순간에 뛰었습니다 — 그 결과가 유효합니다',
    os_verrou_recu: '이 기록은 이미 상대에게 갔습니다 — 되돌릴 수 없습니다',
    os_verrou_envoye: '도전을 보냈습니다 — 상대가 넘어야 할 기록입니다',
    os_verrou_faux: '대결에서의 부정 출발: 경기는 패배입니다. 새 도전을 보내 처음부터 시작하세요.',
    cut_skip: '건너뛰기',

    id_title: '내 이름',
    id_code_title: '복구 코드',
    id_code_note: '적어 두세요. 다른 기기를 이 이름에 연결하고, 남이 가져가지 못하게 막아 줍니다',
    id_show: '내 코드 보기',
    id_reserve: '확보',
    id_taken: '이미 사용 중인 이름입니다',
    id_taken_help: '본인 것이라면 복구 코드를 입력하세요',
    id_link: '연결',
    id_linked: '기기를 {n}에 연결했습니다',
    id_bad_code: '코드가 틀렸습니다',
    id_unknown: '알 수 없는 이름',
    id_link_title: '다른 기기인가요?',
    id_link_help: '이름과 코드를 입력하면 기록과 이력을 여기서 되찾습니다',

    install_title: '게임 설치',
    install_why: '전체 화면, 브라우저 표시줄 없음, 오프라인에서도 플레이',
    install_do: '설치',
    install_later: '나중에',
    install_ios_1: '누르기:',
    install_ios_2: '공유',
    install_ios_3: 'Safari 아래쪽, 그다음',
    install_ios_4: '홈 화면에 추가',

    mode_career_s: '커리어',
    mode_oneshot_s: 'one shot',
    cat_race_sub: '단일 경기 최고 기록',
    cat_run_sub: '여섯 단계 합계',
    empty_cat_run: '아직 전 구간 기록이 없습니다',
    will_enter: '{s}초: TOP 500에서 {r}위, 이름을 남기세요',

    wr_title: '세계 기록',
    wr_sub: '{d}m 세계 최고 기록',
    wr_old: '이전 기록: {s}초',
    wr_first: '기록판에 오르는 첫 기록',
    wr_gain: '{s}초 단축',
    wr_save: '내 이름 새기기',
    wr_saving: '저장 중...',
    wr_done: '{n}은(는) TOP 500에서 {r}위',
    wr_fail: '전송 실패, 다시 시도하세요',
    wr_see: 'TOP 500 보기',
    wr_later: '나중에',
    os_top_checking: '순위를 확인하는 중...',
    os_top_none: 'TOP 500에 드는 기록이 없습니다',
    os_top_intro: '{n}개의 기록이 TOP 500에 듭니다',
    os_top_intro_n: '{n}개의 기록이 TOP 500에 듭니다',
    os_top_line: '{d}m — {s}초 — {r}',
    os_top_saved: '{n} 이름으로 기록을 저장했습니다',
    top500_count: '500개 중 {n}개가 순위에 올랐습니다',
    os_top_better: '{d}m 기록은 {s}초 그대로입니다',
    os_kept_title: '기록이 지켜졌습니다',
    os_kept_line: '{d}m: 이미 {s}초를 보유 중입니다 (TOP 500에서 {r}위)',
    os_kept_now: '이 {s}초로는 넘지 못합니다 — 순위는 최고 기록만 남깁니다',

    pause_title: '경기 일시정지',
    pause_note: '지금 나가면 진행 중인 기록을 포기하게 됩니다',
    resume: '이어하기',

    challenge_them: '도전',
    target_run: '{d}m를 뛰세요: 도전은 {n}에게 갑니다',
    target_sent: '{n}에게 도전을 보냈습니다',
    inbox_one: '도전이 도착했습니다',
    inbox_many: '도전이 {n}건 도착했습니다',
    inbox_from: '{n}이(가) {d}m로 도전해 왔습니다',
    inbox_accept: '수락',
    inbox_later: '나중에',
    run_total_short: '전 구간:',
    run_total_tiny: '주행',
    best_split_tiny: '경기',
    score_saved_race: '{s}초로 세계 TOP 500에서 {r}위',
    mode_career: '커리어',
    mode_oneshot: 'ONE SHOT',
    mode_versus: '도전',
    career_desc: '여섯 단계를 연달아, 기록은 하나',
    oneshot_desc: '종목을 고르고, 기회는 한 번',
    versus_desc: '다른 선수의 고스트와 겨루기',
    pick_events: '종목',
    pick_level: '레벨',
    pick_none: '종목을 하나 이상 고르세요',
    launch_oneshot: '출발',
    event_n: '종목 {n} / {t}',
    next_event: '다음 종목',
    oneshot_done: 'ONE SHOT 완료',
    total_in: '합계: ',
    challenge_code: '도전 코드',
    challenge_enter: '받은 코드를 입력하세요',
    challenge_load: '불러오기',
    challenge_loading: '도전을 불러오는 중...',
    challenge_bad: '코드를 찾을 수 없습니다',
    challenge_net: '연결에 실패했습니다. 다시 시도하세요',
    challenge_from: '{n}의 도전',
    challenge_beat: '목표: {s}초',
    challenge_aveugle: '상대의 기록은 뛰면서 알게 됩니다',
    challenge_accept: '도전 수락',
    challenge_make: '친구에게 도전',
    challenge_making: '도전을 만드는 중...',
    challenge_share: '이 코드를 보내면 친구가 내 고스트와 겨룹니다',
    challenge_copy: '링크 복사',
    challenge_copied: '링크를 복사했습니다',
    challenge_copy_code: '코드 복사',
    share_send: '도전 보내기',
    share_whatsapp: 'WhatsApp',
    share_sms: 'SMS',
    share_other: 'Snapchat, Instagram…',
    share_other_hint: 'Snapchat과 Instagram은 공유 메뉴에서 열립니다.',
    affiche_share: '내 주행 공유',
    affiche_making: '이미지를 만드는 중…',
    affiche_saved: '이미지를 저장했습니다',
    affiche_failed: '이미지를 만들지 못했습니다',
    affiche_hint: '주행 이미지입니다. 인스타그램이나 틱톡에 쓰세요',
    code_copied: '코드를 복사했습니다',
    challenge_rematch: '도전 되돌려주기',
    challenge_rematch_sub: '이겼습니다 — 방금 한 주행으로 되받아 도전하세요',
    challenge_won: '도전 승리',
    challenge_lost: '도전 패배',
    challenge_gap: '차이: {s}초',
    ghost_label: '고스트',
    you_label: '나',
    dnf_short: 'DNF',
    composing: '사운드트랙을 작곡하는 중...',

    sound_off: '소리 꺼짐  (S)',
    press_enter: 'ENTER 누르기',
    skip_now_kb: '다시 ENTER를 누르면 건너뜁니다',
    skip_twice_kb: 'ENTER를 두 번 누르면 건너뜁니다',
    stage_dash: '단계 {n}   -   {s}',
    furthest_kb: '가장 멀리 간 단계: {b} 중 {a}',
    enter_start: 'ENTER: 시작   -   S: 소리   -   L: 언어   -   ESC: 종료',
    how_to_play: '조작 방법',
    help_1: '같은 키를 반복하지 말고  <-  와',
    help_2: '->  를 번갈아 누르세요.',
    help_3: '일정한 리듬이 속도를 만듭니다.',
    help_4: '반복하면 발이 엉키지만,',
    help_5: '언제든 다시 속도를 낼 수 있습니다.',
    best_stage: '이 단계의 최고 기록',
    no_time: '아직 등록된 기록이 없습니다',
    arrows_pick: '화살표로 선택   -   ENTER로 확정   -   ',
    yn_short: 'Y / N 단축키',
    you_beat: '{w}을(를) 이기고 여섯 단계를 모두 통과했습니다.',
    the_zeze: 'ZEZE 일족',
    your_times: '내 기록',
    total: '합계',
    enter_replay: 'ENTER: 다시 뛰기      M: 홈',
    stumble_kb: '발이 엉켰습니다!',
    go_kb: '출발!',
    to_beat_line: '목표:  {n}   -   {s}초',
    best_times_of: '최고 기록  -  {s}',
    enter_next: 'ENTER   ->   단계 {n}: {s}',
    full_run_pc: '전 구간 {s}초',
    announced_pc: '공식 기록: {s}초',
    quit: 'ESC: 종료'
  },

  CUTS: {
    intro: [
      [ // 단계 1
        ['{n}은(는) 삼 년째 운동장의 모든 경기를 이기고 있다.',
         '비결은 간단하다. 아무도 감히 추월하지 않는다. 공이 그의 것이니까.',
         '원칙이라며 학교 신발을 신고 몸을 푼다.',
         '어머니는 울타리 너머에서 찍는다. 주로 울타리가 찍힌다.'],
        ['{n}은(는) 학교 기록 보유자다. 체육관 벽에 매직으로 적혀 있다.',
         '기록을 잰 건 같은 반 친구였고, 바늘 달린 손목시계였다.',
         '체육 선생이 한 번 고개를 끄덕였다. 그걸로 공식이 되었다.',
         '이제는 그 기록을 피해 벽을 칠한다.'],
        ['{n}은(는) 4레인을 요청했다. 4레인을 받았다.',
         '늘 하던 동작을 한다. 무릎 들기, 뒤꿈치 차기, 깊은 한숨.',
         '번호표는 집에서 인쇄했고, 조금 삐뚤다.',
         '번호는 1번. 혼자서, 직접 뽑았다.']
      ],
      [ // 단계 2
        ['{n}은(는) 네 시간째 몸을 풀고 있다.',
         '체육복 등판에는 이름이 대문자로 수놓여 있다.',
         '의식이 있다. 세 걸음 물러나고, 한 번 숨을 쉬고, 윙크 한 번.',
         '그 윙크는 딱히 누구를 향한 것도 아니다.'],
        ['{n}은(는) 스파이크 두 켤레와 아이스박스를 들고 온다.',
         '아이스박스에는 바나나 하나와 넘치는 각오가 들어 있다.',
         '스타팅 블록을 밀리미터까지 맞추고, 다시 맞춘다.',
         '그리고 세 번째. 출발 심판은 기다린다, 정중하게.'],
        ['{n}은(는) 작년 지역 대회에서 2위였다.',
         '맞바람이 훔쳐 간 승리였다고 그는 말한다.',
         '공식 계측은 무풍이었다. 그는 그 계측에 이의를 제기한다.',
         '자기 풍속계를 가져왔다. 쓸 줄은 모른다.']
      ],
      [ // 단계 3
        ['{n}은(는) 지역 방송에 나온 적이 있다.',
         '삼십팔 초짜리 화면. 육백 번을 돌려 봤다.',
         '시간을 아끼려고 경기 전에 사인을 해 준다.',
         '달리 종이가 없어 영수증 뒷면에.'],
        ['{n}에게는 아무도 쓰지 않는 별명이 있다. 북쪽의 화살.',
         '인터뷰마다 본인이 직접 끼워 넣는다.',
         '장내 아나운서가 방금 실수로 본명을 불렀다.',
         '장내 방송으로 정정을 요구해 두었다. 정정은 나중에 온다.'],
        ['{n}은(는) 자기 최고 기록을 팔뚝에 새겼다.',
         '선수 소개 때 슬로모션처럼 천천히 보여 준다.',
         '이 결승의 네 명은 이미 그 숫자를 넘어섰다.',
         '아쉽게도 문신은 스스로 갱신되지 않는다.']
      ],
      [ // 단계 4
        ['{n}에게는 후원사와 에이전트와 물리치료사가 있다.',
         '셋 다 그가 무적이라고 말한다. 셋 다 그가 돈을 준다.',
         '에이전트는 우승 기자회견장까지 벌써 예약해 두었다.',
         '케이터링도 주문했다. 카나페가 나온다.'],
        ['{n}은(는) 열한 달째 세계 랭킹 1위다.',
         '생방송으로 그 소식을 들었고, 그 뒤로 한 번도 뒤를 보지 않았다.',
         '말 그대로다. 물리치료사가 단단히 말렸기 때문이다.',
         '이제는 상체째로 돌린다. 느리지만, 보기에는 근사하다.'],
        ['아나운서가 {n}을(를) 호명한다. 경기장이 일제히 일어선다.',
         '관중석을 가리키고, 하늘을 가리키고, 카메라를 가리킨다.',
         '카메라는 다른 선수를 잡고 있었다. 그는 처음부터 다시 한다.',
         '중계 감독이 물러선다. 이 동작은 십일 초 동안 이어질 것이다.']
      ],
      [ // 단계 5
        ['{n}은(는) 여덟 달째 세리머니를 연습하고 있다.',
         '상표 등록까지 마쳤다. 이제 경기를 이기는 일만 남았다.',
         '마흔 명의 합창단이 그의 신호를 기다린다.',
         '노래도 외워 두었다. 가사에 그의 이름이 길게 나온다.'],
        ['{n}은(는) 나라의 색을 입고, 그 점을 진심으로 중요하게 여긴다.',
         '국기는 스파이크에도, 번호표에도, 수건에도 있다.',
         '수건은 달리지 않지만, 화요일부터 준비되어 있다.',
         '스태프 한 명이 개회식 때부터 어디든 들고 다닌다.'],
        ['{n}은(는) 블록에서 상대를 보지 않겠다고 맹세했었다.',
         '그래서 앞만 똑바로 본다, 남다른 집중력으로.',
         '조금 지나치게 앞을. 선수 소개 때는 벽을 보고 있었다.',
         '그 벽은 이 결승에 오르지 못했다.']
      ],
      [ // 단계 6
        ['{n}은(는) 중력이 선택 사항인 우주에서 왔다.',
         '경기를 시작하겠다고 마음먹기 전에 이미 끝내 버린다.',
         '그의 기록은 열한 개 차원에서 동시에 유효하다.',
         '열두 번째에서는 넘어졌지만, 아무도 그 얘기는 꺼내지 않는다.'],
        ['{n}은(는) 이 백 미터를 열한 개의 평행우주에서 달렸다.',
         '열한 곳 모두 이겼다. 열두 번째는 끝내 공인되지 않았다.',
         '그곳의 결승 심판은 성운이었고, 결승선 판정이 미덥지 못했다.',
         '그 성운은 세 시즌 출전 정지를 받았다.'],
        ['ZEZE 일가가 일곱 레인을 모두 차지한다. 규정에 맞는 일이다.',
         '자기네 출발 심판과 자기네 바람과 자기네 결승선을 가져왔다.',
         '규정은 ZEZE가 썼고 ZEZE가 검토했다.',
         '한 문장짜리다. ZEZE가 이긴다.']
      ]
    ],

    defeat: [
      [ // 단계 1
        ['{n}은(는) 급식 당번에게 결과에 이의를 제기한다.',
         '당번은 샌드위치를 먹고 있다. 결과는 그대로다.',
         '다음으로 반장에게 판정을 청한다.',
         '반장은 꼴찌였다. 이 상황을 아주 즐기고 있다.'],
        ['{n}은(는) 운동장 바닥이 고르지 않다고 설명한다.',
         '천구백육십 년부터 모두에게 고르지 않았다.',
         '이어서 풀린 신발끈 얘기를 꺼낸다. 그의 신발은 찍찍이다.',
         '선생이 벽에 네 기록을 적는다. 그의 기록 바로 위에.'],
        ['{n}은(는) 사실 달린 게 아니었다고 선언한다.',
         '몸을 풀던 중이었고, 진짜 경기는 다음이었다고.',
         '아무도 그 얘기를 듣지 못했는데, 그게 많은 걸 설명해 준다.',
         '종이 울린다. 다음 경기는 영영 오지 않는다.']
      ],
      [ // 단계 2
        ['{n}은(는) 자기 시계가 아예 작동하지 않았다고 설명한다.',
         '그러므로 기술적으로 이 경기는 존재하지 않았다.',
         '지금 당장 다시 하자고 제안한다, 진지한 사람들끼리.',
         '그러다 기차가 있다는 걸 떠올린다. 기차는 없다.'],
        ['{n}은(는) 결승선 사진을 보여 달라고 한다.',
         '사진이 제시된다. 분명히 뒤에 있고, 아주 선명하다.',
         '같은 사진을 다른 각도로 달라고 한다.',
         '그 각도에서도 여전히 뒤에 있다. 다만 조금 흐릴 뿐이다.'],
        ['{n}은(는) 말없이 스파이크 두 켤레를 챙긴다.',
         '더 전술적인 종목인 400으로 옮기겠다고 선언한다.',
         '다음은 800. 그다음은 마라톤, 어차피 모든 게 끝나는 곳.',
         '아이스박스를 들고 떠난다. 바나나는 손도 대지 않았다.']
      ],
      [ // 단계 3
        ['{n}은(는) 생방송에서 은퇴를 발표한다.',
         '그러고는 마음을 바꾼다. 월요일부터 다시 훈련이라고.',
         '하필 그 월요일이 유난히 바쁘다고 덧붙인다.',
         '알고 보니 그다음 월요일도 그렇다.'],
        ['{n}은(는) 우승자에 대한 도핑 검사를 요구한다.',
         '공정을 위해 자신에 대한 검사도 요구한다.',
         '둘 다 음성이 나온다. 그는 그것이 수상하다고 여긴다.',
         '세 번째 검사를 요구한다. 계측 장비를 대상으로.'],
        ['{n}은(는) 기자들에게 팔뚝을 보여 준다.',
         '문신으로 새긴 기록은 그대로다. 그나마 다행이다.',
         '육 주짜리 고지대 훈련을 발표한다.',
         '그가 고른 산은 높이가 이백 미터다.']
      ],
      [ // 단계 4
        ['{n}은(는) 풍속 재계측을 요구한다.',
         '바람이 호출된다. 바람은 나타나지 않는다.',
         '우승 기자회견은 그대로 열린다. 이제 취소할 수 없기 때문이다.',
         '카나페는 훌륭하다. 그것만으로도 어디인가.'],
        ['{n}은(는) 이십 초 동안 대형 화면을 응시한다.',
         '순위는 바뀌지 않는다. 화면도 바뀌지 않는다.',
         '생중계냐고 묻는다. 그렇다는 답이 돌아온다.',
         '그러면 지연 중계는 없느냐고 묻는다. 없다.'],
        ['믹스트존에서 {n}은(는) 성장과 과정에 대해 말한다.',
         '이 분 동안 사이클이라는 단어를 열한 번 쓴다.',
         '한 기자가 기록을 묻는다. 답한다. 기록은 앞으로 온다고.',
         '그의 기록은 뒤쪽 전광판에 이미 떠 있다, 아주 크게.']
      ],
      [ // 단계 5
        ['{n}은(는) 그래도 세리머니를 해 버린다.',
         '관중은 박수를 친다, 예의로.',
         '소식을 못 들은 합창단이 노래를 시작해 버린다.',
         '마흔 명이 그의 이름을 부른다. 그는 침묵이 나았을 것이다.'],
        ['{n}은(는) 계획대로 국기를 들고 트랙을 한 바퀴 돈다.',
         '우승자도 같은 한 바퀴를 돈다, 반대 방향으로.',
         '두 번 마주친다. 두 번째가 더 아프다.',
         '수건은 이런 전개를 예상하지 못했다.'],
        ['{n}은(는) 시상대 두 번째 칸에 오른다.',
         '아주 긴 악수로 우승자를 축하한다.',
         '공식 사진을 세 번 다시 찍을 만큼 긴 악수다.',
         '세 번째에서 그는 웃는다. 그 대가가 눈에 보인다.']
      ],
      [ // 단계 6
        ['{n}은(는) 자기 은하의 궤도를 다시 계산한다.',
         '그 궤도가 하필 2위 자리를 정확히 지나가고 있었다.',
         '시간 이상을 들먹이고, 이어서 신발 문제를 든다.',
         '두 설명은 서로 모순된다. 그는 둘 다 남겨 둔다.'],
        ['{n}은(는) 다른 열한 우주의 순위를 요구한다.',
         '열한 곳 모두에서 그 역시 방금 졌다. 동시에.',
         '열두 번째를 열어 보자고 제안한다, 그저 확인차.',
         '열두 번째는 이미 찼다. 거기서도 1위는 너였다.'],
        ['나머지 여섯 ZEZE가 아주 조용히 {n}을(를) 바라본다.',
         '아무도 한마디 하지 않는다. 침묵은 사 광년 동안 이어진다.',
         '마침내 {n}이(가) 말을 꺼낸다. 오늘은 노면이 달랐다고.',
         '트랙이 깔린 뒤로 노면은 한 번도 바뀐 적이 없다.']
      ]
    ],

    taunt: [
      [ // 단계 1
        ['{n}은(는) 말없이 점수판을 가리킨다.',
         '거기에는 이미 사인까지 해 두었다. 지워지지 않는 펜으로.',
         '자기 샌드위치를 건넨다. 「가는 길에 먹어」라며.',
         '샌드위치를 달라고 한 적은 없다.'],
        ['{n}은(는) 우승 한 바퀴를 돈다. 자리가 없어 삼 미터짜리로.',
         '상상 속 관중을 향해 한참 손을 흔든다.',
         '설욕전을 제안한다. 그러고는 손목시계를 본다.',
         '손목시계는 없다. 그 동작만으로 충분했다.'],
        ['{n}은(는) 느긋하게 짐을 챙긴다, 휘파람을 불면서.',
         '그 가락은 네 이름이고, 개선 행진곡 박자에 얹혀 있다.',
         '어깨를 툭 치며 「다음에는」이라고 말한다.',
         '한순간도 믿지 않는다. 그리고 그게 얼굴에 드러난다.']
      ],
      [ // 단계 2
        ['{n}은(는) 시계를 보고, 그다음 너를 본다, 의미심장하게.',
         '아무 말도 하지 않는다. 그 침묵이 말보다 잔인하다.',
         '사인을 나눠 준다. 첫 장은 네 몫이다.',
         '그것도 달라고 한 적은 없다.'],
        ['{n}은(는) 코치에게 전화한다. 「일찍 끝났습니다」라고.',
         '코치가 왜냐고 묻는다. 「예의상요」라고 답한다.',
         '메달을 들어 보게 해 준다. 딱 한순간만.',
         '그 한순간이 십 분 동안 이어진다. 그는 사진을 찍는다.'],
        ['{n}은(는) 스파이크를 네 이름이 적힌 케이스에 넣는다.',
         '우리끼리 아는 농담이다. 관중은 따라오지 못한다.',
         '자기 물병의 물을 권한다. 물병은 비어 있다.',
         '중요한 건 물이 아니라 마음이라고 그는 말한다.']
      ],
      [ // 단계 3
        ['{n}은(는) 카메라에 손을 흔든다. 그다음 너에게도 흔든다.',
         '두 번째 손짓은 눈에 띄게 덜 다정하다.',
         '기자들과 네 경기를 세세하게 논한다.',
         '그가 제일 좋아하는 대목은 네가 뒤를 돌아본 순간이다.'],
        ['{n}은(는) 마이크를 달라고 한다. 상식과 달리, 받는다.',
         '가족과 소속팀, 그리고 너에게 감사한다. 그 순서로.',
         '「그가 없었으면 이 맛이 안 났을 겁니다」라고 말한다.',
         '무슨 뜻인지는 설명하지 않는다. 설명할 필요도 없다.'],
        ['{n}은(는) 네 경기를 같이 차분히 돌아보자고 제안한다.',
         '복기는 한 단어로 끝난다. 아주 천천히 발음한다.',
         '확실히 하려는 듯, 연달아 두 번 악수한다.',
         '첫 번째는 충분히 설득력 있어 보이지 않았던 모양이다.']
      ],
      [ // 단계 4
        ['{n}이(가) 인터뷰를 한다. 주제는 이상하게도 너다.',
         '삼 분 동안. 자기 경기 얘기는 한마디도 없다.',
         '많이 배웠다는 말로 마무리한다. 네 패배에서.',
         '기자는 한 마디 한 마디 받아 적는다, 불편한 얼굴로.'],
        ['{n}은(는) 에이전트에게 전적에 한 줄 더하라고 신호한다.',
         '그 줄은 간단히 이렇게 적힌다. 너를 상대로, 또 한 번.',
         '우승 기자회견에 너를 초대한다.',
         '의자 하나가 너를 기다린다. 맨 뒤에, 마이크도 없이.'],
        ['{n}은(는) 휴대폰으로 순위를 보여 준다, 확대해 가면서.',
         '한참을 확대한다. 네 줄은 그의 줄보다 한참 아래에 있다.',
         '「메일로 보내 줄까」라고 친절하게 제안한다.',
         '주소를 준 적이 없다. 그는 이미 알고 있다.']
      ],
      [ // 단계 5
        ['{n}은(는) 관중석에 손을 흔들고, 그다음 엄숙하게 너를 향한다.',
         '그 뒤에 하는 동작은 어떤 규정집에도 없다.',
         '한 기자가 패한 상대에게 한마디를 청한다.',
         '그는 일곱 마디를 한다. 기사에 실리는 건 하나도 없다.'],
        ['{n}은(는) 시상대에 올랐다가, 한 칸 내려온다.',
         '메달을 가까이에서 보라고 너를 부른다.',
         '아주 가까이에서. 금이다. 그 점을 강조한다.',
         '국가가 시작된다. 너를 보면서 크게 부른다.'],
        ['{n}은(는) 우승을 가족과 후원사와 너에게 바친다.',
         '「이렇게 자극이 되는 상대가 없었다면」이라고, 진심으로 말한다.',
         '자극이라는 말이 정교하게 포장된 모욕처럼 떨어진다.',
         '관중은 박수를 친다. 네가 왜 붉어지는지도 모른 채.']
      ],
      [ // 단계 6
        ['{n}이(가) 나머지 여섯 ZEZE를 본다. 모두 한꺼번에 고개를 끄덕인다.',
         '판정은 만장일치이고, 소리 하나 없이 내려진다.',
         '기념 명판이 새겨진다, 사어(死語)로.',
         '요지는 이렇다. 그는 애썼다. 그것만으로도 어디인가.'],
        ['{n}은(는) 열한 개의 다른 차원에서 네 순위를 다시 계산한다.',
         '어느 차원에서나 결과는 초 단위까지 똑같다.',
         '네가 이겼을 우주의 지도를 준다.',
         '그 우주는 아직 존재하지 않는다고 덧붙인다.'],
        ['{n}이(가) 하늘로 손을 뻗는다. 은하 하나가 순순히 불을 밝힌다.',
         '한순간 그것은 그의 미소 모양을 그린다.',
         '일곱 ZEZE가 상의하고, 그다음 너를 향해 돌아선다.',
         '뒤따르는 침묵은 사 광년 동안 이어진다. 정중하게.']
      ]
    ],

    champion: [
      ['일곱 ZEZE가 오래도록 상의한다.',
       '누구도 받아들일 만한 변명을 찾지 못한다. 처음 있는 일이다.',
       '순위가 백사십억 개 항성계에서 갱신된다.',
       '결승선에 명판이 놓인다.',
       '네 이름은 철자가 틀렸지만, 어쨌든 거기에 있다.'],
      ['아나운서가 단어를 찾는다. 어느 것도 충분히 크지 않다.',
       '결국 기록만 읽는다, 확실히 하려고 두 번.',
       '일곱 ZEZE가 말없이 대형 화면을 응시한다.',
       '결승선을 점검할 위원회가 꾸려진다.',
       '선은 곧다. 순위도 그렇다.'],
      ['우승 한 바퀴가 경기 자체보다 오래 걸린다.',
       '단순한 산수이고, 아무도 불평하지 않는다.',
       '누군가 깃발을 건넨다. 어느 은하의 것인지 알 수 없다.',
       '전부의 것이다. 이날을 위해 도안을 하나로 합쳤다.',
       '합창단은 노래를 다시 썼다. 이제 네 이름이 나온다, 마침내.']
    ]
  }
};
