/* -----------------------------------------------------------------------
   SPRINTER — Nederlands.
   Ce qui manque ici retombe sur l'anglais, cle par cle : voir
   sprinter-i18n.js. Verification : node tools/langues-verifier.mjs nl
   ----------------------------------------------------------------------- */
export default {
  // In het Nederlands: 1e, 2e, 3e.
  ord(n) { return n + 'e'; },

  LEVEL_NAMES: [
    'Schoolwedstrijd', 'Regionaal niveau', 'Nationaal niveau',
    'Wereldkampioenschap', 'Wereldspelen', 'Intergalactisch'
  ],

  RACE_SUB: {
    '100': 'het rechte stuk',
    '200': 'bocht en recht stuk',
    '400': 'één ronde op de baan'
  },

  UI: {
    races: '100 - 200 - 400 METER',
    tagline: 'zes etappes, één tijd om te verslaan',
    tap_start: 'tik op het scherm om te beginnen',
    six_stages: '   -   zes etappes',
    six_stages_bare: 'zes etappes',
    best_runs: 'BESTE RONDES',
    no_run: 'nog geen ronde afgemaakt',
    furthest: 'verste etappe: ',
    of_six: ' van 6',
    start: 'START',
    sound: 'geluid: ',
    yes: 'ja',
    no: 'nee',

    rival: 'DE LOPER OM TE VERSLAAN',
    favourite: 'De favoriet',
    after_race: 'NA DE WEDSTRIJD',
    crowned: 'INTERGALACTISCHE TITEL',
    fastest_1: 'HET SNELSTE WEZEN',
    fastest_2: 'VAN ALLE MELKWEGEN',
    full_run_in: 'hele ronde in ',
    announced: 'aangekondigde tijd: ',
    stage_up: 'ETAPPE ',
    six_cleared: 'ZES ETAPPES GEHAALD',
    skip_now: 'tik nogmaals om over te slaan',
    skip_twice: 'tik twee keer om over te slaan',

    reaction: 'REACTIE',
    react_top: 'PERFECTE REACTIE',
    false_start: 'TE VROEG WEG',
    wait_gun: 'wacht op het schot',
    phase_drive: 'AANZET',
    phase_trans: 'OVERGANG',
    phase_max: 'TOPSNELHEID',
    drive_hint: 'vind je ritme',
    trans_2: 'PERFECTE OVERGANG',
    trans_1: 'GOEDE OVERGANG',
    trans_0: 'OVERGANG GEMIST',
    start_line: 'start: {r} s reactie   -   {g}',
    no_start: 'start gemist',

    stumble: 'JE STRUIKELT',
    to_beat: 'te verslaan: ',
    to_race: 'je loopt tegen ',
    ready: 'OP UW PLAATSEN',
    get_set: 'KLAAR',
    go: 'AF',
    alternate: 'wissel tussen de twee knoppen',
    alternate_kb: 'wissel tussen de twee pijlen',
    you: 'JIJ',
    opponent: 'TEGENSTANDER',
    depart: 'START',
    arrivee: 'FINISH',

    stage_done: 'ETAPPE {n} GEHAALD',
    first_in: '1e plaats in ',
    total_of: ' s   -   totaal ',
    place: '{o} PLAATS',
    dnf: 'opgegeven',
    unfinished: 'niet afgemaakt',
    race_again: 'NOG EEN KEER?',
    next_stage: 'ETAPPE {n}',
    home: 'HOME',
    replay: 'OPNIEUW SPELEN',
    run_done: 'RONDE COMPLEET',
    six_in: 'zes etappes gehaald in ',
    stage_low: 'etappe ',

    new_record: 'NIEUW RECORD',
    top3: 'TOP 3',
    top10: 'TOP 10',
    best_run: 'BESTE RONDE',
    top3_runs: 'TOP 3 RONDES',
    top10_runs: 'TOP 10 RONDES',

    top500: 'TOP 500 - ALLER TIJDEN',
    your_name: 'je naam',
    save_score: 'MIJN TIJD OPSLAAN',
    saving_score: 'versturen...',
    score_saved: '{r} in de wereldwijde TOP 500',
    score_save_fail: 'versturen mislukt, probeer het later',
    score_name_taken: 'deze naam hoort bij een ander apparaat',
    score_taken_help: 'kies een andere, of koppel dit apparaat aan je naam via MIJN WEDSTRIJDEN met je herstelcode',
    view_top500: 'BEKIJK DE TOP 500',
    top500_court: 'TOP 500',
    close: 'SLUITEN',
    loading_ranks: 'ranglijst laden...',
    empty_top500: 'nog geen tijden vastgelegd',
    your_rank: 'JOUW PLAATS: {r}',
    outside_top500: 'buiten de top 500',
    edit_name: 'NAAM WIJZIGEN',
    best_split_short: 'beste etappe:',
    top500_sub: 'beste tijd in één wedstrijd',
    cat_race: 'PER WEDSTRIJD',
    cat_run: 'HELE RONDE',
    cat_mine: 'MIJN WEDSTRIJDEN',
    cat_mine_sub: 'alle wedstrijden die je liep',
    mine_empty: 'nog geen wedstrijd op dit onderdeel',
    mine_count: '{n} wedstrijden — beste: {s} s',
    mine_note: 'De TOP 500 bewaart alleen je beste tijd per onderdeel; deze geschiedenis bewaart alles. Reserveer je naam om hem op je andere apparaten terug te vinden.',

    duel_title: 'DUELRANGLIJST',
    duel_sub: 'verstuurde en beantwoorde uitdagingen',
    duel_open: 'BEKIJK DE DUELRANGLIJST',
    duel_rules_init: 'UITDAGING VERSTUURD',
    duel_rules_recv: 'UITDAGING BEANTWOORD',
    duel_rules_line: 'winst {v}   ·   verlies {d}   ·   gelijk {n}',
    duel_rules_all: 'elk duel telt, verstuurd of beantwoord',
    duel_rules_why: 'wie uitdaagt, laat zijn tijd als eerste zien',
    duel_counts: '{l} verstuurd · {r} beantwoord',
    duel_sur: 'HET DUEL WORDT GELOPEN OP',

    name_set: 'KIES JE NAAM',
    name_title: 'JOUW NAAM',
    name_why: 'dit staat in de TOP 500, op je uitdagingen en in de duels',
    name_save: 'OPSLAAN',
    name_saved: 'OPGESLAGEN',
    name_taken: 'die naam is al bezet',
    name_code: 'JOUW HERSTELCODE',
    pays_title: 'JOUW NATIONALITEIT',
    pays_opt: 'slechts één keer',
    pays_aucun: 'kies je land',
    pays_why: 'je hebt er een nodig voor een nationaal kampioenschap — en daarna is het niet meer te wijzigen',
    pays_vu: 'je lijkt verbinding te maken vanuit {pays} — jij beslist',
    pays_save: 'KIEZEN',
    pays_confirm: 'Uitkomen voor {pays}?\n\nDit is definitief: het bepaalt in welk nationaal kampioenschap je meedoet, en is niet te wijzigen.',
    pays_fige: 'definitief',
    pays_on: 'je komt uit voor dit land — je vlag staat bij je naam op het kampioenschap',
    pays_deja: 'je nationaliteit staat al vast en is niet te wijzigen',
    pays_first: 'sla eerst je naam op',
    pays_bad: 'ongeldig land',
    insta_title: 'JOUW INSTAGRAM',
    insta_ph: 'je gebruikersnaam, zonder de @',
    insta_why: 'je profiel wordt bereikbaar via de TOP 500 en je uitdagingen',
    insta_note: 'door jou opgegeven, niet gecontroleerd — Instagram staat geen echte login meer toe voor een persoonlijk account',
    insta_link: 'MIJN ACCOUNT KOPPELEN',
    insta_linked: 'ACCOUNT GEKOPPELD',
    insta_unlink: 'ONTKOPPELEN',
    insta_on: 'je profiel staat in de TOP 500 — tik erop om te openen',
    insta_gone: 'account ontkoppeld, je profiel staat nergens meer',
    insta_bad: 'ongeldige gebruikersnaam',
    insta_first: 'sla eerst je naam op',
    insta_notyours: 'deze naam is op dit apparaat niet van jou',
    insta_visit: 'bekijk het Instagram-profiel van {n}',
    name_code_why: 'schrijf hem op: hij haalt je naam en wedstrijden terug op een andere telefoon',

    tour_open: 'DOE DE RONDLEIDING',
    tour_1_t: 'WISSELEN',
    tour_1_s: 'links, rechts, links. Meer is de wedstrijd niet.',
    tour_2_t: 'DE CARRIÈRE',
    tour_2_s: 'zes etappes, van het schoolplein tot de intergalactische finale',
    tour_3_t: 'DE TOP 500',
    tour_3_s: 'jouw tijd tegen de hele wereld',
    tour_4_t: 'DE GEEST',
    tour_4_s: 'stuur je wedstrijd naar een vriend — hij loopt tegen jou',
    tour_5_t: 'LIVE',
    tour_5_s: 'hetzelfde schot, elk op je eigen telefoon',
    tour_play: 'LAAT ME SPELEN',

    os_tuto_open: 'WAAR DEZE MODUS VOOR IS',
    os_tuto_1_t: 'KIES JE ONDERDELEN',
    os_tuto_2_t: 'MAAR ÉÉN POGING',
    os_tuto_3_t: 'JOUW TIJD TELT',
    os_tuto_1_s: 'één, twee of alle drie',
    os_tuto_2_s: 'geen herkansing, geen uitschakeling',
    os_tuto_3_s: 'TOP 500, en een vriend kan het oppakken',
    os_tuto_go: 'START EEN ONE SHOT',

    tuto_ask_t: 'EERSTE WEDSTRIJD',
    tuto_ask_s: 'de beweging leer je in dertig seconden',
    tuto_ask_yes: 'LEER DE BEWEGING',
    tuto_ask_no: 'LAAT ME LOPEN',
    tuto_watch: 'KIJK',
    tuto_your_turn: 'JOUW BEURT',
    tuto_1_t: 'WISSELEN',
    tuto_2_t: 'OP HET SCHOT',
    tuto_3_t: 'WIJD, DAN KORT',
    tuto_v_early: 'TE VROEG',
    tuto_v_late: 'te laat',
    tuto_v_perfect: 'PERFECT',
    tuto_v_good: 'GOED',
    tuto_v_slow: 'NIET SNEL GENOEG',
    tuto_v_flat: 'VLAK RITME',
    tuto_replay_demo: 'nog eens kijken',
    tuto_again: 'NOG EENS',
    tuto_next: 'VERDER',
    tuto_done_t: 'NU LOOP JIJ',
    tuto_start: 'START',
    tuto_replay: 'nog eens kijken',
    tuto_skip: 'overslaan',
    tuto_open: 'ZO SPEEL JE',

    live_title: 'LIVEWEDSTRIJD',
    live_desc: 'jullie starten allebei op hetzelfde schot, elk op je eigen telefoon — geen geest, niemand weet wie wint',
    live_create: 'OPEN EEN BAAN',
    live_join: 'MEEDOEN',
    live_or: 'of',
    live_room: 'BAAN OPEN',
    live_waiting: 'stuur deze code naar je tegenstander — de wedstrijd begint zodra jullie met z’n tweeën zijn',
    live_ready: 'KLAAR',
    live_notready: 'NOG NIET',
    live_empty_seat: 'baan vrij — wacht op een tegenstander',
    live_go: 'IK BEN KLAAR',
    live_unready: 'ANNULEREN',
    live_leave: 'baan verlaten',
    live_none: 'geen baan met die code',
    live_full: 'die baan zit al vol',
    live_gone: 'je tegenstander heeft de baan verlaten',
    live_closed: 'de verbinding is weggevallen',
    live_invite: 'Ik wacht op je op de baan. Code {c} — {l}',

    relais_titre: '4 × 100 ESTAFETTE',
    relais_desc: 'vier lopers, één stokje. Een ploeg is haar opstelling: dezelfde vier namen, dezelfde ploeg.',
    relais_invitations: 'JE BENT UITGENODIGD',
    relais_mes_equipes: 'JOUW PLOEGEN',
    relais_creer: 'STEL EEN PLOEG SAMEN',
    relais_nom_equipe: 'naam van de ploeg',
    relais_coequipier: 'ploeggenoot {n}',
    relais_inviter: 'NODIG DE DRIE UIT',
    relais_incomplet: 'er ontbreken een naam en drie ploeggenoten',
    relais_attend: 'in afwachting',
    relais_ok: 'erbij',
    relais_refuse: 'geweigerd',
    relais_fixer_ordre: 'BEPAAL DE LOOPVOLGORDE',
    relais_manque_reponses: 'er ontbreken nog antwoorden voordat er gelopen kan worden',
    relais_manque_refus: 'een ploeggenoot heeft geweigerd — deze ploeg kan niet lopen',
    relais_prete: 'ploeg klaar',
    relais_classement: 'PLOEGENKLASSEMENT',
    relais_plein_titre: 'TWEE PLOEGEN, GEEN DRIE',
    relais_plein: 'je loopt al voor twee ploegen. Verlaat die waarvoor je niet meer loopt om een nieuwe samen te stellen.',
    relais_plein_invit: 'je loopt al voor twee ploegen — verlaat er een om dit aan te nemen.',
    relais_quitter: 'VERLATEN',
    relais_quitter_sur: 'voorgoed verlaten?',
    relais_quitter_sub: 'je komt alleen terug met een nieuwe uitnodiging',
    relais_reste: 'nog één plek vrij',
    relais_place: '1 van 2 ploegen',
    relais_places: '{n} van 2 ploegen',
    relais_courir: 'NAAR DE BAAN',
    relais_mon_rang: 'jij loopt de {n}e wissel',
    relais_premier: 'je start uit het blok, staand. Een valse start schakelt de hele ploeg uit.',
    relais_ta_marque: 'JOUW MERKTEKEN IN DE ZONE',
    relais_zone_debut: 'in',
    relais_zone_fin: 'uit',
    relais_marque_conseil: 'verder naar voren start je sneller, maar je verlaat de zone misschien vóór het stokje. Verder terug krijg je het zeker — vanuit stilstand.',
    relais_attend_equipe: 'er ontbreken nog {n} ploeggenoten',
    relais_temoin_a: 'STOKJE BIJ',
    relais_spectateur: 'DE ANDEREN LOPEN',
    relais_porte: 'DRAAGT',
    relais_attends_temoin: 'WACHT',
    relais_prends: 'PAK HET STOKJE',
    relais_donne: 'GEEF HET STOKJE',
    relais_arrivee: 'ESTAFETTE COMPLEET',
    relais_elimine: 'PLOEG UITGESCHAKELD',
    relais_elimine_pourquoi: 'bij wissel {r}: {c}',
    relais_passages: 'DE DRIE WISSELS',
    relais_elimine_court: 'uit',
    relais_fantome: 'GEEST',

    conf_titre: 'LOOP TEGEN ANDERE PLOEGEN',
    conf_desc: 'één schot, één finishvolgorde. Open een code en deel hem, of voer in wat je gekregen hebt.',
    conf_ouvrir: 'OPEN EEN CONFRONTATIE',
    conf_rejoindre: 'MEEDOEN',
    conf_code: 'code',
    conf_code_court: 'die code is te kort',
    conf_partage: 'DEEL DEZE CODE MET DE ANDERE PLOEGEN',
    conf_places: '{n} ploegen op de baan',
    conf_engagees: '{n} VAN {m} PLOEGEN',
    conf_attend_adversaire: 'er is minstens nog één ploeg nodig, of een geest',
    conf_classement: 'FINISHVOLGORDE',
    conf_encore: 'de anderen lopen nog',

    fantome_titre: 'DAAG DE TIEN BESTE RONDES UIT',
    fantome_desc: 'ze zijn al gelopen: ze worden herhaald en kunnen niet worden uitgeschakeld of bij een wissel verslagen. Zo meet je je met de besten zonder acht mensen bijeen te brengen.',
    fantome_aucun: 'nog geen ronde vastgelegd — de eerste ploeg die een estafette afmaakt, opent de bal.',
    fantome_choisis: '{n} van {m} gekozen',
    fantome_defier: 'DAAG ZE UIT',

    champ_directs: 'de eerste {n} gaan door',
    champ_reveal: 'DE SNELSTE VERLIEZERS',
    champ_reveal_desc: 'ze wonnen geen enkele wedstrijd. Ze komen uit de tijd van alle wedstrijden.',
    champ_continue: 'VERDER',
    champ_sacre: '{n} wordt gekroond — bekijk het podium',
    champ_titre_duree: 'titel voor drie maanden',
    champ_rv_course: 'VOLGENDE WEDSTRIJD',
    champ_rv_reveal: 'SNELSTE VERLIEZERS ONTHULD',
    champ_rv_sacre: 'CEREMONIE',
    champ_quitter: 'kampioenschap verlaten',

    live_lanes: 'BANEN',
    live_lanes_duel: 'een duel: de winnaar pakt punten, de verliezer levert er in',
    live_lanes_course: 'een wedstrijd: een finishvolgorde, geen punten op de duelranglijst',
    live_won: 'WEDSTRIJD GEWONNEN',
    live_sur: 'VAN {n} STARTERS',
    live_ordre: 'FINISHVOLGORDE',
    live_lost: 'WEDSTRIJD VERLOREN',

    pres_title: 'PRESENTATIE VAN DE ATLETEN',
    pres_lane: 'BAAN',
    pres_you: 'DAT BEN JIJ',
    pres_mic_on: 'MICROFOON AAN',
    pres_mic_off: 'microfoon geweigerd',
    mic_winner: 'DE WINNAAR SPREEKT',

    review_title: 'DE VIDEO VAN JOUW WEDSTRIJD',
    review_making: 'opnemen…',
    review_dl: 'DOWNLOADEN',
    review_left: 'verwijderd over {t}',
    review_gone: 'de video is verwijderd',
    review_kept: 'wat je hebt gedownload blijft op je telefoon',
    review_none: 'dit apparaat kan de wedstrijd niet opnemen',
    live_tie: 'GELIJK OVER DE STREEP',
    live_vs: 'live tegen {n}',
    live_gap: '{s} s verschil',
    link_in_app: 'SPEL GEÏNSTALLEERD?',
    link_in_app_sub: 'open het vanaf je beginscherm en voer deze code in — tik om te kopiëren',

    duel_answered: 'JE UITDAGING IS BEANTWOORD',
    duel_more: 'nog {n} uitslag open',
    duel_mores: 'nog {n} uitslagen open',
    duel_next: 'VERDER',
    duel_ok: 'BEGREPEN',

    ghost_mode: 'GEESTMODUS',
    ghost_ahead: 'VOOR',
    ghost_behind: 'ACHTER',
    ghost_level: 'GELIJK',
    ghost_home: 'de geest is over de streep',
    ghost_live: 'de geest loopt naast je',
    duel_must: 'stuur een uitdaging, of beantwoord die van een vriend',
    duel_empty: 'nog geen duel gespeeld',
    duel_pts: 'ptn',

    monde_sprinter_sous: 'het rechte stuk en de ronde',
    monde_hurdlers_sous: 'dezelfde baan, met tien horden erin',
    monde_jumper_sous: 'bouw de aanloop op en kom los van de grond',
    monde_thrower_sous: 'een ring, een werptuig en het hele lichaam',
    monde_bientot: 'BINNENKORT',
    monde_retour: 'TERUG NAAR SPRINTER',

    disc_100: '100 METER',
    disc_200: '200 METER',
    disc_400: '400 METER',
    disc_100h: '100 M HORDEN',
    disc_110h: '110 M HORDEN',
    disc_400h: '400 M HORDEN',
    disc_longueur: 'VERSPRINGEN',
    disc_hauteur: 'HOOGSPRINGEN',
    disc_triple: 'HINKSTAPSPRINGEN',
    disc_perche: 'POLSSTOKHOOGSPRINGEN',
    disc_poids: 'KOGELSTOTEN',
    disc_marteau: 'KOGELSLINGEREN',
    disc_disque: 'DISCUSWERPEN',
    disc_javelot: 'SPEERWERPEN',

    pique_0: 'Ik hoefde het niet eens te proberen.',
    pique_1: 'zal ik het nog eens doen, in slow motion?',
    pique_2: 'ik had tijd om me te vervelen.',
    pique_3: 'de finish is deze kant op.',
    pique_4: 'bedankt voor de warming-up.',
    pique_5: 'ik keek achterom en er was niemand.',
    pique_6: 'heb jij gelopen? ik zag niets voorbijkomen.',
    pique_7: 'bewaar die tijd, dat wordt een mooie herinnering.',

    mot_titre: 'LAAT {n} EEN PAAR WOORDEN NA',
    mot_placeholder: 'prik hem in twee regels',
    mot_vocal: 'STEM',
    mot_ecouter: 'AFSPELEN',
    mot_refaire: 'opnieuw opnemen',
    mot_envoyer: 'VERSTUREN',
    mot_envoye: '{n} leest het bij terugkomst',
    mot_micro_refuse: 'de microfoon is geweigerd — tekst kan ook',
    mot_ecouter_sa_voix: 'HOOR WAT HIJ ZEI',
    mot_ephemere: 'deze opname verdwijnt zodra je dit venster sluit',
    mot_illisible: 'dit bericht speelt niet af op dit apparaat',

    mod_signaler: 'melden',
    mod_titre: 'Waarom meld je dit?',
    mod_explique: 'Een melding wordt door een mens gelezen. Blokkeren werkt meteen.',
    mod_insulte: 'belediging',
    mod_haine: 'haat, racisme',
    mod_sexuel: 'seksueel',
    mod_menace: 'bedreiging',
    mod_autre: 'anders',
    mod_envoye: 'Gemeld. Iemand gaat het lezen.',
    mod_deja: 'al gemeld',
    mod_bloquer: '{n} blokkeren',
    mod_bloque: '{n} kan je niet meer schrijven.',
    mod_annuler: 'annuleren',

    duel_revanche: 'IK WIL REVANCHE',
    duel_revanche_sub: 'zelfde onderdeel — nu zet jij de tijd neer',
    duel_renvoyer: 'stuur de code terug naar {n}',
    duel_revanche_envoyee: 'REVANCHE VERSTUURD',
    os_revanche_sans_cible: '{n} kon niet worden gewaarschuwd — stuur de code zelf',
    duel_revanche_ratee_titre: 'NOG NIET',
    duel_revanche_ratee: 'je had onder {s} s nodig om {n} terug uit te dagen — er is niets verstuurd',

    rang_departemental: 'DISTRICT',
    rang_regional: 'REGIONAAL',
    rang_national: 'NATIONAAL',
    rang_elite: 'ELITE',
    rang_legende: 'LEGENDE',
    rang_court_departemental: 'DIS',
    rang_court_regional: 'REG',
    rang_court_national: 'NAT',
    rang_court_elite: 'ELITE ',
    rang_court_legende: 'LEGENDE',
    duel_lp: 'LP',
    duel_monte_a11y: '{n} plaatsen omhoog',
    duel_descend_a11y: '{n} plaatsen omlaag',
    duel_lp_long: 'competitiepunten',
    duel_promu: 'GEPROMOVEERD NAAR {r}',
    duel_relegue: 'GEDEGRADEERD NAAR {r}',
    duel_reste: 'nog {n} tot de volgende divisie',
    duel_regle: 'een uitdaging beantwoorden levert meer op dan er een sturen: de tijd staat er al, en je weet wat je moet verslaan.',
    duel_record: '{v}W · {d}V · {n}G',
    duel_you: 'JIJ',
    duel_since: 'sinds je laatste bezoek',
    duel_unranked: 'nog niet geplaatst — speel een duel',
    duel_won: 'DUEL GEWONNEN',
    duel_lost: 'DUEL VERLOREN',
    duel_tie: 'GELIJKSPEL',
    duel_final: 'definitieve uitslag — een uitdaging wordt niet overgedaan',
    duel_delta: '{p} punt',
    duel_deltas: '{p} punten',

    false_out: 'VALSE START',
    false_out_sub: 'uitgeschakeld — het duel is verloren',
    false_out_seul: 'uitgeschakeld — deze wedstrijd eindigt hier',
    false_out_rule: 'maar één wedstrijd, geen tweede kans',
    false_out_libre: 'je mag hem opnieuw lopen',
    false_out_gun: 'weg vóór het schot',
    duel_await: 'duelresultaat…',
    duel_vs: 'tegen {n}',
    duel_seen: 'duel al beslist',
    duel_see: 'BEKIJK DE RANGLIJST',

    os_once: 'zodra de uitdaging weg is, ligt de tijd vast',
    os_rejouer: 'NOG EENS LOPEN',
    os_rejouer_sub: 'nog een wedstrijd, nu meteen — deze blijft zoals hij is',
    os_defier: 'DAAG IEMAND UIT',
    os_defier_sub: 'open de ranglijst en kies je tegenstander — een andere, of dezelfde',
    relance_gagne_0: 'PAK ER NOG EEN',
    relance_gagne_0_sub: 'die is geregeld. Volgende.',
    relance_gagne_1: 'DE VOLGENDE, GRAAG',
    relance_gagne_1_sub: 'de ranglijst zit vol mensen, en jij loopt op dreef.',
    relance_gagne_2: 'WIE NOG MEER?',
    relance_gagne_2_sub: 'vraag het de ranglijst. Iemand antwoordt.',
    relance_perdu_0: 'ZOEK IEMAND KLEINER',
    relance_perdu_0_sub: 'zak een divisie — niemand hoeft het te weten',
    relance_perdu_1: 'ZOEK IEMAND LANGZAMER',
    relance_perdu_1_sub: 'ze bestaan. Statistisch bestaan ze.',
    relance_perdu_2: 'ER ZIJN NOG BEGINNERS',
    relance_perdu_2_sub: 'ze vermoeden niets. Dit is het moment.',
    os_defi_sans_cible: '{n} staat niet in de TOP 500 van dit onderdeel — stuur de code zelf',
    os_verrou_direct: 'livewedstrijd: je tegenstander liep op hetzelfde moment — die uitslag geldt',
    os_verrou_recu: 'die tijd is bij je tegenstander — hij kan niet worden teruggenomen',
    os_verrou_envoye: 'de uitdaging is weg — dat is de tijd die hij moet verslaan',
    os_verrou_faux: 'valse start in een duel: de wedstrijd is verloren. Stuur een nieuwe uitdaging om opnieuw te beginnen.',
    cut_skip: 'OVERSLAAN',

    id_title: 'JOUW NAAM',
    id_code_title: 'HERSTELCODE',
    id_code_note: 'schrijf hem op: hij koppelt je andere apparaten aan deze naam en houdt anderen ervan af',
    id_show: 'TOON MIJN CODE',
    id_reserve: 'RESERVEREN',
    id_taken: 'deze naam is al bezet',
    id_taken_help: 'als hij van jou is, voer dan zijn herstelcode in',
    id_link: 'KOPPELEN',
    id_linked: 'apparaat gekoppeld aan {n}',
    id_bad_code: 'verkeerde code',
    id_unknown: 'onbekende naam',
    id_link_title: 'EEN ANDER APPARAAT?',
    id_link_help: 'voer je naam en code in om je tijden en geschiedenis hier terug te vinden',

    install_title: 'INSTALLEER HET SPEL',
    install_why: 'volledig scherm, geen browserbalk, en offline speelbaar',
    install_do: 'INSTALLEREN',
    install_later: 'later',
    install_ios_1: 'Tik op',
    install_ios_2: 'Deel',
    install_ios_3: 'onderaan in Safari, en dan',
    install_ios_4: 'Zet op beginscherm',

    mode_career_s: 'carrière',
    mode_oneshot_s: 'one shot',
    cat_race_sub: 'beste tijd in één wedstrijd',
    cat_run_sub: 'totaal van alle zes etappes',
    empty_cat_run: 'nog geen hele ronde vastgelegd',
    will_enter: '{s} s: {r} in de TOP 500, zet je naam erbij',

    wr_title: 'WERELDRECORD',
    wr_sub: 'beste tijd ter wereld op {d} m',
    wr_old: 'vorig record: {s} s',
    wr_first: 'eerste tijd op het bord',
    wr_gain: '{s} s sneller',
    wr_save: 'ZET MIJN NAAM EROP',
    wr_saving: 'opslaan...',
    wr_done: '{n} is {r} in de TOP 500',
    wr_fail: 'versturen mislukt, probeer opnieuw',
    wr_see: 'BEKIJK DE TOP 500',
    wr_later: 'later',
    top500_count: '{n} tijden geplaatst van 500',

    pause_title: 'WEDSTRIJD GEPAUZEERD',
    pause_note: 'nu stoppen betekent de lopende tijd opgeven',
    resume: 'HERVATTEN',

    challenge_them: 'UITDAGEN',
    target_run: 'loop je {d} m: de uitdaging gaat naar {n}',
    target_sent: 'uitdaging verstuurd naar {n}',
    inbox_one: 'UITDAGING ONTVANGEN',
    inbox_many: '{n} UITDAGINGEN ONTVANGEN',
    inbox_from: '{n} daagt je uit op {d} m',
    inbox_accept: 'AANNEMEN',
    inbox_later: 'later',
    run_total_short: 'hele ronde:',
    run_total_tiny: 'ronde',
    best_split_tiny: 'wedstrijd',
    score_saved_race: '{r} in de wereldwijde TOP 500 met {s} s',
    mode_career: 'CARRIÈRE',
    mode_oneshot: 'ONE SHOT',
    mode_versus: 'UITDAGING',
    career_desc: 'alle zes etappes achter elkaar, één enkele tijd',
    oneshot_desc: 'kies je onderdelen, één enkele poging',
    versus_desc: 'loop tegen de geest van een andere speler',
    pick_events: 'ONDERDELEN',
    pick_level: 'NIVEAU',
    pick_none: 'kies minstens één onderdeel',
    launch_oneshot: 'GAAN',
    event_n: 'ONDERDEEL {n} / {t}',
    next_event: 'VOLGEND ONDERDEEL',
    oneshot_done: 'ONE SHOT COMPLEET',
    total_in: 'totaal: ',
    challenge_code: 'UITDAGINGSCODE',
    challenge_enter: 'voer de code in die je kreeg',
    challenge_load: 'LADEN',
    challenge_loading: 'uitdaging laden...',
    challenge_bad: 'code niet gevonden',
    challenge_net: 'verbinding mislukt, probeer opnieuw',
    challenge_from: 'uitdaging van {n}',
    challenge_beat: 'te verslaan: {s} s',
    challenge_aveugle: 'zijn tijd ontdek je al lopend',
    challenge_accept: 'NEEM DE UITDAGING AAN',
    challenge_make: 'DAAG EEN VRIEND UIT',
    challenge_making: 'uitdaging aanmaken...',
    challenge_share: 'stuur deze code, je vriend loopt tegen jouw geest',
    challenge_copy: 'LINK KOPIËREN',
    challenge_copied: 'link gekopieerd',
    challenge_copy_code: 'CODE KOPIËREN',
    share_send: 'VERSTUUR DE UITDAGING',
    share_whatsapp: 'WhatsApp',
    share_sms: 'SMS',
    share_other: 'Snapchat, Instagram…',
    share_other_hint: 'Snapchat en Instagram open je via het deelmenu.',
    affiche_share: 'DEEL MIJN RONDE',
    affiche_making: 'Afbeelding maken…',
    affiche_saved: 'afbeelding opgeslagen',
    affiche_failed: 'afbeelding mislukt',
    affiche_hint: 'een afbeelding van je ronde, voor Instagram of TikTok',
    code_copied: 'code gekopieerd',
    challenge_rematch: 'DAAG TERUG UIT',
    challenge_rematch_sub: 'je hebt gewonnen — daag hem uit op de ronde die je net liep',
    challenge_won: 'UITDAGING GEWONNEN',
    challenge_lost: 'UITDAGING VERLOREN',
    challenge_gap: 'verschil: {s} s',
    ghost_label: 'GEEST',
    you_label: 'JIJ',
    dnf_short: 'DNF',
    composing: 'soundtrack componeren...',

    sound_off: 'GELUID UIT  (S)',
    press_enter: 'druk op ENTER',
    skip_now_kb: 'druk nog eens op ENTER om over te slaan',
    skip_twice_kb: 'druk twee keer op ENTER om over te slaan',
    stage_dash: 'ETAPPE {n}   -   {s}',
    furthest_kb: 'verste bereikte etappe: {a} van {b}',
    enter_start: 'ENTER: start   -   S: geluid   -   L: taal   -   ESC: stoppen',
    how_to_play: 'ZO SPEEL JE',
    help_1: 'Wissel tussen  <-  en  ->  zonder',
    help_2: 'dezelfde toets te herhalen.',
    help_3: 'Een vast ritme bouwt snelheid op;',
    help_4: 'herhalen laat je struikelen, maar',
    help_5: 'je komt altijd weer op gang.',
    best_stage: 'BESTE TIJDEN VAN DEZE ETAPPE',
    no_time: 'nog geen tijd vastgelegd',
    arrows_pick: 'pijlen om te kiezen   -   ENTER om te bevestigen   -   ',
    yn_short: 'sneltoets J / N',
    you_beat: 'Je hebt {w} verslagen en alle zes etappes gehaald.',
    the_zeze: 'de ZEZE',
    your_times: 'JOUW TIJDEN',
    total: 'TOTAAL',
    enter_replay: 'ENTER: nog eens lopen      M: home',
    stumble_kb: 'JE STRUIKELT!',
    go_kb: 'AF!',
    to_beat_line: 'TE VERSLAAN:  {n}   -   {s} s',
    best_times_of: 'BESTE TIJDEN  -  {s}',
    enter_next: 'ENTER   ->   ETAPPE {n}: {s}',
    full_run_pc: 'hele ronde in {s} s',
    announced_pc: 'aangekondigde tijd: {s} s',
    quit: 'ESC: stoppen',

    // accueil : le nom, le drapeau, Instagram, un pas a la fois
    bienvenue_titre: 'WELKOM',
    bv_nom_t: 'JOUW NAAM',
    bv_nom_s: 'hij volgt al je tijden',
    bv_pays_t: 'JOUW VLAG',
    bv_pays_s: 'voor de kampioenschappen — definitief',
    bv_insta_t: 'JOUW INSTAGRAM',
    bv_insta_s: 'bereikbaar via de ranglijst — opgegeven, niet gecontroleerd',
    bv_passer: 'overslaan',
    bv_suite: 'VERDER',
    bienvenue_plus: 'LATER',
    bienvenue_go: 'WE GAAN',
    contact: 'NEEM CONTACT OP',

    // la montee au classement, annoncee et lue a voix haute
    places_1: 'PLAATS',
    places_n: 'PLAATSEN',
    classement_entree: 'OP DE RANGLIJST',
    classement_bouge_a11y: '{n} plaatsen gewonnen — {r} in {c}',
    classement_perd_a11y: '{n} plaatsen verloren — {r} in {c}',
    classement_entre_a11y: 'op de ranglijst — {r} in {c}',

    // notifications
    avis_title: 'MELDINGEN',
    avis_desc: 'bericht krijgen als het spel dicht is',
    avis_pourquoi: 'een uitdaging die ’s nachts binnenkomt is niets waard als je hem pas de volgende dag vindt',
    avis_activer: 'MELDINGEN AANZETTEN',
    avis_couper: 'NIETS MEER ONTVANGEN',
    avis_actives: 'meldingen staan aan',
    avis_essai: 'STUUR ME EEN TEST',
    avis_essai_ok: 'verstuurd — hij zou binnen een seconde moeten aankomen',
    avis_essai_ko: 'er is niets uitgegaan: controleer of meldingen zijn toegestaan',
    avis_refuse: 'je hebt ze geweigerd: dat zet je weer aan in de telefooninstellingen, niet hier',
    avis_installer: 'op iPhone zet je het spel eerst op je beginscherm: Safari geeft ze alleen aan geïnstalleerde apps',
    avis_indispo: 'deze browser kan ze niet ontvangen',
    avis_erreur: 'de server kon de aanmelding niet vastleggen',
    avis_choisir: 'WAT IK WIL ONTVANGEN',
    avis_g_defi: 'Een ontvangen uitdaging',
    avis_g_defi_s: 'iemand stuurde je een tijd om te verslaan',
    avis_g_selection: 'Een selectie voor een kampioenschap',
    avis_g_selection_s: 'je bent een van de 32 lopers',
    avis_g_direct: 'Een live-uitdaging',
    avis_g_direct_s: 'iemand staat op de baan te wachten, nu',
    avis_g_relais: 'Een estafette-uitnodiging',
    avis_g_relais_s: 'een ploeg wil jou erbij',
    avis_g_rendezvous: 'De starttijden van de kampioenschappen',
    avis_g_rendezvous_s: 'een kwartier voor elke wedstrijd',
    avis_g_assister: 'De finales, en wie ze wint',
    avis_g_assister_s: 'een kwartier vooraf, en dan de kroning — ook als je er niet in zit',
    avis_g_record: 'Een wereldrecord dat sneuvelt',
    avis_g_record_s: 'de koppositie van een afstand wisselt van eigenaar',
    avis_suivre: 'WELKE KAMPIOENSCHAPPEN',
    avis_suivre_national: 'mijn land',
    avis_suivre_continental: 'mijn werelddeel',
    avis_suivre_mondial: 'het Wereldkampioenschap',
    avis_suivre_vide: 'vink er minstens één aan, anders wordt er niets verstuurd',
    avis_suivre_nom: 'reserveer hierboven je naam, dan is je land bekend',

    // inviter quelqu un sur la piste, par son nom
    live_inviter: 'EEN SPELER UITNODIGEN',
    live_inviter_ph: 'zijn naam',
    live_inviter_ok: '{n} is gewaarschuwd — zijn telefoon gaat over',
    live_inviter_ko: 'niemand met die naam heeft hem gereserveerd: stuur hem de code',
    live_invite_recue: '{n} wacht op je op de baan',
    live_invite_rejoindre: 'MEEDOEN',

    // suppression du profil
    id_del: 'MIJN PROFIEL VERWIJDEREN',
    id_del_what: 'je naam, je code, je tijden op de ranglijst, je geschiedenis online, je uitdagingen en je duels worden van de server gehaald, op al je apparaten.',
    id_del_keep: 'je voortgang in de carrière en de wedstrijden die op dit apparaat staan blijven onaangeroerd.',
    id_del_final: 'dit is definitief: niets ervan is terug te halen.',
    id_del_confirm: 'typ {n} om te bevestigen',
    id_del_go: 'VERWIJDEREN',
    id_del_cancel: 'annuleren',
    id_del_done: 'profiel verwijderd',
    id_del_device: 'deze naam was niet gereserveerd: wat van dit apparaat kwam is gewist',
    id_del_code: 'dit apparaat is niet aan deze naam gekoppeld: voer de herstelcode ervan in',

    // le record personnel a la fin d un one shot
    os_record_titre: 'RECORD VERBROKEN',
    os_record_titre_n: 'RECORDS VERBROKEN',
    os_record_sur: 'op {d} m',
    os_record_premier: 'eerste tijd op deze afstand',
    os_record_gain: '{s} s sneller',
    os_record_rang: '{r} in de TOP 500 - ALLER TIJDEN',
    os_record_saved: 'opgeslagen onder {n}',
    os_record_suite: 'VERDER',
    os_record_sansnom: 'kies je naam op het beginscherm om hem in de TOP 500 te zetten',

    // le record du monde qui tombe, et les piques qui l accompagnent
    wrm_titre: 'WERELDRECORD',
    wrm_sur: 'op {d} m',
    wrm_pris: 'afgepakt van {n} — {s} s sneller',
    wrm_pris_soi: 'zijn eigen record, met {s} s aangescherpt',
    wrm_defier: 'GA HET VERSLAAN',
    wrm_note_0: 'bericht aan de uitdagers: de lat ligt net hoger.',
    wrm_note_1: 'wil iemand antwoorden? We wachten.',
    wrm_note_2: 'de rest wordt vriendelijk verzocht harder te lopen.',
    wrm_note_3: 'deze tijd blijft nog wel even staan. Tenzij.',
    wrm_note_4: 'de top van het bord is van eigenaar gewisseld. Voorlopig.',
    wrm_note_5: 'feliciteren mag. Verslaan moet.',
    wrm_note_6: 'er staat een tijd om te verslaan. Niet de jouwe.',
    wrm_note_7: 'ergens heeft iemand net beter gelopen dan jij.',
    wrm_note_8: 'de baan is open. Het record een stuk minder.',
    wrm_note_9: 'lees de tijd gerust nog eens. Vanzelf beweegt hij niet.',
    wrm_note_10: 'twee opties: trainen, of eraan wennen.',
    wrm_note_11: 'een nieuwe naam bovenaan. De jouwe staat lager.',
    wrm_note_12: 'nog nooit iemand die een record verbrak door een melding te lezen.',
    wrm_note_13: 'zijn geest wacht in de TOP 500. Hij bijt niet.',
    wrm_note_14: 'het is maar een record. Records worden teruggepakt.',
    wrm_note_15: 'de blokken zijn vrij. Ik zeg maar wat.'
  },

  CUTS: {
    intro: [
      [ // etappe 1
        ['{n} wint al drie jaar elke wedstrijd op het schoolplein.',
         'Zijn geheim: niemand durft in te halen, de bal is van hem.',
         'Hij warmt op in schoolschoenen, uit principe.',
         'Zijn moeder filmt van achter het hek. Vooral het hek.'],
        ['{n} heeft het schoolrecord, met stift op de gymzaalmuur geschreven.',
         'Een klasgenoot klokte het, op een horloge met wijzers.',
         'De gymleraar knikte één keer. Daarmee was het officieel.',
         'Ze schilderen de muur nu rondom het record.'],
        ['{n} vroeg om baan 4. Hij kreeg baan 4.',
         'Hij doet zijn oefeningen: hoge knieën, hakken billen, diepe zuchten.',
         'Zijn startnummer is thuis geprint, een beetje scheef.',
         'Het nummer is 1. Hij heeft het zelf geprint, alleen.']
      ],
      [ // etappe 2
        ['{n} is al vier uur aan het opwarmen.',
         'Op zijn trainingspak staat zijn naam geborduurd, in hoofdletters.',
         'Hij heeft een ritueel: drie passen terug, één ademteug, een knipoog.',
         'De knipoog is voor niemand in het bijzonder.'],
        ['{n} komt aan met twee paar spikes en een koelbox.',
         'In de koelbox zitten een banaan en heel veel vastberadenheid.',
         'Hij zet zijn blokken op de millimeter, en zet ze dan opnieuw.',
         'En een derde keer. De starter wacht, beleefd.'],
        ['{n} werd vorig jaar tweede op het regionaal.',
         'Hij noemt het een zege die de tegenwind hem ontnam.',
         'De officiële meting gaf windstil. Hij betwist de meting.',
         'Hij nam zijn eigen windmeter mee. Bedienen kan hij hem niet.']
      ],
      [ // etappe 3
        ['{n} is op de regionale televisie geweest.',
         'Achtendertig seconden beeld. Hij keek ze zeshonderd keer terug.',
         'Hij deelt handtekeningen uit vóór de wedstrijd, om tijd te winnen.',
         'Op kassabonnen, bij gebrek aan beter.'],
        ['{n} heeft een bijnaam die niemand gebruikt: de Pijl van het Noorden.',
         'Hij schuift hem zelf in elk interview.',
         'De speaker kondigde hem net met zijn echte naam aan, per ongeluk.',
         'Hij heeft om een rectificatie via de omroep gevraagd. Die komt later.'],
        ['{n} liet zijn persoonlijk record op zijn onderarm tatoeëren.',
         'Hij toont het in slow motion tijdens de atletenpresentatie.',
         'Vier lopers in deze finale hebben dat getal al verbeterd.',
         'De tatoeage werkt zichzelf helaas niet bij.']
      ],
      [ // etappe 4
        ['{n} heeft een sponsor, een zaakwaarnemer en een fysiotherapeut.',
         'Alle drie zeggen dat hij onverslaanbaar is. Alle drie betaalt hij.',
         'Zijn zaakwaarnemer boekte de zaal voor de zegepersconferentie al.',
         'De catering is besteld. Er zijn hapjes.'],
        ['{n} is al elf maanden de nummer één van de wereld.',
         'Hij hoorde het live en heeft sindsdien nooit meer omgekeken.',
         'Letterlijk: zijn fysio raadde het hem sterk af.',
         'Nu draait hij zijn hele bovenlichaam. Trager, maar het staat goed.'],
        ['De speaker roept {n} af. Het stadion komt overeind.',
         'Hij wijst naar de tribune, dan naar de hemel, dan naar de camera.',
         'De camera stond op een andere atleet. Hij begint alles opnieuw.',
         'De regie geeft toe. Het gebaar gaat elf seconden duren.']
      ],
      [ // etappe 5
        ['{n} repeteert zijn viering al acht maanden.',
         'Hij liet hem als merk vastleggen. Hij hoeft alleen nog te winnen.',
         'Een koor van veertig mensen wacht op zijn teken.',
         'Ze leerden een lied. Het lied zegt zijn naam, uitvoerig.'],
        ['{n} draagt de kleuren van zijn land, en dat meent hij.',
         'De vlag staat op de spikes, op het nummer en op de handdoek.',
         'De handdoek loopt niet mee, maar ligt sinds dinsdag klaar.',
         'Een staflid draagt hem overal mee sinds de openingsceremonie.'],
        ['{n} zwoer dat hij in het blok niet naar zijn rivalen zou kijken.',
         'Dus staart hij recht vooruit, met opmerkelijke intensiteit.',
         'Iets te ver vooruit: bij de presentatie staarde hij naar de muur.',
         'De muur had zich niet voor deze finale geplaatst.']
      ],
      [ // etappe 6
        ['{n} komt uit een universum waar zwaartekracht optioneel is.',
         'Hij maakt zijn wedstrijden af voordat hij besluit ze te beginnen.',
         'Zijn record geldt in elf dimensies tegelijk.',
         'In de twaalfde struikelde hij, maar daar begint niemand over.'],
        ['{n} liep deze honderd meter in elf parallelle universa.',
         'Hij won ze alle elf. Het twaalfde werd nooit erkend.',
         'De finishrechter daar was een nevel, onbetrouwbaar op de streep.',
         'De nevel kreeg drie seizoenen schorsing.'],
        ['De familie ZEZE bezet alle zeven banen. Dat is reglementair.',
         'Ze brachten hun eigen starter, hun eigen wind, hun eigen finish mee.',
         'Het reglement is geschreven door een ZEZE en nagekeken door een ZEZE.',
         'Het is één zin lang: een ZEZE wint.']
      ]
    ],

    defeat: [
      [ // etappe 1
        ['{n} gaat tegen de uitslag in beroep bij de pleinwacht.',
         'De pleinwacht eet een boterham. De uitslag blijft staan.',
         'Daarna vraagt hij een oordeel aan de klassenvertegenwoordiger.',
         'De klassenvertegenwoordiger werd laatste. Hij geniet hiervan.'],
        ['{n} legt uit dat de ondergrond van het plein ongelijk is.',
         'Hij is voor iedereen ongelijk sinds negentienhonderdzestig.',
         'Dan noemt hij een losse veter. Zijn schoenen hebben klittenband.',
         'De leraar schrijft jouw tijd op de muur. Vlak boven de zijne.'],
        ['{n} kondigt aan dat hij niet echt aan het lopen was.',
         'Hij was aan het opwarmen. De echte wedstrijd was de volgende.',
         'Niemand was ingelicht, wat een hoop verklaart.',
         'De bel gaat. De volgende wedstrijd komt er nooit.']
      ],
      [ // etappe 2
        ['{n} legt uit dat zijn horloge nooit gestart is.',
         'Dus technisch gezien heeft deze wedstrijd nooit plaatsgevonden.',
         'Hij biedt aan hem meteen over te doen, onder serieuze mensen.',
         'Dan herinnert hij zich een trein. Hij heeft geen trein.'],
        ['{n} vraagt de finishfoto te zien.',
         'Men toont hem de foto. Duidelijk achter, en scherp in beeld.',
         'Hij vraagt dezelfde foto vanuit een andere hoek.',
         'Vanuit die hoek staat hij nog steeds achter, maar iets vager.'],
        ['{n} pakt beide paar spikes in zonder een woord.',
         'Hij kondigt een overstap naar de 400 aan, een tactischer nummer.',
         'Daarna de 800. Daarna de marathon, waar alles toch eindigt.',
         'Hij vertrekt met zijn koelbox. De banaan is onaangeroerd.']
      ],
      [ // etappe 3
        ['{n} kondigt live zijn afscheid aan.',
         'Dan bedenkt hij zich: maandag weer trainen.',
         'Hij merkt op dat juist die maandag erg vol zit.',
         'De maandag daarna trouwens ook.'],
        ['{n} eist een dopingtest voor de winnaar.',
         'Daarna een voor zichzelf, in het belang van de eerlijkheid.',
         'Beide zijn negatief. Dat vindt hij verdacht.',
         'Hij vraagt een derde test. Van de tijdwaarneming.'],
        ['{n} laat de journalisten zijn onderarm zien.',
         'Het getatoeëerde record is niet verschoven. Ook wat waard.',
         'Hij kondigt zes weken hoogtestage aan.',
         'De berg die hij koos is tweehonderd meter hoog.']
      ],
      [ // etappe 4
        ['{n} eist een tweede windmeting.',
         'De wind wordt opgeroepen. De wind verschijnt niet.',
         'De zegepersconferentie gaat toch door, afzeggen kan niet meer.',
         'De hapjes zijn uitstekend. Dat is ook iets.'],
        ['{n} staart twintig seconden naar het grote scherm.',
         'De uitslag verandert niet. Het scherm ook niet.',
         'Hij vraagt of het beeld live is. Men zegt van wel.',
         'Hij vraagt dan of er een vertraagd signaal is. Dat is er niet.'],
        ['In de mixed zone praat {n} over groei en over proces.',
         'Hij gebruikt het woord cyclus elf keer in twee minuten.',
         'Een journalist vraagt zijn tijd. Hij antwoordt: die tijd komt nog.',
         'Zijn tijd staat al achter hem op het bord, heel groot.']
      ],
      [ // etappe 5
        ['{n} doet zijn viering toch maar.',
         'Het publiek applaudisseert, uit beleefdheid.',
         'Het koor, slecht ingelicht, zet het lied in.',
         'Veertig mensen zingen zijn naam. Stilte was hem liever geweest.'],
        ['{n} maakt zijn ereronde met de vlag, zoals gepland.',
         'De winnaar maakt dezelfde ronde, de andere kant op.',
         'Ze passeren elkaar twee keer. De tweede keer is erger.',
         'De handdoek zag het niet aankomen.'],
        ['{n} stapt op de tweede trede van het podium.',
         'Hij feliciteert de winnaar met een zeer lange handdruk.',
         'Lang genoeg om de officiële foto drie keer over te doen.',
         'Op de derde lacht hij. Je ziet wat het hem kost.']
      ],
      [ // etappe 6
        ['{n} herberekent de baan van zijn melkweg.',
         'Die liep toevallig precies door de tweede plaats.',
         'Hij noemt een tijdanomalie, en dan een probleem met zijn schoenen.',
         'De twee verklaringen spreken elkaar tegen. Hij houdt ze allebei.'],
        ['{n} vraagt de uitslagen van de elf andere universa.',
         'In alle elf heeft hij zojuist ook verloren. Gelijktijdig.',
         'Hij biedt aan een twaalfde te openen, gewoon om te kijken.',
         'De twaalfde is bezet. Daar werd jij ook eerste.'],
        ['De zes andere ZEZE kijken heel rustig naar {n}.',
         'Niemand zegt een woord. De stilte duurt vier lichtjaren.',
         '{n} oppert uiteindelijk: de ondergrond was vandaag anders.',
         'De ondergrond is niet veranderd sinds de baan is aangelegd.']
      ]
    ],

    taunt: [
      [ // etappe 1
        ['{n} wijst naar het scorebord, zonder een woord.',
         'Hij heeft het al gesigneerd. Met permanente stift.',
         'Hij geeft je zijn boterham. "Voor onderweg", zegt hij.',
         'Je had niet om een boterham gevraagd.'],
        ['{n} maakt een ereronde. Drie meter, bij gebrek aan ruimte.',
         'Hij zwaait uitvoerig naar een denkbeeldig publiek.',
         'Hij biedt je een revanche aan. Dan kijkt hij op zijn horloge.',
         'Hij heeft geen horloge. Het gebaar zei genoeg.'],
        ['{n} pakt rustig zijn spullen in, fluitend.',
         'De melodie is jouw naam, op de maat van een zegemars.',
         'Hij klopt je op de schouder. "Volgende keer", zegt hij.',
         'Hij gelooft het geen seconde, en dat zie je.']
      ],
      [ // etappe 2
        ['{n} kijkt naar de klok, en dan naar jou, met een blik.',
         'Hij zegt niets. De stilte is wreder dan woorden.',
         'Hij deelt handtekeningen uit. De eerste is voor jou.',
         'Daar had je ook niet om gevraagd.'],
        ['{n} belt zijn coach. "We zijn vroeg klaar", zegt hij.',
         'De coach vraagt waarom. "Uit beleefdheid", antwoordt hij.',
         'Hij laat je zijn medaille vasthouden. Heel even maar.',
         'Dat even duurt tien minuten. Hij maakt foto’s.'],
        ['{n} bergt zijn spikes op in een hoes met jouw naam erop.',
         'Het is een grap onder ons. Het publiek volgt niet.',
         'Hij biedt je water aan uit zijn bidon. Die is leeg.',
         'Het gebaar, zegt hij, telt zwaarder dan het water.']
      ],
      [ // etappe 3
        ['{n} zwaait naar de camera. Daarna zwaait hij naar jou.',
         'Het tweede zwaaien is merkbaar minder vriendelijk.',
         'Hij bespreekt jouw wedstrijd met verslaggevers, tot in detail.',
         'Zijn favoriete detail: het moment dat je omkeek.'],
        ['{n} vraagt de microfoon. Hij krijgt hem, tegen beter weten in.',
         'Hij bedankt zijn familie, zijn club en jou, in die volgorde.',
         '"Zonder hem", zegt hij, "had het niet hetzelfde gesmaakt".',
         'Hij zegt niet wat hij bedoelt. Dat hoeft ook niet.'],
        ['{n} biedt aan jouw wedstrijd samen rustig door te nemen.',
         'De analyse is één woord lang. Hij zegt het heel langzaam.',
         'Hij schudt je twee keer achter elkaar de hand, voor de zekerheid.',
         'De eerste keer leek niet overtuigend genoeg.']
      ],
      [ // etappe 4
        ['{n} geeft een interview. Het onderwerp ben jij, vreemd genoeg.',
         'Drie minuten. Niets over zijn eigen wedstrijd.',
         'Hij besluit met dat hij veel geleerd heeft. Van jouw nederlaag.',
         'De verslaggever schrijft het woord voor woord op, ongemakkelijk.'],
        ['{n} wenkt zijn zaakwaarnemer om een regel aan het palmares toe te voegen.',
         'De regel luidt eenvoudig: tegen jou, nog een keer.',
         'Hij nodigt je uit voor de zegepersconferentie.',
         'Een stoel wacht op je, helemaal achterin, zonder microfoon.'],
        ['{n} laat je de ranglijst op zijn telefoon zien, en zoomt in.',
         'Hij zoomt een hele tijd in. Jouw regel staat ver onder de zijne.',
         '"Ik kan hem je mailen", biedt hij behulpzaam aan.',
         'Je hebt hem je adres nooit gegeven. Hij heeft het al.']
      ],
      [ // etappe 5
        ['{n} zwaait naar de tribune, en draait zich dan plechtig naar jou.',
         'Wat hij daarna doet, staat in geen enkel reglement.',
         'Een verslaggever vraagt om een woord voor de verslagen rivaal.',
         'Hij geeft er zeven. Geen ervan haalt het artikel.'],
        ['{n} stapt op het podium, en dan één trede omlaag.',
         'Hij nodigt je uit de medaille van dichtbij te bekijken.',
         'Heel dichtbij. Hij is van goud. Daar hecht hij aan.',
         'Het volkslied begint. Hij zingt luid, kijkend naar jou.'],
        ['{n} draagt zijn zege op aan zijn familie, zijn sponsors en jou.',
         '"Zonder zo’n motiverende tegenstander", zegt hij, oprecht.',
         'Het woord motiverend klinkt als een goed vermomde belediging.',
         'Het publiek applaudisseert, zonder te weten waarom je rood wordt.']
      ],
      [ // etappe 6
        ['{n} kijkt naar de zes andere ZEZE. Ze knikken, tegelijk.',
         'Het oordeel is unaniem, en valt zonder één geluid.',
         'Er wordt een gedenkplaat gegraveerd, in een dode taal.',
         'Er staat, kort gezegd: hij heeft het geprobeerd. Ook wat waard.'],
        ['{n} herberekent jouw positie in elf verschillende dimensies.',
         'In elke ervan is de uitslag identiek, tot op de seconde.',
         'Hij geeft je een kaart van het universum waarin jij had gewonnen.',
         'Dat universum, merkt hij op, bestaat nog niet.'],
        ['{n} steekt zijn hand naar de hemel. Een melkweg licht op, gehoorzaam.',
         'Even vormt hij de omtrek van zijn glimlach.',
         'De zeven ZEZE overleggen, en draaien zich dan naar jou.',
         'De stilte die volgt duurt vier lichtjaren. Beleefd.']
      ]
    ],

    champion: [
      ['De zeven ZEZE overleggen uitvoerig.',
       'Geen van hen vindt een aanvaardbaar excuus. Dat is een primeur.',
       'De ranglijst wordt bijgewerkt in veertien miljard stelsels.',
       'Er wordt een plaquette bij de finish gelegd.',
       'Jouw naam staat er verkeerd op, maar hij staat er.'],
      ['De speaker zoekt een woord. Geen enkel is groot genoeg.',
       'Hij leest gewoon de tijd voor, twee keer, voor de zekerheid.',
       'Zeven ZEZE staren zwijgend naar het grote scherm.',
       'Er wordt een commissie gevormd om de finishlijn te controleren.',
       'De lijn is recht. De ranglijst ook.'],
      ['De ereronde duurt langer dan de wedstrijd zelf.',
       'Dat is simpele rekenkunde, en niemand klaagt.',
       'Iemand geeft je een vlag. Je kunt de melkweg niet plaatsen.',
       'Hij komt uit allemaal: de ontwerpen zijn voor de gelegenheid samengevoegd.',
       'Het koor heeft zijn lied herschreven. Het zegt eindelijk jouw naam.']
    ]
  }
};
