/* -----------------------------------------------------------------------
   SPRINTER — polski.
   Ce qui manque ici retombe sur l'anglais, cle par cle : voir
   sprinter-i18n.js. Verification : node tools/langues-verifier.mjs pl
   ----------------------------------------------------------------------- */
export default {
  // Po polsku liczebnik porządkowy zapisuje się z kropką: 1., 2., 3.
  ord(n) { return n + '.'; },

  LEVEL_NAMES: [
    'Zawody szkolne', 'Poziom regionalny', 'Poziom krajowy',
    'Mistrzostwa świata', 'Igrzyska światowe', 'Międzygalaktyczny'
  ],

  RACE_SUB: {
    '100': 'prosta',
    '200': 'wiraż i prosta',
    '400': 'jedno okrążenie'
  },

  UI: {
    races: '100 - 200 - 400 METRÓW',
    tagline: 'sześć etapów, jeden czas do pobicia',
    tap_start: 'dotknij ekranu, aby zacząć',
    six_stages: '   -   sześć etapów',
    six_stages_bare: 'sześć etapów',
    best_runs: 'NAJLEPSZE PRZEBIEGI',
    no_run: 'żaden przebieg jeszcze nieukończony',
    furthest: 'najdalszy etap: ',
    of_six: ' z 6',
    start: 'START',
    sound: 'dźwięk: ',
    yes: 'tak',
    no: 'nie',

    rival: 'RYWAL DO POKONANIA',
    favourite: 'Faworyt',
    after_race: 'PO BIEGU',
    crowned: 'TYTUŁ MIĘDZYGALAKTYCZNY',
    fastest_1: 'NAJSZYBSZA ISTOTA',
    fastest_2: 'WSZYSTKICH GALAKTYK',
    full_run_in: 'cały przebieg w ',
    announced: 'ogłoszony czas: ',
    stage_up: 'ETAP ',
    six_cleared: 'SZEŚĆ ETAPÓW ZALICZONYCH',
    skip_now: 'dotknij ponownie, aby pominąć',
    skip_twice: 'dotknij dwa razy, aby pominąć',

    reaction: 'REAKCJA',
    react_top: 'IDEALNA REAKCJA',
    false_start: 'ZA WCZESNY START',
    wait_gun: 'czekaj na strzał',
    phase_drive: 'ROZBIEG',
    phase_trans: 'PRZEJŚCIE',
    phase_max: 'PRĘDKOŚĆ MAKSYMALNA',
    drive_hint: 'złap swój rytm',
    trans_2: 'IDEALNE PRZEJŚCIE',
    trans_1: 'DOBRE PRZEJŚCIE',
    trans_0: 'NIEUDANE PRZEJŚCIE',
    start_line: 'start: {r} s reakcji   -   {g}',
    no_start: 'start nieudany',

    stumble: 'POTYKASZ SIĘ',
    to_beat: 'do pobicia: ',
    to_race: 'biegniesz przeciwko ',
    ready: 'NA MIEJSCA',
    get_set: 'GOTOWI',
    go: 'START',
    alternate: 'naprzemiennie oba przyciski',
    alternate_kb: 'naprzemiennie obie strzałki',
    you: 'TY',
    opponent: 'RYWAL',
    depart: 'START',
    arrivee: 'META',

    stage_done: 'ETAP {n} ZALICZONY',
    first_in: '1. miejsce w ',
    total_of: ' s   -   łącznie ',
    place: '{o} MIEJSCE',
    dnf: 'nie ukończył',
    unfinished: 'nieukończone',
    race_again: 'JESZCZE RAZ?',
    next_stage: 'ETAP {n}',
    home: 'MENU',
    replay: 'ZAGRAJ PONOWNIE',
    run_done: 'PRZEBIEG UKOŃCZONY',
    six_in: 'sześć etapów zaliczonych w ',
    stage_low: 'etap ',

    new_record: 'NOWY REKORD',
    top3: 'TOP 3',
    top10: 'TOP 10',
    best_run: 'NAJLEPSZY PRZEBIEG',
    top3_runs: 'TOP 3 PRZEBIEGÓW',
    top10_runs: 'TOP 10 PRZEBIEGÓW',

    top500: 'TOP 500 - WSZECH CZASÓW',
    your_name: 'twoje imię',
    save_score: 'ZAPISZ MÓJ CZAS',
    saving_score: 'wysyłanie...',
    score_saved: '{r} w światowym TOP 500',
    score_save_fail: 'wysyłka nieudana, spróbuj później',
    score_name_taken: 'to imię należy do innego urządzenia',
    score_taken_help: 'wybierz inne albo połącz to urządzenie ze swoim imieniem w MOJE BIEGI za pomocą kodu odzyskiwania',
    view_top500: 'ZOBACZ TOP 500',
    top500_court: 'TOP 500',
    close: 'ZAMKNIJ',
    loading_ranks: 'wczytywanie rankingu...',
    empty_top500: 'brak zapisanych czasów',
    your_rank: 'TWOJE MIEJSCE: {r}',
    outside_top500: 'poza top 500',
    edit_name: 'ZMIEŃ IMIĘ',
    best_split_short: 'najlepszy etap:',
    top500_sub: 'najlepszy czas w jednym biegu',
    cat_race: 'WEDŁUG BIEGU',
    cat_run: 'CAŁY PRZEBIEG',
    cat_mine: 'MOJE BIEGI',
    cat_mine_sub: 'wszystkie biegi, które przebiegłeś',
    mine_empty: 'brak biegów w tej konkurencji',
    mine_count: '{n} biegów — najlepszy: {s} s',
    mine_note: 'TOP 500 zachowuje tylko twój najlepszy czas w konkurencji; ta historia zachowuje wszystko. Zarezerwuj swoje imię, aby odnaleźć ją na innych urządzeniach.',

    duel_title: 'RANKING POJEDYNKÓW',
    duel_sub: 'wyzwania wysłane i przyjęte',
    duel_open: 'ZOBACZ RANKING POJEDYNKÓW',
    duel_rules_init: 'WYZWANIE WYSŁANE',
    duel_rules_recv: 'WYZWANIE PRZYJĘTE',
    duel_rules_line: 'wygrana {v}   ·   przegrana {d}   ·   remis {n}',
    duel_rules_all: 'liczy się każdy pojedynek, wysłany czy przyjęty',
    duel_rules_why: 'kto wyzywa, ten pierwszy pokazuje swój czas',
    duel_counts: '{l} wysłanych · {r} przyjętych',
    duel_sur: 'POJEDYNEK ROZGRYWANY NA',

    name_set: 'WYBIERZ IMIĘ',
    name_title: 'TWOJE IMIĘ',
    name_why: 'to ono widnieje w TOP 500, na twoich wyzwaniach i w pojedynkach',
    name_save: 'ZAPISZ',
    name_saved: 'ZAPISANE',
    name_taken: 'to imię jest już zajęte',
    name_code: 'TWÓJ KOD ODZYSKIWANIA',
    pays_title: 'TWOJA NARODOWOŚĆ',
    pays_opt: 'tylko raz',
    pays_aucun: 'wybierz kraj',
    pays_why: 'jest potrzebna do mistrzostw krajowych — i później nie da się jej zmienić',
    pays_vu: 'wygląda na to, że łączysz się z {pays} — decyzja należy do ciebie',
    pays_save: 'WYBIERZ',
    pays_confirm: 'Startować dla {pays}?\n\nTo ostateczne: decyduje, do jakich mistrzostw krajowych trafisz, i nie da się tego zmienić.',
    pays_fige: 'ostateczne',
    pays_on: 'startujesz dla tego kraju — twoja flaga towarzyszy imieniu na mistrzostwach',
    pays_deja: 'narodowość jest już wybrana i nie da się jej zmienić',
    pays_first: 'najpierw zapisz swoje imię',
    pays_bad: 'nieprawidłowy kraj',
    insta_title: 'TWÓJ INSTAGRAM',
    insta_ph: 'twoja nazwa, bez @',
    insta_why: 'twój profil staje się dostępny z TOP 500 i z twoich wyzwań',
    insta_note: 'podane przez ciebie, niezweryfikowane — Instagram nie pozwala już na prawdziwe logowanie kontem prywatnym',
    insta_link: 'POŁĄCZ MOJE KONTO',
    insta_linked: 'KONTO POŁĄCZONE',
    insta_unlink: 'ODŁĄCZ',
    insta_on: 'twój profil widnieje w TOP 500 — dotknij, aby otworzyć',
    insta_gone: 'konto odłączone, twój profil nigdzie już nie widnieje',
    insta_bad: 'nieprawidłowa nazwa',
    insta_first: 'najpierw zapisz swoje imię',
    insta_notyours: 'to imię nie należy do ciebie na tym urządzeniu',
    insta_visit: 'zobacz profil {n} na Instagramie',
    name_code_why: 'zapisz go: przywraca twoje imię i biegi na innym telefonie',

    tour_open: 'ZOBACZ PRZEWODNIK',
    tour_1_t: 'NA ZMIANĘ',
    tour_1_s: 'lewa, prawa, lewa. Cały bieg to tyle.',
    tour_2_t: 'KARIERA',
    tour_2_s: 'sześć etapów, od szkolnego boiska po finał międzygalaktyczny',
    tour_3_t: 'TOP 500',
    tour_3_s: 'twój czas przeciwko całemu światu',
    tour_4_t: 'DUCH',
    tour_4_s: 'wyślij swój bieg koledze — pobiegnie przeciwko tobie',
    tour_5_t: 'NA ŻYWO',
    tour_5_s: 'ten sam strzał, każdy na swoim telefonie',
    tour_play: 'CHCĘ GRAĆ',

    os_tuto_open: 'PO CO JEST TEN TRYB',
    os_tuto_1_t: 'WYBIERZ KONKURENCJE',
    os_tuto_2_t: 'TYLKO JEDNA PRÓBA',
    os_tuto_3_t: 'TWÓJ CZAS SIĘ LICZY',
    os_tuto_1_s: 'jedna, dwie albo wszystkie trzy',
    os_tuto_2_s: 'bez powtórki, bez eliminacji',
    os_tuto_3_s: 'TOP 500, a kolega może to podjąć',
    os_tuto_go: 'ZACZNIJ ONE SHOT',

    tuto_ask_t: 'PIERWSZY BIEG',
    tuto_ask_s: 'ruchu uczysz się w trzydzieści sekund',
    tuto_ask_yes: 'NAUCZ MNIE RUCHU',
    tuto_ask_no: 'CHCĘ BIEC',
    tuto_watch: 'PATRZ',
    tuto_your_turn: 'TWOJA KOLEJ',
    tuto_1_t: 'NA ZMIANĘ',
    tuto_2_t: 'NA STRZAŁ',
    tuto_3_t: 'SZEROKO, POTEM KRÓTKO',
    tuto_v_early: 'ZA WCZEŚNIE',
    tuto_v_late: 'za późno',
    tuto_v_perfect: 'IDEALNIE',
    tuto_v_good: 'DOBRZE',
    tuto_v_slow: 'ZA WOLNO',
    tuto_v_flat: 'PŁASKI RYTM',
    tuto_replay_demo: 'obejrzyj ponownie',
    tuto_again: 'JESZCZE RAZ',
    tuto_next: 'DALEJ',
    tuto_done_t: 'TERAZ TY BIEGNIESZ',
    tuto_start: 'START',
    tuto_replay: 'obejrzyj ponownie',
    tuto_skip: 'pomiń',
    tuto_open: 'JAK GRAĆ',

    live_title: 'BIEG NA ŻYWO',
    live_desc: 'startujecie obaj na ten sam strzał, każdy na swoim telefonie — bez ducha, nikt nie wie, kto wygra',
    live_create: 'OTWÓRZ TOR',
    live_join: 'DOŁĄCZ',
    live_or: 'albo',
    live_room: 'TOR OTWARTY',
    live_waiting: 'wyślij ten kod rywalowi — bieg zaczyna się, gdy będzie was dwóch',
    live_ready: 'GOTOWY',
    live_notready: 'JESZCZE NIE',
    live_empty_seat: 'tor wolny — czeka na rywala',
    live_go: 'JESTEM GOTOWY',
    live_unready: 'ANULUJ',
    live_leave: 'opuść tor',
    live_none: 'brak toru o tym kodzie',
    live_full: 'ten tor jest już pełny',
    live_gone: 'twój rywal opuścił tor',
    live_closed: 'połączenie zostało zerwane',
    live_invite: 'Czekam na ciebie na torze. Kod {c} — {l}',

    relais_titre: 'SZTAFETA 4 × 100',
    relais_desc: 'czterech biegaczy, jedna pałeczka. Drużyna to jej skład: te same cztery imiona, ta sama drużyna.',
    relais_invitations: 'MASZ ZAPROSZENIE',
    relais_mes_equipes: 'TWOJE DRUŻYNY',
    relais_creer: 'ZŁÓŻ DRUŻYNĘ',
    relais_nom_equipe: 'nazwa drużyny',
    relais_coequipier: 'partner {n}',
    relais_inviter: 'ZAPROŚ TROJE',
    relais_incomplet: 'brakuje nazwy i trzech partnerów',
    relais_attend: 'oczekuje',
    relais_ok: 'w składzie',
    relais_refuse: 'odmówił',
    relais_fixer_ordre: 'USTAL KOLEJNOŚĆ BIEGU',
    relais_manque_reponses: 'brakuje jeszcze odpowiedzi, zanim będzie można biec',
    relais_manque_refus: 'partner odmówił — ta drużyna nie może biec',
    relais_prete: 'drużyna gotowa',
    relais_classement: 'KLASYFIKACJA DRUŻYN',
    relais_plein_titre: 'DWIE DRUŻYNY, NIE TRZY',
    relais_plein: 'biegasz już dla dwóch drużyn. Opuść tę, dla której już nie biegasz, aby złożyć kolejną.',
    relais_plein_invit: 'biegasz już dla dwóch drużyn — opuść jedną, aby to przyjąć.',
    relais_quitter: 'OPUŚĆ',
    relais_quitter_sur: 'opuścić na zawsze?',
    relais_quitter_sub: 'wracasz tylko z nowym zaproszeniem',
    relais_reste: 'zostało jedno miejsce',
    relais_place: '1 z 2 drużyn',
    relais_places: '{n} z 2 drużyn',
    relais_courir: 'NA TOR',
    relais_mon_rang: 'biegniesz {n}. zmianę',
    relais_premier: 'startujesz z bloków, stojąc. Falstart eliminuje całą drużynę.',
    relais_ta_marque: 'TWÓJ ZNAK W STREFIE',
    relais_zone_debut: 'wejście',
    relais_zone_fin: 'wyjście',
    relais_marque_conseil: 'dalej z przodu ruszasz szybciej, ale możesz opuścić strefę przed pałeczką. Dalej z tyłu odbierzesz ją na pewno — z miejsca.',
    relais_attend_equipe: 'brakuje jeszcze {n} partnerów',
    relais_temoin_a: 'PAŁECZKA U',
    relais_spectateur: 'POZOSTALI BIEGNĄ',
    relais_porte: 'NIESIE',
    relais_attends_temoin: 'CZEKAJ',
    relais_prends: 'ODBIERZ PAŁECZKĘ',
    relais_donne: 'PODAJ PAŁECZKĘ',
    relais_arrivee: 'SZTAFETA UKOŃCZONA',
    relais_elimine: 'DRUŻYNA WYELIMINOWANA',
    relais_elimine_pourquoi: 'na zmianie {r}: {c}',
    relais_passages: 'TRZY ZMIANY',
    relais_elimine_court: 'poza',
    relais_fantome: 'DUCH',

    conf_titre: 'BIEGNIJ PRZECIWKO INNYM DRUŻYNOM',
    conf_desc: 'jeden strzał, jedna kolejność na mecie. Otwórz kod i udostępnij go albo wpisz ten, który dostałeś.',
    conf_ouvrir: 'OTWÓRZ KONFRONTACJĘ',
    conf_rejoindre: 'DOŁĄCZ',
    conf_code: 'kod',
    conf_code_court: 'ten kod jest za krótki',
    conf_partage: 'UDOSTĘPNIJ TEN KOD POZOSTAŁYM DRUŻYNOM',
    conf_places: '{n} drużyn na torze',
    conf_engagees: '{n} Z {m} DRUŻYN',
    conf_attend_adversaire: 'potrzebna jest co najmniej jeszcze jedna drużyna albo duch',
    conf_classement: 'KOLEJNOŚĆ NA MECIE',
    conf_encore: 'pozostali jeszcze biegną',

    fantome_titre: 'RZUĆ WYZWANIE DZIESIĘCIU NAJLEPSZYM PRZEBIEGOM',
    fantome_desc: 'zostały już przebiegnięte: powtarzają się i nie można ich wyeliminować ani pokonać na zmianie. To jedyny sposób, by zmierzyć się z najlepszymi bez zbierania ośmiu osób.',
    fantome_aucun: 'brak zapisanych przebiegów — pierwsza drużyna, która ukończy sztafetę, otwiera bal.',
    fantome_choisis: 'wybrano {n} z {m}',
    fantome_defier: 'RZUĆ IM WYZWANIE',

    champ_directs: 'awansuje {n} pierwszych',
    champ_reveal: 'NAJSZYBSI PRZEGRANI',
    champ_reveal_desc: 'nie wygrali żadnego biegu. Wychodzą z czasu wszystkich biegów.',
    champ_continue: 'DALEJ',
    champ_sacre: '{n} zostaje mistrzem — zobacz podium',
    champ_titre_duree: 'tytuł na trzy miesiące',
    champ_rv_course: 'NASTĘPNY BIEG',
    champ_rv_reveal: 'NAJSZYBSI PRZEGRANI UJAWNIENI',
    champ_rv_sacre: 'CEREMONIA',
    champ_quitter: 'opuść mistrzostwa',

    live_lanes: 'TORY',
    live_lanes_duel: 'pojedynek: zwycięzca bierze punkty, przegrany kilka oddaje',
    live_lanes_course: 'bieg: kolejność na mecie, bez punktów w rankingu pojedynków',
    live_won: 'BIEG WYGRANY',
    live_sur: 'Z {n} STARTUJĄCYCH',
    live_ordre: 'KOLEJNOŚĆ NA MECIE',
    live_lost: 'BIEG PRZEGRANY',

    pres_title: 'PREZENTACJA ZAWODNIKÓW',
    pres_lane: 'TOR',
    pres_you: 'TO TY',
    pres_mic_on: 'MIKROFON WŁĄCZONY',
    pres_mic_off: 'mikrofon odrzucony',
    mic_winner: 'MÓWI ZWYCIĘZCA',

    review_title: 'NAGRANIE TWOJEGO BIEGU',
    review_making: 'nagrywanie…',
    review_dl: 'POBIERZ',
    review_left: 'zostanie usunięte za {t}',
    review_gone: 'nagranie zostało usunięte',
    review_kept: 'to, co pobrałeś, zostaje na twoim telefonie',
    review_none: 'to urządzenie nie może nagrać biegu',
    live_tie: 'REMIS NA MECIE',
    live_vs: 'na żywo przeciwko {n}',
    live_gap: 'różnica {s} s',
    link_in_app: 'GRA ZAINSTALOWANA?',
    link_in_app_sub: 'otwórz ją z ekranu głównego i wpisz ten kod — dotknij, aby skopiować',

    duel_answered: 'TWOJE WYZWANIE ZOSTAŁO PRZYJĘTE',
    duel_more: 'jeszcze {n} wynik czeka',
    duel_mores: 'jeszcze {n} wyników czeka',
    duel_next: 'DALEJ',
    duel_ok: 'ROZUMIEM',

    ghost_mode: 'TRYB DUCHA',
    ghost_ahead: 'PRZED',
    ghost_behind: 'ZA',
    ghost_level: 'RÓWNO',
    ghost_home: 'duch minął metę',
    ghost_live: 'duch biegnie obok ciebie',
    duel_must: 'wyślij wyzwanie albo odpowiedz na wyzwanie kolegi',
    duel_empty: 'brak rozegranych pojedynków',
    duel_pts: 'pkt',

    monde_sprinter_sous: 'prosta i okrążenie',
    monde_hurdlers_sous: 'ten sam tor, z dziesięcioma przeszkodami',
    monde_jumper_sous: 'zbuduj rozbieg i oderwij się od ziemi',
    monde_thrower_sous: 'koło, przyrząd i całe ciało',
    monde_bientot: 'WKRÓTCE',
    monde_retour: 'POWRÓT DO SPRINTERA',

    disc_100: '100 METRÓW',
    disc_200: '200 METRÓW',
    disc_400: '400 METRÓW',
    disc_100h: '100 M PRZEZ PŁOTKI',
    disc_110h: '110 M PRZEZ PŁOTKI',
    disc_400h: '400 M PRZEZ PŁOTKI',
    disc_longueur: 'SKOK W DAL',
    disc_hauteur: 'SKOK WZWYŻ',
    disc_triple: 'TRÓJSKOK',
    disc_perche: 'SKOK O TYCZCE',
    disc_poids: 'PCHNIĘCIE KULĄ',
    disc_marteau: 'RZUT MŁOTEM',
    disc_disque: 'RZUT DYSKIEM',
    disc_javelot: 'RZUT OSZCZEPEM',

    pique_0: 'Nawet nie musiałem się starać.',
    pique_1: 'powtórzyć w zwolnionym tempie?',
    pique_2: 'zdążyłem się znudzić.',
    pique_3: 'meta jest po tej stronie.',
    pique_4: 'dzięki za rozgrzewkę.',
    pique_5: 'obejrzałem się i nikogo nie było.',
    pique_6: 'biegłeś? nic nie widziałem.',
    pique_7: 'zachowaj ten czas, będzie miła pamiątka.',

    mot_titre: 'ZOSTAW {n} PARĘ SŁÓW',
    mot_placeholder: 'ukłuj go w dwóch linijkach',
    mot_vocal: 'GŁOS',
    mot_ecouter: 'ODSŁUCHAJ',
    mot_refaire: 'nagraj ponownie',
    mot_envoyer: 'WYŚLIJ',
    mot_envoye: '{n} przeczyta to po powrocie',
    mot_micro_refuse: 'mikrofon został odrzucony — tekst też wystarczy',
    mot_ecouter_sa_voix: 'POSŁUCHAJ, CO POWIEDZIAŁ',
    mot_ephemere: 'to nagranie znika po zamknięciu tego okna',
    mot_illisible: 'ta wiadomość nie odtworzy się na tym urządzeniu',

    mod_signaler: 'zgłoś',
    mod_titre: 'Dlaczego to zgłaszasz?',
    mod_explique: 'Zgłoszenie czyta człowiek. Blokada działa natychmiast.',
    mod_insulte: 'obelga',
    mod_haine: 'nienawiść, rasizm',
    mod_sexuel: 'treść seksualna',
    mod_menace: 'groźba',
    mod_autre: 'inne',
    mod_envoye: 'Zgłoszone. Ktoś to przeczyta.',
    mod_deja: 'już zgłoszone',
    mod_bloquer: 'zablokuj {n}',
    mod_bloque: '{n} nie może już do ciebie pisać.',
    mod_annuler: 'anuluj',

    duel_revanche: 'CHCĘ REWANŻU',
    duel_revanche_sub: 'ta sama konkurencja — teraz ty ustalasz czas',
    duel_renvoyer: 'odeślij kod do {n}',
    duel_revanche_envoyee: 'REWANŻ WYSŁANY',
    os_revanche_sans_cible: 'nie udało się powiadomić {n} — wyślij kod samodzielnie',
    duel_revanche_ratee_titre: 'JESZCZE NIE',
    duel_revanche_ratee: 'potrzebowałeś poniżej {s} s, aby odesłać wyzwanie do {n} — nic nie poszło',

    rang_departemental: 'POWIATOWA',
    rang_regional: 'REGIONALNA',
    rang_national: 'KRAJOWA',
    rang_elite: 'ELITA',
    rang_legende: 'LEGENDA',
    rang_court_departemental: 'POW',
    rang_court_regional: 'REG',
    rang_court_national: 'KRA',
    rang_court_elite: 'ELITA ',
    rang_court_legende: 'LEGENDA',
    duel_lp: 'PL',
    duel_monte_a11y: 'awans o {n} miejsc',
    duel_descend_a11y: 'spadek o {n} miejsc',
    duel_lp_long: 'punkty ligowe',
    duel_promu: 'AWANS DO {r}',
    duel_relegue: 'SPADEK DO {r}',
    duel_reste: '{n} do następnej dywizji',
    duel_regle: 'przyjęcie wyzwania daje więcej niż jego wysłanie: czas już jest na tablicy i wiesz, co masz pobić.',
    duel_record: '{v}Z · {d}P · {n}R',
    duel_you: 'TY',
    duel_since: 'od twojej ostatniej wizyty',
    duel_unranked: 'jeszcze bez miejsca — rozegraj pojedynek',
    duel_won: 'POJEDYNEK WYGRANY',
    duel_lost: 'POJEDYNEK PRZEGRANY',
    duel_tie: 'REMIS',
    duel_final: 'wynik ostateczny — wyzwania nie powtarza się',
    duel_delta: '{p} punkt',
    duel_deltas: '{p} punktów',

    false_out: 'FALSTART',
    false_out_sub: 'wyeliminowany — pojedynek przegrany',
    false_out_seul: 'wyeliminowany — ten bieg kończy się tutaj',
    false_out_rule: 'tylko jeden bieg, bez drugiej szansy',
    false_out_libre: 'możesz przebiec go ponownie',
    false_out_gun: 'ruszyłeś przed strzałem',
    duel_await: 'wynik pojedynku…',
    duel_vs: 'przeciwko {n}',
    duel_seen: 'pojedynek już rozstrzygnięty',
    duel_see: 'ZOBACZ RANKING',

    os_once: 'gdy wyzwanie zostanie wysłane, czas jest ostateczny',
    os_rejouer: 'BIEGNIJ PONOWNIE',
    os_rejouer_sub: 'jeszcze jeden bieg, teraz — ten zostaje bez zmian',
    os_defier: 'RZUĆ KOMUŚ WYZWANIE',
    os_defier_sub: 'otwórz ranking i wybierz rywala — innego albo tego samego',
    relance_gagne_0: 'WEŹ SIĘ ZA KOLEJNEGO',
    relance_gagne_0_sub: 'ten załatwiony. Następny.',
    relance_gagne_1: 'NASTĘPNY, PROSZĘ',
    relance_gagne_1_sub: 'ranking jest pełen ludzi, a ty jesteś w gazie.',
    relance_gagne_2: 'KTO JESZCZE?',
    relance_gagne_2_sub: 'zapytaj ranking. Ktoś odpowie.',
    relance_perdu_0: 'WEŹ SIĘ ZA MNIEJSZEGO',
    relance_perdu_0_sub: 'zejdź o dywizję — nikt nie musi wiedzieć',
    relance_perdu_1: 'ZNAJDŹ KOGOŚ WOLNIEJSZEGO',
    relance_perdu_1_sub: 'istnieją. Statystycznie istnieją.',
    relance_perdu_2: 'SĄ JESZCZE POCZĄTKUJĄCY',
    relance_perdu_2_sub: 'niczego nie podejrzewają. To ten moment.',
    os_defi_sans_cible: '{n} nie ma w TOP 500 tej konkurencji — wyślij kod samodzielnie',
    os_verrou_direct: 'bieg na żywo: twój rywal biegł w tej samej chwili — ten wynik obowiązuje',
    os_verrou_recu: 'ten czas trafił już do rywala — nie da się go cofnąć',
    os_verrou_envoye: 'wyzwanie wysłane — taki czas ma do pobicia',
    os_verrou_faux: 'falstart w pojedynku: bieg przegrany. Wyślij nowe wyzwanie, aby zacząć od nowa.',
    cut_skip: 'POMIŃ',

    id_title: 'TWOJE IMIĘ',
    id_code_title: 'KOD ODZYSKIWANIA',
    id_code_note: 'zapisz go: łączy twoje inne urządzenia z tym imieniem i chroni je przed przejęciem',
    id_show: 'POKAŻ MÓJ KOD',
    id_reserve: 'ZAREZERWUJ',
    id_taken: 'to imię jest już zajęte',
    id_taken_help: 'jeśli jest twoje, wpisz jego kod odzyskiwania',
    id_link: 'POŁĄCZ',
    id_linked: 'urządzenie połączone z {n}',
    id_bad_code: 'błędny kod',
    id_unknown: 'nieznane imię',
    id_link_title: 'INNE URZĄDZENIE?',
    id_link_help: 'wpisz imię i kod, aby odnaleźć tutaj swoje czasy i historię',

    install_title: 'ZAINSTALUJ GRĘ',
    install_why: 'pełny ekran, bez paska przeglądarki, i gra bez internetu',
    install_do: 'ZAINSTALUJ',
    install_later: 'później',
    install_ios_1: 'Dotknij',
    install_ios_2: 'Udostępnij',
    install_ios_3: 'na dole w Safari, a potem',
    install_ios_4: 'Do ekranu początkowego',

    mode_career_s: 'kariera',
    mode_oneshot_s: 'one shot',
    cat_race_sub: 'najlepszy czas w jednym biegu',
    cat_run_sub: 'suma sześciu etapów',
    empty_cat_run: 'brak zapisanych pełnych przebiegów',
    will_enter: '{s} s: {r} w TOP 500, wpisz swoje imię',

    wr_title: 'REKORD ŚWIATA',
    wr_sub: 'najlepszy czas świata na {d} m',
    wr_old: 'poprzedni rekord: {s} s',
    wr_first: 'pierwszy czas na tablicy',
    wr_gain: 'szybciej o {s} s',
    wr_save: 'WPISZ MOJE IMIĘ',
    wr_saving: 'zapisywanie...',
    wr_done: '{n} jest {r} w TOP 500',
    wr_fail: 'wysyłka nieudana, spróbuj ponownie',
    wr_see: 'ZOBACZ TOP 500',
    wr_later: 'później',
    top500_count: '{n} czasów w rankingu z 500',

    pause_title: 'BIEG WSTRZYMANY',
    pause_note: 'wyjście teraz oznacza rezygnację z bieżącego czasu',
    resume: 'WZNÓW',

    challenge_them: 'WYZWIJ',
    target_run: 'przebiegnij swoje {d} m: wyzwanie idzie do {n}',
    target_sent: 'wyzwanie wysłane do {n}',
    inbox_one: 'OTRZYMANE WYZWANIE',
    inbox_many: 'OTRZYMANE WYZWANIA: {n}',
    inbox_from: '{n} wyzywa cię na {d} m',
    inbox_accept: 'PRZYJMIJ',
    inbox_later: 'później',
    run_total_short: 'cały przebieg:',
    run_total_tiny: 'przebieg',
    best_split_tiny: 'bieg',
    score_saved_race: '{r} w światowym TOP 500 z czasem {s} s',
    mode_career: 'KARIERA',
    mode_oneshot: 'ONE SHOT',
    mode_versus: 'WYZWANIE',
    career_desc: 'sześć etapów pod rząd, jeden czas',
    oneshot_desc: 'wybierz konkurencje, jedna próba',
    versus_desc: 'biegnij przeciwko duchowi innego gracza',
    pick_events: 'KONKURENCJE',
    pick_level: 'POZIOM',
    pick_none: 'wybierz co najmniej jedną konkurencję',
    launch_oneshot: 'START',
    event_n: 'KONKURENCJA {n} / {t}',
    next_event: 'NASTĘPNA KONKURENCJA',
    oneshot_done: 'ONE SHOT UKOŃCZONY',
    total_in: 'łącznie: ',
    challenge_code: 'KOD WYZWANIA',
    challenge_enter: 'wpisz kod, który dostałeś',
    challenge_load: 'WCZYTAJ',
    challenge_loading: 'wczytywanie wyzwania...',
    challenge_bad: 'nie znaleziono kodu',
    challenge_net: 'błąd połączenia, spróbuj ponownie',
    challenge_from: 'wyzwanie od {n}',
    challenge_beat: 'do pobicia: {s} s',
    challenge_aveugle: 'jego czas poznasz w biegu',
    challenge_accept: 'PRZYJMIJ WYZWANIE',
    challenge_make: 'WYZWIJ KOLEGĘ',
    challenge_making: 'tworzenie wyzwania...',
    challenge_share: 'wyślij ten kod, kolega pobiegnie przeciwko twojemu duchowi',
    challenge_copy: 'KOPIUJ LINK',
    challenge_copied: 'link skopiowany',
    challenge_copy_code: 'KOPIUJ KOD',
    share_send: 'WYŚLIJ WYZWANIE',
    share_whatsapp: 'WhatsApp',
    share_sms: 'SMS',
    share_other: 'Snapchat, Instagram…',
    share_other_hint: 'Snapchat i Instagram otwierają się z menu udostępniania.',
    affiche_share: 'UDOSTĘPNIJ MÓJ PRZEBIEG',
    affiche_making: 'Tworzenie obrazu…',
    affiche_saved: 'obraz zapisany',
    affiche_failed: 'nie udało się utworzyć obrazu',
    affiche_hint: 'obraz twojego przebiegu, na Instagram albo TikTok',
    code_copied: 'kod skopiowany',
    challenge_rematch: 'ODEŚLIJ WYZWANIE',
    challenge_rematch_sub: 'wygrałeś — wyzwij go na przebieg, który właśnie zrobiłeś',
    challenge_won: 'WYZWANIE WYGRANE',
    challenge_lost: 'WYZWANIE PRZEGRANE',
    challenge_gap: 'różnica: {s} s',
    ghost_label: 'DUCH',
    you_label: 'TY',
    dnf_short: 'DNF',
    composing: 'komponowanie ścieżki dźwiękowej...',

    sound_off: 'DŹWIĘK WYŁĄCZONY  (S)',
    press_enter: 'naciśnij ENTER',
    skip_now_kb: 'naciśnij ENTER ponownie, aby pominąć',
    skip_twice_kb: 'naciśnij ENTER dwa razy, aby pominąć',
    stage_dash: 'ETAP {n}   -   {s}',
    furthest_kb: 'najdalszy osiągnięty etap: {a} z {b}',
    enter_start: 'ENTER: start   -   S: dźwięk   -   L: język   -   ESC: wyjście',
    how_to_play: 'JAK GRAĆ',
    help_1: 'Naprzemiennie  <-  i  ->  bez',
    help_2: 'powtarzania tego samego klawisza.',
    help_3: 'Równy rytm buduje prędkość;',
    help_4: 'powtórzenie sprawia, że się potykasz,',
    help_5: 'ale zawsze możesz ruszyć od nowa.',
    best_stage: 'NAJLEPSZE CZASY TEGO ETAPU',
    no_time: 'brak zapisanych czasów',
    arrows_pick: 'strzałki, aby wybrać   -   ENTER, aby zatwierdzić   -   ',
    yn_short: 'skrót T / N',
    you_beat: 'Pokonałeś {w} i zaliczyłeś wszystkie sześć etapów.',
    the_zeze: 'ZEZE',
    your_times: 'TWOJE CZASY',
    total: 'ŁĄCZNIE',
    enter_replay: 'ENTER: biegnij ponownie      M: menu',
    stumble_kb: 'POTYKASZ SIĘ!',
    go_kb: 'START!',
    to_beat_line: 'DO POBICIA:  {n}   -   {s} s',
    best_times_of: 'NAJLEPSZE CZASY  -  {s}',
    enter_next: 'ENTER   ->   ETAP {n}: {s}',
    full_run_pc: 'cały przebieg w {s} s',
    announced_pc: 'ogłoszony czas: {s} s',
    quit: 'ESC: wyjście',

    // accueil : le nom, le drapeau, Instagram, un pas a la fois
    bienvenue_titre: 'WITAJ',
    bv_nom_t: 'TWOJE IMIĘ',
    bv_nom_s: 'towarzyszy każdemu twojemu czasowi',
    bv_pays_t: 'TWOJA FLAGA',
    bv_pays_s: 'do mistrzostw — ostatecznie',
    bv_insta_t: 'TWÓJ INSTAGRAM',
    bv_insta_s: 'dostępny z rankingu — podany, niezweryfikowany',
    bv_passer: 'pomiń',
    bv_suite: 'DALEJ',
    bienvenue_plus: 'PÓŹNIEJ',
    bienvenue_go: 'RUSZAMY',
    contact: 'KONTAKT',

    // la montee au classement, annoncee et lue a voix haute
    places_1: 'MIEJSCE',
    places_n: 'MIEJSC',
    classement_entree: 'WCHODZISZ DO RANKINGU',
    classement_bouge_a11y: '{n} miejsc w górę — {r} w {c}',
    classement_perd_a11y: '{n} miejsc w dół — {r} w {c}',
    classement_entre_a11y: 'wchodzisz do rankingu — {r} w {c}',

    // notifications
    avis_title: 'POWIADOMIENIA',
    avis_desc: 'dostać wiadomość przy zamkniętej grze',
    avis_pourquoi: 'wyzwanie, które przyszło w nocy, nic nie znaczy, jeśli znajdziesz je nazajutrz',
    avis_activer: 'WŁĄCZ POWIADOMIENIA',
    avis_couper: 'PRZESTAŃ OTRZYMYWAĆ',
    avis_actives: 'powiadomienia włączone',
    avis_essai: 'WYŚLIJ MI PRÓBNE',
    avis_essai_ok: 'wysłane — powinno dotrzeć w sekundę',
    avis_essai_ko: 'nic nie poszło: sprawdź, czy powiadomienia są dozwolone',
    avis_refuse: 'odrzuciłeś je: to otwiera się z powrotem w ustawieniach telefonu, nie tutaj',
    avis_installer: 'na iPhonie najpierw dodaj grę do ekranu początkowego: Safari daje je tylko zainstalowanym aplikacjom',
    avis_indispo: 'ta przeglądarka nie może ich odbierać',
    avis_erreur: 'serwer nie zdołał zapisać subskrypcji',
    avis_choisir: 'CO CHCĘ OTRZYMYWAĆ',
    avis_g_defi: 'Otrzymane wyzwanie',
    avis_g_defi_s: 'ktoś przysłał ci czas do pobicia',
    avis_g_selection: 'Powołanie na mistrzostwa',
    avis_g_selection_s: 'jesteś w gronie 32 biegaczy',
    avis_g_direct: 'Wyzwanie na żywo',
    avis_g_direct_s: 'ktoś czeka na torze, teraz',
    avis_g_relais: 'Zaproszenie do sztafety',
    avis_g_relais_s: 'drużyna chce ciebie',
    avis_g_rendezvous: 'Godziny biegów mistrzostw',
    avis_g_rendezvous_s: 'kwadrans przed każdym biegiem',
    avis_g_assister: 'Finały i to, kto je wygrywa',
    avis_g_assister_s: 'kwadrans wcześniej, a potem koronacja — nawet gdy cię tam nie ma',
    avis_g_record: 'Rekord świata, który pada',
    avis_g_record_s: 'pierwsze miejsce na dystansie zmienia właściciela',
    avis_suivre: 'KTÓRE MISTRZOSTWA',
    avis_suivre_national: 'mój kraj',
    avis_suivre_continental: 'mój kontynent',
    avis_suivre_mondial: 'mistrzostwa świata',
    avis_suivre_vide: 'zaznacz przynajmniej jedno, inaczej nic nie zostanie wysłane',
    avis_suivre_nom: 'zarezerwuj wyżej swoje imię, żeby znany był twój kraj',

    // inviter quelqu un sur la piste, par son nom
    live_inviter: 'ZAPROŚ GRACZA',
    live_inviter_ph: 'jego imię',
    live_inviter_ok: '{n} został powiadomiony — jego telefon dzwoni',
    live_inviter_ko: 'nikt o tym imieniu go nie zarezerwował: wyślij mu kod',
    live_invite_recue: '{n} czeka na ciebie na torze',
    live_invite_rejoindre: 'DOŁĄCZ',

    // suppression du profil
    id_del: 'USUŃ MÓJ PROFIL',
    id_del_what: 'twoje imię, twój kod, twoje czasy w rankingu, twoja historia w sieci, twoje wyzwania i pojedynki zostają usunięte z serwera, na wszystkich twoich urządzeniach.',
    id_del_keep: 'postęp kariery i biegi zapisane na tym urządzeniu pozostają nietknięte.',
    id_del_final: 'to ostateczne: nic z tego nie da się odzyskać.',
    id_del_confirm: 'wpisz {n}, aby potwierdzić',
    id_del_go: 'USUŃ',
    id_del_cancel: 'anuluj',
    id_del_done: 'profil usunięty',
    id_del_device: 'to imię nie było zarezerwowane: usunięto to, co pochodziło z tego urządzenia',
    id_del_code: 'to urządzenie nie jest połączone z tym imieniem: wpisz jego kod odzyskiwania',

    // le record personnel a la fin d un one shot
    os_record_titre: 'REKORD POBITY',
    os_record_titre_n: 'REKORDY POBITE',
    os_record_sur: 'na {d} m',
    os_record_premier: 'pierwszy czas na tym dystansie',
    os_record_gain: 'szybciej o {s} s',
    os_record_rang: '{r} w TOP 500 - WSZECH CZASÓW',
    os_record_saved: 'zapisane jako {n}',
    os_record_suite: 'DALEJ',
    os_record_sansnom: 'wybierz imię na ekranie głównym, aby wpisać je do TOP 500',

    // le record du monde qui tombe, et les piques qui l accompagnent
    wrm_titre: 'REKORD ŚWIATA',
    wrm_sur: 'na {d} m',
    wrm_pris: 'odebrany {n} — szybciej o {s} s',
    wrm_pris_soi: 'własny rekord, poprawiony o {s} s',
    wrm_defier: 'IDŹ GO POBIĆ',
    wrm_note_0: 'uwaga dla pretendentów: poprzeczka właśnie poszła w górę.',
    wrm_note_1: 'ktoś chce odpowiedzieć? Czekamy.',
    wrm_note_2: 'pozostałych uprzejmie prosimy o szybszy bieg.',
    wrm_note_3: 'ten czas postoi jeszcze chwilę. Chyba że.',
    wrm_note_4: 'szczyt tablicy zmienił właściciela. Na razie.',
    wrm_note_5: 'gratulacje są opcjonalne. Pobicie nie.',
    wrm_note_6: 'jest czas do pobicia. Nie twój.',
    wrm_note_7: 'gdzieś tam ktoś właśnie pobiegł lepiej od ciebie.',
    wrm_note_8: 'tor jest otwarty. Rekord znacznie mniej.',
    wrm_note_9: 'przeczytaj ten czas jeszcze raz, proszę bardzo. Sam się nie ruszy.',
    wrm_note_10: 'dwie możliwości: trenować albo się przyzwyczaić.',
    wrm_note_11: 'nowe imię na szczycie tablicy. Twoje jest niżej.',
    wrm_note_12: 'nikt nigdy nie pobił rekordu, czytając powiadomienie.',
    wrm_note_13: 'jego duch czeka w TOP 500. Nie gryzie.',
    wrm_note_14: 'to tylko rekord. Rekordy się odbiera.',
    wrm_note_15: 'bloki są wolne. Tak tylko mówię.'
  },

  CUTS: {
    intro: [
      [ // etap 1
        ['{n} od trzech lat wygrywa każdy bieg na boisku.',
         'Jego sekret: nikt nie śmie go wyprzedzić, piłka należy do niego.',
         'Rozgrzewa się w szkolnych butach, z zasady.',
         'Matka filmuje zza siatki. Głównie siatkę.'],
        ['{n} ma rekord szkoły, wypisany mazakiem na ścianie sali gimnastycznej.',
         'Zmierzył go kolega z klasy, zegarkiem ze wskazówkami.',
         'Nauczyciel WF-u kiwnął raz głową. To wystarczyło za urzędowe potwierdzenie.',
         'Teraz malują ścianę dookoła rekordu.'],
        ['{n} poprosił o tor 4. Dostał tor 4.',
         'Robi swoje ćwiczenia: kolana wysoko, pięty do pośladków, głębokie westchnienia.',
         'Numer startowy wydrukował w domu, lekko krzywo.',
         'Numer to 1. Wydrukował go sam, w pojedynkę.']
      ],
      [ // etap 2
        ['{n} rozgrzewa się od czterech godzin.',
         'Na plecach dresu ma wyszyte imię, wielkimi literami.',
         'Ma rytuał: trzy kroki w tył, jeden oddech, mrugnięcie.',
         'Mrugnięcie nie jest skierowane do nikogo konkretnego.'],
        ['{n} przychodzi z dwiema parami kolców i lodówką turystyczną.',
         'W lodówce jest banan i ogromna ilość determinacji.',
         'Ustawia bloki co do milimetra, a potem ustawia je od nowa.',
         'I trzeci raz. Starter czeka, uprzejmie.'],
        ['{n} był w zeszłym roku drugi na regionalnych.',
         'Opisuje to jako zwycięstwo skradzione przez wiatr pod nos.',
         'Oficjalny pomiar wykazał bezwietrznie. On kwestionuje pomiar.',
         'Przyniósł własny wiatromierz. Nie umie go obsłużyć.']
      ],
      [ // etap 3
        ['{n} był w telewizji regionalnej.',
         'Trzydzieści osiem sekund materiału. Obejrzał je sześćset razy.',
         'Rozdaje autografy przed biegiem, żeby zaoszczędzić czas.',
         'Na paragonach, z braku czegoś lepszego.'],
        ['{n} ma przydomek, którego nikt nie używa: Strzała Północy.',
         'Sam wciska go do każdego wywiadu.',
         'Spiker właśnie zapowiedział go prawdziwym nazwiskiem, przez pomyłkę.',
         'Poprosił o sprostowanie przez głośniki. Przyjdzie później.'],
        ['{n} wytatuował sobie rekord życiowy na przedramieniu.',
         'Pokazuje go w zwolnionym tempie podczas prezentacji zawodników.',
         'Czterech biegaczy w tym finale już pobiło tę liczbę.',
         'Tatuaż, niestety, sam się nie aktualizuje.']
      ],
      [ // etap 4
        ['{n} ma sponsora, menedżera i fizjoterapeutę.',
         'Wszyscy trzej mówią mu, że jest nie do pobicia. Wszystkim trzem płaci on.',
         'Menedżer zarezerwował już salę na konferencję zwycięstwa.',
         'Catering zamówiony. Są koreczki.'],
        ['{n} jest numerem jeden na świecie od jedenastu miesięcy.',
         'Dowiedział się na żywo i od tamtej pory nigdy nie obejrzał się za siebie.',
         'Dosłownie: fizjoterapeuta stanowczo mu to odradził.',
         'Teraz obraca cały tułów. Wolniej, ale wygląda to elegancko.'],
        ['Spiker zapowiada {n}. Stadion wstaje.',
         'Wskazuje trybunę, potem niebo, potem kamerę.',
         'Kamera była na innym zawodniku. Zaczyna wszystko od nowa.',
         'Reżyser ustępuje. Gest potrwa jedenaście sekund.']
      ],
      [ // etap 5
        ['{n} ćwiczy swoją radość od ośmiu miesięcy.',
         'Zastrzegł ją jako znak towarowy. Zostaje tylko wygrać bieg.',
         'Chór czterdziestu osób czeka na jego znak.',
         'Nauczyli się pieśni. Pieśń wymienia jego imię, obszernie.'],
        ['{n} nosi barwy swojego kraju i naprawdę mu na tym zależy.',
         'Flaga jest na kolcach, na numerze i na ręczniku.',
         'Ręcznik nie biegnie, ale czeka gotowy od wtorku.',
         'Ktoś ze sztabu nosi go wszędzie od ceremonii otwarcia.'],
        ['{n} przysiągł, że nie spojrzy na rywali w blokach.',
         'Więc patrzy prosto przed siebie, z niezwykłą intensywnością.',
         'Odrobinę za daleko: podczas prezentacji wpatrywał się w ścianę.',
         'Ściana nie zakwalifikowała się do tego finału.']
      ],
      [ // etap 6
        ['{n} pochodzi z wszechświata, w którym grawitacja jest opcjonalna.',
         'Kończy swoje biegi, zanim postanowi je zacząć.',
         'Jego rekord obowiązuje w jedenastu wymiarach naraz.',
         'W dwunastym się potknął, ale nikt tego nie porusza.'],
        ['{n} przebiegł te sto metrów w jedenastu równoległych wszechświatach.',
         'Wygrał wszystkie jedenaście. Dwunastego nigdy nie zatwierdzono.',
         'Sędzią na mecie była tam mgławica, zawodna na kresce.',
         'Mgławicę zawieszono na trzy sezony.'],
        ['Rodzina ZEZE zajmuje wszystkie siedem torów. To jest regulaminowe.',
         'Przywieźli własnego startera, własny wiatr i własną metę.',
         'Regulamin napisał ZEZE, a sprawdził go ZEZE.',
         'Ma długość jednego zdania: wygrywa ZEZE.']
      ]
    ],

    defeat: [
      [ // etap 1
        ['{n} odwołuje się od wyniku do dyżurnego na stołówce.',
         'Dyżurny je kanapkę. Wynik pozostaje.',
         'Potem prosi o rozstrzygnięcie gospodarza klasy.',
         'Gospodarz klasy był ostatni. Bardzo mu się to podoba.'],
        ['{n} tłumaczy, że nawierzchnia boiska jest nierówna.',
         'Jest nierówna dla wszystkich od tysiąc dziewięćset sześćdziesiątego.',
         'Potem wspomina o rozwiązanej sznurówce. Jego buty mają rzepy.',
         'Nauczyciel wypisuje twój czas na ścianie. Tuż nad jego.'],
        ['{n} ogłasza, że tak naprawdę nie biegł.',
         'Rozgrzewał się. Prawdziwy bieg miał być następny.',
         'Nikt nie został o tym uprzedzony, co wiele wyjaśnia.',
         'Dzwoni dzwonek. Następny bieg nigdy się nie odbędzie.']
      ],
      [ // etap 2
        ['{n} tłumaczy, że jego zegarek w ogóle nie ruszył.',
         'Więc technicznie rzecz biorąc ten bieg nigdy się nie odbył.',
         'Proponuje powtórkę natychmiast, między poważnymi ludźmi.',
         'Potem przypomina sobie o pociągu. Nie ma żadnego pociągu.'],
        ['{n} prosi o zdjęcie z fotokomórki.',
         'Pokazują mu zdjęcie. Wyraźnie z tyłu i doskonale ostry.',
         'Prosi o to samo zdjęcie pod innym kątem.',
         'Pod tym kątem nadal jest z tyłu, tylko trochę bardziej rozmyty.'],
        ['{n} pakuje obie pary kolców bez słowa.',
         'Ogłasza przejście na 400, konkurencję bardziej taktyczną.',
         'Potem 800. Potem maraton, gdzie i tak wszystko się kończy.',
         'Odchodzi ze swoją lodówką. Banan nietknięty.']
      ],
      [ // etap 3
        ['{n} ogłasza zakończenie kariery na żywo.',
         'Potem zmienia zdanie: w poniedziałek wraca na treningi.',
         'Zauważa, że akurat ten poniedziałek jest wyjątkowo zajęty.',
         'Kolejny poniedziałek, jak się okazuje, również.'],
        ['{n} domaga się kontroli antydopingowej dla zwycięzcy.',
         'Potem także dla siebie, w imię uczciwości.',
         'Obie wychodzą negatywnie. Uważa to za podejrzane.',
         'Prosi o trzecią kontrolę. Sprzętu do pomiaru czasu.'],
        ['{n} pokazuje dziennikarzom przedramię.',
         'Wytatuowany rekord nie drgnął. Zawsze coś.',
         'Ogłasza sześć tygodni zgrupowania na wysokości.',
         'Góra, którą wybrał, ma dwieście metrów.']
      ],
      [ // etap 4
        ['{n} domaga się drugiego pomiaru wiatru.',
         'Wiatr zostaje wezwany. Wiatr się nie stawia.',
         'Konferencja zwycięstwa odbywa się mimo wszystko, nie da się jej odwołać.',
         'Koreczki są znakomite. To zawsze coś.'],
        ['{n} wpatruje się w telebim przez dwadzieścia sekund.',
         'Klasyfikacja się nie zmienia. Telebim też nie.',
         'Pyta, czy obraz jest na żywo. Słyszy, że tak.',
         'Pyta więc, czy jest sygnał opóźniony. Nie ma.'],
        ['W strefie mieszanej {n} mówi o rozwoju i o procesie.',
         'Używa słowa cykl jedenaście razy w dwie minuty.',
         'Dziennikarz pyta o jego czas. Odpowiada: czas jeszcze przyjdzie.',
         'Jego czas widnieje już za nim na tablicy, bardzo dużymi cyframi.']
      ],
      [ // etap 5
        ['{n} i tak wykonuje swoją radość.',
         'Publiczność bije brawo, z uprzejmości.',
         'Chór, źle poinformowany, zaczyna pieśń.',
         'Czterdzieści osób śpiewa jego imię. Wolałby ciszę.'],
        ['{n} robi rundę honorową z flagą, zgodnie z planem.',
         'Zwycięzca robi tę samą rundę, w przeciwną stronę.',
         'Mijają się dwa razy. Drugi raz jest gorszy.',
         'Ręcznik tego nie przewidział.'],
        ['{n} wchodzi na drugi stopień podium.',
         'Gratuluje zwycięzcy bardzo długim uściskiem dłoni.',
         'Dość długim, by oficjalne zdjęcie powtarzano trzy razy.',
         'Na trzecim się uśmiecha. Widać, ile go to kosztuje.']
      ],
      [ // etap 6
        ['{n} przelicza trajektorię swojej galaktyki.',
         'Przechodziła akurat dokładnie przez drugie miejsce.',
         'Powołuje się na anomalię czasową, a potem na problem z butami.',
         'Obie wersje są sprzeczne. Zatrzymuje obie.'],
        ['{n} prosi o klasyfikacje z jedenastu innych wszechświatów.',
         'We wszystkich jedenastu również właśnie przegrał. Jednocześnie.',
         'Proponuje otworzyć dwunasty, tak tylko, żeby zobaczyć.',
         'Dwunasty jest zajęty. Tam też byłeś pierwszy.'],
        ['Pozostałych sześciu ZEZE patrzy na {n} bardzo spokojnie.',
         'Nikt nie mówi ani słowa. Cisza trwa cztery lata świetlne.',
         '{n} w końcu proponuje: dzisiaj nawierzchnia była inna.',
         'Nawierzchnia nie zmieniła się od czasu budowy bieżni.']
      ]
    ],

    taunt: [
      [ // etap 1
        ['{n} wskazuje tablicę wyników, bez słowa.',
         'Już ją podpisał. Markerem nie do zmycia.',
         'Podaje ci swoją kanapkę. "Na drogę", mówi.',
         'Nie prosiłeś o żadną kanapkę.'],
        ['{n} robi rundę honorową. Trzy metry, z braku miejsca.',
         'Długo macha wyimaginowanej publiczności.',
         'Proponuje ci rewanż. Potem patrzy na zegarek.',
         'Nie ma zegarka. Gest powiedział wszystko.'],
        ['{n} spokojnie pakuje swoje rzeczy, pogwizdując.',
         'Melodia to twoje imię, w rytmie marsza triumfalnego.',
         'Klepie cię po ramieniu. "Następnym razem", mówi.',
         'Nie wierzy w to ani przez sekundę, i widać to.']
      ],
      [ // etap 2
        ['{n} patrzy na zegar, a potem na ciebie, znacząco.',
         'Nic nie mówi. Cisza jest okrutniejsza niż słowa.',
         'Rozdaje autografy. Pierwszy jest dla ciebie.',
         'O to też nie prosiłeś.'],
        ['{n} dzwoni do trenera. "Skończyliśmy wcześniej", mówi.',
         'Trener pyta dlaczego. "Z uprzejmości", odpowiada.',
         'Pozwala ci potrzymać swój medal. Tylko chwilę.',
         'Chwila trwa dziesięć minut. Robi zdjęcia.'],
        ['{n} chowa kolce do pokrowca z twoim imieniem.',
         'To wewnętrzny żart. Publiczność nie nadąża.',
         'Częstuje cię wodą ze swojego bidonu. Bidon jest pusty.',
         'Gest, mówi, liczy się bardziej niż woda.']
      ],
      [ // etap 3
        ['{n} macha do kamery. Potem macha do ciebie.',
         'Drugie machnięcie jest wyraźnie mniej serdeczne.',
         'Omawia twój bieg z dziennikarzami, szczegółowo.',
         'Jego ulubiony szczegół: moment, w którym się obejrzałeś.'],
        ['{n} prosi o mikrofon. Dostaje go, wbrew rozsądkowi.',
         'Dziękuje rodzinie, klubowi i tobie, w tej kolejności.',
         '"Bez niego", mówi, "nie smakowałoby tak samo".',
         'Nie mówi, co ma na myśli. Nie musi.'],
        ['{n} proponuje, żeby spokojnie przeanalizować twój bieg razem.',
         'Analiza ma długość jednego słowa. Wypowiada je bardzo powoli.',
         'Ściska ci dłoń dwa razy pod rząd, dla pewności.',
         'Za pierwszym razem wydało mu się to mało przekonujące.']
      ],
      [ // etap 4
        ['{n} udziela wywiadu. Tematem jesteś, o dziwo, ty.',
         'Trzy minuty. Ani słowa o własnym biegu.',
         'Kończy stwierdzeniem, że wiele się nauczył. Z twojej porażki.',
         'Dziennikarz zapisuje to słowo w słowo, z zażenowaniem.'],
        ['{n} daje znak menedżerowi, by dopisał linijkę do dorobku.',
         'Linijka brzmi po prostu: przeciwko tobie, znowu.',
         'Zaprasza cię na konferencję zwycięstwa.',
         'Czeka na ciebie krzesło, na samym końcu, bez mikrofonu.'],
        ['{n} pokazuje ci klasyfikację na telefonie, powiększając.',
         'Powiększa dłuższą chwilę. Twoja linijka jest daleko pod jego.',
         '"Mogę ci to wysłać mailem", proponuje usłużnie.',
         'Nigdy nie podałeś mu adresu. On już go ma.']
      ],
      [ // etap 5
        ['{n} macha do trybun, a potem odwraca się do ciebie, uroczyście.',
         'To, co robi potem, nie figuruje w żadnym regulaminie.',
         'Dziennikarz prosi o słowo dla pokonanego rywala.',
         'Mówi siedem. Żadne nie trafi do artykułu.'],
        ['{n} wchodzi na podium, a potem schodzi o stopień niżej.',
         'Zaprasza cię, byś obejrzał medal z bliska.',
         'Z bardzo bliska. Jest złoty. Kładzie na to nacisk.',
         'Zaczyna się hymn. Śpiewa głośno, patrząc na ciebie.'],
        ['{n} dedykuje zwycięstwo rodzinie, sponsorom i tobie.',
         '"Bez tak motywującego rywala", mówi szczerze.',
         'Słowo motywujący brzmi jak zręcznie ukryta obelga.',
         'Publiczność bije brawo, nie rozumiejąc, czemu się czerwienisz.']
      ],
      [ // etap 6
        ['{n} patrzy na pozostałych sześciu ZEZE. Kiwają głowami, razem.',
         'Werdykt jest jednogłośny i zapada bez jednego dźwięku.',
         'Zostaje wygrawerowana tablica pamiątkowa, w martwym języku.',
         'Głosi mniej więcej: próbował. To już coś.'],
        ['{n} przelicza twoją pozycję w jedenastu różnych wymiarach.',
         'W każdym wynik jest identyczny, co do sekundy.',
         'Wręcza ci mapę wszechświata, w którym byś wygrał.',
         'Ten wszechświat, zaznacza, jeszcze nie istnieje.'],
        ['{n} wyciąga rękę ku niebu. Galaktyka zapala się, posłusznie.',
         'Przez chwilę układa się w kształt jego uśmiechu.',
         'Siedmiu ZEZE naradza się, a potem odwraca do ciebie.',
         'Cisza, która następuje, trwa cztery lata świetlne. Uprzejmie.']
      ]
    ],

    champion: [
      ['Siedmiu ZEZE naradza się długo.',
       'Żaden nie znajduje wymówki do przyjęcia. To pierwszy raz.',
       'Klasyfikacja zostaje zaktualizowana w czternastu miliardach układów.',
       'Na linii mety zostaje położona tablica.',
       'Twoje imię jest na niej z błędem, ale jest.'],
      ['Spiker szuka słowa. Żadne nie jest dość wielkie.',
       'Po prostu odczytuje czas, dwa razy, dla pewności.',
       'Siedmiu ZEZE wpatruje się w telebim bez słowa.',
       'Powołana zostaje komisja do sprawdzenia linii mety.',
       'Linia jest prosta. Klasyfikacja również.'],
      ['Runda honorowa trwa dłużej niż sam bieg.',
       'To zwykła arytmetyka i nikt nie narzeka.',
       'Ktoś podaje ci flagę. Nie wiesz, z jakiej galaktyki pochodzi.',
       'Pochodzi ze wszystkich: wzory połączono na tę okazję.',
       'Chór przepisał swoją pieśń. Wymienia wreszcie twoje imię.']
    ]
  }
};
