/* -----------------------------------------------------------------------
   SPRINTER — português (brasileiro).
   Ce qui manque ici retombe sur l'anglais, cle par cle : voir
   sprinter-i18n.js. Verification : node tools/langues-verifier.mjs pt
   ----------------------------------------------------------------------- */
export default {
  ord(n, feminine) { return n + (feminine ? 'ª' : 'º'); },

  LEVEL_NAMES: [
    'Torneio escolar', 'Nível regional', 'Nível nacional',
    'Campeonato Mundial', 'Jogos Olímpicos', 'Intergaláctico'
  ],

  RACE_SUB: {
    '100': 'a reta',
    '200': 'curva e reta',
    '400': 'uma volta na pista'
  },

  UI: {
    races: '100 - 200 - 400 METROS',
    tagline: 'seis etapas, um só tempo a bater',
    tap_start: 'toque na tela para começar',
    six_stages: '   -   seis etapas',
    six_stages_bare: 'seis etapas',
    best_runs: 'MELHORES PERCURSOS',
    no_run: 'nenhum percurso concluído ainda',
    furthest: 'etapa mais distante: ',
    of_six: ' de 6',
    start: 'COMEÇAR',
    sound: 'som: ',
    yes: 'sim',
    no: 'não',

    rival: 'O CORREDOR A BATER',
    favourite: 'O favorito',
    after_race: 'DEPOIS DA CORRIDA',
    crowned: 'TÍTULO INTERGALÁCTICO',
    fastest_1: 'O SER MAIS RÁPIDO',
    fastest_2: 'DE TODAS AS GALÁXIAS',
    full_run_in: 'percurso completo em ',
    announced: 'tempo anunciado: ',
    stage_up: 'ETAPA ',
    six_cleared: 'SEIS ETAPAS VENCIDAS',
    skip_now: 'toque de novo para pular',
    skip_twice: 'toque duas vezes para pular',

    reaction: 'REAÇÃO',
    react_top: 'REAÇÃO PERFEITA',
    false_start: 'SAIU CEDO DEMAIS',
    wait_gun: 'espere o tiro',
    phase_drive: 'IMPULSÃO',
    phase_trans: 'TRANSIÇÃO',
    phase_max: 'VELOCIDADE MÁXIMA',
    drive_hint: 'firme sua cadência',
    trans_2: 'TRANSIÇÃO PERFEITA',
    trans_1: 'BOA TRANSIÇÃO',
    trans_0: 'TRANSIÇÃO FALHADA',
    start_line: 'largada: {r} s de reação   -   {g}',
    no_start: 'largada perdida',

    stumble: 'VOCÊ TROPEÇA',
    to_beat: 'a bater: ',
    to_race: 'você corre contra ',
    ready: 'ÀS SUAS MARCAS',
    get_set: 'PREPARAR',
    go: 'JÁ',
    alternate: 'alterne os dois botões',
    alternate_kb: 'alterne as duas setas',
    you: 'VOCÊ',
    opponent: 'ADVERSÁRIO',
    depart: 'LARGADA',
    arrivee: 'CHEGADA',

    stage_done: 'ETAPA {n} VENCIDA',
    first_in: '1º lugar em ',
    total_of: ' s   -   total ',
    place: '{o} LUGAR',
    dnf: 'abandono',
    unfinished: 'não concluído',
    race_again: 'DE NOVO?',
    next_stage: 'ETAPA {n}',
    home: 'INÍCIO',
    replay: 'JOGAR DE NOVO',
    run_done: 'PERCURSO CONCLUÍDO',
    six_in: 'seis etapas vencidas em ',
    stage_low: 'etapa ',

    new_record: 'NOVO RECORDE',
    top3: 'TOP 3',
    top10: 'TOP 10',
    best_run: 'MELHOR PERCURSO',
    top3_runs: 'TOP 3 DE PERCURSOS',
    top10_runs: 'TOP 10 DE PERCURSOS',

    top500: 'TOP 500 - DE TODOS OS TEMPOS',
    your_name: 'seu nome',
    save_score: 'SALVAR MEU TEMPO',
    saving_score: 'enviando...',
    score_saved: '{r} no TOP 500 mundial',
    score_save_fail: 'falha no envio, tente mais tarde',
    score_name_taken: 'este nome pertence a outro aparelho',
    score_taken_help: 'escolha outro, ou ligue este aparelho ao seu nome em MINHAS CORRIDAS com seu código de recuperação',
    view_top500: 'VER O TOP 500',
    top500_court: 'TOP 500',
    close: 'FECHAR',
    loading_ranks: 'carregando a classificação...',
    empty_top500: 'nenhum tempo registrado ainda',
    your_rank: 'SUA POSIÇÃO: {r}',
    outside_top500: 'fora do top 500',
    edit_name: 'MUDAR O NOME',
    best_split_short: 'melhor etapa:',
    top500_sub: 'melhor tempo em uma única corrida',
    cat_race: 'POR CORRIDA',
    cat_run: 'PERCURSO COMPLETO',
    cat_mine: 'MINHAS CORRIDAS',
    cat_mine_sub: 'todas as corridas que você fez',
    mine_empty: 'nenhuma corrida nesta prova ainda',
    mine_count: '{n} corridas — melhor: {s} s',
    mine_note: 'O TOP 500 guarda apenas seu melhor tempo por prova; este histórico guarda tudo. Reserve seu nome para encontrá-lo nos seus outros aparelhos.',

    duel_title: 'CLASSIFICAÇÃO DE DUELOS',
    duel_sub: 'desafios enviados e respondidos',
    duel_open: 'VER A CLASSIFICAÇÃO DE DUELOS',
    duel_rules_init: 'DESAFIO ENVIADO',
    duel_rules_recv: 'DESAFIO RESPONDIDO',
    duel_rules_line: 'vitória {v}   ·   derrota {d}   ·   empate {n}',
    duel_rules_all: 'todos os duelos contam, enviados ou respondidos',
    duel_rules_why: 'enviar um desafio é mostrar seu tempo primeiro',
    duel_counts: '{l} enviados · {r} respondidos',
    duel_sur: 'O DUELO É CORRIDO EM',

    name_set: 'ESCOLHA SEU NOME',
    name_title: 'SEU NOME',
    name_why: 'é o que aparece no TOP 500, nos seus desafios e nos duelos',
    name_save: 'SALVAR',
    name_saved: 'SALVO',
    name_taken: 'esse nome já está em uso',
    name_code: 'SEU CÓDIGO DE RECUPERAÇÃO',
    pays_title: 'SUA NACIONALIDADE',
    pays_opt: 'apenas uma vez',
    pays_aucun: 'escolha seu país',
    pays_why: 'você precisa dela para correr um campeonato nacional — e depois não dá para mudar',
    pays_vu: 'parece que você se conecta do {pays} — você decide',
    pays_save: 'ESCOLHER',
    pays_confirm: 'Correr pelo {pays}?\n\nÉ definitivo: decide em qual campeonato nacional você entra, e não pode ser mudado.',
    pays_fige: 'definitivo',
    pays_on: 'você corre por este país — sua bandeira acompanha seu nome no campeonato',
    pays_deja: 'sua nacionalidade já foi escolhida, não pode ser mudada',
    pays_first: 'salve seu nome primeiro',
    pays_bad: 'país inválido',
    insta_title: 'SEU INSTAGRAM',
    insta_ph: 'seu usuário, sem o @',
    insta_why: 'seu perfil fica acessível pelo TOP 500 e pelos seus desafios',
    insta_note: 'declarado por você, sem verificação — o Instagram não permite mais um login real para conta pessoal',
    insta_link: 'LIGAR MINHA CONTA',
    insta_linked: 'CONTA LIGADA',
    insta_unlink: 'DESLIGAR',
    insta_on: 'seu perfil aparece no TOP 500 — toque para abrir',
    insta_gone: 'conta desligada, seu perfil não aparece mais em lugar nenhum',
    insta_bad: 'usuário inválido',
    insta_first: 'salve seu nome primeiro',
    insta_notyours: 'este nome não é seu neste aparelho',
    insta_visit: 'ver o perfil de Instagram de {n}',
    name_code_why: 'anote: ele recupera seu nome e suas corridas em outro celular',

    tour_open: 'FAZER O TOUR',
    tour_1_t: 'ALTERNE',
    tour_1_s: 'esquerda, direita, esquerda. A corrida é só isso.',
    tour_2_t: 'A CARREIRA',
    tour_2_s: 'seis etapas, do pátio da escola à final intergaláctica',
    tour_3_t: 'O TOP 500',
    tour_3_s: 'seu tempo contra o mundo inteiro',
    tour_4_t: 'O FANTASMA',
    tour_4_s: 'mande sua corrida a um amigo — ele corre contra você',
    tour_5_t: 'AO VIVO',
    tour_5_s: 'o mesmo tiro, cada um no seu celular',
    tour_play: 'DEIXA EU JOGAR',

    os_tuto_open: 'PARA QUE SERVE ESTE MODO',
    os_tuto_1_t: 'ESCOLHA SUAS PROVAS',
    os_tuto_2_t: 'UMA TENTATIVA SÓ',
    os_tuto_3_t: 'SEU TEMPO CONTA',
    os_tuto_1_s: 'uma, duas ou as três',
    os_tuto_2_s: 'sem repetir, sem eliminação',
    os_tuto_3_s: 'TOP 500, e um amigo pode encarar',
    os_tuto_go: 'COMEÇAR UM ONE SHOT',

    tuto_ask_t: 'PRIMEIRA CORRIDA',
    tuto_ask_s: 'o gesto se aprende em trinta segundos',
    tuto_ask_yes: 'APRENDER O GESTO',
    tuto_ask_no: 'DEIXA EU CORRER',
    tuto_watch: 'OLHE',
    tuto_your_turn: 'SUA VEZ',
    tuto_1_t: 'ALTERNE',
    tuto_2_t: 'NO TIRO',
    tuto_3_t: 'AMPLO, DEPOIS CURTO',
    tuto_v_early: 'CEDO DEMAIS',
    tuto_v_late: 'tarde demais',
    tuto_v_perfect: 'PERFEITO',
    tuto_v_good: 'BOM',
    tuto_v_slow: 'NÃO É RÁPIDO O BASTANTE',
    tuto_v_flat: 'RITMO CHAPADO',
    tuto_replay_demo: 'ver de novo',
    tuto_again: 'DE NOVO',
    tuto_next: 'PRÓXIMO',
    tuto_done_t: 'SUA VEZ DE CORRER',
    tuto_start: 'COMEÇAR',
    tuto_replay: 'ver de novo',
    tuto_skip: 'pular',
    tuto_open: 'COMO JOGAR',

    live_title: 'CORRIDA AO VIVO',
    live_desc: 'vocês dois largam no mesmo tiro, cada um no seu celular — sem fantasma, ninguém sabe quem ganha',
    live_create: 'ABRIR UMA PISTA',
    live_join: 'ENTRAR',
    live_or: 'ou',
    live_room: 'PISTA ABERTA',
    live_waiting: 'mande este código ao seu adversário — a corrida começa quando vocês forem dois',
    live_ready: 'PRONTO',
    live_notready: 'AINDA NÃO',
    live_empty_seat: 'raia livre — esperando um adversário',
    live_go: 'ESTOU PRONTO',
    live_unready: 'CANCELAR',
    live_leave: 'sair da pista',
    live_none: 'nenhuma pista com esse código',
    live_full: 'essa pista já está cheia',
    live_gone: 'seu adversário saiu da pista',
    live_closed: 'a conexão caiu',
    live_invite: 'Estou te esperando na pista. Código {c} — {l}',

    relais_titre: 'REVEZAMENTO 4 × 100',
    relais_desc: 'quatro corredores, um bastão. Uma equipe é sua escalação: os mesmos quatro nomes, a mesma equipe.',
    relais_invitations: 'VOCÊ FOI CONVIDADO',
    relais_mes_equipes: 'SUAS EQUIPES',
    relais_creer: 'MONTAR UMA EQUIPE',
    relais_nom_equipe: 'nome da equipe',
    relais_coequipier: 'companheiro {n}',
    relais_inviter: 'CONVIDAR OS TRÊS',
    relais_incomplet: 'faltam um nome e três companheiros',
    relais_attend: 'pendente',
    relais_ok: 'dentro',
    relais_refuse: 'recusou',
    relais_fixer_ordre: 'DEFINIR A ORDEM DE CORRIDA',
    relais_manque_reponses: 'ainda faltam respostas antes de poder correr',
    relais_manque_refus: 'um companheiro recusou — esta equipe não pode correr',
    relais_prete: 'equipe pronta',
    relais_classement: 'CLASSIFICAÇÃO POR EQUIPES',
    relais_plein_titre: 'DUAS EQUIPES, NÃO TRÊS',
    relais_plein: 'você já corre por duas equipes. Deixe aquela em que não corre mais para montar outra.',
    relais_plein_invit: 'você já corre por duas equipes — deixe uma para aceitar isto.',
    relais_quitter: 'SAIR',
    relais_quitter_sur: 'sair de vez?',
    relais_quitter_sub: 'você só volta com um novo convite',
    relais_reste: 'resta uma vaga',
    relais_place: '1 de 2 equipes',
    relais_places: '{n} de 2 equipes',
    relais_courir: 'IR PARA A PISTA',
    relais_mon_rang: 'você corre a {n}ª perna',
    relais_premier: 'você larga do bloco, de pé. Uma queima elimina a equipe inteira.',
    relais_ta_marque: 'SUA MARCA NA ZONA',
    relais_zone_debut: 'dentro',
    relais_zone_fin: 'fora',
    relais_marque_conseil: 'mais à frente você sai mais rápido, mas pode deixar a zona antes do bastão. Mais atrás você recebe com certeza — parado.',
    relais_attend_equipe: 'falta(m) {n} companheiro(s)',
    relais_temoin_a: 'BASTÃO EM',
    relais_spectateur: 'OS OUTROS ESTÃO CORRENDO',
    relais_porte: 'LEVA',
    relais_attends_temoin: 'ESPERE',
    relais_prends: 'PEGUE O BASTÃO',
    relais_donne: 'PASSE O BASTÃO',
    relais_arrivee: 'REVEZAMENTO CONCLUÍDO',
    relais_elimine: 'EQUIPE ELIMINADA',
    relais_elimine_pourquoi: 'na perna {r}: {c}',
    relais_passages: 'AS TRÊS PASSAGENS',
    relais_elimine_court: 'fora',
    relais_fantome: 'FANTASMA',

    conf_titre: 'CORRER CONTRA OUTRAS EQUIPES',
    conf_desc: 'um tiro, uma ordem de chegada. Abra um código e compartilhe, ou digite o que te deram.',
    conf_ouvrir: 'ABRIR UM CONFRONTO',
    conf_rejoindre: 'ENTRAR',
    conf_code: 'código',
    conf_code_court: 'esse código é curto demais',
    conf_partage: 'COMPARTILHE ESTE CÓDIGO COM AS OUTRAS EQUIPES',
    conf_places: '{n} equipes na pista',
    conf_engagees: '{n} DE {m} EQUIPES',
    conf_attend_adversaire: 'falta pelo menos mais uma equipe, ou um fantasma',
    conf_classement: 'ORDEM DE CHEGADA',
    conf_encore: 'os outros ainda estão correndo',

    fantome_titre: 'DESAFIAR OS DEZ MELHORES PERCURSOS',
    fantome_desc: 'eles já foram corridos: repetem, e não podem ser eliminados nem batidos numa passagem. É o único jeito de encarar os melhores sem juntar oito pessoas.',
    fantome_aucun: 'nenhum percurso registrado ainda — a primeira equipe a completar um revezamento abre o baile.',
    fantome_choisis: '{n} de {m} escolhidos',
    fantome_defier: 'DESAFIAR',

    champ_directs: 'os {n} primeiros passam',
    champ_reveal: 'OS MELHORES PERDEDORES',
    champ_reveal_desc: 'não ganharam nenhuma corrida. Vêm do tempo de todas elas.',
    champ_continue: 'CONTINUAR',
    champ_sacre: '{n} é sagrado campeão — ver o pódio',
    champ_titre_duree: 'título por três meses',
    champ_rv_course: 'PRÓXIMA CORRIDA',
    champ_rv_reveal: 'MELHORES PERDEDORES REVELADOS',
    champ_rv_sacre: 'CERIMÔNIA',
    champ_quitter: 'sair do campeonato',

    live_lanes: 'RAIAS',
    live_lanes_duel: 'um duelo: o vencedor leva pontos, o perdedor devolve alguns',
    live_lanes_course: 'uma corrida: uma ordem de chegada, sem pontos de duelo',
    live_won: 'CORRIDA VENCIDA',
    live_sur: 'DE {n} PARTICIPANTES',
    live_ordre: 'ORDEM DE CHEGADA',
    live_lost: 'CORRIDA PERDIDA',

    pres_title: 'APRESENTAÇÃO DOS ATLETAS',
    pres_lane: 'RAIA',
    pres_you: 'ESSE É VOCÊ',
    pres_mic_on: 'MICROFONE ABERTO',
    pres_mic_off: 'microfone recusado',
    mic_winner: 'O VENCEDOR FALA',

    review_title: 'O VÍDEO DA SUA CORRIDA',
    review_making: 'gravando…',
    review_dl: 'BAIXAR',
    review_left: 'apagado em {t}',
    review_gone: 'o vídeo foi apagado',
    review_kept: 'o que você baixou fica no seu celular',
    review_none: 'este aparelho não consegue gravar a corrida',
    live_tie: 'CHEGADA EMPATADA',
    live_vs: 'ao vivo contra {n}',
    live_gap: '{s} s de diferença',
    link_in_app: 'JOGO INSTALADO?',
    link_in_app_sub: 'abra pela sua tela inicial e digite este código — toque para copiar',

    duel_answered: 'SEU DESAFIO FOI RESPONDIDO',
    duel_more: 'falta {n} resultado',
    duel_mores: 'faltam {n} resultados',
    duel_next: 'PRÓXIMO',
    duel_ok: 'ENTENDI',

    ghost_mode: 'MODO FANTASMA',
    ghost_ahead: 'NA FRENTE',
    ghost_behind: 'ATRÁS',
    ghost_level: 'EMPARELHADO',
    ghost_home: 'o fantasma cruzou a linha',
    ghost_live: 'o fantasma corre ao seu lado',
    duel_must: 'mande um desafio, ou responda ao de um amigo',
    duel_empty: 'nenhum duelo jogado ainda',
    duel_pts: 'pts',

    monde_sprinter_sous: 'a reta e a volta',
    monde_hurdlers_sous: 'a mesma raia, com dez obstáculos dentro',
    monde_jumper_sous: 'construa a corrida e saia do chão',
    monde_thrower_sous: 'um círculo, um implemento e o corpo inteiro',
    monde_bientot: 'EM BREVE',
    monde_retour: 'VOLTAR AO SPRINTER',

    disc_100: '100 METROS',
    disc_200: '200 METROS',
    disc_400: '400 METROS',
    disc_100h: '100 M COM BARREIRAS',
    disc_110h: '110 M COM BARREIRAS',
    disc_400h: '400 M COM BARREIRAS',
    disc_longueur: 'SALTO EM DISTÂNCIA',
    disc_hauteur: 'SALTO EM ALTURA',
    disc_triple: 'SALTO TRIPLO',
    disc_perche: 'SALTO COM VARA',
    disc_poids: 'ARREMESSO DE PESO',
    disc_marteau: 'LANÇAMENTO DE MARTELO',
    disc_disque: 'LANÇAMENTO DE DISCO',
    disc_javelot: 'LANÇAMENTO DE DARDO',

    pique_0: 'Nem precisei tentar.',
    pique_1: 'quer que eu faça de novo em câmera lenta?',
    pique_2: 'deu tempo de eu ficar entediado.',
    pique_3: 'a chegada é para cá.',
    pique_4: 'obrigado pelo aquecimento.',
    pique_5: 'olhei para trás e não tinha ninguém.',
    pique_6: 'você correu? não vi nada passar.',
    pique_7: 'guarda esse tempo, vai dar uma bela lembrança.',

    mot_titre: 'DEIXE UMAS PALAVRAS PARA {n}',
    mot_placeholder: 'alfinete em duas linhas',
    mot_vocal: 'VOZ',
    mot_ecouter: 'OUVIR',
    mot_refaire: 'gravar de novo',
    mot_envoyer: 'ENVIAR',
    mot_envoye: '{n} vai ler quando voltar',
    mot_micro_refuse: 'o microfone foi recusado — texto também serve',
    mot_ecouter_sa_voix: 'OUVIR O QUE ELE DISSE',
    mot_ephemere: 'esta gravação some quando você fechar esta janela',
    mot_illisible: 'esta mensagem não toca neste aparelho',

    mod_signaler: 'denunciar',
    mod_titre: 'Por que você está denunciando?',
    mod_explique: 'Uma denúncia é lida por uma pessoa. O bloqueio vale na hora.',
    mod_insulte: 'ofensa',
    mod_haine: 'ódio, racismo',
    mod_sexuel: 'sexual',
    mod_menace: 'ameaça',
    mod_autre: 'outro',
    mod_envoye: 'Denunciado. Alguém vai ler.',
    mod_deja: 'já denunciado',
    mod_bloquer: 'bloquear {n}',
    mod_bloque: '{n} não pode mais te escrever.',
    mod_annuler: 'cancelar',

    duel_revanche: 'QUERO A REVANCHE',
    duel_revanche_sub: 'mesma prova — agora é você que põe o tempo',
    duel_renvoyer: 'devolver o código para {n}',
    duel_revanche_envoyee: 'REVANCHE ENVIADA',
    os_revanche_sans_cible: 'não deu para avisar {n} — mande o código você mesmo',
    duel_revanche_ratee_titre: 'AINDA NÃO',
    duel_revanche_ratee: 'você precisava de menos de {s} s para devolver o desafio a {n} — nada foi enviado',

    rang_departemental: 'MUNICIPAL',
    rang_regional: 'REGIONAL',
    rang_national: 'NACIONAL',
    rang_elite: 'ELITE',
    rang_legende: 'LENDA',
    rang_court_departemental: 'MUN',
    rang_court_regional: 'REG',
    rang_court_national: 'NAC',
    rang_court_elite: 'ELITE ',
    rang_court_legende: 'LENDA',
    duel_lp: 'PL',
    duel_monte_a11y: 'sobe {n} posições',
    duel_descend_a11y: 'desce {n} posições',
    duel_lp_long: 'pontos de liga',
    duel_promu: 'PROMOVIDO A {r}',
    duel_relegue: 'REBAIXADO A {r}',
    duel_reste: '{n} para a próxima divisão',
    duel_regle: 'responder a um desafio paga mais do que enviar um: o tempo já está no quadro, e você sabe o que precisa bater.',
    duel_record: '{v}V · {d}D · {n}E',
    duel_you: 'VOCÊ',
    duel_since: 'desde sua última visita',
    duel_unranked: 'ainda sem classificação — jogue um duelo',
    duel_won: 'DUELO VENCIDO',
    duel_lost: 'DUELO PERDIDO',
    duel_tie: 'EMPATE',
    duel_final: 'resultado definitivo — um desafio não se repete',
    duel_delta: '{p} ponto',
    duel_deltas: '{p} pontos',

    false_out: 'QUEIMA DA LARGADA',
    false_out_sub: 'eliminado — o duelo está perdido',
    false_out_seul: 'eliminado — esta corrida acaba aqui',
    false_out_rule: 'uma corrida só, sem segunda chance',
    false_out_libre: 'você pode correr de novo',
    false_out_gun: 'saiu antes do tiro',
    duel_await: 'resultado do duelo…',
    duel_vs: 'contra {n}',
    duel_seen: 'duelo já resolvido',
    duel_see: 'VER A CLASSIFICAÇÃO',

    os_once: 'depois que o desafio for enviado, o tempo é definitivo',
    os_rejouer: 'CORRER DE NOVO',
    os_rejouer_sub: 'mais uma corrida, agora — esta fica como está',
    os_defier: 'DESAFIAR ALGUÉM',
    os_defier_sub: 'abra a classificação e escolha seu adversário — outro, ou o mesmo',
    relance_gagne_0: 'VAI PEGAR OUTRO',
    relance_gagne_0_sub: 'esse já foi. Próximo.',
    relance_gagne_1: 'O PRÓXIMO, POR FAVOR',
    relance_gagne_1_sub: 'a classificação está cheia de gente, e você está voando.',
    relance_gagne_2: 'QUEM MAIS?',
    relance_gagne_2_sub: 'pergunte à classificação. Alguém responde.',
    relance_perdu_0: 'PEGUE ALGUÉM MENOR',
    relance_perdu_0_sub: 'desça uma divisão — ninguém precisa saber',
    relance_perdu_1: 'ACHE ALGUÉM MAIS LENTO',
    relance_perdu_1_sub: 'eles existem. Estatisticamente, existem.',
    relance_perdu_2: 'AINDA HÁ INICIANTES',
    relance_perdu_2_sub: 'eles não desconfiam de nada. É a hora.',
    os_defi_sans_cible: '{n} não está no TOP 500 desta prova — mande o código você mesmo',
    os_verrou_direct: 'corrida ao vivo: seu adversário correu no mesmo momento — esse resultado vale',
    os_verrou_recu: 'esse tempo já foi para o seu adversário — não dá para voltar atrás',
    os_verrou_envoye: 'o desafio foi enviado — é esse o tempo que ele tem de bater',
    os_verrou_faux: 'queima da largada num duelo: a corrida está perdida. Mande um novo desafio para recomeçar.',
    cut_skip: 'PULAR',

    id_title: 'SEU NOME',
    id_code_title: 'CÓDIGO DE RECUPERAÇÃO',
    id_code_note: 'anote: ele liga seus outros aparelhos a este nome, e impede que alguém o pegue',
    id_show: 'VER MEU CÓDIGO',
    id_reserve: 'RESERVAR',
    id_taken: 'este nome já está em uso',
    id_taken_help: 'se for seu, digite o código de recuperação dele',
    id_link: 'LIGAR',
    id_linked: 'aparelho ligado a {n}',
    id_bad_code: 'código errado',
    id_unknown: 'nome desconhecido',
    id_link_title: 'OUTRO APARELHO?',
    id_link_help: 'digite seu nome e seu código para achar aqui seus tempos e seu histórico',

    install_title: 'INSTALAR O JOGO',
    install_why: 'tela cheia, sem barra do navegador, e joga sem internet',
    install_do: 'INSTALAR',
    install_later: 'mais tarde',
    install_ios_1: 'Toque em',
    install_ios_2: 'Compartilhar',
    install_ios_3: 'na parte de baixo do Safari, e depois',
    install_ios_4: 'Adicionar à Tela de Início',

    mode_career_s: 'carreira',
    mode_oneshot_s: 'one shot',
    cat_race_sub: 'melhor tempo em uma única corrida',
    cat_run_sub: 'total das seis etapas',
    empty_cat_run: 'nenhum percurso completo registrado ainda',
    will_enter: '{s} s: {r} no TOP 500, ponha seu nome',

    wr_title: 'RECORDE MUNDIAL',
    wr_sub: 'melhor tempo do mundo nos {d} m',
    wr_old: 'recorde anterior: {s} s',
    wr_first: 'primeiro tempo no quadro',
    wr_gain: '{s} s mais rápido',
    wr_save: 'PÔR MEU NOME',
    wr_saving: 'salvando...',
    wr_done: '{n} é {r} no TOP 500',
    wr_fail: 'falha no envio, tente de novo',
    wr_see: 'VER O TOP 500',
    wr_later: 'mais tarde',
    os_top_checking: 'conferindo as classificações...',
    os_top_none: 'nenhum tempo entra no TOP 500',
    os_top_intro: '{n} tempo entra no TOP 500',
    os_top_intro_n: '{n} tempos entram no TOP 500',
    os_top_line: '{d} m — {s} s — {r}',
    os_top_saved: 'tempos salvos como {n}',
    top500_count: '{n} tempos classificados de 500',
    os_top_better: 'seu recorde dos {d} m continua {s} s',
    os_kept_title: 'SEU RECORDE SE MANTÉM',
    os_kept_line: '{d} m: você já tem {s} s ({r} no TOP 500)',
    os_kept_now: 'estes {s} s não batem — a classificação guarda só o seu melhor',

    pause_title: 'CORRIDA PAUSADA',
    pause_note: 'sair agora abre mão do tempo atual',
    resume: 'CONTINUAR',

    challenge_them: 'DESAFIAR',
    target_run: 'corra seus {d} m: o desafio vai para {n}',
    target_sent: 'desafio enviado a {n}',
    inbox_one: 'DESAFIO RECEBIDO',
    inbox_many: '{n} DESAFIOS RECEBIDOS',
    inbox_from: '{n} te desafia nos {d} m',
    inbox_accept: 'ACEITAR',
    inbox_later: 'mais tarde',
    run_total_short: 'percurso completo:',
    run_total_tiny: 'percurso',
    best_split_tiny: 'corrida',
    score_saved_race: '{r} no TOP 500 mundial com {s} s',
    mode_career: 'CARREIRA',
    mode_oneshot: 'ONE SHOT',
    mode_versus: 'DESAFIO',
    career_desc: 'as seis etapas seguidas, um só tempo',
    oneshot_desc: 'escolha suas provas, uma só tentativa',
    versus_desc: 'corra contra o fantasma de outro jogador',
    pick_events: 'PROVAS',
    pick_level: 'NÍVEL',
    pick_none: 'escolha pelo menos uma prova',
    launch_oneshot: 'VAMOS',
    event_n: 'PROVA {n} / {t}',
    next_event: 'PRÓXIMA PROVA',
    oneshot_done: 'ONE SHOT CONCLUÍDO',
    total_in: 'total: ',
    challenge_code: 'CÓDIGO DE DESAFIO',
    challenge_enter: 'digite o código que você recebeu',
    challenge_load: 'CARREGAR',
    challenge_loading: 'carregando o desafio...',
    challenge_bad: 'código não encontrado',
    challenge_net: 'falha de conexão, tente de novo',
    challenge_from: 'desafio de {n}',
    challenge_beat: 'a bater: {s} s',
    challenge_aveugle: 'você vai descobrir o tempo dele correndo',
    challenge_accept: 'ACEITAR O DESAFIO',
    challenge_make: 'DESAFIAR UM AMIGO',
    challenge_making: 'criando o desafio...',
    challenge_share: 'mande este código e seu amigo corre contra o seu fantasma',
    challenge_copy: 'COPIAR LINK',
    challenge_copied: 'link copiado',
    challenge_copy_code: 'COPIAR CÓDIGO',
    share_send: 'ENVIAR O DESAFIO',
    share_whatsapp: 'WhatsApp',
    share_sms: 'SMS',
    share_other: 'Snapchat, Instagram…',
    share_other_hint: 'Snapchat e Instagram abrem pelo menu de compartilhar.',
    affiche_share: 'COMPARTILHAR MEU PERCURSO',
    affiche_making: 'Criando a imagem…',
    affiche_saved: 'imagem salva',
    affiche_failed: 'a imagem falhou',
    affiche_hint: 'uma imagem do seu percurso, para Instagram ou TikTok',
    code_copied: 'código copiado',
    challenge_rematch: 'DEVOLVER O DESAFIO',
    challenge_rematch_sub: 'você ganhou — desafie no percurso que acabou de fazer',
    challenge_won: 'DESAFIO VENCIDO',
    challenge_lost: 'DESAFIO PERDIDO',
    challenge_gap: 'diferença: {s} s',
    ghost_label: 'FANTASMA',
    you_label: 'VOCÊ',
    dnf_short: 'ABD',
    composing: 'compondo a trilha sonora...',

    sound_off: 'SOM DESLIGADO  (S)',
    press_enter: 'aperte ENTER',
    skip_now_kb: 'aperte ENTER de novo para pular',
    skip_twice_kb: 'aperte ENTER duas vezes para pular',
    stage_dash: 'ETAPA {n}   -   {s}',
    furthest_kb: 'etapa mais distante alcançada: {a} de {b}',
    enter_start: 'ENTER: começar   -   S: som   -   L: idioma   -   ESC: sair',
    how_to_play: 'COMO JOGAR',
    help_1: 'Alterne  <-  e  ->  sem',
    help_2: 'repetir a mesma tecla.',
    help_3: 'Um ritmo constante dá velocidade;',
    help_4: 'repetir faz você tropeçar, mas',
    help_5: 'dá sempre para arrancar de novo.',
    best_stage: 'MELHORES TEMPOS DESTA ETAPA',
    no_time: 'nenhum tempo registrado ainda',
    arrows_pick: 'setas para escolher   -   ENTER para confirmar   -   ',
    yn_short: 'atalho S / N',
    you_beat: 'Você bateu {w} e venceu as seis etapas.',
    the_zeze: 'os ZEZE',
    your_times: 'SEUS TEMPOS',
    total: 'TOTAL',
    enter_replay: 'ENTER: correr de novo      M: início',
    stumble_kb: 'VOCÊ TROPEÇA!',
    go_kb: 'JÁ!',
    to_beat_line: 'A BATER:  {n}   -   {s} s',
    best_times_of: 'MELHORES TEMPOS  -  {s}',
    enter_next: 'ENTER   ->   ETAPA {n}: {s}',
    full_run_pc: 'percurso completo em {s} s',
    announced_pc: 'tempo anunciado: {s} s',
    quit: 'ESC: sair'
  },

  CUTS: {
    intro: [
      [ // etapa 1
        ['{n} ganha todas as corridas do pátio há três anos.',
         'O segredo: ninguém ousa ultrapassá-lo, a bola é dele.',
         'Aquece de sapato de colégio, por princípio.',
         'A mãe filma de trás da grade. Principalmente a grade.'],
        ['{n} tem o recorde da escola, escrito a caneta na parede do ginásio.',
         'Um colega cronometrou, num relógio de ponteiros.',
         'O professor de educação física assentiu uma vez. Ficou oficial.',
         'Agora repintam a parede em volta do recorde.'],
        ['{n} pediu a raia 4. Deram a raia 4.',
         'Faz seus exercícios: joelhos altos, calcanhar no glúteo, suspiros fundos.',
         'O número dele foi impresso em casa, um pouco torto.',
         'O número é 1. Ele mesmo imprimiu, sozinho.']
      ],
      [ // etapa 2
        ['{n} está aquecendo há quatro horas.',
         'O agasalho tem o nome bordado nas costas, em maiúsculas.',
         'Tem um ritual: três passos atrás, uma respiração, uma piscada.',
         'A piscada não é para ninguém em particular.'],
        ['{n} chega com dois pares de sapatilhas e uma caixa térmica.',
         'A caixa tem uma banana e uma enorme determinação.',
         'Ajusta os blocos ao milímetro, e depois ajusta de novo.',
         'E uma terceira vez. O starter espera, educadamente.'],
        ['{n} ficou em segundo no regional do ano passado.',
         'Descreve como uma vitória roubada pelo vento contra.',
         'A medição oficial deu vento zero. Ele contesta a medição.',
         'Trouxe o próprio anemômetro. Não sabe usar.']
      ],
      [ // etapa 3
        ['{n} já apareceu na televisão regional.',
         'Trinta e oito segundos de imagem. Assistiu seiscentas vezes.',
         'Dá autógrafos antes da corrida, para ganhar tempo.',
         'Em cupons fiscais, na falta de coisa melhor.'],
        ['{n} tem um apelido que ninguém usa: a Flecha do Norte.',
         'Ele mesmo enfia o apelido em toda entrevista.',
         'O locutor acabou de apresentá-lo pelo nome real, por engano.',
         'Ele pediu uma correção no alto-falante. Vem mais tarde.'],
        ['{n} tatuou o recorde pessoal no antebraço.',
         'Mostra em câmera lenta durante a apresentação dos atletas.',
         'Quatro corredores desta final já bateram aquele número.',
         'A tatuagem, infelizmente, não se atualiza.']
      ],
      [ // etapa 4
        ['{n} tem patrocinador, empresário e fisioterapeuta.',
         'Os três dizem que ele é imbatível. Ele paga os três.',
         'O empresário já reservou a sala da coletiva da vitória.',
         'O bufê está encomendado. Tem canapés.'],
        ['{n} é o número um do mundo há onze meses.',
         'Soube ao vivo e desde então nunca mais olhou para trás.',
         'Literalmente: o fisioterapeuta desaconselhou com firmeza.',
         'Agora gira o tronco inteiro. Mais lento, mas fica elegante.'],
        ['O locutor anuncia {n}. O estádio se levanta.',
         'Ele aponta para a arquibancada, depois para o céu, depois para a câmera.',
         'A câmera estava em outro atleta. Ele recomeça tudo.',
         'O diretor cede. O gesto vai durar onze segundos.']
      ],
      [ // etapa 5
        ['{n} ensaia a comemoração há oito meses.',
         'Registrou como marca. Só falta ganhar a corrida.',
         'Um coro de quarenta pessoas espera o sinal dele.',
         'Aprenderam uma canção. A canção diz o nome dele, longamente.'],
        ['{n} veste as cores do país, e leva isso muito a sério.',
         'A bandeira está nas sapatilhas, no número e na toalha.',
         'A toalha não corre, mas está pronta desde terça.',
         'Um membro da equipe a carrega para todo lado desde a abertura.'],
        ['{n} jurou que não olharia para os rivais nos blocos.',
         'Então olha para a frente, com uma intensidade notável.',
         'Um pouco longe demais: olhou para a parede durante a apresentação.',
         'A parede não se classificou para esta final.']
      ],
      [ // etapa 6
        ['{n} vem de um universo onde a gravidade é opcional.',
         'Termina as corridas antes de decidir começá-las.',
         'O recorde dele vale em onze dimensões ao mesmo tempo.',
         'Na décima segunda ele tropeçou, mas ninguém toca no assunto.'],
        ['{n} correu estes cem metros em onze universos paralelos.',
         'Ganhou os onze. O décimo segundo nunca foi homologado.',
         'Lá o juiz de chegada era uma nebulosa, pouco confiável na linha.',
         'A nebulosa foi suspensa por três temporadas.'],
        ['A família ZEZE ocupa as sete raias. É regulamentar.',
         'Trouxeram o próprio starter, o próprio vento, a própria chegada.',
         'O regulamento foi escrito por um ZEZE e revisado por um ZEZE.',
         'Tem uma frase só: um ZEZE ganha.']
      ]
    ],

    defeat: [
      [ // etapa 1
        ['{n} recorre do resultado ao inspetor do refeitório.',
         'O inspetor está comendo um sanduíche. O resultado se mantém.',
         'Depois pede uma decisão ao representante de turma.',
         'O representante de turma ficou em último. Está adorando.'],
        ['{n} explica que o piso do pátio é irregular.',
         'Está irregular para todo mundo desde mil novecentos e sessenta.',
         'Depois menciona um cadarço solto. O sapato dele é de velcro.',
         'O professor escreve seu tempo na parede. Logo acima do dele.'],
        ['{n} anuncia que não estava correndo de verdade.',
         'Estava aquecendo. A corrida de verdade era a próxima.',
         'Ninguém tinha sido avisado, o que explica muita coisa.',
         'O sinal toca. A próxima corrida nunca vai acontecer.']
      ],
      [ // etapa 2
        ['{n} explica que o relógio dele nunca chegou a começar.',
         'Então, tecnicamente, esta corrida não existiu.',
         'Se oferece para correr de novo agora, entre gente séria.',
         'Depois lembra que tem um trem. Não tem trem nenhum.'],
        ['{n} pede para ver a foto de chegada.',
         'Mostram a foto. Claramente atrás, e bem focado.',
         'Pede a mesma foto de outro ângulo.',
         'Desse ângulo continua atrás, mas um pouco mais borrado.'],
        ['{n} guarda os dois pares de sapatilhas sem dizer nada.',
         'Anuncia que vai subir para os 400, prova mais tática.',
         'Depois os 800. Depois a maratona, onde tudo acaba mesmo.',
         'Vai embora com a caixa térmica. A banana está intacta.']
      ],
      [ // etapa 3
        ['{n} anuncia a aposentadoria ao vivo.',
         'Depois repensa: volta aos treinos na segunda.',
         'Observa que essa segunda em particular está bem cheia.',
         'A segunda seguinte também, pelo visto.'],
        ['{n} exige um exame antidoping para o vencedor.',
         'E depois um para si mesmo, em nome da justiça.',
         'Os dois dão negativo. Ele acha isso suspeito.',
         'Pede um terceiro exame. No equipamento de cronometragem.'],
        ['{n} mostra o antebraço aos jornalistas.',
         'O recorde tatuado não se mexeu. Antes assim.',
         'Anuncia seis semanas de treino em altitude.',
         'A montanha que escolheu tem duzentos metros.']
      ],
      [ // etapa 4
        ['{n} exige uma segunda medição do vento.',
         'O vento é convocado. O vento não comparece.',
         'A coletiva da vitória acontece assim mesmo, não dá mais para cancelar.',
         'Os canapés estão excelentes. Já é alguma coisa.'],
        ['{n} encara o telão por vinte segundos.',
         'A classificação não muda. O telão também não.',
         'Pergunta se a imagem é ao vivo. Dizem que sim.',
         'Pergunta então se existe um sinal com atraso. Não existe.'],
        ['Na zona mista, {n} fala de evolução e de processo.',
         'Usa a palavra ciclo onze vezes em dois minutos.',
         'Um jornalista pergunta o tempo dele. Responde: o tempo virá.',
         'O tempo dele já está no painel atrás, bem grande.']
      ],
      [ // etapa 5
        ['{n} faz a comemoração assim mesmo.',
         'O público aplaude, por educação.',
         'O coro, mal informado, emenda a canção.',
         'Quarenta pessoas cantam o nome dele. Teria preferido silêncio.'],
        ['{n} dá a volta olímpica com a bandeira, como planejado.',
         'O vencedor dá a mesma volta, no sentido contrário.',
         'Cruzam duas vezes. A segunda é pior.',
         'A toalha não viu isso chegando.'],
        ['{n} sobe no segundo degrau do pódio.',
         'Cumprimenta o vencedor com um aperto de mão longuíssimo.',
         'Longo o bastante para refazer a foto oficial três vezes.',
         'Na terceira ele sorri. Dá para ver o quanto custa.']
      ],
      [ // etapa 6
        ['{n} recalcula a trajetória da própria galáxia.',
         'Ela passava exatamente pelo segundo lugar.',
         'Alega uma anomalia temporal, e depois um problema no calçado.',
         'As duas explicações se contradizem. Fica com as duas.'],
        ['{n} pede a classificação dos outros onze universos.',
         'Nos onze ele também acabou de perder. Ao mesmo tempo.',
         'Se oferece para abrir um décimo segundo, só para ver.',
         'O décimo segundo está ocupado. Lá você também chegou em primeiro.'],
        ['Os outros seis ZEZE olham para {n} com muita calma.',
         'Ninguém diz uma palavra. O silêncio dura quatro anos-luz.',
         '{n} acaba propondo: o chão estava diferente hoje.',
         'O chão não mudou desde que a pista foi construída.']
      ]
    ],

    taunt: [
      [ // etapa 1
        ['{n} aponta para o placar, sem dizer nada.',
         'Já assinou. Com caneta permanente.',
         'Te entrega o sanduíche dele. "Para a estrada", diz.',
         'Você não tinha pedido sanduíche nenhum.'],
        ['{n} dá a volta olímpica. Três metros, por falta de espaço.',
         'Acena longamente para um público imaginário.',
         'Te oferece revanche. Depois olha o relógio.',
         'Não tem relógio. O gesto já disse tudo.'],
        ['{n} guarda as coisas tranquilamente, assobiando.',
         'A melodia é o seu nome, em ritmo de marcha triunfal.',
         'Dá um tapinha no seu ombro. "Na próxima", diz.',
         'Não acredita nisso nem por um segundo, e dá para ver.']
      ],
      [ // etapa 2
        ['{n} olha o cronômetro, e depois olha para você, com intenção.',
         'Não diz nada. O silêncio é mais cruel que as palavras.',
         'Dá autógrafos. O primeiro é para você.',
         'Isso também você não tinha pedido.'],
        ['{n} liga para o treinador. "Terminamos cedo", diz.',
         'O treinador pergunta por quê. "Por educação", responde.',
         'Te oferece a medalha para segurar. Só um instante.',
         'O instante dura dez minutos. Ele tira fotos.'],
        ['{n} guarda as sapatilhas num estojo com o seu nome.',
         'É uma piada interna. O público não acompanha.',
         'Te oferece água da garrafa dele. Está vazia.',
         'O gesto, diz ele, importa mais que a água.']
      ],
      [ // etapa 3
        ['{n} acena para a câmera. Depois acena para você.',
         'O segundo aceno é bem menos simpático.',
         'Comenta sua corrida com os jornalistas, em detalhe.',
         'O detalhe favorito dele: a hora em que você olhou para trás.'],
        ['{n} pede o microfone. Dão a ele, contra todo bom senso.',
         'Agradece à família, ao clube e a você, nessa ordem.',
         '"Sem ele", diz, "não teria o mesmo gosto".',
         'Não explica o que quer dizer. Não precisa.'],
        ['{n} se oferece para rever sua corrida junto, com calma.',
         'A revisão tem uma palavra só. Ele diz bem devagar.',
         'Aperta sua mão duas vezes seguidas, por garantia.',
         'A primeira não pareceu convincente o bastante.']
      ],
      [ // etapa 4
        ['{n} dá uma entrevista. O assunto é você, curiosamente.',
         'Três minutos. Nada sobre a corrida dele.',
         'Conclui dizendo que aprendeu muito. Com a sua derrota.',
         'O jornalista anota palavra por palavra, sem jeito.'],
        ['{n} faz sinal ao empresário para acrescentar uma linha ao currículo.',
         'A linha diz apenas: contra você, mais uma vez.',
         'Te convida para a coletiva da vitória.',
         'Uma cadeira te espera, bem no fundo, sem microfone.'],
        ['{n} te mostra a classificação no celular, dando zoom.',
         'Dá zoom por um bom tempo. Sua linha fica bem abaixo da dele.',
         '"Posso te mandar por e-mail", oferece, prestativo.',
         'Você nunca deu seu endereço. Ele já tem.']
      ],
      [ // etapa 5
        ['{n} acena para a arquibancada, e depois se vira para você, solene.',
         'O gesto que faz em seguida não está em regulamento nenhum.',
         'Um jornalista pede uma palavra para o rival derrotado.',
         'Ele diz sete. Nenhuma vai sair na matéria.'],
        ['{n} sobe no pódio, e depois desce um degrau.',
         'Te convida para ver a medalha de perto.',
         'Bem de perto. É de ouro. Ele faz questão desse ponto.',
         'O hino começa. Ele canta alto, olhando para você.'],
        ['{n} dedica a vitória à família, aos patrocinadores e a você.',
         '"Sem um adversário tão motivador", diz, sincero.',
         'A palavra motivador soa como um insulto bem disfarçado.',
         'O público aplaude, sem entender por que você fica vermelho.']
      ],
      [ // etapa 6
        ['{n} olha para os outros seis ZEZE. Eles assentem, juntos.',
         'O veredito é unânime, e sai sem um único som.',
         'Uma placa comemorativa é gravada, numa língua morta.',
         'Diz, em essência: ele tentou. Já é alguma coisa.'],
        ['{n} recalcula sua posição em onze dimensões diferentes.',
         'Em todas elas o resultado é idêntico, ao segundo.',
         'Te dá um mapa do universo em que você teria ganhado.',
         'Esse universo, observa ele, ainda não existe.'],
        ['{n} estende a mão para o céu. Uma galáxia se acende, dócil.',
         'Por um instante ela forma o contorno do sorriso dele.',
         'Os sete ZEZE se consultam, e depois se viram para você.',
         'O silêncio que se segue dura quatro anos-luz. Educadamente.']
      ]
    ],

    champion: [
      ['Os sete ZEZE deliberam longamente.',
       'Nenhum acha uma desculpa aceitável. É a primeira vez.',
       'A classificação é atualizada em catorze bilhões de sistemas.',
       'Uma placa é colocada na linha de chegada.',
       'Seu nome está escrito errado, mas está lá.'],
      ['O locutor procura uma palavra. Nenhuma é grande o bastante.',
       'Ele apenas lê o tempo, duas vezes, para ter certeza.',
       'Sete ZEZE encaram o telão sem dizer nada.',
       'Uma comissão é criada para conferir a linha de chegada.',
       'A linha está reta. A classificação também.'],
      ['A volta olímpica dura mais que a corrida.',
       'É aritmética simples, e ninguém reclama.',
       'Te entregam uma bandeira. Você não sabe de que galáxia vem.',
       'Vem de todas: fundiram os desenhos para a ocasião.',
       'O coro reescreveu a canção. Ela diz o seu nome, enfim.']
    ]
  }
};
