/* -----------------------------------------------------------------------
   SPRINTER — Türkçe.
   Ce qui manque ici retombe sur l'anglais, cle par cle : voir
   sprinter-i18n.js. Verification : node tools/langues-verifier.mjs tr
   ----------------------------------------------------------------------- */
export default {
  // Türkçede sıra sayısı noktayla yazılır: 1., 2., 3.
  ord(n) { return n + '.'; },

  LEVEL_NAMES: [
    'Okul yarışması', 'Bölgesel seviye', 'Ulusal seviye',
    'Dünya Şampiyonası', 'Dünya Oyunları', 'Galaksiler arası'
  ],

  RACE_SUB: {
    '100': 'düzlük',
    '200': 'viraj ve düzlük',
    '400': 'pistte bir tur'
  },

  UI: {
    races: '100 - 200 - 400 METRE',
    tagline: 'altı etap, geçilecek tek bir süre',
    tap_start: 'başlamak için ekrana dokun',
    six_stages: '   -   altı etap',
    six_stages_bare: 'altı etap',
    best_runs: 'EN İYİ PARKURLAR',
    no_run: 'henüz tamamlanmış parkur yok',
    furthest: 'en uzak etap: ',
    of_six: ' / 6',
    start: 'BAŞLA',
    sound: 'ses: ',
    yes: 'evet',
    no: 'hayır',

    rival: 'GEÇİLECEK KOŞUCU',
    favourite: 'Favori',
    after_race: 'YARIŞTAN SONRA',
    crowned: 'GALAKSİLER ARASI ŞAMPİYON',
    fastest_1: 'EN HIZLI VARLIK',
    fastest_2: 'TÜM GALAKSİLERİN',
    full_run_in: 'tam parkur şu sürede: ',
    announced: 'açıklanan süre: ',
    stage_up: 'ETAP ',
    six_cleared: 'ALTI ETAP GEÇİLDİ',
    skip_now: 'geçmek için tekrar dokun',
    skip_twice: 'geçmek için iki kez dokun',

    reaction: 'TEPKİ',
    react_top: 'KUSURSUZ TEPKİ',
    false_start: 'ERKEN ÇIKTIN',
    wait_gun: 'silahı bekle',
    phase_drive: 'İTİŞ',
    phase_trans: 'GEÇİŞ',
    phase_max: 'AZAMİ HIZ',
    drive_hint: 'temponu otur',
    trans_2: 'KUSURSUZ GEÇİŞ',
    trans_1: 'İYİ GEÇİŞ',
    trans_0: 'GEÇİŞ KAÇTI',
    start_line: 'çıkış: {r} s tepki   -   {g}',
    no_start: 'çıkış kaçtı',

    stumble: 'TÖKEZLİYORSUN',
    to_beat: 'geçilecek: ',
    to_race: 'karşında ',
    ready: 'YERLERİNİZE',
    get_set: 'HAZIR',
    go: 'MARŞ',
    alternate: 'iki tuşu sırayla kullan',
    alternate_kb: 'iki oku sırayla kullan',
    you: 'SEN',
    opponent: 'RAKİP',
    depart: 'ÇIKIŞ',
    arrivee: 'VARIŞ',

    stage_done: 'ETAP {n} GEÇİLDİ',
    first_in: '1. sıra, süre ',
    total_of: ' s   -   toplam ',
    place: '{o} SIRA',
    dnf: 'bıraktı',
    unfinished: 'tamamlanmadı',
    race_again: 'TEKRAR MI?',
    next_stage: 'ETAP {n}',
    home: 'ANA EKRAN',
    replay: 'TEKRAR OYNA',
    run_done: 'PARKUR TAMAMLANDI',
    six_in: 'altı etap şu sürede geçildi: ',
    stage_low: 'etap ',

    new_record: 'YENİ REKOR',
    top3: 'İLK 3',
    top10: 'İLK 10',
    best_run: 'EN İYİ PARKUR',
    top3_runs: 'PARKURLARDA İLK 3',
    top10_runs: 'PARKURLARDA İLK 10',

    top500: 'TOP 500 - TÜM ZAMANLAR',
    your_name: 'adın',
    save_score: 'SÜREMİ KAYDET',
    saving_score: 'gönderiliyor...',
    score_saved: 'dünya TOP 500 listesinde {r}',
    score_save_fail: 'gönderilemedi, sonra tekrar dene',
    score_name_taken: 'bu ad başka bir cihaza ait',
    score_taken_help: 'başka bir tane seç ya da kurtarma kodunla bu cihazı YARIŞLARIM bölümünden adına bağla',
    view_top500: 'TOP 500 LİSTESİNİ GÖR',
    top500_court: 'TOP 500',
    close: 'KAPAT',
    loading_ranks: 'sıralama yükleniyor...',
    empty_top500: 'henüz kayıtlı süre yok',
    your_rank: 'SIRAN: {r}',
    outside_top500: 'ilk 500 dışında',
    edit_name: 'ADI DEĞİŞTİR',
    best_split_short: 'en iyi etap:',
    top500_sub: 'tek bir yarıştaki en iyi süre',
    cat_race: 'YARIŞA GÖRE',
    cat_run: 'TAM PARKUR',
    cat_mine: 'YARIŞLARIM',
    cat_mine_sub: 'koştuğun bütün yarışlar',
    mine_empty: 'bu branşta henüz yarış yok',
    mine_count: '{n} yarış — en iyi: {s} s',
    mine_note: 'TOP 500 yalnızca branş başına en iyi süreni tutar; bu geçmiş her şeyi tutar. Diğer cihazlarında bulabilmek için adını ayır.',

    duel_title: 'DÜELLO SIRALAMASI',
    duel_sub: 'gönderilen ve yanıtlanan meydan okumalar',
    duel_open: 'DÜELLO SIRALAMASINI GÖR',
    duel_rules_init: 'MEYDAN OKUMA GÖNDERİLDİ',
    duel_rules_recv: 'MEYDAN OKUMA YANITLANDI',
    duel_rules_line: 'galibiyet {v}   ·   yenilgi {d}   ·   beraberlik {n}',
    duel_rules_all: 'her düello sayılır, gönderilen de yanıtlanan da',
    duel_rules_why: 'meydan okuyan, süresini önce gösteren kişidir',
    duel_counts: '{l} gönderildi · {r} yanıtlandı',
    duel_sur: 'DÜELLO ŞU MESAFEDE',

    name_set: 'ADINI SEÇ',
    name_title: 'ADIN',
    name_why: 'TOP 500 listesinde, meydan okumalarında ve düellolarda bu görünür',
    name_save: 'KAYDET',
    name_saved: 'KAYDEDİLDİ',
    name_taken: 'bu ad zaten alınmış',
    name_code: 'KURTARMA KODUN',
    pays_title: 'UYRUĞUN',
    pays_opt: 'yalnızca bir kez',
    pays_aucun: 'ülkeni seç',
    pays_why: 'ulusal şampiyona koşmak için gerekli — ve sonradan değiştirilemez',
    pays_vu: '{pays} üzerinden bağlanıyor gibisin — karar senin',
    pays_save: 'SEÇ',
    pays_confirm: '{pays} adına mı koşacaksın?\n\nBu kesindir: hangi ulusal şampiyonaya gireceğini belirler ve değiştirilemez.',
    pays_fige: 'kesin',
    pays_on: 'bu ülke adına koşuyorsun — şampiyonada bayrağın adının yanında olur',
    pays_deja: 'uyruğun zaten seçildi, değiştirilemez',
    pays_first: 'önce adını kaydet',
    pays_bad: 'geçersiz ülke',
    insta_title: 'INSTAGRAM HESABIN',
    insta_ph: 'kullanıcı adın, @ olmadan',
    insta_why: 'profilin TOP 500 listesinden ve meydan okumalarından açılabilir olur',
    insta_note: 'senin beyanın, doğrulanmadı — Instagram kişisel hesaplar için artık gerçek girişe izin vermiyor',
    insta_link: 'HESABIMI BAĞLA',
    insta_linked: 'HESAP BAĞLANDI',
    insta_unlink: 'BAĞLANTIYI KALDIR',
    insta_on: 'profilin TOP 500 listesinde görünüyor — açmak için dokun',
    insta_gone: 'hesap bağlantısı kaldırıldı, profilin artık hiçbir yerde görünmüyor',
    insta_bad: 'geçersiz kullanıcı adı',
    insta_first: 'önce adını kaydet',
    insta_notyours: 'bu ad bu cihazda sana ait değil',
    insta_visit: '{n} kişisinin Instagram profilini gör',
    name_code_why: 'not al: başka bir telefonda adını ve yarışlarını geri getirir',

    tour_open: 'TURA ÇIK',
    tour_1_t: 'SIRAYLA BAS',
    tour_1_s: 'sol, sağ, sol. Yarışın tamamı bu.',
    tour_2_t: 'KARİYER',
    tour_2_s: 'altı etap, okul bahçesinden galaksiler arası finale',
    tour_3_t: 'TOP 500',
    tour_3_s: 'senin süren, bütün dünyaya karşı',
    tour_4_t: 'HAYALET',
    tour_4_s: 'yarışını bir arkadaşına gönder — sana karşı koşar',
    tour_5_t: 'CANLI',
    tour_5_s: 'aynı silah, her biriniz kendi telefonunda',
    tour_play: 'BIRAK DA OYNAYAYIM',

    os_tuto_open: 'BU MOD NE İŞE YARAR',
    os_tuto_1_t: 'BRANŞLARINI SEÇ',
    os_tuto_2_t: 'TEK BİR DENEME',
    os_tuto_3_t: 'SÜREN SAYILIR',
    os_tuto_1_s: 'bir, iki ya da üçü birden',
    os_tuto_2_s: 'tekrar yok, eleme yok',
    os_tuto_3_s: 'TOP 500, ve bir arkadaşın devralabilir',
    os_tuto_go: 'ONE SHOT BAŞLAT',

    tuto_ask_t: 'İLK YARIŞ',
    tuto_ask_s: 'hareket otuz saniyede öğrenilir',
    tuto_ask_yes: 'HAREKETİ ÖĞREN',
    tuto_ask_no: 'BIRAK DA KOŞAYIM',
    tuto_watch: 'İZLE',
    tuto_your_turn: 'SIRA SENDE',
    tuto_1_t: 'SIRAYLA BAS',
    tuto_2_t: 'SİLAHLA BİRLİKTE',
    tuto_3_t: 'GENİŞ, SONRA KISA',
    tuto_v_early: 'ÇOK ERKEN',
    tuto_v_late: 'çok geç',
    tuto_v_perfect: 'KUSURSUZ',
    tuto_v_good: 'İYİ',
    tuto_v_slow: 'YETERİNCE HIZLI DEĞİL',
    tuto_v_flat: 'DÜZ TEMPO',
    tuto_replay_demo: 'tekrar izle',
    tuto_again: 'TEKRAR',
    tuto_next: 'DEVAM',
    tuto_done_t: 'KOŞMA SIRASI SENDE',
    tuto_start: 'BAŞLA',
    tuto_replay: 'tekrar izle',
    tuto_skip: 'geç',
    tuto_open: 'NASIL OYNANIR',

    live_title: 'CANLI YARIŞ',
    live_desc: 'ikiniz de aynı silahla çıkıyorsunuz, her biriniz kendi telefonunda — hayalet yok, kimin kazanacağını kimse bilmiyor',
    live_create: 'PİST AÇ',
    live_join: 'KATIL',
    live_or: 'ya da',
    live_room: 'PİST AÇIK',
    live_waiting: 'bu kodu rakibine gönder — iki kişi olunca yarış başlar',
    live_ready: 'HAZIR',
    live_notready: 'HENÜZ DEĞİL',
    live_empty_seat: 'kulvar boş — rakip bekleniyor',
    live_go: 'HAZIRIM',
    live_unready: 'VAZGEÇ',
    live_leave: 'pistten ayrıl',
    live_none: 'bu kodla pist yok',
    live_full: 'bu pist zaten dolu',
    live_gone: 'rakibin pistten ayrıldı',
    live_closed: 'bağlantı koptu',
    live_invite: 'Seni pistte bekliyorum. Kod {c} — {l}',

    relais_titre: '4 × 100 BAYRAK',
    relais_desc: 'dört koşucu, bir bayrak. Bir takım kadrosudur: aynı dört ad, aynı takım.',
    relais_invitations: 'DAVET EDİLDİN',
    relais_mes_equipes: 'TAKIMLARIN',
    relais_creer: 'TAKIM KUR',
    relais_nom_equipe: 'takım adı',
    relais_coequipier: 'takım arkadaşı {n}',
    relais_inviter: 'ÜÇÜNÜ DE DAVET ET',
    relais_incomplet: 'bir ad ve üç takım arkadaşı gerekli',
    relais_attend: 'bekliyor',
    relais_ok: 'kadroda',
    relais_refuse: 'reddetti',
    relais_fixer_ordre: 'KOŞU SIRASINI BELİRLE',
    relais_manque_reponses: 'koşabilmek için hâlâ yanıt bekleniyor',
    relais_manque_refus: 'bir takım arkadaşı reddetti — bu takım koşamaz',
    relais_prete: 'takım hazır',
    relais_classement: 'TAKIM SIRALAMASI',
    relais_plein_titre: 'İKİ TAKIM, ÜÇ DEĞİL',
    relais_plein: 'zaten iki takım adına koşuyorsun. Yeni bir takım kurmak için artık koşmadığın takımdan ayrıl.',
    relais_plein_invit: 'zaten iki takım adına koşuyorsun — bunu kabul etmek için birinden ayrıl.',
    relais_quitter: 'AYRIL',
    relais_quitter_sur: 'temelli ayrılınsın mı?',
    relais_quitter_sub: 'ancak yeni bir davetle geri dönersin',
    relais_reste: 'bir yer kaldı',
    relais_place: '2 takımdan 1',
    relais_places: '2 takımdan {n}',
    relais_courir: 'PİSTE ÇIK',
    relais_mon_rang: '{n}. etabı sen koşuyorsun',
    relais_premier: 'bloklardan, ayakta çıkıyorsun. Hatalı çıkış bütün takımı eler.',
    relais_ta_marque: 'DEĞİŞİM ALANINDAKİ İŞARETİN',
    relais_zone_debut: 'giriş',
    relais_zone_fin: 'çıkış',
    relais_marque_conseil: 'daha ileride daha hızlı çıkarsın ama bayraktan önce alanı terk edebilirsin. Daha geride bayrağı kesin alırsın — durur hâlde.',
    relais_attend_equipe: 'hâlâ {n} takım arkadaşı eksik',
    relais_temoin_a: 'BAYRAK ŞURADA',
    relais_spectateur: 'DİĞERLERİ KOŞUYOR',
    relais_porte: 'TAŞIYOR',
    relais_attends_temoin: 'BEKLE',
    relais_prends: 'BAYRAĞI AL',
    relais_donne: 'BAYRAĞI VER',
    relais_arrivee: 'BAYRAK TAMAMLANDI',
    relais_elimine: 'TAKIM ELENDİ',
    relais_elimine_pourquoi: '{r}. etapta: {c}',
    relais_passages: 'ÜÇ DEĞİŞİM',
    relais_elimine_court: 'elendi',
    relais_fantome: 'HAYALET',

    conf_titre: 'BAŞKA TAKIMLARA KARŞI KOŞ',
    conf_desc: 'tek silah, tek varış sırası. Bir kod aç ve paylaş, ya da sana verilen kodu gir.',
    conf_ouvrir: 'KARŞILAŞMA AÇ',
    conf_rejoindre: 'KATIL',
    conf_code: 'kod',
    conf_code_court: 'bu kod fazla kısa',
    conf_partage: 'BU KODU DİĞER TAKIMLARLA PAYLAŞ',
    conf_places: 'pistte {n} takım',
    conf_engagees: '{m} TAKIMDAN {n}',
    conf_attend_adversaire: 'en az bir takım daha gerek, ya da bir hayalet',
    conf_classement: 'VARIŞ SIRASI',
    conf_encore: 'diğerleri hâlâ koşuyor',

    fantome_titre: 'EN İYİ ON PARKURA MEYDAN OKU',
    fantome_desc: 'onlar çoktan koşuldu: tekrar oynanırlar, elenemez ve bir değişimde geçilemezler. Sekiz kişiyi bir araya getirmeden en iyilerle ölçüşmenin tek yolu budur.',
    fantome_aucun: 'henüz kayıtlı parkur yok — bayrağı tamamlayan ilk takım balo açar.',
    fantome_choisis: '{m} parkurdan {n} seçildi',
    fantome_defier: 'MEYDAN OKU',

    champ_directs: 'ilk {n} tur atlar',
    champ_reveal: 'EN HIZLI KAYBEDENLER',
    champ_reveal_desc: 'hiçbir yarış kazanmadılar. Bütün yarışların süresinden geliyorlar.',
    champ_continue: 'DEVAM',
    champ_sacre: '{n} şampiyon oldu — podyumu gör',
    champ_titre_duree: 'unvan üç ay sürer',
    champ_rv_course: 'SONRAKİ YARIŞ',
    champ_rv_reveal: 'EN HIZLI KAYBEDENLER AÇIKLANDI',
    champ_rv_sacre: 'TÖREN',
    champ_quitter: 'şampiyonadan ayrıl',

    live_lanes: 'KULVARLAR',
    live_lanes_duel: 'bir düello: kazanan puan alır, kaybeden puan verir',
    live_lanes_course: 'bir yarış: varış sırası var, düello sıralamasında puan yok',
    live_won: 'YARIŞ KAZANILDI',
    live_sur: '{n} KOŞUCUDAN',
    live_ordre: 'VARIŞ SIRASI',
    live_lost: 'YARIŞ KAYBEDİLDİ',

    pres_title: 'SPORCU TANITIMI',
    pres_lane: 'KULVAR',
    pres_you: 'BU SENSİN',
    pres_mic_on: 'MİKROFON AÇIK',
    pres_mic_off: 'mikrofon reddedildi',
    mic_winner: 'KAZANAN KONUŞUYOR',

    review_title: 'YARIŞININ VİDEOSU',
    review_making: 'kaydediliyor…',
    review_dl: 'İNDİR',
    review_left: '{t} sonra silinir',
    review_gone: 'video silindi',
    review_kept: 'indirdiğin telefonunda kalır',
    review_none: 'bu cihaz yarışı kaydedemiyor',
    live_tie: 'BAŞA BAŞ VARIŞ',
    live_vs: 'canlı, karşında {n}',
    live_gap: '{s} s fark',
    link_in_app: 'OYUN KURULU MU?',
    link_in_app_sub: 'ana ekrandan aç ve bu kodu gir — kopyalamak için dokun',

    duel_answered: 'MEYDAN OKUMAN YANITLANDI',
    duel_more: '{n} sonuç daha bekliyor',
    duel_mores: '{n} sonuç daha bekliyor',
    duel_next: 'DEVAM',
    duel_ok: 'ANLAŞILDI',

    ghost_mode: 'HAYALET MODU',
    ghost_ahead: 'ÖNDE',
    ghost_behind: 'GERİDE',
    ghost_level: 'BAŞA BAŞ',
    ghost_home: 'hayalet çizgiyi geçti',
    ghost_live: 'hayalet yanında koşuyor',
    duel_must: 'bir meydan okuma gönder, ya da bir arkadaşınınkini yanıtla',
    duel_empty: 'henüz düello oynanmadı',
    duel_pts: 'puan',

    monde_sprinter_sous: 'düzlük ve tur',
    monde_hurdlers_sous: 'aynı kulvar, içinde on engelle',
    monde_jumper_sous: 'koşuyu kur ve yerden kesil',
    monde_thrower_sous: 'bir daire, bir alet ve bütün beden',
    monde_bientot: 'YAKINDA',
    monde_retour: 'SPRINTER’A DÖN',

    disc_100: '100 METRE',
    disc_200: '200 METRE',
    disc_400: '400 METRE',
    disc_100h: '100 M ENGELLİ',
    disc_110h: '110 M ENGELLİ',
    disc_400h: '400 M ENGELLİ',
    disc_longueur: 'UZUN ATLAMA',
    disc_hauteur: 'YÜKSEK ATLAMA',
    disc_triple: 'ÜÇ ADIM ATLAMA',
    disc_perche: 'SIRIKLA ATLAMA',
    disc_poids: 'GÜLLE ATMA',
    disc_marteau: 'ÇEKİÇ ATMA',
    disc_disque: 'DİSK ATMA',
    disc_javelot: 'CİRİT ATMA',

    pique_0: 'Denemem bile gerekmedi.',
    pique_1: 'ağır çekimde tekrar edeyim mi?',
    pique_2: 'sıkılacak kadar vaktim oldu.',
    pique_3: 'varış çizgisi bu tarafta.',
    pique_4: 'ısınma için teşekkürler.',
    pique_5: 'arkama baktım, kimse yoktu.',
    pique_6: 'koştun mu? bir şeyin geçtiğini görmedim.',
    pique_7: 'o süreyi sakla, güzel bir hatıra olur.',

    mot_titre: '{n} İÇİN İKİ KELİME BIRAK',
    mot_placeholder: 'iki satırda iğnele',
    mot_vocal: 'SES',
    mot_ecouter: 'DİNLE',
    mot_refaire: 'yeniden kaydet',
    mot_envoyer: 'GÖNDER',
    mot_envoye: '{n} döndüğünde okuyacak',
    mot_micro_refuse: 'mikrofon reddedildi — yazı da olur',
    mot_ecouter_sa_voix: 'NE DEDİĞİNİ DİNLE',
    mot_ephemere: 'bu kayıt bu pencereyi kapatınca kaybolur',
    mot_illisible: 'bu mesaj bu cihazda oynatılamıyor',

    mod_signaler: 'bildir',
    mod_titre: 'Neden bildiriyorsun?',
    mod_explique: 'Bildirimi bir insan okur. Engelleme anında geçerli olur.',
    mod_insulte: 'hakaret',
    mod_haine: 'nefret, ırkçılık',
    mod_sexuel: 'cinsel içerik',
    mod_menace: 'tehdit',
    mod_autre: 'diğer',
    mod_envoye: 'Bildirildi. Biri okuyacak.',
    mod_deja: 'zaten bildirildi',
    mod_bloquer: '{n} kişisini engelle',
    mod_bloque: '{n} artık sana yazamaz.',
    mod_annuler: 'vazgeç',

    duel_revanche: 'REVANŞ İSTİYORUM',
    duel_revanche_sub: 'aynı branş — süreyi bu kez sen koyuyorsun',
    duel_renvoyer: 'kodu {n} kişisine geri gönder',
    duel_revanche_envoyee: 'REVANŞ GÖNDERİLDİ',
    os_revanche_sans_cible: '{n} kişisine haber verilemedi — kodu kendin gönder',
    duel_revanche_ratee_titre: 'HENÜZ DEĞİL',
    duel_revanche_ratee: '{n} kişisine meydan okumayı geri göndermek için {s} s altına inmen gerekiyordu — hiçbir şey gitmedi',

    rang_departemental: 'İL',
    rang_regional: 'BÖLGE',
    rang_national: 'ULUSAL',
    rang_elite: 'ELİT',
    rang_legende: 'EFSANE',
    rang_court_departemental: 'İL',
    rang_court_regional: 'BÖL',
    rang_court_national: 'ULU',
    rang_court_elite: 'ELİT ',
    rang_court_legende: 'EFSANE',
    duel_lp: 'LP',
    duel_monte_a11y: '{n} sıra yükseliyor',
    duel_descend_a11y: '{n} sıra düşüyor',
    duel_lp_long: 'lig puanı',
    duel_promu: '{r} SEVİYESİNE YÜKSELDİN',
    duel_relegue: '{r} SEVİYESİNE DÜŞTÜN',
    duel_reste: 'bir üst seviyeye {n}',
    duel_regle: 'meydan okumayı yanıtlamak, göndermekten çok kazandırır: süre çoktan tabelada ve neyi geçeceğini biliyorsun.',
    duel_record: '{v}G · {d}M · {n}B',
    duel_you: 'SEN',
    duel_since: 'son ziyaretinden beri',
    duel_unranked: 'henüz sıralanmadın — bir düello oyna',
    duel_won: 'DÜELLO KAZANILDI',
    duel_lost: 'DÜELLO KAYBEDİLDİ',
    duel_tie: 'BERABERE',
    duel_final: 'kesin sonuç — bir meydan okuma tekrarlanmaz',
    duel_delta: '{p} puan',
    duel_deltas: '{p} puan',

    false_out: 'HATALI ÇIKIŞ',
    false_out_sub: 'elendin — düello kaybedildi',
    false_out_seul: 'elendin — bu yarış burada bitiyor',
    false_out_rule: 'tek yarış, ikinci şans yok',
    false_out_libre: 'tekrar koşabilirsin',
    false_out_gun: 'silahtan önce çıktın',
    duel_await: 'düello sonucu…',
    duel_vs: 'karşında {n}',
    duel_seen: 'düello çoktan sonuçlandı',
    duel_see: 'SIRALAMAYI GÖR',

    os_once: 'meydan okuma gönderildikten sonra süre kesinleşir',
    os_rejouer: 'TEKRAR KOŞ',
    os_rejouer_sub: 'hemen bir yarış daha — bu olduğu gibi kalır',
    os_defier: 'BİRİNE MEYDAN OKU',
    os_defier_sub: 'sıralamayı aç ve rakibini seç — başkası ya da aynısı',
    relance_gagne_0: 'GİT BİR TANE DAHA AL',
    relance_gagne_0_sub: 'o hallolmuş. Sıradaki.',
    relance_gagne_1: 'SIRADAKİ, LÜTFEN',
    relance_gagne_1_sub: 'sıralama insan dolu, sen de formdasın.',
    relance_gagne_2: 'BAŞKA KİM VAR?',
    relance_gagne_2_sub: 'sıralamaya sor. Biri yanıt verir.',
    relance_perdu_0: 'DAHA KÜÇÜĞÜNÜ SEÇ',
    relance_perdu_0_sub: 'bir seviye in — kimsenin bilmesi gerekmez',
    relance_perdu_1: 'DAHA YAVAŞ BİRİNİ BUL',
    relance_perdu_1_sub: 'varlar. İstatistiksel olarak varlar.',
    relance_perdu_2: 'HÂLÂ ACEMİLER VAR',
    relance_perdu_2_sub: 'hiçbir şeyden şüphelenmiyorlar. Tam zamanı.',
    os_defi_sans_cible: '{n} bu branşın TOP 500 listesinde değil — kodu kendin gönder',
    os_verrou_direct: 'canlı yarış: rakibin aynı anda koştu — o sonuç geçerli',
    os_verrou_recu: 'o süre rakibine gitti — geri alınamaz',
    os_verrou_envoye: 'meydan okuma gönderildi — geçmesi gereken süre bu',
    os_verrou_faux: 'düelloda hatalı çıkış: yarış kaybedildi. Baştan başlamak için yeni bir meydan okuma gönder.',
    cut_skip: 'GEÇ',

    id_title: 'ADIN',
    id_code_title: 'KURTARMA KODU',
    id_code_note: 'not al: diğer cihazlarını bu ada bağlar ve kimsenin almasını engeller',
    id_show: 'KODUMU GÖSTER',
    id_reserve: 'AYIR',
    id_taken: 'bu ad zaten alınmış',
    id_taken_help: 'senin ise, kurtarma kodunu gir',
    id_link: 'BAĞLA',
    id_linked: 'cihaz {n} adına bağlandı',
    id_bad_code: 'yanlış kod',
    id_unknown: 'bilinmeyen ad',
    id_link_title: 'BAŞKA BİR CİHAZ MI?',
    id_link_help: 'sürelerini ve geçmişini burada bulmak için adını ve kodunu gir',

    install_title: 'OYUNU KUR',
    install_why: 'tam ekran, tarayıcı çubuğu yok, ve çevrimdışı oynanır',
    install_do: 'KUR',
    install_later: 'sonra',
    install_ios_1: 'Şuna dokun:',
    install_ios_2: 'Paylaş',
    install_ios_3: 'Safari’nin altında, sonra',
    install_ios_4: 'Ana Ekrana Ekle',

    mode_career_s: 'kariyer',
    mode_oneshot_s: 'one shot',
    cat_race_sub: 'tek bir yarıştaki en iyi süre',
    cat_run_sub: 'altı etabın toplamı',
    empty_cat_run: 'henüz kayıtlı tam parkur yok',
    will_enter: '{s} s: TOP 500 listesinde {r}, adını ekle',

    wr_title: 'DÜNYA REKORU',
    wr_sub: '{d} m’de dünyanın en iyi süresi',
    wr_old: 'önceki rekor: {s} s',
    wr_first: 'tabeladaki ilk süre',
    wr_gain: '{s} s daha hızlı',
    wr_save: 'ADIMI YAZ',
    wr_saving: 'kaydediliyor...',
    wr_done: '{n} TOP 500 listesinde {r}',
    wr_fail: 'gönderilemedi, tekrar dene',
    wr_see: 'TOP 500 LİSTESİNİ GÖR',
    wr_later: 'sonra',
    os_top_checking: 'sıralamalar kontrol ediliyor...',
    os_top_none: 'hiçbir süre TOP 500’e giremiyor',
    os_top_intro: '{n} süre TOP 500’e giriyor',
    os_top_intro_n: '{n} süre TOP 500’e giriyor',
    os_top_line: '{d} m — {s} s — {r}',
    os_top_saved: 'süreler {n} adıyla kaydedildi',
    top500_count: '500 sürenin {n} tanesi sıralamada',
    os_top_better: '{d} m rekorun {s} s olarak kalıyor',
    os_kept_title: 'REKORUN AYAKTA',
    os_kept_line: '{d} m: elinde zaten {s} s var (TOP 500’de {r})',
    os_kept_now: 'bu {s} s onu geçmiyor — sıralama yalnızca en iyini tutar',

    pause_title: 'YARIŞ DURAKLADI',
    pause_note: 'şimdi çıkmak, sürmekte olan süreden vazgeçmek demektir',
    resume: 'DEVAM ET',

    challenge_them: 'MEYDAN OKU',
    target_run: '{d} m’ni koş: meydan okuma {n} kişisine gidiyor',
    target_sent: 'meydan okuma {n} kişisine gönderildi',
    inbox_one: 'MEYDAN OKUMA GELDİ',
    inbox_many: '{n} MEYDAN OKUMA GELDİ',
    inbox_from: '{n} sana {d} m’de meydan okuyor',
    inbox_accept: 'KABUL ET',
    inbox_later: 'sonra',
    run_total_short: 'tam parkur:',
    run_total_tiny: 'parkur',
    best_split_tiny: 'yarış',
    score_saved_race: 'dünya TOP 500 listesinde {s} s ile {r}',
    mode_career: 'KARİYER',
    mode_oneshot: 'ONE SHOT',
    mode_versus: 'MEYDAN OKUMA',
    career_desc: 'altı etap arka arkaya, tek bir süre',
    oneshot_desc: 'branşlarını seç, tek bir deneme',
    versus_desc: 'başka bir oyuncunun hayaletine karşı koş',
    pick_events: 'BRANŞLAR',
    pick_level: 'SEVİYE',
    pick_none: 'en az bir branş seç',
    launch_oneshot: 'HADİ',
    event_n: 'BRANŞ {n} / {t}',
    next_event: 'SONRAKİ BRANŞ',
    oneshot_done: 'ONE SHOT TAMAMLANDI',
    total_in: 'toplam: ',
    challenge_code: 'MEYDAN OKUMA KODU',
    challenge_enter: 'sana verilen kodu gir',
    challenge_load: 'YÜKLE',
    challenge_loading: 'meydan okuma yükleniyor...',
    challenge_bad: 'kod bulunamadı',
    challenge_net: 'bağlantı kurulamadı, tekrar dene',
    challenge_from: '{n} kişisinden meydan okuma',
    challenge_beat: 'geçilecek: {s} s',
    challenge_aveugle: 'onun süresini koşarken öğreneceksin',
    challenge_accept: 'MEYDAN OKUMAYI KABUL ET',
    challenge_make: 'BİR ARKADAŞINA MEYDAN OKU',
    challenge_making: 'meydan okuma oluşturuluyor...',
    challenge_share: 'bu kodu gönder, arkadaşın senin hayaletine karşı koşsun',
    challenge_copy: 'BAĞLANTIYI KOPYALA',
    challenge_copied: 'bağlantı kopyalandı',
    challenge_copy_code: 'KODU KOPYALA',
    share_send: 'MEYDAN OKUMAYI GÖNDER',
    share_whatsapp: 'WhatsApp',
    share_sms: 'SMS',
    share_other: 'Snapchat, Instagram…',
    share_other_hint: 'Snapchat ve Instagram paylaşım menüsünden açılır.',
    affiche_share: 'PARKURUMU PAYLAŞ',
    affiche_making: 'Görsel hazırlanıyor…',
    affiche_saved: 'görsel kaydedildi',
    affiche_failed: 'görsel oluşturulamadı',
    affiche_hint: 'parkurunun bir görseli, Instagram ya da TikTok için',
    code_copied: 'kod kopyalandı',
    challenge_rematch: 'KARŞI MEYDAN OKU',
    challenge_rematch_sub: 'kazandın — az önce yaptığın parkurda ona meydan oku',
    challenge_won: 'MEYDAN OKUMA KAZANILDI',
    challenge_lost: 'MEYDAN OKUMA KAYBEDİLDİ',
    challenge_gap: 'fark: {s} s',
    ghost_label: 'HAYALET',
    you_label: 'SEN',
    dnf_short: 'BRK',
    composing: 'müzik besteleniyor...',

    sound_off: 'SES KAPALI  (S)',
    press_enter: 'ENTER’a bas',
    skip_now_kb: 'geçmek için tekrar ENTER’a bas',
    skip_twice_kb: 'geçmek için iki kez ENTER’a bas',
    stage_dash: 'ETAP {n}   -   {s}',
    furthest_kb: 'ulaşılan en uzak etap: {b} etaptan {a}',
    enter_start: 'ENTER: başla   -   S: ses   -   L: dil   -   ESC: çık',
    how_to_play: 'NASIL OYNANIR',
    help_1: 'Aynı tuşu tekrarlamadan  <-  ve',
    help_2: '->  tuşlarına sırayla bas.',
    help_3: 'Düzenli tempo hız kazandırır;',
    help_4: 'tekrar seni tökezletir, ama',
    help_5: 'her zaman yeniden hızlanabilirsin.',
    best_stage: 'BU ETABIN EN İYİ SÜRELERİ',
    no_time: 'henüz kayıtlı süre yok',
    arrows_pick: 'seçmek için oklar   -   onaylamak için ENTER   -   ',
    yn_short: 'kısayol E / H',
    you_beat: '{w} rakibini geçtin ve altı etabı da tamamladın.',
    the_zeze: 'ZEZE’ler',
    your_times: 'SÜRELERİN',
    total: 'TOPLAM',
    enter_replay: 'ENTER: tekrar koş      M: ana ekran',
    stumble_kb: 'TÖKEZLİYORSUN!',
    go_kb: 'MARŞ!',
    to_beat_line: 'GEÇİLECEK:  {n}   -   {s} s',
    best_times_of: 'EN İYİ SÜRELER  -  {s}',
    enter_next: 'ENTER   ->   ETAP {n}: {s}',
    full_run_pc: 'tam parkur {s} s',
    announced_pc: 'açıklanan süre: {s} s',
    quit: 'ESC: çık'
  },

  CUTS: {
    intro: [
      [ // etap 1
        ['{n} üç yıldır bahçedeki bütün yarışları kazanıyor.',
         'Sırrı şu: kimse onu geçmeye cesaret edemiyor, top onun.',
         'İlke gereği okul ayakkabısıyla ısınıyor.',
         'Annesi tel örgünün arkasından çekiyor. Çoğunlukla tel örgüyü.'],
        ['{n} okul rekorunun sahibi, spor salonunun duvarına keçeli kalemle yazılmış.',
         'Bir sınıf arkadaşı tuttu süreyi, akrepli bir saatle.',
         'Beden öğretmeni bir kez başını salladı. Resmiyet böyle kazanıldı.',
         'Artık duvarı rekorun etrafından boyuyorlar.'],
        ['{n} 4. kulvarı istedi. 4. kulvar verildi.',
         'Alıştırmalarını yapıyor: diz çekme, topuk vurma, derin iç çekişler.',
         'Göğüs numarasını evde basmış, hafif eğri.',
         'Numara 1. Kendi bastı, tek başına.']
      ],
      [ // etap 2
        ['{n} dört saattir ısınıyor.',
         'Eşofmanının sırtında adı işlenmiş, büyük harflerle.',
         'Bir ritüeli var: üç adım geri, bir nefes, bir göz kırpma.',
         'Göz kırpma kimseye özel değil.'],
        ['{n} iki çift kramponla ve bir buzlukla geliyor.',
         'Buzlukta bir muz ve son derece bol miktarda kararlılık var.',
         'Takozları milimetrik ayarlıyor, sonra baştan ayarlıyor.',
         'Bir üçüncü kez daha. Starter bekliyor, nazikçe.'],
        ['{n} geçen yıl bölgesel yarışta ikinci oldu.',
         'Bunu ters rüzgârın çaldığı bir zafer diye anlatıyor.',
         'Resmî ölçüm rüzgârsız dedi. O ölçüme itiraz ediyor.',
         'Kendi rüzgâr ölçerini getirmiş. Kullanmayı bilmiyor.']
      ],
      [ // etap 3
        ['{n} bölgesel televizyona çıktı.',
         'Otuz sekiz saniyelik görüntü. Altı yüz kez izledi.',
         'Zamandan kazanmak için yarıştan önce imza dağıtıyor.',
         'Market fişlerine, daha iyisi olmadığı için.'],
        ['{n} kimsenin kullanmadığı bir lakaba sahip: Kuzeyin Oku.',
         'Her röportaja bunu kendi sıkıştırıyor.',
         'Spiker az önce onu yanlışlıkla gerçek adıyla anons etti.',
         'Hoparlörden düzeltme istedi. Sonra gelecek.'],
        ['{n} kişisel rekorunu ön koluna dövme yaptırdı.',
         'Sporcu tanıtımında ağır çekimde gösteriyor.',
         'Bu finaldeki dört koşucu o sayıyı çoktan geçti.',
         'Dövme ne yazık ki kendini güncellemiyor.']
      ],
      [ // etap 4
        ['{n} bir sponsoru, bir menajeri ve bir fizyoterapisti var.',
         'Üçü de ona yenilmez diyor. Üçüne de o para ödüyor.',
         'Menajeri zafer basın toplantısı için salonu bile ayırttı.',
         'İkram sipariş edildi. Kanepeler var.'],
        ['{n} on bir aydır dünyanın bir numarası.',
         'Canlı yayında öğrendi ve o günden beri hiç arkasına bakmadı.',
         'Kelimenin tam anlamıyla: fizyoterapisti şiddetle önerdi bunu.',
         'Şimdi bütün gövdesini çeviriyor. Daha yavaş, ama şık duruyor.'],
        ['Spiker {n} adını anons ediyor. Stat ayağa kalkıyor.',
         'Tribünü gösteriyor, sonra gökyüzünü, sonra kamerayı.',
         'Kamera başka bir sporcudaydı. Her şeye baştan başlıyor.',
         'Yönetmen boyun eğiyor. Hareket on bir saniye sürecek.']
      ],
      [ // etap 5
        ['{n} sevinç gösterisini sekiz aydır prova ediyor.',
         'Marka olarak tescil ettirdi. Geriye sadece yarışı kazanmak kaldı.',
         'Kırk kişilik bir koro onun işaretini bekliyor.',
         'Bir şarkı öğrendiler. Şarkı onun adını söylüyor, uzun uzun.'],
        ['{n} ülkesinin renklerini taşıyor ve bunu gerçekten önemsiyor.',
         'Bayrak kramponlarda, göğüs numarasında ve havluda.',
         'Havlu koşmuyor ama salıdan beri hazır bekliyor.',
         'Ekipten biri açılış töreninden beri onu her yere taşıyor.'],
        ['{n} takozlarda rakiplerine bakmayacağına yemin etmişti.',
         'Bu yüzden dosdoğru ileriye bakıyor, dikkat çekici bir yoğunlukla.',
         'Biraz fazla ileriye: tanıtım sırasında duvara bakıyordu.',
         'Duvar bu finale kalamamıştı.']
      ],
      [ // etap 6
        ['{n} yerçekiminin isteğe bağlı olduğu bir evrenden geliyor.',
         'Yarışlarını, onlara başlamaya karar vermeden önce bitiriyor.',
         'Rekoru aynı anda on bir boyutta geçerli.',
         'On ikincide tökezledi ama kimse bunu açmıyor.'],
        ['{n} bu yüz metreyi on bir paralel evrende koştu.',
         'On birini de kazandı. On ikincisi hiç onaylanmadı.',
         'Oradaki varış hakemi bir bulutsuydu, çizgide güvenilmez.',
         'Bulutsu üç sezon men edildi.'],
        ['ZEZE ailesi yedi kulvarın hepsini dolduruyor. Bu kurallara uygun.',
         'Kendi starterlarını, kendi rüzgârlarını, kendi varışlarını getirdiler.',
         'Talimatı bir ZEZE yazdı ve bir ZEZE gözden geçirdi.',
         'Tek cümle uzunluğunda: bir ZEZE kazanır.']
      ]
    ],

    defeat: [
      [ // etap 1
        ['{n} sonuca yemekhane nöbetçisi nezdinde itiraz ediyor.',
         'Nöbetçi sandviç yiyor. Sonuç değişmiyor.',
         'Sonra sınıf başkanından bir karar istiyor.',
         'Sınıf başkanı sonuncu oldu. Bundan keyif alıyor.'],
        ['{n} bahçe zemininin bozuk olduğunu açıklıyor.',
         'Zemin bin dokuz yüz altmıştan beri herkes için bozuk.',
         'Sonra çözülmüş bir bağcıktan söz ediyor. Ayakkabıları cırt cırtlı.',
         'Öğretmen senin süreni duvara yazıyor. Tam onunkinin üstüne.'],
        ['{n} aslında koşmadığını duyuruyor.',
         'Isınıyormuş. Asıl yarış bir sonrakiymiş.',
         'Kimseye söylenmemişti, ki bu çok şeyi açıklıyor.',
         'Zil çalıyor. Sonraki yarış hiçbir zaman olmayacak.']
      ],
      [ // etap 2
        ['{n} saatinin hiç çalışmadığını açıklıyor.',
         'Yani teknik olarak bu yarış hiç yapılmadı.',
         'Hemen şimdi tekrarlamayı öneriyor, ciddi insanlar arasında.',
         'Sonra bir treni olduğunu hatırlıyor. Hiç treni yok.'],
        ['{n} varış fotoğrafını görmek istiyor.',
         'Fotoğrafı gösteriyorlar. Açıkça geride ve gayet net.',
         'Aynı fotoğrafı başka bir açıdan istiyor.',
         'O açıdan hâlâ geride, sadece biraz daha bulanık.'],
        ['{n} iki çift kramponu tek kelime etmeden topluyor.',
         '400’e geçeceğini duyuruyor, daha taktik bir branş.',
         'Sonra 800. Sonra maraton, nasılsa her şey orada bitiyor.',
         'Buzluğuyla gidiyor. Muza dokunulmamış.']
      ],
      [ // etap 3
        ['{n} canlı yayında bıraktığını duyuruyor.',
         'Sonra fikrini değiştiriyor: pazartesi antrenmana dönüyor.',
         'O pazartesinin özellikle yoğun olduğunu belirtiyor.',
         'Sonraki pazartesi de öyleymiş, anlaşıldığı kadarıyla.'],
        ['{n} kazanan için doping testi talep ediyor.',
         'Sonra adalet olsun diye kendisi için de.',
         'İkisi de negatif çıkıyor. Bunu şüpheli buluyor.',
         'Üçüncü bir test istiyor. Zaman ölçüm cihazından.'],
        ['{n} gazetecilere ön kolunu gösteriyor.',
         'Dövmeli rekor yerinden kıpırdamamış. Yine de bir şey.',
         'Altı haftalık yükseklik kampı duyuruyor.',
         'Seçtiği dağ iki yüz metre yüksekliğinde.']
      ],
      [ // etap 4
        ['{n} ikinci bir rüzgâr ölçümü talep ediyor.',
         'Rüzgâr çağrılıyor. Rüzgâr gelmiyor.',
         'Zafer basın toplantısı yine de yapılıyor, artık iptal edilemiyor.',
         'Kanepeler nefis. Bu da bir şey.'],
        ['{n} dev ekrana yirmi saniye bakıyor.',
         'Sıralama değişmiyor. Ekran da değişmiyor.',
         'Görüntünün canlı olup olmadığını soruyor. Canlı diyorlar.',
         'O zaman gecikmeli bir yayın var mı diye soruyor. Yok.'],
        ['Karma bölgede {n} gelişimden ve süreçten söz ediyor.',
         'İki dakikada on bir kez döngü kelimesini kullanıyor.',
         'Bir gazeteci süresini soruyor. Yanıtlıyor: süre gelecek.',
         'Süresi arkasındaki tabelada zaten yazıyor, kocaman.']
      ],
      [ // etap 5
        ['{n} sevinç gösterisini yine de yapıyor.',
         'Seyirci alkışlıyor, nezaketen.',
         'Koro, yanlış bilgilendirilmiş, şarkıya giriyor.',
         'Kırk kişi adını söylüyor. Sessizliği tercih ederdi.'],
        ['{n} planlandığı gibi bayrakla onur turuna çıkıyor.',
         'Kazanan aynı turu ters yönde atıyor.',
         'İki kez karşılaşıyorlar. İkincisi daha kötü.',
         'Havlu bunu beklemiyordu.'],
        ['{n} podyumun ikinci basamağına çıkıyor.',
         'Kazananı çok uzun bir el sıkışmayla tebrik ediyor.',
         'Resmî fotoğrafın üç kez tekrarlanmasına yetecek kadar uzun.',
         'Üçüncüsünde gülümsüyor. Kendisine neye mal olduğu görülüyor.']
      ],
      [ // etap 6
        ['{n} kendi galaksisinin yörüngesini yeniden hesaplıyor.',
         'Yörünge tam da ikinci sıradan geçiyormuş.',
         'Zamansal bir anomali öne sürüyor, sonra ayakkabı sorunu.',
         'İki açıklama birbirini çürütüyor. İkisini de tutuyor.'],
        ['{n} diğer on bir evrenin sıralamalarını istiyor.',
         'On birinde de az önce kaybetmiş. Aynı anda.',
         'Sırf görmek için bir on ikincisini açmayı öneriyor.',
         'On ikincisi dolu. Orada da birinci sen oldun.'],
        ['Diğer altı ZEZE {n} kişisine çok sakin bakıyor.',
         'Kimse tek kelime etmiyor. Sessizlik dört ışık yılı sürüyor.',
         '{n} sonunda öneriyor: bugün zemin farklıydı.',
         'Zemin pist yapıldığından beri hiç değişmedi.']
      ]
    ],

    taunt: [
      [ // etap 1
        ['{n} tek kelime etmeden skor tabelasını gösteriyor.',
         'Çoktan imzalamış bile. Silinmez kalemle.',
         'Sana sandviçini uzatıyor. "Yolda yersin", diyor.',
         'Sen hiç sandviç istememiştin.'],
        ['{n} onur turu atıyor. Yer olmadığından üç metre.',
         'Hayalî bir seyirciye uzun uzun el sallıyor.',
         'Sana rövanş öneriyor. Sonra saatine bakıyor.',
         'Saati yok. Hareket her şeyi söyledi.'],
        ['{n} eşyalarını sakin sakin topluyor, ıslık çalarak.',
         'Melodi senin adın, zafer marşı düzeninde.',
         'Omzuna vuruyor. "Bir dahaki sefere", diyor.',
         'Buna bir saniye bile inanmıyor, ve bu belli oluyor.']
      ],
      [ // etap 2
        ['{n} saate bakıyor, sonra sana bakıyor, anlamlı bir bakışla.',
         'Hiçbir şey söylemiyor. Sessizlik sözlerden daha acımasız.',
         'İmza dağıtıyor. İlki senin için.',
         'Onu da istememiştin.'],
        ['{n} antrenörünü arıyor. "Erken bitirdik", diyor.',
         'Antrenör nedenini soruyor. "Nezaketen", diye yanıtlıyor.',
         'Madalyasını tutmana izin veriyor. Sadece bir an.',
         'An on dakika sürüyor. Fotoğraf çekiyor.'],
        ['{n} kramponlarını üstünde senin adın yazan bir kılıfa koyuyor.',
         'Bu aramızda bir espri. Seyirci takip edemiyor.',
         'Matarasından su ikram ediyor. Matara boş.',
         'Hareket, diyor, sudan daha önemli.']
      ],
      [ // etap 3
        ['{n} kameraya el sallıyor. Sonra sana el sallıyor.',
         'İkinci selam gözle görülür biçimde daha az dostane.',
         'Yarışını gazetecilerle ayrıntılı biçimde konuşuyor.',
         'En sevdiği ayrıntı: arkana baktığın an.'],
        ['{n} mikrofon istiyor. Akla aykırı biçimde veriyorlar.',
         'Ailesine, kulübüne ve sana teşekkür ediyor, bu sırayla.',
         '"O olmasaydı", diyor, "tadı aynı olmazdı".',
         'Ne demek istediğini söylemiyor. Söylemesine gerek yok.'],
        ['{n} yarışını birlikte sakin sakin izlemeyi öneriyor.',
         'İnceleme tek kelime uzunluğunda. Çok yavaş söylüyor.',
         'Emin olmak için elini arka arkaya iki kez sıkıyor.',
         'İlki yeterince inandırıcı gelmemiş.']
      ],
      [ // etap 4
        ['{n} röportaj veriyor. Konu, ilginçtir, sensin.',
         'Üç dakika. Kendi yarışı hakkında tek kelime yok.',
         'Çok şey öğrendiğini söyleyerek bitiriyor. Senin yenilginden.',
         'Gazeteci kelimesi kelimesine yazıyor, rahatsız.'],
        ['{n} menajerine palmaresine bir satır eklemesi için işaret ediyor.',
         'Satırda sadece şu yazıyor: sana karşı, bir kez daha.',
         'Seni zafer basın toplantısına davet ediyor.',
         'Seni bir sandalye bekliyor, en arkada, mikrofonsuz.'],
        ['{n} sıralamayı telefonunda gösteriyor, yakınlaştırarak.',
         'Uzun süre yakınlaştırıyor. Senin satırın onunkinin çok altında.',
         '"Sana e-postayla yollayabilirim", diye yardımcı oluyor.',
         'Ona adresini hiç vermedin. O zaten sahip.']
      ],
      [ // etap 5
        ['{n} tribünlere el sallıyor, sonra ciddiyetle sana dönüyor.',
         'Ardından yaptığı hareket hiçbir talimatta yer almıyor.',
         'Bir gazeteci yenilen rakip için iki kelime istiyor.',
         'Yedi kelime söylüyor. Hiçbiri habere girmeyecek.'],
        ['{n} podyuma çıkıyor, sonra bir basamak iniyor.',
         'Madalyayı yakından görmeye davet ediyor.',
         'Çok yakından. Altın. Bu noktanın altını çiziyor.',
         'Marş başlıyor. Sana bakarak yüksek sesle söylüyor.'],
        ['{n} zaferini ailesine, sponsorlarına ve sana adıyor.',
         '"Böyle motive edici bir rakip olmasaydı", diyor, içtenlikle.',
         'Motive edici kelimesi ustaca gizlenmiş bir hakaret gibi düşüyor.',
         'Seyirci alkışlıyor, neden kızardığını anlamadan.']
      ],
      [ // etap 6
        ['{n} diğer altı ZEZE’ye bakıyor. Hepsi birlikte başını sallıyor.',
         'Karar oybirliğiyle ve tek bir ses çıkmadan veriliyor.',
         'Ölü bir dilde bir anma plaketi kazınıyor.',
         'Özetle şöyle diyor: denedi. O da bir şey.'],
        ['{n} senin konumunu on bir farklı boyutta yeniden hesaplıyor.',
         'Hepsinde sonuç aynı, saniyesi saniyesine.',
         'Sana kazandığın evrenin haritasını veriyor.',
         'O evren, diye ekliyor, henüz yok.'],
        ['{n} elini gökyüzüne uzatıyor. Bir galaksi uysalca yanıyor.',
         'Bir an için onun gülümsemesinin biçimini alıyor.',
         'Yedi ZEZE aralarında konuşuyor, sonra sana dönüyor.',
         'Ardından gelen sessizlik dört ışık yılı sürüyor. Nazikçe.']
      ]
    ],

    champion: [
      ['Yedi ZEZE uzun uzun görüşüyor.',
       'Hiçbiri kabul edilebilir bir bahane bulamıyor. Bu bir ilk.',
       'Sıralama on dört milyar sistemde güncelleniyor.',
       'Varış çizgisine bir plaket konuyor.',
       'Adın üstünde yanlış yazılmış, ama yazılmış.'],
      ['Spiker bir kelime arıyor. Hiçbiri yeterince büyük değil.',
       'Sadece süreyi okuyor, iki kez, emin olmak için.',
       'Yedi ZEZE dev ekrana tek kelime etmeden bakıyor.',
       'Varış çizgisini incelemek için bir komisyon kuruluyor.',
       'Çizgi düz. Sıralama da öyle.'],
      ['Onur turu yarışın kendisinden uzun sürüyor.',
       'Bu basit bir aritmetik ve kimse şikâyet etmiyor.',
       'Sana bir bayrak uzatıyorlar. Hangi galaksiden geldiğini bilmiyorsun.',
       'Hepsinden geliyor: desenler bu vesileyle birleştirildi.',
       'Koro şarkısını yeniden yazdı. Sonunda senin adını söylüyor.']
    ]
  }
};
