/* -----------------------------------------------------------------------
   SPRINTER — 中文（简体）.
   Ce qui manque ici retombe sur l'anglais, cle par cle : voir
   sprinter-i18n.js. Verification : node tools/langues-verifier.mjs zh
   ----------------------------------------------------------------------- */
export default {
  // place 键已写成「第{o}名」，这里只返回数字。
  ord(n) { return String(n); },

  LEVEL_NAMES: [
    '校内比赛', '地区级别', '全国级别',
    '世界锦标赛', '奥林匹克运动会', '星系之间'
  ],

  RACE_SUB: {
    '100': '直道',
    '200': '弯道加直道',
    '400': '绕场一圈'
  },

  UI: {
    races: '100 - 200 - 400 米',
    tagline: '六个阶段，只有一个成绩要超越',
    tap_start: '点击屏幕开始',
    six_stages: '   -   六个阶段',
    six_stages_bare: '六个阶段',
    best_runs: '最佳跑程',
    no_run: '还没有完成过任何跑程',
    furthest: '最远阶段：',
    of_six: ' / 6',
    start: '开始',
    sound: '声音：',
    yes: '开',
    no: '关',

    rival: '要击败的对手',
    favourite: '夺冠热门',
    after_race: '比赛之后',
    crowned: '星系之间的冠军',
    fastest_1: '最快的生灵',
    fastest_2: '在所有星系中',
    full_run_in: '全程成绩 ',
    announced: '公布成绩：',
    stage_up: '阶段 ',
    six_cleared: '六个阶段全部通过',
    skip_now: '再点一次跳过',
    skip_twice: '点两次跳过',

    reaction: '反应',
    react_top: '完美反应',
    false_start: '起跑太早',
    wait_gun: '等待枪声',
    phase_drive: '加速',
    phase_trans: '转换',
    phase_max: '最高速度',
    drive_hint: '稳住你的节奏',
    trans_2: '完美转换',
    trans_1: '不错的转换',
    trans_0: '转换失误',
    start_line: '起跑：反应 {r} 秒   -   {g}',
    no_start: '起跑失误',

    stumble: '你绊了一下',
    to_beat: '目标：',
    to_race: '你的对手是 ',
    ready: '各就位',
    get_set: '预备',
    go: '跑',
    alternate: '交替按两个按钮',
    alternate_kb: '交替按两个方向键',
    you: '你',
    opponent: '对手',
    depart: '起点',
    arrivee: '终点',

    stage_done: '阶段 {n} 通过',
    first_in: '第一名，成绩 ',
    total_of: ' 秒   -   合计 ',
    place: '第{o}名',
    dnf: '退赛',
    unfinished: '未完成',
    race_again: '再来一次？',
    next_stage: '阶段 {n}',
    home: '主页',
    replay: '再玩一次',
    run_done: '跑程完成',
    six_in: '六个阶段全部通过，用时 ',
    stage_low: '阶段 ',

    new_record: '个人新纪录',
    top3: '前三名',
    top10: '前十名',
    best_run: '最佳跑程',
    top3_runs: '跑程前三名',
    top10_runs: '跑程前十名',

    top500: 'TOP 500 - 历史总榜',
    your_name: '你的名字',
    save_score: '保存我的成绩',
    saving_score: '发送中...',
    score_saved: '世界 TOP 500 第 {r} 名',
    score_save_fail: '发送失败，请稍后再试',
    score_name_taken: '这个名字属于另一台设备',
    score_taken_help: '换一个名字，或在「我的比赛」里用恢复码把这台设备连到你的名字上',
    view_top500: '查看 TOP 500',
    top500_court: 'TOP 500',
    close: '关闭',
    loading_ranks: '正在载入排行榜...',
    empty_top500: '目前还没有成绩记录',
    your_rank: '你的名次：{r}',
    outside_top500: '在前 500 名之外',
    edit_name: '修改名字',
    best_split_short: '最佳阶段：',
    top500_sub: '单场比赛的最佳成绩',
    cat_race: '按项目',
    cat_run: '完整跑程',
    cat_mine: '我的比赛',
    cat_mine_sub: '你跑过的所有比赛',
    mine_empty: '这个项目还没有比赛',
    mine_count: '{n} 场比赛 — 最佳：{s} 秒',
    mine_note: 'TOP 500 只保留你在每个项目的最佳成绩；这份记录保留全部。预留你的名字，就能在其他设备上找回它。',

    duel_title: '对决排行榜',
    duel_sub: '发出的和应答的挑战',
    duel_open: '查看对决排行榜',
    duel_rules_init: '挑战已发出',
    duel_rules_recv: '挑战已应答',
    duel_rules_line: '胜 {v}   ·   负 {d}   ·   平 {n}',
    duel_rules_all: '无论发出还是应答，每一场对决都计入',
    duel_rules_why: '发起挑战的人，要先亮出自己的成绩',
    duel_counts: '发出 {l} · 应答 {r}',
    duel_sur: '对决项目',

    name_set: '取一个名字',
    name_title: '你的名字',
    name_why: '它会出现在 TOP 500、你的挑战和对决里',
    name_save: '保存',
    name_saved: '已保存',
    name_taken: '这个名字已被占用',
    name_code: '你的恢复码',
    pays_title: '你的国籍',
    pays_opt: '只能选一次',
    pays_aucun: '选择你的国家',
    pays_why: '参加全国锦标赛需要它 — 之后无法更改',
    pays_vu: '看起来你从 {pays} 连接 — 由你决定',
    pays_save: '选定',
    pays_confirm: '代表 {pays} 参赛？\n\n这是最终决定：它决定你进入哪个全国锦标赛，且无法更改。',
    pays_fige: '已确定',
    pays_on: '你代表这个国家参赛 — 锦标赛上国旗会跟着你的名字',
    pays_deja: '国籍已经选定，无法更改',
    pays_first: '请先保存你的名字',
    pays_bad: '无效的国家',
    insta_title: '你的 Instagram',
    insta_ph: '你的用户名，不带 @',
    insta_why: '别人可以从 TOP 500 和你的挑战里打开你的主页',
    insta_note: '由你自行填写，未经核验 — Instagram 已不再允许个人账号真正登录',
    insta_link: '关联我的账号',
    insta_linked: '账号已关联',
    insta_unlink: '取消关联',
    insta_on: '你的主页出现在 TOP 500 上 — 点击即可打开',
    insta_gone: '已取消关联，你的主页不再出现在任何地方',
    insta_bad: '无效的用户名',
    insta_first: '请先保存你的名字',
    insta_notyours: '在这台设备上，这个名字不属于你',
    insta_visit: '查看 {n} 的 Instagram 主页',
    name_code_why: '记下它：在别的手机上能找回你的名字和比赛',

    tour_open: '看看导览',
    tour_1_t: '交替',
    tour_1_s: '左，右，左。整场比赛就这么简单。',
    tour_2_t: '生涯',
    tour_2_s: '六个阶段，从学校操场到星系之间的决赛',
    tour_3_t: 'TOP 500',
    tour_3_s: '你的成绩，对上整个世界',
    tour_4_t: '幽灵',
    tour_4_s: '把你的比赛发给朋友 — 他会和你同场竞跑',
    tour_5_t: '实时',
    tour_5_s: '同一声枪响，各自用自己的手机',
    tour_play: '让我开始玩',

    os_tuto_open: '这个模式有什么用',
    os_tuto_1_t: '选择你的项目',
    os_tuto_2_t: '只有一次机会',
    os_tuto_3_t: '你的成绩会被记录',
    os_tuto_1_s: '一项、两项，或者三项全选',
    os_tuto_2_s: '不能重来，也不会淘汰',
    os_tuto_3_s: 'TOP 500，朋友也可以接下这一战',
    os_tuto_go: '开始 ONE SHOT',

    tuto_ask_t: '第一场比赛',
    tuto_ask_s: '这个操作三十秒就能学会',
    tuto_ask_yes: '学习操作',
    tuto_ask_no: '让我直接跑',
    tuto_watch: '看',
    tuto_your_turn: '轮到你了',
    tuto_1_t: '交替',
    tuto_2_t: '随枪声起跑',
    tuto_3_t: '先大，再小',
    tuto_v_early: '太早了',
    tuto_v_late: '太晚了',
    tuto_v_perfect: '完美',
    tuto_v_good: '不错',
    tuto_v_slow: '速度还不够',
    tuto_v_flat: '节奏太平',
    tuto_replay_demo: '再看一次',
    tuto_again: '再来',
    tuto_next: '下一步',
    tuto_done_t: '该你上场了',
    tuto_start: '开始',
    tuto_replay: '再看一次',
    tuto_skip: '跳过',
    tuto_open: '怎么玩',

    live_title: '实时比赛',
    live_desc: '你们随同一声枪响起跑，各自用自己的手机 — 没有幽灵，谁赢没人知道',
    live_create: '开一条跑道',
    live_join: '加入',
    live_or: '或者',
    live_room: '跑道已开放',
    live_waiting: '把这个代码发给对手 — 两人到齐就开跑',
    live_ready: '准备好了',
    live_notready: '还没有',
    live_empty_seat: '分道空着 — 等待对手',
    live_go: '我准备好了',
    live_unready: '取消',
    live_leave: '离开跑道',
    live_none: '没有这个代码的跑道',
    live_full: '这条跑道已经满了',
    live_gone: '你的对手离开了跑道',
    live_closed: '连接已中断',
    live_invite: '我在跑道上等你。代码 {c} — {l}',

    relais_titre: '4 × 100 接力',
    relais_desc: '四名跑者，一根接力棒。一支队伍就是它的阵容：同样的四个名字，同一支队伍。',
    relais_invitations: '你收到了邀请',
    relais_mes_equipes: '你的队伍',
    relais_creer: '组建队伍',
    relais_nom_equipe: '队伍名称',
    relais_coequipier: '队友 {n}',
    relais_inviter: '邀请这三位',
    relais_incomplet: '还缺一个名称和三名队友',
    relais_attend: '等待中',
    relais_ok: '已加入',
    relais_refuse: '已拒绝',
    relais_fixer_ordre: '确定跑动顺序',
    relais_manque_reponses: '开跑前还差一些回复',
    relais_manque_refus: '有队友拒绝了 — 这支队伍无法参赛',
    relais_prete: '队伍已就位',
    relais_classement: '队伍排行榜',
    relais_plein_titre: '最多两支队伍',
    relais_plein: '你已经在两支队伍里跑。要另组一支，请先退出你已不再效力的那支。',
    relais_plein_invit: '你已经在两支队伍里跑 — 退出一支才能接受这个邀请。',
    relais_quitter: '退出',
    relais_quitter_sur: '要彻底退出吗？',
    relais_quitter_sub: '只有收到新邀请才能回来',
    relais_reste: '还剩一个位置',
    relais_place: '2 支队伍中的 1 支',
    relais_places: '2 支队伍中的 {n} 支',
    relais_courir: '去跑道',
    relais_mon_rang: '你跑第 {n} 棒',
    relais_premier: '你从起跑器站立起跑。抢跑会让全队被取消资格。',
    relais_ta_marque: '你在接力区的标记',
    relais_zone_debut: '入口',
    relais_zone_fin: '出口',
    relais_marque_conseil: '标记越靠前起动越快，但可能在接到棒之前就跑出接力区。越靠后一定能接到 — 只是从静止开始。',
    relais_attend_equipe: '还差 {n} 名队友',
    relais_temoin_a: '接力棒在',
    relais_spectateur: '其他人正在跑',
    relais_porte: '持棒',
    relais_attends_temoin: '等待',
    relais_prends: '接棒',
    relais_donne: '交棒',
    relais_arrivee: '接力完成',
    relais_elimine: '队伍被取消资格',
    relais_elimine_pourquoi: '第 {r} 棒：{c}',
    relais_passages: '三次交接',
    relais_elimine_court: '出局',
    relais_fantome: '幽灵',

    conf_titre: '与其他队伍同场竞跑',
    conf_desc: '一声枪响，一份名次。开一个代码分享出去，或输入别人给你的代码。',
    conf_ouvrir: '发起一场对抗',
    conf_rejoindre: '加入',
    conf_code: '代码',
    conf_code_court: '这个代码太短了',
    conf_partage: '把这个代码分享给其他队伍',
    conf_places: '跑道上有 {n} 支队伍',
    conf_engagees: '{m} 支队伍中的 {n} 支',
    conf_attend_adversaire: '至少还需要一支队伍，或者一个幽灵',
    conf_classement: '到达顺序',
    conf_encore: '其他人还在跑',

    fantome_titre: '挑战最好的十次跑程',
    fantome_desc: '它们已经跑过了：只会重放，既不会被取消资格，也不会在交接处被超越。这是不召集八个人就能与最强者较量的唯一方式。',
    fantome_aucun: '还没有记录在案的跑程 — 第一支完成接力的队伍将开这个头。',
    fantome_choisis: '已选 {n} / {m}',
    fantome_defier: '向他们挑战',

    champ_directs: '前 {n} 名晋级',
    champ_reveal: '跑得最快的败者',
    champ_reveal_desc: '他们一场也没赢。他们是从所有比赛的成绩里挑出来的。',
    champ_continue: '继续',
    champ_sacre: '{n} 加冕 — 查看领奖台',
    champ_titre_duree: '头衔保持三个月',
    champ_rv_course: '下一场比赛',
    champ_rv_reveal: '公布跑得最快的败者',
    champ_rv_sacre: '颁奖仪式',
    champ_quitter: '退出锦标赛',

    live_lanes: '分道',
    live_lanes_duel: '对决：赢的人拿分，输的人吐出一部分',
    live_lanes_course: '比赛：只排名次，不计对决排行榜的分数',
    live_won: '比赛获胜',
    live_sur: '在 {n} 名参赛者中',
    live_ordre: '到达顺序',
    live_lost: '比赛失利',

    pres_title: '运动员介绍',
    pres_lane: '分道',
    pres_you: '这就是你',
    pres_mic_on: '麦克风已开',
    pres_mic_off: '已拒绝麦克风',
    mic_winner: '获胜者发言',

    review_title: '你这场比赛的视频',
    review_making: '录制中…',
    review_dl: '下载',
    review_left: '{t} 后删除',
    review_gone: '视频已被删除',
    review_kept: '你下载的内容会留在手机里',
    review_none: '这台设备无法录制比赛',
    live_tie: '同时到达',
    live_vs: '实时对阵 {n}',
    live_gap: '相差 {s} 秒',
    link_in_app: '装了游戏吗？',
    link_in_app_sub: '从主屏幕打开它并输入这个代码 — 点击即可复制',

    duel_answered: '你的挑战有人应答了',
    duel_more: '还有 {n} 个结果在等',
    duel_mores: '还有 {n} 个结果在等',
    duel_next: '下一个',
    duel_ok: '知道了',

    ghost_mode: '幽灵模式',
    ghost_ahead: '领先',
    ghost_behind: '落后',
    ghost_level: '并驾齐驱',
    ghost_home: '幽灵已经冲线',
    ghost_live: '幽灵就在你身旁跑',
    duel_must: '发出一个挑战，或者应答朋友的挑战',
    duel_empty: '还没有打过对决',
    duel_pts: '分',

    monde_sprinter_sous: '直道与一圈',
    monde_hurdlers_sous: '同一条分道，里面放了十个栏架',
    monde_jumper_sous: '把助跑跑起来，然后离地',
    monde_thrower_sous: '一个圈，一件器械，还有整个身体',
    monde_bientot: '即将推出',
    monde_retour: '返回 SPRINTER',

    disc_100: '100 米',
    disc_200: '200 米',
    disc_400: '400 米',
    disc_100h: '100 米栏',
    disc_110h: '110 米栏',
    disc_400h: '400 米栏',
    disc_longueur: '跳远',
    disc_hauteur: '跳高',
    disc_triple: '三级跳远',
    disc_perche: '撑杆跳高',
    disc_poids: '铅球',
    disc_marteau: '链球',
    disc_disque: '铁饼',
    disc_javelot: '标枪',

    pique_0: '我甚至都不用使劲。',
    pique_1: '要我用慢动作再来一遍吗？',
    pique_2: '我都等到无聊了。',
    pique_3: '终点在这边。',
    pique_4: '谢谢你陪我热身。',
    pique_5: '我回头看了一眼，后面没人。',
    pique_6: '你跑了吗？我没看见什么东西经过。',
    pique_7: '这个成绩留着吧，会是段不错的回忆。',

    mot_titre: '给 {n} 留两句话',
    mot_placeholder: '用两行扎他一下',
    mot_vocal: '语音',
    mot_ecouter: '重听',
    mot_refaire: '重新录制',
    mot_envoyer: '发送',
    mot_envoye: '{n} 回来时会读到',
    mot_micro_refuse: '麦克风被拒绝了 — 打字也行',
    mot_ecouter_sa_voix: '听听他说了什么',
    mot_ephemere: '关掉这个窗口，这段录音就消失了',
    mot_illisible: '这条消息在这台设备上无法播放',

    mod_signaler: '举报',
    mod_titre: '你为什么要举报？',
    mod_explique: '举报会由真人阅读。屏蔽立即生效。',
    mod_insulte: '辱骂',
    mod_haine: '仇恨、种族歧视',
    mod_sexuel: '性内容',
    mod_menace: '威胁',
    mod_autre: '其他',
    mod_envoye: '已举报。会有人来看。',
    mod_deja: '已经举报过了',
    mod_bloquer: '屏蔽 {n}',
    mod_bloque: '{n} 再也不能给你留言了。',
    mod_annuler: '取消',

    duel_revanche: '我要复仇',
    duel_revanche_sub: '同一个项目 — 这次轮到你先跑出成绩',
    duel_renvoyer: '把代码回发给 {n}',
    duel_revanche_envoyee: '复仇挑战已发出',
    os_revanche_sans_cible: '无法通知 {n} — 请你自己把代码发过去',
    duel_revanche_ratee_titre: '还不行',
    duel_revanche_ratee: '要把挑战回敬给 {n}，你需要跑进 {s} 秒 — 什么也没发出去',

    rang_departemental: '县级',
    rang_regional: '地区级',
    rang_national: '全国级',
    rang_elite: '精英',
    rang_legende: '传奇',
    rang_court_departemental: '县',
    rang_court_regional: '地区',
    rang_court_national: '全国',
    rang_court_elite: '精英 ',
    rang_court_legende: '传奇',
    duel_lp: '联赛分',
    duel_monte_a11y: '上升 {n} 位',
    duel_descend_a11y: '下降 {n} 位',
    duel_lp_long: '联赛积分',
    duel_promu: '晋升到 {r}',
    duel_relegue: '降级到 {r}',
    duel_reste: '距离下一级还差 {n}',
    duel_regle: '应答挑战比发起挑战得分更多：成绩已经摆在那里，你也知道要超越什么。',
    duel_record: '{v}胜 · {d}负 · {n}平',
    duel_you: '你',
    duel_since: '自你上次来访以来',
    duel_unranked: '还没有名次 — 先打一场对决',
    duel_won: '对决获胜',
    duel_lost: '对决失利',
    duel_tie: '平局',
    duel_final: '最终结果 — 挑战不能重来',
    duel_delta: '{p} 分',
    duel_deltas: '{p} 分',

    false_out: '抢跑',
    false_out_sub: '被取消资格 — 对决判负',
    false_out_seul: '被取消资格 — 这场比赛到此为止',
    false_out_rule: '只有一场比赛，没有第二次机会',
    false_out_libre: '你可以重新跑一次',
    false_out_gun: '在枪响之前就出发了',
    duel_await: '对决结果…',
    duel_vs: '对阵 {n}',
    duel_seen: '这场对决已经有结果了',
    duel_see: '查看排行榜',

    os_once: '挑战一经发出，成绩就是最终的',
    os_rejouer: '再跑一次',
    os_rejouer_sub: '马上再跑一场 — 这一场保持原样',
    os_defier: '向某人挑战',
    os_defier_sub: '打开排行榜挑一个对手 — 换一个人，或者还是那个人',
    relance_gagne_0: '去逮下一个',
    relance_gagne_0_sub: '这个搞定了。下一个。',
    relance_gagne_1: '下一位，请',
    relance_gagne_1_sub: '排行榜上人多得很，而你正手感火热。',
    relance_gagne_2: '还有谁？',
    relance_gagne_2_sub: '去问排行榜。总有人会应。',
    relance_perdu_0: '挑个小一点的',
    relance_perdu_0_sub: '降一个级别 — 没人需要知道',
    relance_perdu_1: '找个更慢的',
    relance_perdu_1_sub: '一定有。从统计上说，一定有。',
    relance_perdu_2: '新手还是有的',
    relance_perdu_2_sub: '他们什么都没察觉。就是现在。',
    os_defi_sans_cible: '{n} 不在这个项目的 TOP 500 里 — 请你自己把代码发过去',
    os_verrou_direct: '实时比赛：你的对手在同一时刻跑了 — 那个结果有效',
    os_verrou_recu: '这个成绩已经送到对手那里 — 收不回来了',
    os_verrou_envoye: '挑战已发出 — 他要超越的就是这个成绩',
    os_verrou_faux: '对决中抢跑：比赛判负。发一个新的挑战重新开始。',
    cut_skip: '跳过',

    id_title: '你的名字',
    id_code_title: '恢复码',
    id_code_note: '记下它：它把你的其他设备连到这个名字上，也防止别人把名字抢走',
    id_show: '显示我的恢复码',
    id_reserve: '预留',
    id_taken: '这个名字已被占用',
    id_taken_help: '如果它是你的，请输入它的恢复码',
    id_link: '关联',
    id_linked: '设备已关联到 {n}',
    id_bad_code: '恢复码不对',
    id_unknown: '未知的名字',
    id_link_title: '换了一台设备？',
    id_link_help: '输入名字和恢复码，就能在这里找回你的成绩和记录',

    install_title: '安装游戏',
    install_why: '全屏，没有浏览器地址栏，离线也能玩',
    install_do: '安装',
    install_later: '以后再说',
    install_ios_1: '点击',
    install_ios_2: '分享',
    install_ios_3: 'Safari 底部，然后',
    install_ios_4: '添加到主屏幕',

    mode_career_s: '生涯',
    mode_oneshot_s: 'one shot',
    cat_race_sub: '单场比赛的最佳成绩',
    cat_run_sub: '六个阶段的总和',
    empty_cat_run: '还没有完整跑程的记录',
    will_enter: '{s} 秒：TOP 500 第 {r} 名，把名字写上去',

    wr_title: '世界纪录',
    wr_sub: '{d} 米的世界最好成绩',
    wr_old: '此前纪录：{s} 秒',
    wr_first: '成绩榜上的第一个成绩',
    wr_gain: '快了 {s} 秒',
    wr_save: '把我的名字刻上去',
    wr_saving: '保存中...',
    wr_done: '{n} 位列 TOP 500 第 {r} 名',
    wr_fail: '发送失败，请再试一次',
    wr_see: '查看 TOP 500',
    wr_later: '以后再说',
    os_top_checking: '正在核对排行榜...',
    os_top_none: '没有成绩能进 TOP 500',
    os_top_intro: '有 {n} 个成绩进入 TOP 500',
    os_top_intro_n: '有 {n} 个成绩进入 TOP 500',
    os_top_line: '{d} 米 — {s} 秒 — {r}',
    os_top_saved: '成绩已以 {n} 的名义保存',
    top500_count: '500 个成绩中有 {n} 个上榜',
    os_top_better: '你的 {d} 米纪录仍是 {s} 秒',
    os_kept_title: '你的纪录守住了',
    os_kept_line: '{d} 米：你已经有 {s} 秒（TOP 500 第 {r} 名）',
    os_kept_now: '这个 {s} 秒没能超过它 — 排行榜只留最好的一个',

    pause_title: '比赛已暂停',
    pause_note: '现在离开，就等于放弃正在进行的成绩',
    resume: '继续',

    challenge_them: '发起挑战',
    target_run: '跑你的 {d} 米：挑战会发给 {n}',
    target_sent: '挑战已发给 {n}',
    inbox_one: '收到一个挑战',
    inbox_many: '收到 {n} 个挑战',
    inbox_from: '{n} 在 {d} 米上向你挑战',
    inbox_accept: '接受',
    inbox_later: '以后再说',
    run_total_short: '完整跑程：',
    run_total_tiny: '跑程',
    best_split_tiny: '比赛',
    score_saved_race: '以 {s} 秒位列世界 TOP 500 第 {r} 名',
    mode_career: '生涯',
    mode_oneshot: 'ONE SHOT',
    mode_versus: '挑战',
    career_desc: '六个阶段一气呵成，只算一个成绩',
    oneshot_desc: '选好项目，只有一次机会',
    versus_desc: '与另一名玩家的幽灵同场竞跑',
    pick_events: '项目',
    pick_level: '级别',
    pick_none: '至少选一个项目',
    launch_oneshot: '出发',
    event_n: '项目 {n} / {t}',
    next_event: '下一个项目',
    oneshot_done: 'ONE SHOT 完成',
    total_in: '合计：',
    challenge_code: '挑战代码',
    challenge_enter: '输入你收到的代码',
    challenge_load: '载入',
    challenge_loading: '正在载入挑战...',
    challenge_bad: '找不到这个代码',
    challenge_net: '连接失败，请再试一次',
    challenge_from: '来自 {n} 的挑战',
    challenge_beat: '目标：{s} 秒',
    challenge_aveugle: '他的成绩要边跑边揭晓',
    challenge_accept: '接受挑战',
    challenge_make: '向朋友挑战',
    challenge_making: '正在创建挑战...',
    challenge_share: '把这个代码发出去，朋友就会和你的幽灵同场竞跑',
    challenge_copy: '复制链接',
    challenge_copied: '链接已复制',
    challenge_copy_code: '复制代码',
    share_send: '发送挑战',
    share_whatsapp: 'WhatsApp',
    share_sms: '短信',
    share_other: 'Snapchat、Instagram…',
    share_other_hint: 'Snapchat 和 Instagram 从分享菜单里打开。',
    affiche_share: '分享我的跑程',
    affiche_making: '正在生成图片…',
    affiche_saved: '图片已保存',
    affiche_failed: '图片生成失败',
    affiche_hint: '一张你跑程的图片，可以发到 Instagram 或 TikTok',
    code_copied: '代码已复制',
    challenge_rematch: '回敬挑战',
    challenge_rematch_sub: '你赢了 — 用刚刚跑完的这一程向他挑战',
    challenge_won: '挑战获胜',
    challenge_lost: '挑战失利',
    challenge_gap: '差距：{s} 秒',
    ghost_label: '幽灵',
    you_label: '你',
    dnf_short: '退赛',
    composing: '正在谱写配乐...',

    sound_off: '声音已关闭  (S)',
    press_enter: '按 ENTER',
    skip_now_kb: '再按一次 ENTER 跳过',
    skip_twice_kb: '按两次 ENTER 跳过',
    stage_dash: '阶段 {n}   -   {s}',
    furthest_kb: '到达过的最远阶段：{b} 中的 {a}',
    enter_start: 'ENTER：开始   -   S：声音   -   L：语言   -   ESC：退出',
    how_to_play: '怎么玩',
    help_1: '交替按  <-  和  ->  ，',
    help_2: '不要重复按同一个键。',
    help_3: '稳定的节奏能积累速度；',
    help_4: '重复按会让你绊一下，不过',
    help_5: '你随时都能重新提速。',
    best_stage: '这个阶段的最佳成绩',
    no_time: '还没有成绩记录',
    arrows_pick: '方向键选择   -   ENTER 确认   -   ',
    yn_short: 'Y / N 快捷键',
    you_beat: '你击败了 {w}，并通过了全部六个阶段。',
    the_zeze: 'ZEZE 一族',
    your_times: '你的成绩',
    total: '合计',
    enter_replay: 'ENTER：再跑一次      M：主页',
    stumble_kb: '你绊了一下！',
    go_kb: '跑！',
    to_beat_line: '目标：  {n}   -   {s} 秒',
    best_times_of: '最佳成绩  -  {s}',
    enter_next: 'ENTER   ->   阶段 {n}：{s}',
    full_run_pc: '全程 {s} 秒',
    announced_pc: '公布成绩：{s} 秒',
    quit: 'ESC：退出'
  },

  CUTS: {
    intro: [
      [ // 阶段一
        ['{n} 已经连续三年赢下操场上的每一场比赛。',
         '秘诀很简单：没人敢超他，球是他的。',
         '出于原则，他穿着校鞋热身。',
         '他母亲在围栏后面拍摄。拍到的多半是围栏。'],
        ['{n} 保持着校纪录，用记号笔写在体育馆墙上。',
         '计时的是同班同学，用的是一块有指针的手表。',
         '体育老师点了一次头。这就算正式了。',
         '现在刷墙都要绕开那个纪录。'],
        ['{n} 要了第 4 道。他拿到了第 4 道。',
         '他做着固定的动作：高抬腿，后踢腿，深深叹气。',
         '号码布是在家里打印的，有点歪。',
         '号码是 1。他自己一个人打印的。']
      ],
      [ // 阶段二
        ['{n} 已经热身了四个小时。',
         '运动服后背绣着他的名字，全是大写。',
         '他有一套仪式：后退三步，吸一口气，眨一下眼。',
         '那一眨眼并不是对谁眨的。'],
        ['{n} 带着两双钉鞋和一个保温箱到场。',
         '箱子里装着一根香蕉，以及多得过分的决心。',
         '他把起跑器调到毫米级，然后重新调一次。',
         '接着是第三次。发令员在等，很有礼貌地等。'],
        ['{n} 去年在地区赛拿了第二。',
         '他形容那是一场被逆风偷走的胜利。',
         '官方读数显示无风。他对那个读数提出异议。',
         '他自带了风速仪。他不会用。']
      ],
      [ // 阶段三
        ['{n} 上过地区电视台。',
         '三十八秒的画面。他看了六百遍。',
         '为了省时间，他在比赛前就开始签名。',
         '签在购物小票上，因为实在没别的纸。'],
        ['{n} 有个没人用的外号：北方之箭。',
         '每次采访他都自己把它塞进去。',
         '播报员刚刚把他的真名念了出来，念错了。',
         '他已经要求用广播更正。更正会晚点到。'],
        ['{n} 把个人最好成绩纹在了前臂上。',
         '运动员介绍时，他用慢动作般的速度展示。',
         '这场决赛里已经有四个人跑进了那个数字。',
         '可惜纹身不会自动更新。']
      ],
      [ // 阶段四
        ['{n} 有赞助商、经纪人和理疗师各一位。',
         '三个人都说他不可战胜。三个人的钱都是他付的。',
         '经纪人连夺冠发布会的场地都订好了。',
         '茶点也订了。有小点心。'],
        ['{n} 已经当了十一个月的世界第一。',
         '他是在直播里知道的，从那以后再没回过头。',
         '这是字面意思：理疗师强烈建议他别回头。',
         '现在他整个上身一起转。慢一些，但看着挺帅。'],
        ['播报员念到 {n}。全场起立。',
         '他指看台，再指天空，再指镜头。',
         '镜头当时在别的选手身上。他从头再来一遍。',
         '导播让步了。这个动作将持续十一秒。']
      ],
      [ // 阶段五
        ['{n} 已经排练了八个月的庆祝动作。',
         '他还把它注册成了商标。剩下的只是赢下比赛。',
         '一支四十人的合唱队在等他的手势。',
         '他们学了一首歌。歌里念他的名字，念得很长。'],
        ['{n} 穿着自己国家的颜色，而且是真的在意这件事。',
         '国旗在钉鞋上，在号码布上，也在毛巾上。',
         '毛巾不用跑，但从星期二就准备好了。',
         '有位工作人员从开幕式起就把它带到每个地方。'],
        ['{n} 曾发誓在起跑器上绝不看对手。',
         '于是他直勾勾地看着正前方，专注得惊人。',
         '稍微看得太前了一点：介绍时他盯着的是墙。',
         '那面墙没有闯进这场决赛。']
      ],
      [ // 阶段六
        ['{n} 来自一个重力可选的宇宙。',
         '他在决定开跑之前就已经跑完了比赛。',
         '他的纪录在十一个维度里同时有效。',
         '第十二个维度里他绊了一下，不过没人提这件事。'],
        ['{n} 在十一个平行宇宙里跑过这一百米。',
         '十一个他都赢了。第十二个从未被承认。',
         '那里的终点裁判是一团星云，在压线判定上不太靠谱。',
         '那团星云被禁赛三个赛季。'],
        ['ZEZE 一家占满了全部七条分道。这是合规的。',
         '他们带来了自己的发令员、自己的风、自己的终点线。',
         '规则由一个 ZEZE 写，再由一个 ZEZE 审。',
         '规则只有一句话：ZEZE 获胜。']
      ]
    ],

    defeat: [
      [ // 阶段一
        ['{n} 向食堂值班老师申诉这个结果。',
         '值班老师正在吃三明治。结果维持不变。',
         '接着他请班长做个裁定。',
         '班长跑了最后一名。他正享受这一刻。'],
        ['{n} 解释说操场地面不平。',
         '从一九六〇年起，它对所有人都不平。',
         '接着他提到鞋带松了。他的鞋是粘扣的。',
         '老师把你的成绩写在墙上。就写在他的上面。'],
        ['{n} 宣布他其实并没有在比赛。',
         '他是在热身。真正的比赛是下一场。',
         '这件事没人被告知过，倒是解释了不少东西。',
         '铃声响了。下一场比赛永远不会到来。']
      ],
      [ // 阶段二
        ['{n} 解释说他的表根本没启动。',
         '所以严格来说，这场比赛从未发生。',
         '他提议现在就重跑一次，在明事理的人之间。',
         '接着他想起自己要赶火车。他没有火车。'],
        ['{n} 要求看终点照片。',
         '照片给他看了。明显在后面，而且非常清晰。',
         '他要求换一个角度的同一张照片。',
         '那个角度他还是在后面，只是稍微糊一点。'],
        ['{n} 一言不发地收起两双钉鞋。',
         '他宣布改练 400，一个更讲战术的项目。',
         '然后是 800。再然后是马拉松，反正一切都在那里结束。',
         '他提着保温箱走了。香蕉一口没动。']
      ],
      [ // 阶段三
        ['{n} 在直播里宣布退役。',
         '接着又改了主意：星期一恢复训练。',
         '他补充说，偏偏那个星期一格外忙。',
         '结果下一个星期一也一样。'],
        ['{n} 要求给冠军做兴奋剂检测。',
         '为了公平起见，接着又要求给自己做一个。',
         '两个都是阴性。他觉得这很可疑。',
         '他要求做第三次检测。检测计时设备。'],
        ['{n} 把前臂亮给记者看。',
         '纹上去的纪录一动没动。这也算聊胜于无。',
         '他宣布要去高原集训六周。',
         '他挑的那座山，海拔两百米。']
      ],
      [ // 阶段四
        ['{n} 要求重新测一次风速。',
         '风被传唤了。风没有到场。',
         '夺冠发布会照常举行，因为已经取消不了了。',
         '小点心非常出色。这总归也是件好事。'],
        ['{n} 盯着大屏幕看了二十秒。',
         '排名没有变。屏幕也没有变。',
         '他问画面是不是直播。别人告诉他是。',
         '他于是问有没有延时信号。没有。'],
        ['在混合区，{n} 谈起进步和过程。',
         '两分钟里他把「周期」这个词用了十一次。',
         '一位记者问他的成绩。他答：成绩会来的。',
         '他的成绩已经挂在身后的记分牌上，字很大。']
      ],
      [ // 阶段五
        ['{n} 还是把庆祝动作做完了。',
         '观众鼓掌，出于礼貌。',
         '合唱队没接到通知，把那首歌唱了起来。',
         '四十个人唱他的名字。他其实更希望是安静。'],
        ['{n} 按计划举着国旗跑了一圈致意。',
         '冠军也跑同样一圈，方向相反。',
         '他们迎面遇上两次。第二次更难受。',
         '毛巾没料到会是这样。'],
        ['{n} 站上领奖台的第二级。',
         '他用一次极长的握手祝贺冠军。',
         '长到官方合影重拍了三次。',
         '第三次他笑了。看得出这一笑的代价。']
      ],
      [ // 阶段六
        ['{n} 重新计算了自己那条星系的轨道。',
         '那条轨道恰好从第二名的位置穿过。',
         '他先说是时间异常，接着说是鞋子出了问题。',
         '两种说法互相矛盾。他两种都留着。'],
        ['{n} 索要另外十一个宇宙的排名。',
         '在这十一个宇宙里，他也都刚刚输掉。同时输的。',
         '他提议再开一个第十二宇宙，就看一眼。',
         '第十二个已经有人了。在那里第一名也是你。'],
        ['另外六个 ZEZE 非常平静地看着 {n}。',
         '没有人说一个字。沉默持续了四光年。',
         '{n} 最后开口：今天的地面不一样。',
         '自从跑道建成，地面就没变过。']
      ]
    ],

    taunt: [
      [ // 阶段一
        ['{n} 一言不发地指了指记分牌。',
         '他已经在上面签好名了。用的是不可擦的记号笔。',
         '他把自己的三明治递给你。「路上吃」，他说。',
         '你并没有要过三明治。'],
        ['{n} 跑了一圈致意。因为地方不够，只有三米。',
         '他对着想象中的观众挥了很久的手。',
         '他提出再比一场。然后看了看手表。',
         '他没有手表。这个动作已经说明一切。'],
        ['{n} 不慌不忙地收拾东西，一边吹着口哨。',
         '那调子是你的名字，配上凯旋进行曲的节奏。',
         '他拍拍你的肩：「下次吧」。',
         '他一秒钟也不相信这句话，而且脸上写着。']
      ],
      [ // 阶段二
        ['{n} 看了看计时器，又看了看你，眼神意味深长。',
         '他什么也没说。沉默比语言更残忍。',
         '他开始签名。第一张给你。',
         '那个你也没要过。'],
        ['{n} 给教练打电话：「我们提前结束了」。',
         '教练问为什么。「出于礼貌」，他答。',
         '他让你拿一下他的奖牌。只拿一小会儿。',
         '这一小会儿持续了十分钟。他在不停拍照。'],
        ['{n} 把钉鞋收进一个写着你名字的鞋袋里。',
         '这是内部玩笑。观众跟不上。',
         '他请你喝他水壶里的水。水壶是空的。',
         '他说，重要的是这份心意，不是水。']
      ],
      [ // 阶段三
        ['{n} 对着镜头挥手。接着又对你挥手。',
         '第二次挥手明显没那么友好。',
         '他和记者们细细地谈论你的这一场。',
         '他最喜欢的细节是：你回头的那一刻。'],
        ['{n} 要了话筒。尽管不太明智，他还是拿到了。',
         '他感谢家人、俱乐部，还有你，就按这个顺序。',
         '「要不是他」，他说，「这滋味就不一样了」。',
         '他没说他指的是什么。也不需要说。'],
        ['{n} 提议和你一起心平气和地复盘这一场。',
         '复盘只有一个词。他说得非常慢。',
         '为了保险起见，他连着握了你两次手。',
         '第一次他大概觉得不够有说服力。']
      ],
      [ // 阶段四
        ['{n} 接受了采访。主题很奇怪，是你。',
         '三分钟。关于自己那一场，一个字也没有。',
         '他最后说自己学到了很多。从你的失利里。',
         '记者一字一句记下来，神色有点尴尬。'],
        ['{n} 示意经纪人在战绩里加一行。',
         '那一行只写着：又一次，赢了你。',
         '他邀请你去参加夺冠发布会。',
         '有一把椅子在等你，就在最后一排，没有话筒。'],
        ['{n} 用手机把排名给你看，一边放大。',
         '他放大了好一会儿。你那一行远在他那一行下面。',
         '「我可以发邮件给你」，他很热心地提议。',
         '你从没给过他邮箱。他已经有了。']
      ],
      [ // 阶段五
        ['{n} 向看台挥手，然后郑重其事地转向你。',
         '他接下来做的动作，任何规则手册里都找不到。',
         '一位记者请他为落败的对手说一句话。',
         '他说了七句。一句也不会进文章。'],
        ['{n} 登上领奖台，然后又走下一级。',
         '他邀请你近看那枚奖牌。',
         '非常近地看。是金的。他特意强调这一点。',
         '国歌响起。他唱得很大声，一边看着你。'],
        ['{n} 把这场胜利献给家人、赞助商，还有你。',
         '「要是没有这么有激励作用的对手」，他很真诚地说。',
         '「激励」这个词落下来，像一句包装精致的羞辱。',
         '观众鼓掌，并不明白你为什么脸红。']
      ],
      [ // 阶段六
        ['{n} 看向另外六个 ZEZE。他们一起点头。',
         '判决是一致的，而且没有发出任何声音。',
         '一块纪念铭牌被刻了出来，用的是一种死去的语言。',
         '大意是：他努力过了。这也算是一件事。'],
        ['{n} 在十一个不同维度里重新计算了你的名次。',
         '每一个维度里结果都一模一样，精确到秒。',
         '他送你一张地图，画的是你本该获胜的那个宇宙。',
         '那个宇宙，他补充说，目前还不存在。'],
        ['{n} 向天空伸出手。一条星系顺从地亮了起来。',
         '有那么一瞬，它勾出了他微笑的形状。',
         '七个 ZEZE 商议了一下，然后一起转向你。',
         '随之而来的沉默持续四光年。很有礼貌地沉默。']
      ]
    ],

    champion: [
      ['七个 ZEZE 商议了很久。',
       '没有一个能找出说得过去的借口。这是头一回。',
       '排名在一百四十亿个星系里同步更新。',
       '终点线上安放了一块铭牌。',
       '你的名字在上面拼错了，但确实在上面。'],
      ['播报员在找一个词。没有一个词够大。',
       '他索性把成绩念了出来，念两遍，为了稳妥。',
       '七个 ZEZE 盯着大屏幕，一言不发。',
       '一个委员会成立了，专门检查终点线。',
       '那条线是直的。排名也是。'],
      ['致意的那一圈，比比赛本身还长。',
       '这只是简单的算术，也没人抱怨。',
       '有人递给你一面旗。你说不出它来自哪个星系。',
       '它来自所有星系：为了这个场合，图样被合到了一起。',
       '合唱队重写了他们的歌。这一次，歌里终于有你的名字。']
    ]
  }
};
